openebs/maya

scripts/install_go.sh

Updated GO_VERSION from the old 1.7.3 to the latest 1.8

Updated GO_VERSION

---

command/vsm_stats.go
commands.go
glide.lock
glide.yaml

This will fetch the replica stats through http request

Getting runtime stats from replica

---

command/stats.go
command/vsm_stats.go

Updated vsm-stats command with latest mayaserver apis

Update vsm-stats command with latest mayaserver apis

---

command/vsm_stats.go

Added few parameters which are:
SectorSize, UsedLogicalBlocks and UsedBlocks
Now output have two tables:
1. Performance Stats
2. Capacity Stats

Added few parameters

---

command/command_suite_test.go
command/vsm_stats.go
command/vsm_stats_test.go

Separated the code of output into another function  StatsOutput to make it more readable.

Refactoring the output

---

command/command_suite_test.go
command/vsm_stats.go
command/vsm_stats_test.go

Updated vsm_stats and added unit test.
* Some changes are needed for writing the unit tests
* Code refactoring

Vsm stats test

---

command/helpers.go
command/snapshot_create.go
command/snapshot_delete.go
command/snapshot_revert.go
command/stats.go
command/volume_stats.go
types/v1/types.go
volumes/provisioner/jiva/model.go
volumes/provisioner/jiva/snapshot_create.go
volumes/provisioner/jiva/snapshot_list.go
volumes/provisioner/jiva/snapshot_revert.go

**Feature Request:**
**Why this Change Required ??**
This commit will add snapshot API struct as well as the API handlers
which is going to use in M-apiserver to perform CRUD operations with 
respect to Snapshot.
**How does this change address the issue ?**
This will be initial commit which add the snapshot API struct and handlers.
issue : openebs/maya#79

Snapshot api #79

---

volumes/profile/volumeprovisioner/profile.go

Closes https://github.com/openebs/openebs/issues/403

Remove commented code

---

command/model.go
command/snapshot_list.go
command/volume_stats.go

To comply with latest Jiva rest APIs, these change are being commited.
**How does this change address the issue ?**
This commit wil fix the issue related to marshalling of
replication counter data struct.
fixes openebs/openebs#418
fixes openebs/openebs#417

Fix: Update data structure for stats command

---

Vagrantfile
buildscripts/install_go.sh

This PR fixes https://github.com/openebs/openebs/issues/568

Simplify maya's Vagrantfile to help build & compile the maya repository

---

README.md

Remove the references to deprecated concepts like VSM, OSH/OMM, hyperconverged mode, 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #579
Also reworded the description to reflect that this repo, now hosts many of maya components instead of only mayactl.

Cleanup openebs/maya/readme #579

---

buildscripts/apiserver/build.sh
buildscripts/build.sh

Move from gox to go build in apiserver build

---

Vagrantfile

The current Vagrantfile in maya repository helps
in setting up a development environment for maya
code. It helps in compile & building Docker images of
mayactl, apiserver & others.
However, there is a need to have some features tested
before submitting a PR. Some of these features require
a K8s setup to test the functionality. Hence, it
will be ideal to update the current Vagrantfile to
include minikube setup.
- Modified Vagrantfile to include minikube & kubectl
- Run below commands:
- Vagrant up
- kubectl get po
- None
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes …

Adds minikube setup in maya's Vagrant VM

---

.travis.yml

Initial Commit for https://github.com/openebs/openebs/issues/642

Adding Kubernetes Environment to travis

---

command/os_exec_commands.go

Fixes golint issues mentioned in https://github.com/openebs/openebs/issues/769

Fix golint issues in os_exec_commands.go

---

orchprovider/k8s/v1/k8s_test.go

**What this PR does / why we need it**: Fix Go linting issues
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/openebs/issues/778

Fix linting issues for returns

---

command/install_maya.go

Goreport is showing several linting errors. Please see the report at
https://goreportcard.com/report/github.com/openebs/maya
This pull request is to fix the errors in
https://github.com/openebs/maya/blob/master/command/install_maya.go
fixes https://github.com/openebs/openebs/issues/767
Signed-off-by: Manoj Kumar <bmanojkumar24@gmail.com>

Fix linting errors

---

orchprovider/nomad/v1/helper_funcs.go

Fixes https://github.com/openebs/openebs/issues/761
@vharsh @nsathyaseelan

Fix lint errors in maya/orchprovider/nomad/v1/helper_funcs.go

---

orchprovider/k8s/v1/k8s_test.go

k8s_test: fix misspells

---

command/volume_stats.go
command/volume_stats_test.go

volume_stats: fix lint

---

cmd/maya-agent/k8s/constants.go

**What this PR does / why we need it**: Fixes linting issues
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/openebs/issues/773

Fix linting issues

---

command/install.go
command/install_openebs.go

PS: I couldnt return to the last PR since I forced-update after closing It /:
related to openebs/maya#153
fix openebs/openebs#780

install: fix lint

---

command/snapshot_revert.go
command/version.go
command/volume.go
command/volume_create.go
command/volume_create_test.go
command/volume_list.go
command/volume_stats.go
command/volume_stop.go
command/volume_update.go

Fixes openebs/openebs#362
Fixed a portion of some mixed indentation in some files.
Extension to https://github.com/openebs/maya/pull/138

command: Fix indent of files

---

command/meta.go

**What this PR does / why we need it**: fixes linting issues
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes [openebs/openebs#768](https://github.com/openebs/openebs/issues/768)

Fix linting issues maya/command/meta.go

---

cmd/maya-apiserver/app/server/http.go
cmd/maya-apiserver/app/server/snapshot_endpoint.go
cmd/maya-apiserver/app/server/volume_endpoint.go

This commit will add glog as a default logger pkg for
volume API's for proper logging.
**Which issue this PR fixes** :
fixes # openebs/openebs#265
ref - openebs/mayaserver#77

Switch to glog for Volume API logging

---

command/volume_list.go
command/volume_stats_test.go
command/volume_stop.go

all: fix error handling

---

command/eval_status.go
command/meta.go
command/node_status.go
command/volume_list.go
command/volume_stop.go

This commit will fix the golint errors in meta.go files

Fix golint errors in meta.go

---

buildscripts/exporter/Dockerfile
cmd/maya-volume-exporter/app/command/command.go

Fix name typo

---

types/v1/util.go

Signed-off-by: Pannatat Supharatnodom <pannatat.s@outlook.com>
**What this PR does / why we need it**: Fix linting issues maya/types/v1/util.go
issue 764 in openebs repo
https://github.com/openebs/openebs/issues/764

Fix linting issues maya/types/v1/util.go

---

command/volume_update.go

**What this PR does / why we need it**: Fixes linting issues reported by GOREPORT in maya/command/volume_update.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/openebs/issues/772

#772 Fixes linting issues reported by GOREPORT in maya/command/volume_update.go

---

command/snapshot_list.go

[GOREPORT] Fix linting issues maya/command/snapshot_list.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/openebs/issues/759
Fix #759 in 'openebs/openebs' repo
Signed-off-by: Pannatat Supharatnodom <pannatat.s@outlook.com>

Fix linting issues maya/command/snapshot_list.go

---

command/eval_status.go

[GOREPORT] Fix linting issues maya/command/eval_status.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/openebs/issues/763
Fixed #763 in openebs/openebs repo
Signed-off-by: Pannatat Supharatnodom <pannatat.s@outlook.com>

Fix linting issues maya/command/eval_status.go

---

command/snapshot_create.go

[GOREPORT] Fix linting issues maya/command/snapshot_create.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/openebs/issues/758
Fixed #758 in openebs/openebs repo
Signed-off-by: Pannatat Supharatnodom <pannatat.s@outlook.com>

Fix linting issues maya/command/snapshot_create.go

---

cmd/maya-apiserver/app/server/metadata_endpoint.go
orchprovider/k8s/v1/k8s.go
orchprovider/nomad/v1/api.go
types/v1/profile/doc.go
types/v1/types.go
volume/provisioners/jiva/util.go

Signed-off-by: dungeonmaster18 <umesh4257@gmail.com>
**What this PR does / why we need it**: It fixes all the misspell in the maya repo. Hence improves GO REPORT.
openebs-hackfest

Fixed all the misspell

---

orchprovider/k8s/v1/k8s.go
orchprovider/k8s/v1/k8s_test.go
orchprovider/k8s/v1/util.go
pkg/util/util.go
types/v1/defaults.go
types/v1/envs.go
types/v1/policies.go
types/v1/types.go
volume/policies/v1/policy_jiva_k8s.go

Refer - https://github.com/openebs/openebs/issues/925

Add monitoring as a sidecar during volume provisioning

---

docs/developer.md

This pr replaces wrong development path in developer.md file

Fixed development path issue.

---

pkg/maya/maya.go
pkg/maya/maya_test.go

fixes https://github.com/openebs/openebs/issues/986
- This will help maya in building a K8s Service object
from various options that are DevOps friendly
- This is part of openebs/openebs#976
- Added MayaService structure
- Added methods to generate K8s Service from yaml
- Added unit tests to verify these changes
- `cd pkg/maya && go test`
- `make` should run without any errors
- none
```bash
vagrant@maya-01:/opt/gopath/src/github.com/openebs/maya/pkg/maya$ go test -v
=== RUN   TestMayaBytes
--- PASS: TestMayaBytes (0.00s)
=== RUN   TestMayaAnyK8sGenerateService
=== RUN   TestMayaAnyK8sGenerateService/blank_service
=== RUN   TestMayaAnyK8sGenerateService/hello_service
=== RUN   TestMayaAnyK8sGenerateService/invalid_service
=== RUN   TestMayaAnyK8sGenerateService/valid_service
--- PASS: …
```

maya wrapper over kubernetes service object

---

volume/provisioners/jiva/model.go

This PR fix golint errors in model.go file under volume/provisioners/jiva.
**Which issue this PR fixes**  
fixes: https://github.com/openebs/openebs/issues/771

fixing golint errors in model.go file

---

command/snapshot_delete.go

Fixes lint issue for snapshot_delete.go
fixes https://github.com/openebs/openebs/issues/765

fix lint warning and improve code

---

cmd/maya-volume-exporter/app/collector/collector.go
command/volume_stats.go
command/volume_stop.go
pkg/client/jiva/controller_client.go
pkg/client/jiva/replica_client.go
pkg/client/mapiserver/snapshot.go
types/v1/amount.go
types/v1/quantity.go

Drops unnecessary code
No directly relevant issue
* Drop unnecessary type conversions
* Inline client into initialization since it's simple

Drop various unnecessary type conversions

---

orchprovider/k8s/v1/util.go

Makes relevant part simpler
No direct issue as far as I know
* Drop bool checking
* Drop unnecessary type conversions

Simplify container state checking under k8s

---

cmd/maya-apiserver/app/server/volume_endpoint.go
orchprovider/k8s/v1/k8s.go
orchprovider/k8s/v1/util.go
pkg/client/mapiserver/snapshot.go
types/v1/defaults.go
volume/policies/v1/policy_k8s.go

Fixes Merge Conflict on master branch.
**Which issue this PR fixes** : fixes [openebs/openebs #1066](https://github.com/openebs/openebs/issues/1066)
/cc @kmova @AmitKumarDas

Fix Merge Conflict for namespace

---

cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
pkg/apis/openebs.io/v1alpha1/policy.go
pkg/task/fetch.go
pkg/task/runner.go
pkg/task/task.go
pkg/util/unstructured.go
pkg/volume/policy.go
pkg/volume/volume.go

Reworks based on the review comments for PR #249 
closes openebs/openebs#1168

Reworks w.r.t reviews submitted for volume policy

---

cmd/mayactl/app/command/stats_helper.go
cmd/mayactl/app/command/stats_helper_test.go
pkg/client/jiva/controller_client.go
pkg/client/jiva/controller_client_test.go
pkg/client/jiva/replica_client.go
pkg/util/util.go

- To improve coverage in unit test
- To add unit test
- Adds unit test in respective pkg
- Run `go test -v -cover`
- Some new errors created and moved to util.go under util pkg
improvement : openebs/openebs#1174 , openebs/openebs#1175
* More test will be added soon

Add unit test and improve coverage

---

cmd/mayactl/app/command/volume_delete.go
pkg/client/mapiserver/snapshot.go
pkg/client/mapiserver/snapshot_test.go
pkg/client/mapiserver/status.go
pkg/client/mapiserver/utils_test.go
pkg/client/mapiserver/volume_create.go
pkg/client/mapiserver/volume_create_test.go
pkg/client/mapiserver/volume_delete.go
pkg/client/mapiserver/volume_delete_test.go
pkg/client/mapiserver/volumes_list.go
pkg/client/mapiserver/volumes_list_test.go

- To improve test coverage
- It will reduce run time errors
- Adds unit tests in `pkg/client/mapiserver` dir
- Run `go test -v -cover`
- Few errors and unneccessary statements are removed and using the new errors
created in `pkg/util/utils.go`.
improvement: openebs/openebs#1183
<!--

Add unit test to improve coverage in pkg/client/mapiserver dir

---

Gopkg.lock
Gopkg.toml

this cleans up the un-required packages from dep
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #https://github.com/openebs/openebs/issues/1176

cleans up Gopkg.toml w.r.t vendoring

---

orchprovider/k8s/v1/k8s.go

fixes https://github.com/openebs/openebs/issues/1214
It was observed that volume service was not deleted
in certain cases. e.g. when volume replica count was
greater than k8s node count.
- This makes use of deployment delete only
- It removes the logic w.r.t pod delete
- It makes use of DeletePropagationBackground
- It removes the logic w.r.t OrphanDependents
- create a openebs volume & delete the same will
create & delete the volume service
- this fix should work on kubernetes version 1.7 & above
as DeletePropagationBackground is supported from these
versions.
Signed-off-by: amitkumardas <amit.das@openebs.io>
**What this PR does / why …

fixes issues observed during volume delete

---

.travis.yml
ci/helm_install_openebs.sh
ci/setup_env.sh

merge helm/rbac changes from master PR#269

---

orchprovider/k8s/v1/util.go
orchprovider/k8s/v1/util_test.go

Related to https://github.com/openebs/maya/pull/274
- Fixed the unit test for multi-valued.
- Added additional test case for single valued entry
- Fixed the issue with having duplicate entries for multi-valued. (Merged the code from master back to 0.5)

Fix #1275 - remove the duplicate entries

---

ci/helm_install_openebs.sh

Fixes openebs/openebs#1305
Also includes a change to display the pod details in yaml format, which should give information about the actual image used for the containers.

Fix openebs/openebs#1305 - set the apiserver tag correctly

---

cmd/mayactl/app/command/commands.go

fixes # openebs/openebs/issues/1360

Fix cli header name in help text (maya-->mayactl)

---

README.md

Signed-off-by: sachinmukherjee <sachinmukherjee29@gmail.com>
- It adds a missing period at the end of a sentence.
- Earlier there was no period and it was written like this `Design proposals for Maya components are located at OpenEBS Designs directory`
- Now in this PR it looks like this `Design proposals for Maya components are located at OpenEBS Designs directory.`
**Which issue this PR fixes**: fixes https://github.com/openebs/maya/issues/309

Adds missing period in README file

---

cmd/mayactl/app/command/volume_create.go
cmd/mayactl/app/command/volume_create_test.go

This PR adds check functionality before creating a volume.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/openebs/issues/117

Add function to check if volume exists already

---

README.md

Signed-off-by: Utkarsh Gupta (guptautkarsh2102@gmail.com)
**What this PR does / why we need it**: This PR fixes all the periods missing in the README.md
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #324.
**Special notes for your reviewer**: Since @NisantaSahoo labelled #324 as `summerhack` and hence wanted to contribute for the same.

[Fixed] Missing periods in README.md

---

cmd/mayactl/app/command/volume_info.go
cmd/mayactl/app/command/volume_info_test.go

**What this PR does / why we need it**:There was a bug in volume info command in which the status was incorrect . This PR fixes that bug .
fixes: https://github.com/openebs/openebs/issues/1574

Fixes invalid status and ip error in volume info command

---

cmd/mayactl/app/command/volume_info.go
cmd/mayactl/app/command/volume_stats.go
cmd/mayactl/app/command/volume_stats_test.go
types/v1/constant.go

Signed-off-by: Sumit Lalwani <sumit.lalwani97@gmail.com>
* Add templates for each table details.
* Uses template along with tabwriter for the proper alignment.
* Edit unit test cases accordingly.
**Which issue this PR fixes**: <https://github.com/openebs/openebs/issues/1597>

Improve volume stats using template and maintain unit test cases

---

pkg/client/jiva/model.go
pkg/client/mapiserver/snapshot.go
pkg/client/mapiserver/snapshot_test.go
pkg/client/mapiserver/utils.go

* Adds template to display snapshots.
* Adds Parent and Children details in snapshot list command
* Adds unit test cases in snapshot_test.go file
**Which issue this PR fixes**: <https://github.com/openebs/openebs/issues/1604>

Add parent and child details in snapshot list command

---

cmd/maya-apiserver/app/server/volume_endpoint.go
pkg/apis/openebs.io/v1alpha1/cas_volume.go
pkg/apis/openebs.io/v1alpha1/custom_resource.go
pkg/util/env.go
pkg/util/env_test.go

Introduced new properties in CASVolumeSpec and CStorVolumeSpec. Updated logic to check CAS template gate feature.

CASVolume spec update and Feature Gate check update

---

pkg/apis/openebs.io/v1alpha1/cas_volume.go

Hardcode template name to cstor templates.
This has to be reverted back with better logic.

Update CAS template names to use cstor cas templates

---

cmd/maya-apiserver/spc-watcher/handler.go

The PR will fix the bug which is causing the storage pool deletion failure.
Check the comments in the checked in code.

This commit fixes storagepool deletion bug.

---

cmd/cstor-volume-mgmt/controller/common/common.go

Use openebs as the default namespace

using default namespace as openebs

---

cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
pkg/client/k8s/k8s.go
pkg/volume/volume.go

- m-apiserver would extract the sc name of pv from request header, if missing it will fetch the pv object then extract the sc name
- Removed default read cas template

[WIP]Read sc name from request

---

cmd/maya-apiserver/spc-watcher/controller_test.go

This commit will add test cases for IsDeleteEvent
function in controller.

[TA2160]Adding test case in controller for testing isDeleteEvent function.

---

cmd/cstor-volume-mgmt/volume/volume.go

made LogicalUnit2 to 1 in lun section of istgt.conf

---

cmd/maya-apiserver/spc-watcher/controller_test.go

This commit will add test for controller instance
of spc watcher.

[TA2178] Add test for controller instance in spc controller

---

cmd/maya-apiserver/spc-watcher/controller_test.go
install/v1alpha1-0.7.0/cstor-volume/volume.yaml
pkg/template/template.go
pkg/template/template_test.go

- Fixed runTask `cstor-volume-create-putcstorvolumereplicacr-default-0.7.0` post to save object name.
- Added formatted string on template jsonpath error.
- Commented unwanted test case.

Update runTask yaml bug and add formatted error.

---

pkg/task/runner.go

Due to error in repeatWith tasks none of the successfully executed
runtasks were added to rollback instances. Now the code would attempt
attempt to create rollback instance even if the task is overall
failure.

Fix rollback plan for repeatWith tasks.

---

install/v1alpha1-0.7.0/cstor-volume/volume.yaml

- change namespace of deployment(target) and service to openebs

Update all namespace to openebs

---

install/v1alpha1-0.7.0/cstor-volume/volume.yaml

Updated `cstor volume replica cr` runtask  put label to name.
Updated `create cstor volume cast` to use latest images.

Update cstor volume yamls.

---

install/v1alpha1-0.7.0/cstor-pool/pool.yaml

Update image tag for cstor-pool-sidecar

Update image tag for cstor-pool-sidecar

---

install/v1alpha1-0.7.0/cstor-volume/volume.yaml

remove un-needed comment

---

install/v1alpha1-0.7.0/jiva-volume/volume.yaml

remove a cas runtask that is not being used currently

remove a cas runtask that is not being used currently

---

install/v1alpha1-0.7.0/cstor-volume/volume.yaml

- As decided adding '-target' to all the cstor target deployment names.
- This will help to distinguish target deployment w other deployments

Append 'target' to target deployment name

---

cmd/maya-apiserver/spc-watcher/controller.go
cmd/maya-apiserver/spc-watcher/controller_test.go
cmd/maya-apiserver/spc-watcher/handler.go
cmd/maya-apiserver/spc-watcher/handler_test.go
cmd/maya-apiserver/spc-watcher/runner.go
cmd/maya-apiserver/spc-watcher/runner_test.go

This commit will do following:
1. Add unit tests for various components
of SPC watcher.
2. Remove unwanted code.
3. Refactor code.

[US2361]Add unit test for spc watcher

---

.travis.yml
GNUmakefile
buildscripts/agent/build.sh
buildscripts/apiserver/build.sh
buildscripts/cstor-pool-mgmt/build.sh
buildscripts/cstor-volume-mgmt/build.sh
buildscripts/exporter/build.sh
buildscripts/mayactl/build.sh
buildscripts/test-cov.sh
buildscripts/test.sh

Fix the indentation for ignored go pkg and bump Go version 1.10.3

---

cmd/mayactl/app/command/commands.go
cmd/mayactl/app/command/snapshot/create.go
cmd/mayactl/app/command/snapshot/list.go
cmd/mayactl/app/command/snapshot/snapshot.go
cmd/mayactl/app/command/stats_helper.go
cmd/mayactl/app/command/stats_helper_test.go
cmd/mayactl/app/command/version.go
cmd/mayactl/app/command/volume.go
cmd/mayactl/app/command/volume_create.go
cmd/mayactl/app/command/volume_create_test.go
cmd/mayactl/app/command/volume_delete.go
cmd/mayactl/app/command/volume_info.go
cmd/mayactl/app/command/volume_info_test.go
cmd/mayactl/app/command/volume_stats.go
cmd/mayactl/main.go
orchprovider/k8s/v1/k8s_test.go
pkg/client/mapiserver/snapshot.go
pkg/client/mapiserver/snapshot_test.go
pkg/client/mapiserver/status.go
pkg/client/mapiserver/utils.go
pkg/client/mapiserver/utils_test.go
pkg/client/mapiserver/volume_create.go
pkg/client/mapiserver/volume_create_test.go
pkg/client/mapiserver/volume_delete.go
pkg/client/mapiserver/volume_delete_test.go
pkg/client/mapiserver/volumes_list.go
pkg/client/mapiserver/volumes_list_test.go
types/v1/envs.go

**What this PR does / why we need it**: 
-> This pr adds support for accessing mayactl outside the pod inside the master with cluster IP (Currently not working in google cloud).
-> Refactors the code to reduce complexity and meet go standards.
-> Adds get and post method in util.go to avoid repetitive steps.
-> Adds unit tests to improve code coverage.
-> Removed redundant checking of mapiaddr in each function and added the check in command.go .
-> Merge this PR after merging this pr https://github.com/openebs/maya/pull/370 .

Adds support to access mayactl with cluster ip and refactors code to increase modularity 

---

cmd/maya-apiserver/spc-watcher/controller.go
pkg/client/mapiserver/utils_test.go

Fix unit test of GetURL function

---

.travis.yml
ci/install_openebs.sh
ci/setup_env.sh
ci/travis-ci.sh
cmd/mayactl/app/command/stats_helper.go
cmd/mayactl/app/command/volume_info.go
cmd/mayactl/app/command/volume_stats.go
pkg/client/mapiserver/utils.go
pkg/client/mapiserver/volume_delete.go
pkg/client/mapiserver/volumes_list.go

This commit will enhance mayactl commands volume list/stats/info/delete
to work with cas template based volume provisioning.

Enhance mayactl commands for cas-template based provisioning

---

ci/setup_env.sh
cmd/maya-apiserver/app/server/snapshot_endpoint.go
cmd/mayactl/app/command/snapshot/create.go
cmd/mayactl/app/command/volume_create.go
cmd/mayactl/app/command/volumes_list.go
pkg/client/mapiserver/snapshot.go
pkg/client/mapiserver/volume_create.go
pkg/client/mapiserver/volume_create_test.go

1. This commit will enhance mayctl snapshot commands create/list/revert to work
with CAS template based volume provisioning.
2. Add basic integration test for volume snapshot related operations based on
CAS template based provisioning.
```sh
************** Running mayactl volume info *******************************
---------------
IQN     :   iqn.2016-09.com.openebs.jiva:default-demo-vol1-claim
Volume  :   default-demo-vol1-claim
Portal  :   10.109.212.163:3260
Size    :   
Status  :   running,running
Replica Details :
----------------
NAME                                             ACCESSMODE      STATUS      IP             NODE
-----                                            -----------     -------     ---            ----- …
```

Enhance mayactl snapshot commands for cas template based provisioning

---

pkg/apis/openebs.io/v1alpha1/cas_volume.go

- So that engine used to provision volume could be differentiated. It is required by mayactl.

Add CasType in CASVolume spec

---

cmd/cstor-volume-mgmt/volume/volume.go

Changed the default LUWorkers to 6 in istgt.conf

---

pkg/volume/volume.go

-> This PR modifies List function to parse csv formated values of CAS_TEMPLATE_TO_LIST env variable.
-> This will help us to fetch both cstor and jiva volumes in mayactl.
-> Getting pkey as name in cstor volume name.
-> mayactl list volume response:
```root@maya-apiserver-7cf69f86db-8tdxs:/tmp# ./mayactl volume list
Name                   Status   Type
pkey                   Running  CSTOR
default-testclaimjiva  Running  JIVA

Enable mapi server to take csv formated values of cas template from env

---

cmd/cstor-pool-mgmt/controller/replica-controller/handler.go

Addressing [review comment](https://github.com/openebs/maya/pull/467#discussion_r212246117) 

Add cvr name in delete fail log message

---

pkg/apis/openebs.io/v1alpha1/cas_template_keys.go
pkg/apis/openebs.io/v1alpha1/cas_volume.go
pkg/util/util.go
pkg/util/util_test.go
pkg/volume/volume.go

This commit fix jiva clone operations for CAS template
based volume provisioning.

Jiva volume clone for CAS based volume provisioning

---

cmd/mayactl/app/command/snapshot/create.go
cmd/mayactl/app/command/snapshot/list.go
cmd/mayactl/app/command/snapshot/revert.go
cmd/mayactl/app/command/volume.go
cmd/mayactl/app/command/volume_create.go
cmd/mayactl/app/command/volume_delete.go
cmd/mayactl/app/command/volume_test.go
cmd/mayactl/app/command/volumes_list.go

-> Improved error message when volume not found at maya-apiserver
-> Added UT for volumes.go function .

Improved mayactl error message when volumeInfo UT

---

cmd/mayactl/app/command/volume.go

->     Disabled volume create and delete command in mayactl
-> Will enable it once api starts working .

Disabled volume create and delete command in mayactl

---

cmd/maya-apiserver/spc-watcher/select_disk.go
cmd/maya-apiserver/spc-watcher/select_disk_test.go
cmd/maya-apiserver/spc-watcher/storagepool_create.go
cmd/maya-apiserver/spc-watcher/storagepool_create_test.go

Refactor code and add unit tests. 

Refactor code and add unit tests

---

cmd/mayactl/app/command/volume.go
cmd/mayactl/app/command/volume_info.go
cmd/mayactl/app/command/volume_info_test.go

-> This fix error message when volume is not found in namespace.

Fix error message when volume no found in namespaces

---

pkg/client/k8s/v1alpha1/unstructured.go
pkg/install/v1alpha1/installer.go

This commit has following feature:
- Installer adds installer specific label against each artifact it installs
- Version information is made available from pkg/version
e.g. `openebs.io/version: v0.7.0` is set against each artifact installed by installer when maya-apiserver is of version v0.7.0

include installer based label on all artifacts

---

.travis.yml
ci/install_openebs.sh
ci/setup_env.sh
cmd/mayactl/app/command/volume_info.go

Adds basic integration test for cstor based volume and sparse based pool provisioning. 

Extend travis CI for cstor volume and pool provisioning

---

pkg/util/unixsock.go
pkg/util/unixsock_test.go

handle missing End Of Line marker in the first line of response from istgt.

---

GNUmakefile
buildscripts/cstor-pool-mgmt/Dockerfile

If release is tagged use release travis tag instead of ci tag

Use release tag as a base-image tag for cstor-pool

---

cmd/mayactl/app/command/volume.go
cmd/mayactl/app/command/volume_info.go
cmd/mayactl/app/command/volumes_list.go

-> Adds controller node name in volume info portal.
-> Adds Namespace column in volume list.
-> Some Output:
```
Namespace  Name                                Status   Type
---------  ----                                ------   ----
default    default-jiva-testvol-1-1101115345   Running  jiva
openebs    default-cstor-testvol-1-1294368585  Running  cstor
----------------
IQN               :   iqn.2016-09.com.openebs.jiva:default-jiva-testvol-1-1101115345
Volume            :   default-jiva-testvol-1-1101115345
Portal            :   10.0.0.209:3260
Size              :   5G
Controller Status :   running,running
Controller Node   :   127.0.0.1
Replica Count     :   1
Replica …
```

(Feature) Adds Controller Node Name in volume info and  NS in volume list command

---

orchprovider/k8s/v1/util.go

closes https://github.com/openebs/openebs/issues/1941
**What this PR does / why we need it**: Fixes typo in util.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/openebs/issues/1941
**Special notes for your reviewer**: None

#1914 Fix typo in util.go

---

pkg/install/v1alpha1/jiva_volume_0.7.0.go

Signed-off-by: Ramit Sawhney <ramitsawhney27@gmail.com>
**What this PR does / why we need it**: Fixes typo in jiva_volume_0.7.0.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes openebs/openebs#1938
**Special notes for your reviewer**: None

Fix typo in jiva_volume_0.7.0.go

---

types/v1/util.go

Fix type in util.go
substracted->subtracted and substraction->subtraction
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
fixes [openebs/openebs#1939](https://github.com/openebs/openebs/issues/1939)

Fix type in util.go

---

pkg/task/v1alpha1/jiva_volume_delete.go

- Changes occured to occurred
**Which issue this PR fixes**:
This fixes https://github.com/openebs/openebs/issues/1933

Fix typo in jiva_volume_delete.go

---

pkg/task/v1alpha1/runtask_command.go

**Which issue this PR fixes** Fixed typo in runtask_command.go #https://github.com/openebs/openebs/issues/1934

Fixed typo in runtask_command.go #1934

---

pkg/template/template.go

Fixes typo 
**Which issue this PR fixes**:
Fixes https://github.com/openebs/openebs/issues/1935
Signed-off-by: Simar <simarkalra1993@gmail.com>

Fix overridden typo

---

pkg/engine/cas_template_engine.go

Signed-off-by: Naveen Bellary <bellary.naveen@gmail.com>
**What this PR does / why we need it**: This PR fixes lint issues in cas_template_engine.go
**Which issue this PR fixes** : fixes https://github.com/openebs/openebs/issues/1930

Fixing the lint issues in cas_template_engine.go

---

cmd/maya-agent/app/command/iscsi.go

Signed-off-by: Jia-wei Yu <art96962006@gmail.com>
Fixes the linting issue from: https://github.com/openebs/maya/blob/master/cmd/maya-agent/app/command/iscsi.go
- fixes https://github.com/openebs/openebs/issues/1925

Fix lint error in iscsi.go

---

types/v1/constant.go

Signed-off-by: Naveen Bellary <bellary.naveen@gmail.com>
**What this PR does / why we need it**: Fixes a few typos and lint issues in constant.go file
**Which issue this PR fixes** : https://github.com/openebs/openebs/issues/1924

Fix lint issues in constant.go

---

pkg/template/template_test.go
vendor/github.com/aokoli/goutils/wordutils.go

Fixes typo
**Which issue this PR fixes**:
Fixes issue https://github.com/openebs/openebs/issues/1936

Fix separator typo

---

cmd/maya-exporter/app/command/exporter.go

Signed-off-by: Naveen Bellary <bellary.naveen@gmail.com>
**What this PR does / why we need it**: Fixes lint issues in exporter.go
**Which issue this PR fixes** : https://github.com/openebs/openebs/issues/1929
**Special notes for your reviewer**: Can you confirm if that is the intended change or whether the comment was actually for exporter.go and Package was added by mistake?

Fixing lint issue in exporter.go

---

cmd/maya-apiserver/spc-watcher/handler_test.go

This PR fixes a typo in handler_test.go
Closes openebs/openebs#1937

Fix typo in handler_test.go

---

cmd/mayactl/app/command/volume_info.go

Signed-off-by: Pratik Gadhiya <pratik.gadhiya@hotmail.com>
**What this PR does / why we need it**: Fixes typos in volume_info.go
**Which issue this PR fixes**: fixes https://github.com/openebs/openebs/issues/1921, fixes https://github.com/openebs/openebs/issues/1940

Fixes typos

---

pkg/storagepool/storagepool_template_engine.go

Signed-off-by: Gunwoo Ben Kim <gunwoo@gunwoo.org>
It fixes the lint issue in `pkg/storagepool/storagepool_template_engine.go`.
**Which issue this PR fixes**: [openebs/openebs#1926](https://github.com/openebs/openebs/issues/1926)

Fix the lint issue about package comments

---

volume/provisioners/jiva/jiva.go

Fixes go lint in jiva.go

---

pkg/install/v1alpha1/version_test.go

Fixes https://github.com/openebs/openebs/issues/1922

Adding unit test for Version method

---

pkg/client/jiva/controller_client.go

Signed-off-by: Gunwoo Ben Kim <gunwoo@gunwoo.org>
What this PR does / why we need it:
It fixes golint issue in `pkg/client/jiva/controller_client.go`.
Which issue this PR fixes: [openebs/openebs#1948](https://github.com/openebs/openebs/issues/1948)

Fix golint issue in controller_client.go

---

pkg/apis/openebs.io/v1alpha1/storage_pool_claim.go

Fixed linting issue 
**Which issue this PR fixes** : fixes [#1969](https://github.com/openebs/openebs/issues/1969)

Fixes golint issue in storage_pool_claim.go

---

pkg/client/jiva/replica_client.go

Fix golint issue in replica_client.go
**Which issue this PR fixes**: fixes https://github.com/openebs/openebs/issues/1949

Fix golint issue in replica_client.go

---

types/v1/math.go

**What this PR does / why we need it**: fixes golint issues in math.go
**Which issue this PR fixes**: fixes https://github.com/openebs/openebs/issues/1952

Fixes golint issues

---

pkg/apis/openebs.io/v1alpha1/cstor_pool.go

Fixes https://github.com/openebs/openebs/issues/1968

Fix golint issue in file cstor_pool.go

---

types/doc.go

fix golint for doc.go in types folder
**Which issue this PR fixes** *: fixes https://github.com/openebs/openebs/issues/1965

fix golint for types/doc.go

---

pkg/install/v1alpha1/template_values.go

Signed-off-by: Rajat Varyani <rajat.varyani@outlook.com>
It fixes https://github.com/openebs/openebs/issues/1954

#openebs/1954 Fix golint issues

---

pkg/client/k8s/v1alpha1/resource.go
pkg/volume/volume.go

Fixing https://github.com/openebs/openebs/issues/1957 issue.

Fix golint issue in resource.go #1957

---

types/v1/envs.go

fix golint for types/v1/envs.go
**Which issue this PR fixes** : fixes https://github.com/openebs/openebs/issues/1962

fix golint for types/v1/envs.go

---

cmd/maya-apiserver/spc-watcher/handler.go

Signed-off-by: Indraneel Sarkar <indraneel.sarkar96@gmail.com>
**What this PR does / why we need it**: Fixes linting issues in handler.go
https://github.com/openebs/openebs/issues/1959

Fixes linting issue in handler.go

---

pkg/signals/signal_posix.go

This PR closes https://github.com/openebs/openebs/issues/1964

Fixes go lint in signal package

---

CONTRIBUTING.md
docs/developer.md

Fixes punctuation (dots, semi colons, etc.), formatting (trailing spaces, new lines) and minor typos in docs.
Signed-off by: StrikerRUS  nekit94-08@mail.ru
</details>

fix punctuation, formatting and typos in docs

---

cmd/maya-apiserver/spc-watcher/storagepool_create.go
cmd/maya-apiserver/spc-watcher/storagepool_create_test.go

Signed-off-by: Igor German <iggerman@yandex.ru>
fixes https://github.com/openebs/openebs/issues/1960

Fix golint issue in storagepool_create.go

---

buildscripts/push

uncomment `docker push` cmd from build script to push image in docker
registry, which was left commented in previous commit PR #595

fix(build): push image in docker registry

---

ci/install_openebs.sh

Added a few variable to that can be used to have the installer run with images from release branches. 
Also, refactored to remove duplicated code using functions. 

refactor(ci): enable running ci on release branches

---

ci/install_openebs.sh

fix(build): update image tags to v0.7.x-ci on v0.7.x branch

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
cmd/cstor-pool-mgmt/controller/start-controller/controller.go
cmd/cstor-pool-mgmt/pool/pool.go
cmd/cstor-pool-mgmt/pool/pool_test.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
cmd/cstor-pool-mgmt/volumereplica/volumreplica_test.go
pkg/install/v1alpha1/cstor_volume_0.7.0.go
pkg/install/v1alpha1/jiva_volume_0.7.0.go
pkg/template/template.go
pkg/template/template_test.go

Fixes some of the know issues from 0.7.0 release that are fixed in master.

Cherry Pick fixes from master to v0.7.x

---

integration-tests/README.md
integration-tests/cstor-pool/README.md
integration-tests/cstor-volume/README.md

Added the following directory structure for integration tests.
```
integration-tests/
├── cstor-pool
│   └── README.md
├── cstor-volume
│   └── README.md
└── README.md
```

chore(integration-test): Create directory and add README.md

---

cmd/mayactl/app/command/volume.go

In this pr I've changed the error message for volumes
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1991
https://github.com/openebs/openebs/issues/1991

Issue-1991 changed error message

---

hack/cstor-pool-test/README.md

**What this PR does / why we need it**: There was a typo error in README file on 2nd line at (https://github.com/openebs/maya/tree/master/hack/cstor-pool-test).
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2038

Fixed the typo "shhould"

---

pkg/k8s/from_yaml.go
pkg/util/unstructured.go

Issue: https://github.com/openebs/maya/issues/630
Signed-off-by: Kislay <k.two.apps@gmail.com>

Fix lint errors as reported by Go report card

---

pkg/task/v1alpha1/cstor_snapshot_command.go
pkg/task/v1alpha1/cstor_snapshot_create.go
pkg/task/v1alpha1/cstor_snapshot_delete.go

Signed-off-by: harshit sharma <harshit.sharma1080@gmail.com>
Change method name from getSnapshotObj() to casSnapshot()
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2000

Change method name from getSnapshotObj() to casSnapshot()

---

cmd/maya-apiserver/app/server/snapshot_endpoint_v1alpha1.go

Signed-off-by: Chacree Sombutwong <pleumofficial@gmail.com>
remove passing resp http.ResponseWriter, req *http.Request objects
**Which issue this PR fixes**: fixes https://github.com/openebs/openebs/issues/1997

remove passing resp, req

---

pkg/task/identity_test.go

Signed-off-by: Rajat Varyani <rajat.varyani@outlook.com>
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/openebs/issues/1583

Add tests for /maya/pkg/task/identity.go

---

ci/setup_env.sh
cmd/mayactl/app/command/volume_info.go

Mayactl volume info command should be changed to mayactl volume describe #1990
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #[1990](https://github.com/openebs/openebs/issues/1990)

Mayactl volume info command should be changed to mayactl volume describe #1990

---

pkg/task/v1alpha1/runtask_command.go

Signed-off-by: knrt10 <tripathi.kautilya@gmail.com>
This PR solves golint errors
**Which issue this PR fixes** : fixes [#1943](https://github.com/openebs/openebs/issues/1943)

Fixes #1943

---

cmd/mayactl/app/command/volumes_list.go

Signed-off-by: Pratik Gandhi <pratikgandhi1997@gmail.com>
**Which issue this PR fixes** https://github.com/openebs/openebs/issues/1980#issuecomment-427289861

Adding capacity parameter in ebs volumes list

---

README.md

**What this PR does / why we need it**: add license section and badge to readme file

Update README - add license section and badge

---

pkg/k8s/from_yaml.go

- Fixes all the linting issue from: https://github.com/openebs/maya/blob/master/pkg/k8s/from_yaml.go
- https://github.com/openebs/openebs/issues/1931
- See code review comment: https://github.com/openebs/maya/pull/551#pullrequestreview-161018580
Signed-off-by: Richard Burk Orofeo <chardy.orofeo@yahoo.com.ph>

Removed comment from package k8s as commented

---

pkg/apis/openebs.io/v1alpha1/cas_template_keys.go
pkg/task/runner.go
pkg/task/task.go

Signed-off-by: RajuKalidindi <krkraju997@gmail.com>
**What this PR does / why we need it**: Fixed golint issue in cas_template_key.go
**Which issue this PR fixes**: fixes [#1961](https://github.com/openebs/openebs/issues/1961)

Fixed golint issue in cas_template_key.go

---

pkg/install/v1alpha1/env_registrar.go

Add cstor and jiva default snapshot cast.

chore(install): Add snapshot cast as environment variables m-apiserver.

---

cmd/maya-agent/k8s/types.go
cmd/maya-apiserver/spc-watcher/lease.go
cmd/maya-apiserver/spc-watcher/spc_lease.go
pkg/util/util.go

refactor(maya): go-fmt fix

---

volume/policies/v1/doc.go

Signed-off-by: Peeyush Gupta <peeyushgupta91@gmail.com>
Fixes: https://github.com/openebs/openebs/issues/2115

Fixing golint issues in doc.go

---

pkg/task/fetch.go

Fixes https://github.com/openebs/openebs/issues/2160
Signed-off-by: infiniteoverflow <aswingopinathan1871@gmail.com>

Fixed the golint error in maya/pkg/task/fetch.go

---

cmd/maya-apiserver/spc-watcher/runner.go

Signed-off-by: aishwaryavarma <aishwarya270290@gmail.com>

Fix golint issue in spc_watcher/runner.go file

---

pkg/template/template.go

Fixes https://github.com/openebs/openebs/issues/2154
Signed-off-by: Kaustumbh <kaustumbhjaiswal11@gmail.com>

Fixed golint issues

---

pkg/client/k8s/v1alpha1/clientset.go

Signed-off-by: Peeyush Gupta <peeyushgupta91@gmail.com>
Fixes: https://github.com/openebs/openebs/issues/2130

Fixing golint issues in clientset.go

---

pkg/client/k8s/v1alpha1/unstructured.go

Added a new line between comment and package name
fixes https://github.com/openebs/openebs/issues/2157
Signed-off-by: diehard-coder <nikhiljoshi0902@gmail.com>

Fixed linting issue in /pkg/client/k8s/v1alpha1/unstructured.go

---

pkg/env/v1alpha1/env.go
types/v1/policies.go

Change ReplicaImageVK to JivaReplicaImageVK in the comment
Signed-off-by: Shaunak Gupta <shaunak.gupta@gmail.com>
https://github.com/openebs/openebs/issues/2155
https://github.com/openebs/openebs/issues/2150

Fixed golint issue

---

volume/provisioners/registry.go

Signed-off-by: Nikhil M <m_nikhil@outlook.com>
**What this PR does / why we need it**:  Hacktoberfest - golint bug fix
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # https://github.com/openebs/openebs/issues/2123

golint bugs fix

---

pkg/template/query.go

What this PR does / why we need it:
Fixes some linting issues
Which issue this PR fixes
fixes: openebs/openebs#2102

Fix for issue #2102

---

orchprovider/nomad/v1/api.go
types/v1/scale_int.go

Added one line between comment and package
Fixes openebs/openebs#2119
Signed-off-by: diehard-coder <nikhiljoshi0902@gmail.com>

Fixed Linting issue in  maya/orchprovider/nomad/v1/api.go

---

types/v1/util.go

Fixes a couple of linting issues
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
fixes #2114
fixes [https://github.com/openebs/openebs/issues/2114](https://github.com/openebs/openebs/issues/2114)

Fix linting for issue 2114

---

cmd/maya-apiserver/spc-watcher/handler.go
cmd/maya-apiserver/spc-watcher/spc_lease_test.go
cmd/maya-apiserver/spc-watcher/storagepool_create.go

Fixes issue openebs/openebs#2158 by separating license from package comment
**What this PR does / why we need it**: Fixes issue openebs/openebs#2158 by separating license from package comment
**Which issue this PR fixes**: openebs/openebs#2158

Fix package comment

---

cmd/maya-agent/app/command/device-format.go
cmd/maya-agent/types/v1/block_device_info.go
cmd/maya-apiserver/spc-watcher/handler.go
cmd/maya-apiserver/spc-watcher/storagepool_delete.go
orchprovider/k8s/v1/doc.go
orchprovider/nomad/v1/doc.go
types/v1/profile/doc.go

Signed-off-by: Peeyush Gupta <peeyushgupta91@gmail.com>
As suggested by @prateekpandey14, merged #660 #663 #664 #659

Fixing multiple golint issues

---

pkg/task/patch.go

Fix golint issue in maya/pkg/task/patch.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2088
The issue was raised in the main openebs repo: https://github.com/openebs/openebs/issues/2088

Fix #2088 golint issue in maya/pkg/task/patch.go

---

pkg/task/v1alpha1/store_command.go
types/profiles/v1/doc.go
volume/policies/v1/doc.go

Fix Issue https://github.com/openebs/openebs/issues/2153

Fix Golint Issues

---

.gitlab-ci.yml

Signed-off-by: atulabhi <atulabhi@gmail.com>
This PR contains the gitlab-ci yaml to build maya components and push the image with "commit id" to docker hub on each commit to 'Master' branch and run our E2E pipeline with new image.
Build Pipeline:

added gitlab-ci yml to run ci and e2e for maya

---

cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica_test.go
cmd/cstor-volume-mgmt/controller/volume-controller/handler.go
cmd/cstor-volume-mgmt/volume/volume.go
cmd/cstor-volume-mgmt/volume/volume_test.go
pkg/apis/openebs.io/v1alpha1/cstor_volume_replica.go

Support cStor volume clone from snapshot.
Update the snapshot name.
Remove unused fields from cstorvolumereplica.

[TA3375] feat(clone): Support cstor snapshot clone

---

cmd/maya-apiserver/spc-watcher/select_disk.go

**What this PR does / why we need it**: This is fix in golint at select_disk.go
**Which issue this PR fixes**: [fixes#2092](https://github.com/openebs/openebs/issues/2092)

modified method signature to fix golint issue

---

pkg/version/version.go

Fixes a few linting issues
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
fixes #2100
fixes [https://github.com/openebs/openebs/issues/2100](https://github.com/openebs/openebs/issues/2100)

Fix linting for issue #2100

---

volume/policies/v1/policy.go

**Which issue this PR fixes**: fixes https://github.com/openebs/openebs/issues/2106

Fix #2106 go lint issues

---

types/v1/profile/orchestrator/profile.go

This PR fixes golint issues reported for ``maya/types/v1/profile/orchestrator/profile.go``.
**Which issue this PR fixes**: fixes openebs/openebs#2112
Signed-off-by: Julio Cezar M <juliocmdsilva@gmail.com>

Fixes #2112 golint issues

---

pkg/nethelper/ipcalc.go
pkg/template/template.go

Fixed all the golint issues that were there in the `maya/pkg/nethelper/ipcalc.go`.
fixes openebs/openebs#2125
Signed-off-by: Axle7XStriker <amanbansal1997@gmail.com>

Fixed golint issues in maya/pkg/nethelper/ipcalc.go

---

cmd/maya-apiserver/app/server/metadata_endpoint.go

This PR fixes golint issues reported for ``maya/cmd/maya-apiserver/app/server/metadata_endpoint.go``.
**Which issue this PR fixes**: fixes openebs/openebs#2120
Signed-off-by: Julio Cezar M <juliocmdsilva@gmail.com>

Fixes #2120 golint issues

---

types/v1/suffix.go

**What this PR does / why we need it**: Golint fixes. Ref.: https://github.com/golang/go/wiki/Comments .
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/openebs/issues/2136
**Special notes for your reviewer**: N/A.

suffix.go: Fix golint issues

---

types/v1/amount.go

Signed-off-by: galihmelon <galihmelon@gmail.com>
Fix golint issue in maya/types/v1/amount.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2098
The issue was raised in the main openebs repo: https://github.com/openebs/openebs/issues/2098

[WIP]Fix #2098 golint issue in maya/types/v1/amount.go

---

pkg/task/runner.go

Signed-off-by: Abilash Menon <abilashmenon95@gmail.com>
Fix golint issue in maya/pkg/task/runner.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2090
The issue was raised in the main openebs repo: openebs/openebs#2090

[WIP]Fix golint issue in maya/pkg/task/runner.go (openebs#2090)

---

pkg/install/v1alpha1/env_setter.go
pkg/task/identity.go
pkg/task/v1alpha1/store_command.go

Fixes openebs/openebs#2099
Fixes openebs/openebs#2104
Fixes openebs/openebs#2105

Fix issues openebs/openebs#2099, 2104, 2105

---

volume/policies/v1/policy_jiva_k8s.go

Fixed 2 lint issues in go file related to package documentation
and comments on exported function
Signed-off-by: Sona Praneeth Akula <sonapraneeth.akula@gmail.com>
Fixed 2 lint issues in go file related to package documentation
and comments on exported function
Fixes [#2103](https://github.com/openebs/openebs/issues/2103)

Fixed Go lint issues in file: policy_jiva_k8s.go

---

pkg/task/meta_test.go

Signed-off-by: Philippe Martin <feloy1@gmail.com>
Add test on NewMetaTaskExecutor
Fixes https://github.com/openebs/openebs/issues/1585

Add negative test on NewMetaTaskExecutor

---

pkg/apis/openebs.io/v1alpha1/register.go

Signed-off-by: Francesco Cartier <francescocartier@gmail.com>
**What this PR does / why we need it**: fixes a go-lint issue regarding comments for some exported vars
**Which issue this PR fixes**: fixes openebs issue [#2085](https://github.com/openebs/openebs/issues/2085)
**Special notes for your reviewer**: There wasn't really much to say in the comments, the function exported are basic initializations of runtime methods (if I got it right).

fixed go-lint issue in maya/pkg/apis/openebs.io/v1alpha1/register.go

---

types/v1/meta.go

This PR fixes golint issues reported for ``maya/types/v1/meta.go``.
**Which issue this PR fixes**: fixes openebs/openebs#2121
Signed-off-by: Julio Cezar M <juliocmdsilva@gmail.com>

[WIP]Fixes #2121 golint issues

---

.gitlab-ci.yml

Update the platform refs for branches.

refactor(yaml): Update the platform refs for branches.

---

integration-tests/cstor-pool/cstor_integration_test.go

Fixes [2190](https://github.com/openebs/openebs/issues/2190)

Adds IT for sparse-mirrored-auto(dynamic) spc with maxpool count 0 (2190)

---

integration-tests/cstor-pool/cstor_integration_test.go

fixes [#2187](https://github.com/openebs/openebs/issues/2187)

Adds IT for sparse-mirrored-auto(dynamic) spc with maxpool count 3 (2187)

---

cmd/cstor-pool-mgmt/pool/pool.go

Closes openebs/openebs#1953
Signed-off-by: Sarnava Konar <konarsarnava@gmail.com>
**What this PR does / why we need it**: Golint fixes
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/openebs/issues/1953
**Special notes for your reviewer**:N/A

pool.go: Fix golint issues#1953

---

types/v1/math.go

Fixes https://github.com/openebs/openebs/issues/2198
Golint fix: Simplify condition using increment and decrement

Simplify condition using increment and decrement

---

orchprovider/k8s/v1/k8s.go
orchprovider/k8s/v1/util.go
orchprovider/nomad/v1/helper_funcs.go
pkg/apis/openebs.io/v1alpha1/cas_keys.go
pkg/apis/openebs.io/v1alpha1/cas_template_keys.go
pkg/apis/openebs.io/v1alpha1/storage_pool_claim.go
pkg/task/v1alpha1/runtask_command_test.go
pkg/template/template_test.go
pkg/volume/volume_template_engine_test.go
volume/policies/v1/policy_jiva.go

Related to #630
This PR is just a run of `gofmt -s` on the files that need it. See https://goreportcard.com/report/github.com/openebs/maya pretty straightforward cleanup.

Running gofmt -s

---

pkg/client/k8s/v1alpha1/unstructured.go

Removes unreachable return statements in `pkg/client/k8s/v1alpha1/unstructured.go`.

Removes unreachable return statements.

---

cmd/maya-exporter/app/command/command.go
cmd/maya-exporter/app/command/exporter.go
cmd/maya-exporter/app/command/exporter_test.go

-> Add support in  Prometheus handler to get metrics in JSON format. 

feat(exporter): add support in exporter for giving JSON response

---

cmd/cstor-pool-mgmt/pool/pool.go
pkg/client/jiva/controller_client_test.go
types/v1/meta.go

**What this PR does / why we need it**: 
-> Ran make format on maya repo.

refactor(pool.go,controller_client_test.go,meta.go): ran go format on maya repo

---

integration-tests/cstor-pool/cstor_integration_test.go

Signed-off-by: Dilpreet Singh <singhsince94@gmail.com>
Adds test for case 10
Fixes: https://github.com/openebs/openebs/issues/2250
@sonasingh46 @princerachit Please review

Adds integration tests for case 10 sparse-mirrored-auto-spc

---

pkg/task/v1alpha1/http_command.go
pkg/task/v1alpha1/http_command_test.go

**What this PR does / why we need it**:.
-> Add `unmarshal` option in http_command
-> Suggestion for better names is always welcome.

feat(http_command.go): add 'unmarshal' option in http command

---

pkg/volume/volume.go
pkg/volume/volume_template_engine.go

This commit enables volume delete operation to make use of cas config available at PVC, SC to influence the delete logic.
The priority of cas config is as follows:
PVC >> SC >> default

feat(cast): use cas config from PVC & SC for volume delete

---

volume/provisioners/jiva/util.go

Signed-off-by: sachinmukherjee <sachinmukherjee29@gmail.com>
**What this PR does / why we need it**: It fixes golint issue present in the file maya/volume/provisioners/jiva/util.go
**Which issue this PR fixes** : fixes https://github.com/openebs/openebs/issues/2116
**Special notes for your reviewer**: @ashishranjan738 Please review it.

Fixes golit issue in maya/volume/provisioners/jiva/util.go

---

ci/install_openebs.sh
ci/setup_env.sh
ci/snapshot/cstor/busybox.yaml
ci/snapshot/cstor/busybox_clone.yaml
ci/snapshot/cstor/snapshot.yaml
ci/snapshot/cstor/snapshot_claim.yaml
ci/snapshot/jiva/busybox.yaml
ci/snapshot/jiva/busybox_clone.yaml
ci/snapshot/jiva/snapshot.yaml
ci/snapshot/jiva/snapshot_claim.yaml

This commits adds following test in travis CI :
1. Add jiva snapshot and clone related integration tests
2. Add cstor snapshot and clone related integration tests
3. Add required snapshot and busybox application yaml configs files.

test(snapshot-clone): Add snapshot and clone integration tests

---

cmd/maya-apiserver/app/server/http.go
cmd/maya-apiserver/app/server/pool_endpoint_v1alpha1.go
cmd/mayactl/app/command/commands.go
cmd/mayactl/app/command/pool/describe.go
cmd/mayactl/app/command/pool/describe_test.go
cmd/mayactl/app/command/pool/list.go
cmd/mayactl/app/command/pool/list_test.go
cmd/mayactl/app/command/pool/pool.go
cmd/mayactl/app/command/pool/pool_test.go
cmd/mayactl/app/command/volume_info.go
pkg/client/mapiserver/pool.go
pkg/client/mapiserver/pool_test.go
pkg/client/mapiserver/utils.go
pkg/env/v1alpha1/env.go
pkg/install/v1alpha1/env_setter.go
pkg/install/v1alpha1/registrar.go
pkg/install/v1alpha1/storage_pool.go
pkg/storagepool/storagepool.go

-> This will add pool list and describe command to mayactl.
Output of pool list:
```
POOL NAME                  NODE NAME     POOL TYPE
---------                  ---------     ---------
cstor-sparse-pool-qte1     127.0.0.1     striped
```
Output of pool describe:
```
Pool Details :
--------------
Storage Pool Name  : cstor-sparse-pool-qte1
Node Name          : 127.0.0.1
CAS Template Used  : cstor-pool-create-default-0.8.0
CAS Type           : cstor
StoragePoolClaim   : cstor-sparse-pool
UID                : b5a62c11-e8eb-11e8-9ec2-b4b686bd0cff
Pool Type          : striped
Over Provisioning  : false
Disk List :
----------
sparse-5a92ced3e2ee21eac7b930f670b5eab5
```

[US3437] feat(mayactl): add pool list and describe command to mayactl.

---

Gopkg.lock
Gopkg.toml
cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
pkg/usage/size.go
pkg/usage/size_test.go
pkg/usage/usage.go
vendor/github.com/docker/go-units/CONTRIBUTING.md
vendor/github.com/docker/go-units/LICENSE
vendor/github.com/docker/go-units/MAINTAINERS
vendor/github.com/docker/go-units/README.md
vendor/github.com/docker/go-units/circle.yml
vendor/github.com/docker/go-units/duration.go
vendor/github.com/docker/go-units/size.go
vendor/github.com/docker/go-units/ulimit.go

- Provides insight into success/failure of volume creation
- Provides insight by sending volume capcity
issue: https://github.com/openebs/openebs/issues/2257

feat(volume-events) Send volume events when a volume operation is performed

---

.gitlab-ci.yml

Signed-off-by: ksatchit <karthik.s@openebs.io>
- Triggers a separate pipeline for infra chaos on AWS.

(refactor)(ci) triggers additional pipeline for infra chaos on aws patform

---

ci/setup_env.sh
pkg/client/mapiserver/utils.go
pkg/client/mapiserver/volume_delete.go

-> Adds API's status checks in travis.

fix(ci): add maya-api status checks in travis

---

cmd/cstor-pool-mgmt/pool/pool.go
cmd/cstor-pool-mgmt/pool/pool_test.go
pkg/apis/openebs.io/v1alpha1/cstor_pool.go

CSP mapping
Following PR needs to be merged first :
https://github.com/openebs/maya/pull/819

feat(csp): zpool status mapping

---

pkg/client/http/v1alpha1/http_client_test.go
pkg/client/k8s/v1alpha1/config_test.go
pkg/task/v1alpha1/cstor_snapshot_create_test.go
pkg/task/v1alpha1/cstor_snapshot_delete_test.go
pkg/task/v1alpha1/http_command_test.go
pkg/task/v1alpha1/jiva_volume_delete_test.go
pkg/template/runtask_functions_test.go

-> http based UTs were taking time as the http request was going to a valid IP which cause make test to get stuck for some time.
-> Changed valid IPs.

fix(make): Optimized make test time

---

pkg/install/v1alpha1/cstor_pool.go

Make pool deployment strategy to "Recreate" in runtask.

feat(runtask): make pool deployment strategy to "Recreate" in runtask.

---

ci/setup_env.sh

-> Add pool test commands in mayactl.

enhance(ci): add mayactl pool test commands in ci

---

.gitlab-ci.yml

- The cleanup currently is failing to run if the build stage fails. To
fix this the cleanup stage has been set to run always.

fix<gitlab>: Perform the cleanup stage for all passed and failed builds

---

hack/cstor_volume/test/test_5/app.yaml
hack/cstor_volume/test/test_5/description
hack/cstor_volume/test/test_5/pvc.yaml
hack/cstor_volume/test/test_5/sc.yaml
hack/cstor_volume/test/test_5/service-account.yaml
hack/cstor_volume/test/test_5/test-script.sh
hack/cstor_volume/test/vol-test.sh

Tests https://github.com/openebs/maya/pull/838

test(affinity): test if target and workload scheduled on same node

---

.gitlab-ci.yml

Signed-off-by: Chandan Kumar <chandan.kumar@mayadata.io>
Update project-id inside `gitlab-ci.yml` for triggers all platform pipeline

update(yml): Update platform project id inside gitlab-ci.yml

---

cmd/mayactl/app/command/pool/describe_test.go
cmd/mayactl/app/command/pool/list_test.go
cmd/mayactl/app/command/pool/pool.go
cmd/mayactl/app/command/pool/pool_test.go
cmd/mayactl/app/command/volume_create_test.go
cmd/mayactl/app/command/volume_stats_test.go
cmd/mayactl/app/command/volume_test.go

-> Add copyright text in mayactl files.

refactor(mayactl): add copyright text in mayactl files

---

.travis.yml

feat(build): use xenial dist as travis CI image

---

cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go

fixes https://github.com/openebs/openebs/issues/2322

fix(cvr_status): fix cvr invalid status update bug

---

cmd/cstor-pool-mgmt/pool/pool.go
cmd/cstor-pool-mgmt/pool/pool_test.go
cmd/maya-apiserver/spc-watcher/handler.go
cmd/maya-apiserver/spc-watcher/handler_test.go
cmd/maya-apiserver/spc-watcher/select_disk.go
cmd/maya-apiserver/spc-watcher/select_disk_test.go
pkg/apis/openebs.io/v1alpha1/cas_pool.go

- Add support for raidz and raidz2 type
none

[TA4633] feat(pool-mgmt): add raid support in cstor-pool-mgmt

---

.gitlab-ci.yml

- Decrease the number of platform pipelines to 3 for master branch
- Platform for master branches will consist of AKS, EKS and GKE.

Reduce the number of platform pipelines for master branches.

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler_test.go
cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica_test.go
pkg/apis/openebs.io/v1alpha1/cstor_volume_replica.go

This PR contains the cherry-picks for quorum in 0.8.x
Bellow are the PR information of commits:
#901 
#887

fix(travis): cherry pick for quorum

---

.gitlab-ci.yml

- Update pipeline project links for v0.8.x branch.

fix(CI): Update the Gitlab pipelines project links for v0.8.x.

---

cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go

This PR contains cherry-pick of https://github.com/openebs/maya/pull/915

chore(vol-event): cherry-pick from master of PR 915

---

docs/idiomatic-maya-guide.md

This commit tries to explain more about what idiomatic maya is all about. This is intended to be a live document and is currently a work in progress.

docs(contribute, design): add guidelines on idiomatic maya

---

cmd/maya-apiserver/cstor-operator/storagepool_create.go
cmd/maya-apiserver/cstor-operator/storagepool_create_test.go
pkg/algorithm/nodeselect/v1alpha1/config.go
pkg/algorithm/nodeselect/v1alpha1/select_node.go
pkg/algorithm/nodeselect/v1alpha1/select_node_test.go

This PR does following:
1. Improve naming of structs, package etc
2. Improve code comments
3. Fix lints.
Also fixes https://github.com/openebs/openebs/issues/2375

bug_fix:(nodeselect) Improve comments, naming and fix lints and fix maya-apiserver restart at startup.

---

pkg/apis/openebs.io/v1alpha1/cstor_volume.go

Following PR has been cherry-picked:
- feat(troubleshoot): Adds InQuorum field in describe ouput of cstorvolumes #928

feat(troubleshoot): Cherrypick from replication to v0.8.x

---

pkg/install/v1alpha1/cstor_pool.go

Currently, the StoragePool related CRS don't have owner references which can lead to stale resources in K8s when the hierarchy of the storage pools breaks. The hierarchy followed by the StoragePools is ` SPC -> CSP -> Pool Deployment -> SP `. This issue can be solved by using the power of k8s garbage collection. For information regarding this refer to this https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/ .
-> This PR adds owner references to StoragePool and PoolDeployment CR's which can be used by the garbage collector for collecting stale objects.
-> Adding owner references to Resources will delete all the orphaned objects when the parent is deleted which will …

enhance(StoragePool): add owner references to StoragePool related CRs for garbage collection

---

integration-tests/sanity/sanity_suite_test.go
integration-tests/sanity/sanity_test.go

This commit adds sanity package in BDD test

enhance(BDD): adds sanity package in BDD Test

---

integration-tests/artifacts/openebs-ci.go
integration-tests/artifacts/openebs-ci.yaml
integration-tests/kubernetes/kubeclient.go
integration-tests/kubernetes/utils.go
integration-tests/sanity/sanity_suite_test.go
pkg/artifact/v1alpha1/artifact.go

This commit implements BeforeSuite of sanity package integrations-test. The BeforeSuite will install openebs components on the cluster.
-> artifactList has been exported so that it can be used integration-test packages.

enhance(BDD): implements BeforeSuite of sanity

---

integration-tests/kubernetes/kubernetes.go
integration-tests/sanity/sanity_suite_test.go
integration-tests/sanity/sanity_test.go
pkg/client/k8s/v1alpha1/resource.go

1. This commit implements after suite function in sanity package which is responsible for cleanup of openebs components after the test.
2. And also implements delete functionality in resource.go of `pkg/client/k8s/v1alpha1` which will allow deletion of objects using this package.
-> Testing namespace can be overrided by `--namespace` flag.
output of test:
```
=== RUN   TestSource
Running Suite: Sanity
=====================
Random Seed: 1550226072
Will run 0 of 15 specs
P [PENDING]
Sanity
/home/ashishranjan738/Project/go/src/github.com/openebs/maya/integration-tests/sanity/sanity_test.go:8
should create cstor volume
/home/ashishranjan738/Project/go/src/github.com/openebs/maya/integration-tests/sanity/sanity_test.go:9
should apply the …
```

enhance(BDD): implements after suite in sanity package

---

integration-tests/artifacts/cr-schema.yaml
integration-tests/artifacts/cstor-pvc.yaml
integration-tests/artifacts/cvr-schema.yaml
integration-tests/artifacts/jiva-pvc.yaml
integration-tests/artifacts/openebs-ci.go
integration-tests/artifacts/single-replica.yaml
integration-tests/kubernetes/kubernetes.go
integration-tests/sanity/sanity_suite_test.go
integration-tests/sanity/sanity_test.go
pkg/client/k8s/v1alpha1/resource.go

This commit implements sanity BDD test.
output of `go test -v` :
```
=== RUN   TestSource
Running Suite: Sanity
=====================
Random Seed: 1550558999
Will run 19 of 19 specs
• [SLOW TEST:20.024 seconds]
Sanity
/home/ashishranjan738/Project/go/src/github.com/openebs/maya/integration-tests/sanity/sanity_test.go:22
should update storageclass
/home/ashishranjan738/Project/go/src/github.com/openebs/maya/integration-tests/sanity/sanity_test.go:23
should update storageclass wih replica count to 1
/home/ashishranjan738/Project/go/src/github.com/openebs/maya/integration-tests/sanity/sanity_test.go:24
------------------------------
• [SLOW TEST:50.063 seconds]
Sanity
/home/ashishranjan738/Project/go/src/github.com/openebs/maya/integrat …
```

enhance(BDD): implements sanity test

---

.github/PULL_REQUEST_TEMPLATE.md

This commit adds checklist to pull request template which will be
helpful for staying in track during release cycles.

enhance(github): Adds checklist to pull request template

---

pkg/algorithm/cstorpoolselect/v1alpha1/select_test.go

This commit fixes the invalid test cases in UT which was the cause of travis build failure.
This error got injected due to #950 
**Checklist:**

fix(travis): updates invalid UT testcase

---

pkg/algorithm/cstorpoolselect/v1alpha1/select.go
pkg/algorithm/cstorpoolselect/v1alpha1/select_test.go
pkg/cstorpool/v1alpha2/cstorpool_test.go
pkg/cstorvolumereplica/v1alpha1/kubernetes_test.go

This commit adds unit tests for untested functions in select.go file.
**Checklist:**

refactor(select.go): Adds unit test for untested functions

---

pkg/castemplate/v1alpha1/cas_template_engine.go
pkg/castemplate/v1alpha1/cas_template_engine_test.go
pkg/snapshot/v1alpha1/snapshot.go
pkg/snapshot/v1alpha1/snapshot_template_engine.go
pkg/storagepool/storagepool.go
pkg/storagepool/storagepool_template_engine.go
pkg/volume/volume.go
pkg/volume/volume_template_engine.go
pkg/volume/volume_template_engine_test.go

This PR will add support for versionize template engine. Older engine code moved to `alpha1v1` version inside `pkg/castemplate/v1alpha1` folder. If we want to create a new version of castemplate engine with
more support then those code will be inside `pkg/castemplate/v2alpha1` folder.
**Checklist:**

refactor(cast engine): refactor template engine to support package version

---

cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
pkg/client/k8s/k8s.go
pkg/install/v1alpha1/cstor_volume.go
pkg/k8s/from_yaml.go
pkg/task/identity.go
pkg/task/meta.go
pkg/task/task.go

This PR has below cherrypicks:
- fix(cvr delete, finalizer): remove finalizers to ensure successful deletion (#955)
- feat(cast, statefulset): add support for statefulset in castemplate
**Checklist:**

cherry picks to 0.8.x

---

.gitlab-ci.yml

- Remove the unit test runs for maya for GitLab CI pipelines.
**Checklist:**

refactor(gitlab):Remove the integration tests for GitLab CI runs in maya.

---

pkg/algorithm/cstorpoolselect/v1alpha1/select.go
pkg/algorithm/cstorpoolselect/v1alpha1/select_test.go
pkg/cstorpool/v1alpha2/cstorpool.go
pkg/cstorpool/v1alpha2/cstorpool_test.go
pkg/cstorpool/v1alpha2/doc.go
pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica.go
pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica_test.go
pkg/cstorvolumereplica/v1alpha1/kubernetes.go
pkg/cstorvolumereplica/v1alpha1/kubernetes_test.go
pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go
pkg/template/template.go

cherry-pick(cstor, sts): cherry-pick from master

---

pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go

This commit contains the cherry-pick of PR #886 .

chore(provision): cherry-pick of PR #886

---

cmd/maya-exporter/app/collector/zvol/list_test.go

Fixes the Travis failure in the master branch.
To fix the Travis failure in the master branch.
**Checklist:**

Comments the unit test case to fix the travis failure

---

cmd/maya-exporter/app/collector/zvol/list_test.go

Fixes the Travis failure in the v0.8.x branch.
To fix the Travis failure in the v0.8.x branch.
cherry-pick from: https://github.com/openebs/maya/pull/997
**Checklist:**

[cherry-pick] fix(unit test): comments the test case to fix the travis failure (#997)

---

.gitlab-ci.yml

- Enable e2e pipelines to run on openshift
- Maintain separate baseline for specific branches.
**Checklist:**

feat(gitlab-ci): add openshift platform to mdap ci

---

pkg/kubernetes/persistentvolumeclaim/v1alpha1/persistentvolumeclaim.go
pkg/kubernetes/pod/v1alpha1/pod.go

This commit fixes typo in PVC and POD packages of kubernetes.
**Checklist:**

fix(typo): fix typo in pvc and pod packages

---

pkg/install/v1alpha1/cstor_pool.go

This commit adds toleration policy to cstor pool by which users can add taint(s) at kubernetes nodes and corresponding toleration(s) via `cas.openebs.io/config` annotation of StoragePoolClaim. 
Below is an example of SPC for achieving this.
```yaml
metadata:
name: cstor-sparse-pool
annotations:
- name: PoolResourceRequests
value: |-
memory: 0.5Gi
cpu: 100m
- name: PoolResourceLimits
value: |-
memory: 2Gi
cpu: 500m
#- name: AuxResourceLimits
- name: Tolerations
value: |-
t1:
effect: NoSchedule
key: nodeA
operator: Equal
t2:
effect: NoSchedule
key: app
operator: Equal
value: storage
spec:
name: cstor-sparse-pool
type: sparse
maxPools: 3
poolSpec:
```
**Which issue this PR fixes** *(optional, in …

feat(cstorpool, toleration): adds toleration policy for cstor pool pods

---

pkg/install/v1alpha1/cstor_pool.go

This commit adds toleration policy to cstor pool by which users can add taint(s) at kubernetes nodes and corresponding toleration(s) via cas.openebs.io/config annotation of StoragePoolClaim.
Below is an example of SPC for achieving this.
```yaml
metadata:
name: cstor-sparse-pool
annotations:
- name: PoolResourceRequests
value: |-
memory: 0.5Gi
cpu: 100m
- name: PoolResourceLimits
value: |-
memory: 2Gi
cpu: 500m
#- name: AuxResourceLimits
- name: Tolerations
value: |-
t1:
effect: NoSchedule
key: nodeA
operator: Equal
t2:
effect: NoSchedule
key: app
operator: Equal
value: storage
spec:
name: cstor-sparse-pool
type: sparse
maxPools: 3
poolSpec:
poolType: …
```

chore(cherry-pick,cstorpool): Adds toleration policy for cstor pool (#1007)

---

integration-tests/sts/sts_test.go
pkg/algorithm/cstorpoolselect/v1alpha1/select.go
pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica.go
pkg/cstorvolumereplica/v1alpha1/kubernetes.go
pkg/cstorvolumereplica/v1alpha1/kubernetes_test.go

This commit adds check for CVR health in sts BDD, which means the test will proceed only if all the CVRs are in healthy state.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/openebs/issues/2454
**Checklist:**

enhance(BDD): Adds check for CVR health in sts bdd

---

pkg/unstruct/v1alpha2/interface.go
pkg/unstruct/v1alpha2/kubernetes.go
pkg/unstruct/v1alpha2/unstruct.go
pkg/unstruct/v1alpha2/unstruct_test.go

This commit adds a new version of `unstruct package` which has been written in maya
idiomatic fashion.
**Checklist:**

enhance(unstruct): adds new version of unstruct package

---

cmd/mayactl/app/command/volume_info.go
pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go

This commit removes application information from mayactl volume describe command and api server read response.
The commits that gets reverted after this PR:
https://github.com/openebs/maya/commit/cec89577a2492a0929b0cfd2588e126ab333003c
https://github.com/openebs/maya/commit/8321b6f9b5f3dd088f1f2c75c9f43629e50b39bd
https://github.com/openebs/maya/commit/0e9ae16f5ab0dd53da270f5bef6d9bb0864d4340
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/maya/issues/1028
**Checklist:**

refactor(mayactl,runtask): Removes application information from mayactl

---

pkg/unstruct/v1alpha2/unstruct.go
pkg/unstruct/v1alpha2/unstruct_test.go

This commit add list support for unstruct package which will help in operating over list of unstruct object
**Checklist:**

enhance(unstruct): add list support in unstruct package

---

pkg/install/v1alpha1/cstor_pool.go

This reverts commit 4aec97f28ece919b13490d3b06ce096a7013dac0.
-  New changes have been added.
**Checklist:**

fix(pool exporter, revert): remove pool exporter yaml in runTask

---

pkg/install/v1alpha1/cstor_pool.go

What this PR does / why we need it:
This reverts commit 4aec97f.
Special notes for your reviewer:
New changes have been added.
**Checklist:**

revert(exporter): remove pool exporter yaml in RunTask

---

pkg/client/k8s/v1alpha1/resource.go

This PR handles unknown error occured while installing resources. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #https://github.com/openebs/openebs/issues/2491
**Checklist:**

fix(installer): improve error handling during installation of resources

---

GNUmakefile
docs/developer.md

-bump go version to 1.10+ in developer docs
-remove stale 'dev' target from makefile and update the dev docs

refactor(makefile, docs): bumped version of go in developer docs & changes to makefile

---

pkg/cstorpool/v1alpha2/cstorpool.go
pkg/cstorpool/v1alpha2/cstorpool_test.go

- pinned `pool` variable to avoid scopelint
- added ut to test WithAPIList function
**Checklist:**

fix(cstor, pool): fix scopelint errors in cstorpool

---

pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica.go
pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica_test.go

- pinned variable in for loop to avoid scopelint errors
- added ut to test WithFilter function
**Checklist:**

fix(cstorvolumereplica): pin variables to avoid scope related issues

---

GNUmakefile

Add upgrade-image with target all to fix gitlab ci.

chore(gitlab): add upgrade-image with target all

---

.bettercodehub.yml
bettercodehub.yml

This commit fixes BCH config yml file as required by BCH tool.
refer - https://bettercodehub.com/docs/configuration-manual
**Checklist:**

fix(bch, config): rename bettercodehub.yml to .bettercodehub.yml

---

pkg/install/v1alpha1/cstor_pool.go
pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go

This PR adds the openebs.io/version label to the data plane pods.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #https://github.com/openebs/openebs/issues/2516
**Checklist:**

feat(install, cas templates): adds openebs.io/version label to the OpenEBS dataplane components

---

cmd/maya-exporter/app/collector/pool/pool_test.go

This PR remove the flaky unit test from pool exporter.
**Checklist:**

fix(pool-exporter, UT): remove flaky test case

---

pkg/kubernetes/pod/v1alpha1/pod.go
pkg/kubernetes/pod/v1alpha1/pod_test.go

- pinned variable(s) to avoid scopelint errors
- fixed UT to test `WithAPIObjects` function
**Checklist:**

fix(pod, lint): fix scopelint errors in pod package

---

pkg/kubernetes/deployment/appsv1/v1alpha1/deployment.go
pkg/kubernetes/deployment/appsv1/v1alpha1/kubernetes.go
pkg/kubernetes/deployment/appsv1/v1alpha1/rollout_status.go
pkg/kubernetes/deployment/extnv1beta1/v1alpha1/deployment.go
pkg/kubernetes/deployment/extnv1beta1/v1alpha1/kubernetes.go
pkg/kubernetes/deployment/extnv1beta1/v1alpha1/rollout_status.go
pkg/task/identity.go
pkg/task/meta.go

This PR refactors the rollout status code for deployment for both apps/v1 and extensions/v1beta1 apiVersion.
**Checklist:**

refactor(cast, deployment, rollout status): refactor rollout status code of deployment

---

.gitlab-ci.yml

- Enable e2e pipelines to run on openshift

feat[gitlab]: Add openshift platform to mdap ci

---

README.md

Include small and large license badges that provide
details of the license scan of the code and the dependent
libraries.

chore(license): Add FOSSA badges

---

README.md

Update the readme with CII badge.
Also fixed minor doc issue with displaying the links.

chore(badge): Add CII badge

---

cmd/admission-server/main.go

- handled `error` returned by `Shutdown` func
**Checklist:**

fix(lint):fix errcheck in admission-server

---

pkg/install/v1alpha1/cstor_pool.go

This reverts commit 2d1fff111059ba8484e33ff94a73384a33808335.
**Checklist:**

Revert "revert(exporter): add pool exporter yaml in runTask (#1040)"

---

GNUmakefile
docs/developer.md
pkg/cstorpool/v1alpha2/cstorpool.go
pkg/cstorpool/v1alpha2/cstorpool_test.go
pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica.go
pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica_test.go
pkg/kubernetes/pod/v1alpha1/pod.go
pkg/kubernetes/pod/v1alpha1/pod_test.go

This PR fixes some linting errors reported by golangci.
**Checklist:**

cherry-pick(lint, v0.9.x): fix lint errors 

---

pkg/kubernetes/pod/v1alpha1/buildlist.go
pkg/kubernetes/pod/v1alpha1/buildlist_test.go
pkg/kubernetes/pod/v1alpha1/kubernetes.go
pkg/kubernetes/pod/v1alpha1/kubernetes_test.go
pkg/kubernetes/pod/v1alpha1/pod.go
pkg/kubernetes/pod/v1alpha1/pod_test.go

This PR enhances the pod package to support for pod operations(delete and get) by writing wrappers on k8s client-go.
**Checklist:**

feat(pod, idiomatic) add support for pod get and delete operations

---

GNUmakefile
buildscripts/test-cov.sh
integration-tests/framework/v1alpha1/framework.go
integration-tests/sanity/sanity_suite_test.go
integration-tests/sts/sts_suite_test.go
integration-tests/sts/sts_test.go

Include integration-test package in travis unit test.
**Why we need this**:
This will compile the integration-test code.
**Checklist:**

feat(travis, integration-test): Include integration-test package in travis unit test

---

pkg/castemplate/v1alpha1/cas_template_engine.go
pkg/client/mapiserver/utils.go
pkg/kubernetes/deployment/appsv1/v1alpha1/deployment.go
pkg/kubernetes/deployment/extnv1beta1/v1alpha1/deployment.go

- removed unused `err` parameter from `cas_template_engine`
- fixed return value to `body` in `utils`
- removed unused `name` parameter from `deployment`
**Checklist:**

fix(lint):fix unused func param and result issues in pkg

---

ci/travis-ci.sh

Update branch name tag to use 0.9.x based openebs
operator
**Checklist:**

Refact(ci): update branch name tag to 0.9.x

---

pkg/storagepoolclaim/v1beta1/doc.go
pkg/storagepoolclaim/v1beta1/kubernetes.go
pkg/storagepoolclaim/v1beta1/storagepoolclaim.go
pkg/storagepoolclaim/v1beta1/storagepoolclaim_test.go
pkg/storagepoolclaim/v1beta1/validate.go

This PR will add SPC package for SPC version v1beta1
**NOTE:** 
Some validation function work with respect to following a validation pattern and adding more validation functions needs to be done.
This will be taken in later PR -- as while implementing the v1beta provisioning logic, picture will be more vivid wrt validations.

feat(spc): add v1beta1 storagepoolclaim package

---

pkg/kubernetes/persistentvolumeclaim/v1alpha1/buildlist.go
pkg/kubernetes/persistentvolumeclaim/v1alpha1/persistentvolumeclaim.go
pkg/kubernetes/pod/v1alpha1/buildlist.go
pkg/kubernetes/pod/v1alpha1/buildlist_test.go
pkg/kubernetes/storageclass/v1alpha1/buildlist.go

This PR fixes the bug in wrapper over Kubernetes client-go packages.
**Checklist:**

fix(idiomatic): fix kubernetes idiomatic packages

---

docs/idiomatic-maya-guide.md

This PR updates the idiomatic maya guide as per the standards being followed for making maya code idiomatic
**Checklist:**

docs(idiomatic maya): add best practices guide to writing code in idiomatic maya based patterns

---

pkg/client/k8s/k8s.go
pkg/kubernetes/pod/v1alpha1/kubernetes.go
pkg/task/meta.go
pkg/task/task.go

This PR links get pod support in runtask and fix Job get action in runtask.

chore (runtask) : Link get pod support in runtask

---

pkg/client/k8s/k8s.go
pkg/task/identity.go
pkg/task/meta.go
pkg/task/task.go

This PR will add get and patch operation support in CAS Teamplate for cstorpoolcluster resource.

feat(runtask): add get and patch task operation support for cstorpoolcluster

---

pkg/client/k8s/k8s.go
pkg/cstorvolume/v1alpha1/kubernetes.go
pkg/kubernetes/service/v1alpha1/kubernetes.go
pkg/task/meta.go
pkg/task/task.go

This PR adds get support for corev1 service and openebs/v1alpha1 CStor volume in runtask.
**Checklist:**

feat(CAST, runtask): add runtask get support for service and CStor volume

---

pkg/install/v1alpha1/cstor_pool.go

Cherry-Pick of following PR
https://github.com/openebs/maya/pull/1170

feat(runtask, cstorpool) : add csp label to cStor-pool pod

---

pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go

This PR adds the openebs.io/version label to the data plane pods.
**Checklist:**

cherrypick(install): adds openebs.io/version label to the OpenEBS dataplane components (#1066)

---

integration-tests/artifacts/hostpath-pv-pod.yaml
integration-tests/artifacts/sc-hostpath.yaml
pkg/install/v1alpha1/localpv_sc.go
pkg/install/v1alpha1/registrar.go

This PR automates the installation of the Local PV
StorageClass for StorageType=hostpath, as part of the
maya-apiserver startup.

feat(localpv): auto-install localpv hostpath storage class

---

cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go
pkg/apis/openebs.io/v1alpha1/cstor_volume_replica.go

Cherry-Pick of following PR
https://github.com/openebs/maya/pull/1181

cherrypick(cstor_volume_replica) : cvr was not reconciled for status once it  went into error state.

---

pkg/install/v1alpha1/jiva_snapshot.go
pkg/install/v1alpha1/jiva_volume.go

Fixes https://github.com/openebs/openebs/issues/2518
Related Issue: https://github.com/openebs/openebs/issues/1661
There have been some use cases where, users have requested for
an option to deploy the jiva pods in non-user (PVC) namespace.
For example:
- Granting additional privileges to jiva pods to access hostpath
might involve granting privileges to the entire namespace.
- When using backup with velero, on pvc namespace,
even the jiva pod related information is backed up
and during restore - duplicate set of jiva pods will be
created.
This PR introduces a StorageClass Policy for deploying the
jiva pods in OpenEBS Namespace. (Default is false, same
as earlier releases).
The feature has been manually tested, by creating a
storage class with DeployInOpenEBSNamespace enabled.
Performing …

feat(jiva): allow deploying of jiva pods in openebs ns (#1183)

---

pkg/client/k8s/k8s.go
pkg/kubernetes/snapshot/v1alpha1/kubernetes.go
pkg/kubernetes/snapshot/v1alpha1/kubernetes_test.go
pkg/kubernetes/snapshotdata/v1alpha1/kubernetes.go
pkg/kubernetes/snapshotdata/v1alpha1/kubernetes_test.go
pkg/task/identity.go
pkg/task/meta.go
pkg/task/task.go

This PR adds the support to perform various operations on volumesnapshotdata as a part of upgrade. 
**Checklist:**

feat(upgrade): add support for volumesnapshotdata using runtask

---

cmd/cstor-pool-mgmt/controller/common/common.go
cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
cmd/cstor-pool-mgmt/pool/pool.go
pkg/apis/openebs.io/v1alpha1/cstor_pool.go

This PR pushed regular logs in success path of CSP 'Sync' event to higher level. Added few comments in the code about Empty and Pending status of CSP.
It have error handling in the case of errors during setting cache file or getting volume list.
**Checklist:**

fix(logs): increased log level for regular logs

---

tests/cstor/snapshot/snapshot_test.go
tests/cstor/snapshot/suite_test.go
tests/cstor/volume/provision_test.go
tests/cstor/volume/suite_test.go
tests/operations.go

Add cstor volume snapshot related BDD tests
```
ginkgo -v -- -kubeconfig=/var/run/kubernetes/admin.kubeconfig
Running Suite: Test cstor volume snapshots provisioning
Random Seed: 1558719740
[cstor] TEST SNAPSHOT PROVISIONING when cstor pvc with replicacount 1 is created 
/home/prateek/gocode/src/github.com/openebs/maya/tests/cstor/snapshot/snapshot_test.go:90
STEP: building object of storageclass
STEP: …
```

feat(cstor, snapshot): add cstor volume snapshots BDD

---

tests/upgrade/0.8.2-0.9.0/jiva/suite_test.go
tests/upgrade/0.8.2-0.9.0/jiva/volume_test.go

This PR adds a check that verify after upgrade the controller pod has the same number of replicas connected as the replica count.
```
user:jiva$ ginkgo -v -- -kubeconfig=/home/user/.kube/config -replicas=1
Running Suite: Test jiva volume upgrade
=======================================
Random Seed: 1559121536
STEP: applying openebs 0.8.2
STEP: creating above storageclass
STEP: building a pvc
STEP: creating above pvc
STEP: verifying controller pod count 
STEP: verifying replica pod count 
STEP: verifying status as bound
[jiva] TEST VOLUME UPGRADE when jiva pvc is …
```

refact(bdd): added check for registered jiva replica count after upgrade

---

pkg/kubernetes/deployment/appsv1/v1alpha1/deployment.go
pkg/kubernetes/deployment/appsv1/v1alpha1/kubernetes.go
pkg/kubernetes/deployment/appsv1/v1alpha1/rollout_status.go
pkg/task/task.go
tests/kubernetes/deployment/app_test.go
tests/kubernetes/deployment/suite_test.go
tests/operations.go

This PR adds a BDD which launches a simple busybox application and verifies the pod status.
**Sample test output**
```
user:deployment$ ginkgo -v -- -kubeconfig=/home/user/.kube/config 
Running Suite: Test application deployment
==========================================
Random Seed: 1559210295
Will run 2 of 2 specs
TEST DEPLOYMENT CREATION  when deployment with busybox image is created 
should create a deployment and a running pod
/home/user/work/src/github.com/openebs/maya/tests/deployment/app_test.go:43
STEP: building a container
STEP: building a deployment
STEP: creating above deployment
STEP: verifying pod count as 1
• [SLOW TEST:26.419 …
```

feat(bdd, deploy): BDD to launch an application

---

pkg/install/v1alpha1/openebs_crds.go

Install BlockDevice and BlockDeviceClaim CRDs from maya api-server.
This PR adds blockdevice(BD) and blockdeviceclaim(BDC) crd spec into maya, so that the CRDs are installed by the m-apiserver.
**Checklist:**

fix(install): install BlockDevice and BlockDeviceClaim CRDs

---

.gitlab-ci.yml

- Enable e2e pipelines to run on openshift for v1.0.x branch

feat(gitlab-ci): Add openshift platform to mdap ci for v1.0.x branch

---

cmd/maya-apiserver/app/command/start.go

This commit adds a log to indicate successful installation of openebs resources.
In addition, it makes use of maya's error package which is better in terms of reporting root causes via stacktrace.
**Checklist:**

chore(log, install): add log for successful installation of resources

---

cmd/maya-apiserver/app/command/start.go

This commit adds a log to indicate successful installation of openebs resources.
In addition, it makes use of maya's error package which is better in terms of reporting root causes via stacktrace.
**Checklist:**

cherry-pick(log, install): add log for successful installation of resources (#1240)

---

pkg/blockdeviceclaim/v1alpha1/build.go

This PR is to fix builder pattern to build blockdevice claim.
**Checklist:**

fix(builder, bdc): fix builder pattern to build blockdevice claim

---

cmd/provisioner-localpv/app/helper_blockdevice.go

When a PVC with Local PV host device is triggered,
Local PV provisioner will create BDC and waits
for 60 seconds to get the BD attached. Post that
it returns the control back to K8s.
K8s will re-attempt to create a PV, and in
the second iteration - the Local PV provisioner
will check if the BDC was already created
and will try to re-use it instead of creating another one.
Creating another BDC, in the setup where BD/BDC takes
longer will never result in PV getting created. Also,
timing out and reporting the error to user will make the
process intuitive when BD/BDC process is taking longer.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close …

fix(localpv): handle case of BDC-BD taking longer time

---

cmd/cstor-pool-mgmt/controller/common/common.go
cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go
cmd/cstor-pool-mgmt/controller/replica-controller/run_replica_controller.go

This commit has following changes:
- remove the check where reconcile was avoided in case of previous delete failures
- reduce instances of log flooding
- improve log messages
- modify & indent code to make it more readable
- https://github.com/openebs/maya/pull/1256
This commit tries to fix the symptom 2 talked in PR 1256
**Checklist:**

fix(cvr, delete): ensure cvr gets deleted during reconcile

---

pkg/algorithm/nodeselect/v1alpha1/select_node.go
pkg/blockdeviceclaim/v1alpha1/build.go

This PR fixes typo in builder pattern of block device claim from openebs.io/version --> openebs.io/v1alpha1
**Checklist:**

fix(blockdeviceclaims): fix openebs version type in blockdeviceclaim

---

tests/cstor/clone/clone_test.go
tests/cstor/clone/suite_test.go

Change verifies the data consistency between source and clone
cstor volume using busybox application.
**Checklist:**

feat(bdd,cstor): enhance cstor volume data integrity tests

---

tests/cstor/snapshot/snapshot_test.go

This PR fixes cstor snapshot BDD to take flag values at verification of csps.
**Checklist:**

fix(bdd, cstor) fix poolCount verification to take values from flag

---

GNUmakefile
pkg/blockdevice/v1alpha2/kubernetes.go
pkg/kubernetes/deployment/appsv1/v1alpha1/deployment.go
pkg/kubernetes/persistentvolumeclaim/v1alpha1/build.go
pkg/kubernetes/persistentvolumeclaim/v1alpha1/build_test.go
pkg/kubernetes/persistentvolumeclaim/v1alpha1/buildlist.go
pkg/kubernetes/persistentvolumeclaim/v1alpha1/kubernetes.go
pkg/kubernetes/persistentvolumeclaim/v1alpha1/kubernetes_test.go
pkg/kubernetes/pod/v1alpha1/kubernetes.go
pkg/kubernetes/pod/v1alpha1/kubernetes_test.go
tests/cstor/clone/clone_test.go
tests/cstor/clone/suite_test.go
tests/cstor/pool/negative/provision_without_disk_test.go
tests/cstor/snapshot/snapshot_test.go
tests/cstor/volume/provision_bulk_test.go
tests/exporter/exporter_test.go
tests/jiva/clone/provision_test.go
tests/jiva/volume/provision_test.go
tests/jiva/volume/suite_test.go
tests/kubernetes/deployment/app_test.go
tests/localpv/hostdevice_test.go
tests/localpv/hostpath_test.go
tests/localpv/suite_test.go
tests/operations.go

cherry-pick PR's #1287 #1277 #1276 #1272 #1271 #1279

Cherry-pick #1287 #1277 #1276 #1272 #1271

---

cmd/provisioner-localpv/app/provisioner.go
pkg/usage/const.go

- Collecting anonymous information about local-pv provisioning
fixes: https://github.com/openebs/openebs/issues/2257
**Checklist:**

feat(usage) Initial code to send localpv analytics

---

Gopkg.lock
pkg/kubernetes/node/v1alpha1/kubernetes.go
pkg/kubernetes/node/v1alpha1/kubernetes_test.go
pkg/kubernetes/node/v1alpha1/node.go
pkg/kubernetes/node/v1alpha1/node_test.go

feat(cordon,taint): add builder pattern for node taint and cordon

---

cmd/provisioner-localpv/app/helper_hostpath.go
cmd/provisioner-localpv/app/provisioner_hostpath.go
pkg/kubernetes/persistentvolume/v1alpha1/build.go
pkg/kubernetes/persistentvolume/v1alpha1/build_test.go
pkg/kubernetes/persistentvolume/v1alpha1/kubernetes.go
pkg/kubernetes/persistentvolume/v1alpha1/persistentvolume.go

This PR moves the logic to parse the PV attributes to
PV helper pkg.

refactor(localpv): move the pv parsing to pv helper package

---

pkg/apis/openebs.io/v1alpha1/cstorpool_cluster.go
pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/cstorpoolcluster.go
pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/fake/fake_cstorpoolcluster.go
pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/fake/fake_openebs.io_client.go
pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/openebs.io_client.go
pkg/client/generated/informers/externalversions/openebs.io/v1alpha1/cstorpoolcluster.go
pkg/client/generated/informers/externalversions/openebs.io/v1alpha1/interface.go
pkg/client/generated/listers/openebs.io/v1alpha1/cstorpoolcluster.go
pkg/client/generated/listers/openebs.io/v1alpha1/expansion_generated.go
pkg/client/k8s/k8s.go
pkg/install/v1alpha1/openebs_crds.go

This PR moves CSPC to namespace scope.

feat(cstor-operator): move CSPC to namespace scope

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler.go

This PR imports the cStor-pool in case of pool pod restarts, cstor-pool container restarts and at upgrade time.
**During upgrade time:**
At the time of upgrade to honour csp schema changes we are doing upgrade of cstor pools in below way:
1. Patch the cstor pool deployment with new images and required changes.
2. Patch the csp with new schema changes.
Due to this cstor-pool-mgmt undergoes restarts due to unavailability of pool in cstor-pool container to fix this we are importing the pool if it not found.  
**Special notes for your …

fix(cstor-pool-mgmt): import cstor pool using UID in CSP object without reading disklist

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler.go

This PR import cstor pool using UID in CSP object without reading disklist.
**Checklist:**

[cherry-pick] fix(cstor-pool-mgmt): import cstor pool using UID in CSP object without reading disklist

---

pkg/kubernetes/client/v1alpha1/client.go
pkg/kubernetes/deployment/appsv1/v1alpha1/kubernetes.go

This commit refactors kubernetes client and deployment packages as
per idiomatic maya standards:
- All lines of code within 80 chars
- All code comments within 80 chars
- Add sync.Once to get singleton client instance
- Refactor code to make it readable
**Checklist:**

refactor(k8s client): update k8s packages based on idiomatic maya

---

pkg/kubernetes/service/v1alpha1/build.go
pkg/kubernetes/service/v1alpha1/kubernetes.go
pkg/kubernetes/service/v1alpha1/service.go
pkg/task/task.go

This PR adds builder pattern for the service object.
TODO: Add unit tests.
**Checklist:**

feat(builder) added builder pattern for service object

---

pkg/cstorvolume/v1alpha1/build.go
pkg/cstorvolume/v1alpha1/build_test.go
pkg/cstorvolume/v1alpha1/kubernetes.go
pkg/cstorvolume/v1alpha1/kubernetes_test.go

This PR adds builder pattern for the cstorvolume object.
**Checklist:**

feat(builder) added builder pattern for cstorvolume

---

pkg/algorithm/cstorpoolselect/v1alpha1/select.go
pkg/cstorvolumereplica/v1alpha1/build.go
pkg/cstorvolumereplica/v1alpha1/build_test.go
pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica.go
pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica_test.go
pkg/cstorvolumereplica/v1alpha1/kubernetes.go
pkg/cstorvolumereplica/v1alpha1/kubernetes_test.go
tests/operations.go
tests/sts/sts_test.go

This PR adds builder pattern for cstorvolumereplica object.
**Checklist:**

feat(builder) added builder pattern for cstorvolumereplica

---

cmd/provisioner-localpv/app/helper_hostpath.go
pkg/kubernetes/container/v1alpha1/container.go
pkg/kubernetes/container/v1alpha1/container_test.go
pkg/kubernetes/volume/v1alpha1/build.go
pkg/kubernetes/volume/v1alpha1/build_test.go
tests/cstor/clone/clone_test.go
tests/jiva/clone/provision_test.go
tests/kubernetes/deployment/app_test.go
tests/localpv/hostdevice_test.go
tests/localpv/hostpath_test.go

This PR adds functions required for creating cstor volumes.
**Checklist:**

refact(builder) added new methods to volume and container builder

---

cmd/maya-apiserver/cstor-operator/cspc/handler.go
cmd/maya-apiserver/cstor-operator/cspc/storagepool_create.go
pkg/algorithm/nodeselect/v1alpha2/pool.go

This PR will add reconciliation for pool deployment.

chore(cstor-operator,cspc) : add pool deployment reconciliation

---

cmd/maya-apiserver/app/command/start.go
pkg/install/v1alpha1/openebs_crds.go

This PR will disable CSPC controller

chore(maya): disable cspc controller and remove cspc artifacts

---

cmd/maya-apiserver/cstor-operator/spc/controller.go
cmd/maya-apiserver/cstor-operator/spc/handler.go
pkg/algorithm/nodeselect/v1alpha1/select_node.go
pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim.go
pkg/blockdeviceclaim/v1alpha1/kubernetes.go
pkg/cstor/pool/v1alpha3/kubernetes.go
pkg/storagepoolclaim/v1alpha1/storagepoolclaim.go
tests/cstor/pool/reconciliation/reconciliation_test.go
tests/cstor/pool/reconciliation/suite_test.go
tests/operations.go

This PR handles finalizer removal in case of SPC deletion.

chore(spc, bdc finalizer): finalizer handling in spc deletion

---

cmd/maya-exporter/app/collector/collector.go
cmd/maya-exporter/app/collector/jiva.go
cmd/maya-exporter/app/collector/metrics.go
pkg/stats/v1alpha1/stats.go

Add client status in exporter metrics, this is useful in identifying
whether a client is connected to jiva target or not.
Depends on: openebs/jiva#233, openebs/gotgt#22
**Checklist:**

feat(exporter): add jiva target client status

---

pkg/install/v1alpha1/openebs_crds.go

This PR adds upgrade task CRD to openebs crds list in pkg/install so that it can also be applied/created during maya installation along with other openebs crds.
**Checklist:**

cherry-pick(upgrade): add upgradetask crd to openebs crds list (#1359)

---

cmd/cstor-pool-mgmt/pool/v1alpha2/disk_operation.go
cmd/cstor-pool-mgmt/pool/v1alpha2/modify.go
cmd/maya-apiserver/app/command/start.go
cmd/maya-apiserver/cstor-operator/cspc/handler.go
cmd/maya-apiserver/cstor-operator/cspc/operations.go
cmd/maya-apiserver/cstor-operator/cspc/storagepool_delete.go
pkg/cstor/newpool/v1alpha3/cstorpool.go
pkg/cstor/newpool/v1alpha3/kubernetes.go

TODO: PR description
**Checklist:**

[WIP] feat(cspc,cstor-operator) : add support for cStor pool expansion and deletion.

---

cmd/maya-apiserver/cstor-operator/spc/controller.go
cmd/maya-apiserver/cstor-operator/spc/runner.go
cmd/provisioner-localpv/app/backward_compatability.go
cmd/provisioner-localpv/app/start.go
pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim.go
pkg/blockdeviceclaim/v1alpha1/build.go
pkg/blockdeviceclaim/v1alpha1/kubernetes.go
pkg/storagepoolclaim/v1alpha1/kubernetes.go
pkg/storagepoolclaim/v1alpha1/storagepoolclaim.go
pkg/storagepoolclaim/v1alpha1/upgrade.go
tests/cstor/pool/reconciliation/reconciliation_test.go
tests/cstor/pool/reconciliation/suite_test.go
tests/localpv/hostdevice_test.go
tests/localpv/suite_test.go
tests/operations.go

This PR is cherry-pick of #1357 and #1364 
It adds finalizers on BDCs that are used by SPC and local pv provisioned PVs.
**Checklist:**

feat(upgrade): set finalizers on BDCs related to SPCs and localPV provisioned PVs as 1.1 preupgrade

---

cmd/upgrade/main.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/csp_upgrade.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/cstor_volume_upgrade.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/exec.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/helper.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/jiva_upgrade.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/spc_upgrade.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/template.go

This PR
- added flag to support base image url and image tag changes
- added support for RC builds to execute from same pkg
- added proper wrapping of errors
- refactored the code into smaller files
```
user:maya$ upgrade 1.0.0 1.1.0-RC1 jivaVolume pvc-b6b6f5fb-aec4-11e9-93a1-42010a8000ec openebs xyz/openebsnew/ 1.0-latest
--  failed to rollout replica update in-progress: 0 of 1 updated replicas are available
```
This commands replaces the existing baseImage to given image url prefix and image tag.
**Note : Assuming that the image name remains the same and only the url to the directory is provided**
Before upgrade
```
containers:
- args:
- replica
- --frontendIP
- 10.0.66.50
- --size
- 4G
- …
```

refact(upgrade): added support for base image url and image tag flags

---

pkg/upgrade/1.0.0-1.1.0/v1alpha1/cstor_volume_upgrade.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/helper.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/spc_upgrade.go

This PR fixes the missing length checks required after listing a resource to avoid any index out of bound errors or false positives.
**Checklist:**

fix(upgrade): added missing checks for listed resources

---

pkg/upgrade/v1alpha2/kubernetes.go
pkg/upgrade/v1alpha2/kubernetes_test.go

This PR adds `kubeclient` to perform different CRUD actions on the `upgradetask` CR for upgrade.
**Checklist:**

feat(upgrade): added KubeClient for UpgradeTask CR

---

pkg/apis/openebs.io/upgrade/v1alpha1/upgradetask.go

This PR fixes the mismatch between the schema field and the json tagging for `options` field.
**Checklist:**

 fix(upgrade): fixed json tagging for options field 

---

cmd/maya-apiserver/cstor-operator/cspc/handler.go
pkg/apis/openebs.io/v1alpha1/cstorpool_cluster.go
pkg/webhook/admission_response.go
pkg/webhook/cspc.go
pkg/webhook/webhook.go

This PR adds validation for CSPC create and update.
**Checklist:**

feat(cspc validation webhook): adds validation webhook module for CSPC

---

GNUmakefile
buildscripts/cspi-mgmt/Dockerfile
buildscripts/cspi-mgmt/entrypoint.sh
cmd/cspc-operator/app/storagepool_create.go
cmd/cspi-mgmt/app/controller.go
cmd/cspi-mgmt/app/handler.go
cmd/cspi-mgmt/app/runner.go
cmd/cspi-mgmt/app/start.go
cmd/cspi-mgmt/app/utils.go
cmd/cspi-mgmt/main.go

This PR decouples cspi-mgmt from cstor-pool mgmt

chore(cspi-mgmt): decouple cspi mgmt from cstor-pool mgmt

---

.gitlab-ci.yml

- Triggers e2e-pipelines on konvoy cluster on successful maya build.
**Checklist:**

feat(gitlab ci): trigger e2e on konvoy pipelines

---

GNUmakefile

chore(makefile): fix make file cspi-mgmt image

---

tests/cstor/pool/negative/provision_without_disk_test.go

This PR fixes the negative cstor pool provisioning without a disk.
**Checklist:**

fix(BDD, cstor): fix negative cstor pool provisioning test

---

cmd/cspc-operator/app/storagepool_create.go
cmd/cspi-mgmt/app/handler.go
cmd/cspi-mgmt/app/start.go
cmd/cstor-pool-mgmt/controller/common/common.go
cmd/cstor-pool-mgmt/controller/common/common_test.go
cmd/cstor-pool-mgmt/pool/v1alpha2/delete.go
cmd/cstor-pool-mgmt/pool/v1alpha2/import.go
cmd/cstor-pool-mgmt/pool/v1alpha2/pool_utils.go
pkg/zfs/cmd/v1alpha1/zpool/import/builder.go

fix(cspc-operator): zpool import in case of single pool failure

---

cmd/cstor-pool-mgmt/pool/pool.go

cstor-pool-mgmt, currently, creates pool by looking at state of CSP. API that creates the pool currently just checks for any importable pool but not for imported pools.
Even though state is maintained fine in the code, its better if API can check for imported pools as well before attempting to create the pool.
This PR is to check for any imported pools as well before creating one.
**Checklist:**

fix(pool_create): check for imported pool before creating it

---

cmd/cspc-operator/app/storagepool_create.go

fix(cspc-operator): get cspc name from cspi labels instead of annotations (#1428)

---

cmd/cstor-pool-mgmt/pool/pool.go

cherry-pick #1427 
**Checklist:**

fix(pool_create): check for imported pool before creating it (#1427)

---

pkg/install/v1alpha1/openebs_crds.go

This PR removes the CSPC CRD from the maya install pkg. This installation is crashing the maya-apiserver. 
The CSPC CRD will be installed by the cspc operator yaml. We will provide an installation instruction for CSPC to remove old CRD
**Checklist:**

fix(upgrade): removed cspc crd from openebs_crds

---

cmd/cstor-pool-mgmt/volumereplica/volumereplica.go

Changes:
- Fixing pool name for cStor restore command
Removing `poolPrefix(cstor-)` from `buildVolumeRestoreCommand` since `PoolNameFromRestore` is already taking care of that
- Also fixing error reporting for cStor backup/restore
**Checklist:**

fix(restore): fixing pool name for cStor restore command

---

cmd/cspi-mgmt/app/controller.go
cmd/cspi-mgmt/app/handler.go
cmd/cstor-pool-mgmt/pool/v1alpha2/create.go
cmd/cstor-pool-mgmt/pool/v1alpha2/delete.go
cmd/cstor-pool-mgmt/pool/v1alpha2/disk_operation.go
cmd/cstor-pool-mgmt/pool/v1alpha2/import.go
cmd/cstor-pool-mgmt/pool/v1alpha2/modify.go
cmd/cstor-pool-mgmt/pool/v1alpha2/pool_utils.go
pkg/apis/openebs.io/zpool/v1alpha1/pool_topology.go
pkg/zfs/cmd/v1alpha1/zpool/dump/builder.go
pkg/zfs/cmd/v1alpha1/zpool/dump/utils.go
pkg/zfs/cmd/v1alpha1/zpool/dump/utils_test.go

cherry-pick for #1431 
**Checklist:**

cherry-pick(cspi, replaceDisk): removing partition suffix from vdev path (#1431)

---

cmd/cstor-pool-mgmt/volumereplica/volumereplica.go

cherry-pick for #1437 
**Checklist:**

cherr-pick(restore): fixing pool name for cStor restore command #1437

---

pkg/install/v1alpha1/openebs_crds.go

This PR adds the cherry-pick for PR #1434 .
**Checklist:**

fix(upgrade): removed cspc crd from openebs_crds (#1434)

---

pkg/apis/openebs.io/v1alpha1/cstor_volume.go
pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
pkg/cstor/volume/v1alpha1/cstorvolume.go

fix(cstor-volume-mgmt): convert cstorvolume trusty replica data type

---

pkg/blockdevice/v1alpha2/blockdevice.go
tests/csi/cstor/volume/utils.go
tests/cstor/cspc/positive/provisioning/cspc_provisioning_utils_test.go
tests/cstor/cspc/positive/provisioning/provisioning_test.go
tests/cstor/cspc/positive/provisioning/suite_test.go
tests/operations.go

This PR adds positive test cases for CSPC provisioning.

feat(cspc_provisioning_bdd) : add positive bdd test cases for cspc provisioning

---

cmd/maya-agent/types/doc.go

https://github.com/openebs/openebs/issues/2148
Signed-off-by: wenzdey <56051809+wenzdey@users.noreply.github.com>
**Checklist:**

Fixed golint issue in doc.go #2148

---

cmd/cstorvolumeclaim/cstorvolumeclaim.go
pkg/cstor/volumereplica/v1alpha1/build.go
pkg/cstor/volumereplica/v1alpha1/cstorvolumereplica.go
pkg/cstor/volumereplica/v1alpha1/kubernetes.go
pkg/storagepoolclaim/v1alpha1/kubernetes.go
tests/admission/admission_test.go
tests/cstor/clone/clone_test.go
tests/cstor/node-selector/volume_selector_test.go
tests/cstor/pool/negative/invalid_config_test.go
tests/cstor/pool/negative/invalid_storageclass_test.go
tests/cstor/pool/negative/provision_without_disk_test.go
tests/cstor/pool/reconciliation/reconciliation_test.go
tests/cstor/snapshot/snapshot_test.go
tests/cstor/volume/provision_bulk_test.go
tests/cstor/volume/provision_test.go
tests/cstor/volume/sclaeup_replica/scaleup_replica_test.go
tests/cstor/volume/sclaeup_replica/scaleup_replica_utils_test.go
tests/cstor/volume/sclaeup_replica/suite_test.go
tests/exporter/exporter_test.go
tests/operations.go

This PR adds a positive case of cStor scaleup replica BDD test.
**Steps to Run BDD**
1. Clone maya repo (git clone https://github.com/openebs/maya.git)
2. cd maya/tests/cstor/volume/sclaeup_replica
3. ginkgo -v -- -kubeconfig=/home/sai/.kube/config -cstor-maxpools=3
**Checklist:**

feat(scaleup replica, cstor): add scaleup replica bdd test for cstor

---

.travis.yml

Commit remove travis github deploy as its not required further

refact(travis): remove travis github release deploy

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-volume-mgmt/controller/volume-controller/handler.go
cmd/cstor-volume-mgmt/volume/volume.go
cmd/cstor-volume-mgmt/volume/volume_test.go
cmd/maya-apiserver/cstor-operator/spc/handler.go
pkg/upgrade/upgrader/csp_upgrade.go
pkg/upgrade/upgrader/cstor_volume_upgrade.go
pkg/upgrade/upgrader/spc_upgrade.go

This PR fixes multiple restart of cstor target pod while upgrade.
#1478 
**Checklist:**

cherry-pick(upgrade): fix multiple restart of target pod while upgrade 

---

cmd/cspc-operator/app/handler.go

This PR fixes nil object fields access  when an error happens
while populating version details on cspc object
**Checklist:**

fix(cspc operator): fix bug while populating version details on cspc

---

cmd/cspc-operator/app/storagepool_create.go

This is cherry-pick of https://github.com/openebs/maya/pull/1481
**Checklist:**

feat(CA): safe-to-evict to false to disable scaledown for CSPI pods

---

cmd/cstor-volume-mgmt/volume/volume.go
pkg/apis/openebs.io/v1alpha1/cstor_volume.go
pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
pkg/cstor/volume/v1alpha1/cstorvolume.go
tests/cstor/volume/replica_replace/replica_replace_utils_test.go
tests/cstor/volume/scaleup_replica/scaleup_replica_utils_test.go

This PR adds known replicas information in the spec section of cstor-volume CR.
With this PR we are maintaining trusty/known replica information in the spec
as well as the status of cstorvolume. Known replica list under spec or status
will be updated by cstor-volume-mgmt only when cstor-istgt send request to 
cstor-volume-mgmt.
**Why we need to maintain in KnownReplicas information in the spec:**
This is needed operator/user will remove known replica information under
spec section of cStorvolume(during replica scaledown scenario).
**Why we need to maintain in KnownReplicas information in the status:**
This is needed to know whether scaledown operation is successful or
not(When scaledown is …

chore(cstor-volume-mgmt): add knownreplicas information in spec of cstor volume

---

CONTRIBUTING.md

Signed-off-by: Ayan Banerjee <ayanbn7@gmail.com>
**What this PR does / why we need it**:  Fixed `familiar` typo.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1494
**Checklist:**

CONTRIBUTING.md: Fix typo of `familiar`

---

cmd/provisioner-localpv/app/helper_hostpath.go

Signed-off-by: Rounak Agarwal <rounakr.ag73@gmail.com>
**What this PR does / why we need it**: This PR makes our codebase more maintainable and improves Better Code Hub's Write Short Units of Code guideline rating!
**Which issue this PR fixes** : fixes #1162 
**Special notes for your reviewer**: In PR #1162, it was asked to refactor `Provisioner.createCleanupPod` which originally existed in `helper.go` but now it is present in `helper_hostpath.go`
**Checklist:**

refactor helper_hostpath.go

---

cmd/cstorvolumeclaim/controller.go
cmd/cstorvolumeclaim/cstorvolumeclaim.go
cmd/cstorvolumeclaim/cstorvolumedeployment.go
pkg/apis/openebs.io/v1alpha1/cstor_volume_claim.go
pkg/cstor/volume/v1alpha1/build.go
pkg/cstor/volumereplica/v1alpha1/build.go
pkg/webhook/webhook.go

This PR adds the following changes to cstor volumes provisioned using csi:
1. Add "isClone" label and "sourceVolume" and "SourceSnapshot" annotations to cvr resource for clone creation.
2. Add "volume-source" label to cstorvolume resource and cvc resource for validation webhook to avoid source volume deletion if clone volume exists.
Signed-off-by: Payes <payes.anand@mayadata.io>

feat(clone): Implement clone feature for cstor via CSI

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-volume-mgmt/controller/volume-controller/handler.go
cmd/maya-apiserver/cstor-operator/spc/handler.go
cmd/upgrade/executor/cstor_spc.go
cmd/upgrade/executor/cstor_volume.go
cmd/upgrade/executor/jiva_volume.go
cmd/upgrade/executor/options.go
cmd/upgrade/executor/resource.go
pkg/apis/openebs.io/v1alpha1/versionDetails.go

This PR adds the support for upgrade from 1.0.0 onward to 1.4.0. 
TODO : Design a more efficient way to register new version. 
**Checklist:**

refact(upgrade): add support for 1.4.0 upgrade

---

cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica_test.go
cmd/upgrade/executor/cstor_spc.go
pkg/apis/openebs.io/v1alpha1/cstor_volume_replica.go

This PR is cherry-picking of #1514
**Checklist:**

fix(CVR status): update CVR phase based on quorum/nonquorum scenario (#1514)

---

tests/cstor/volume/scaleup_replica/scaleup_replica_test.go
tests/cstor/volume/scaleup_replica/scaleup_replica_utils_test.go
tests/operations.go

This PR does the following changes to existing replica scaleup BDD
1. Add positive flow BDD for the replica scaledown feature.
2. Fix flaky issue of replica scaleup BDD.
**Checklist:**

chore(BDD, replica scaledown): add positive flow BDD for replica scaledown feature

---

pkg/upgrade/upgrader/exec.go

Cherry-pick the PR 
fix(upgrade): handle errors for upgradeTask CR (#1518)
**Checklist:**

cherry-pick(upgrade): fix for wrong error logging 

---

pkg/kubernetes/secret/kubernetes.go
pkg/kubernetes/webhook/validate/v1alpha1/kubernetes.go
pkg/webhook/configuration.go

refact(admission): automate deletion of older config (#1521)

---

pkg/upgrade/templates/v1/cstor_pool.go

This PR cherry-picks fix(upgrade): update livenessprobe command for cstor pools #1523 
**Checklist:**

cherry-pick(upgrade): liveness probe command patch

---

pkg/webhook/configuration.go

This change requires in case of helm chart where deployment
name can be changed in automated env's in some cases.
Use admission deployment labels to get the deployment object
to create the OwnerReference to set in created admission
configuration and resources.
**Checklist:**

refact(admission): use admission label to get the deployment

---

cmd/upgrade/executor/cstor_spc.go
cmd/upgrade/executor/cstor_volume.go
cmd/upgrade/executor/jiva_volume.go
cmd/upgrade/executor/options.go
cmd/upgrade/executor/setup_job.go
pkg/kubernetes/deployment/appsv1/v1alpha1/deployment.go
pkg/upgrade/upgrader/csp_upgrade.go
pkg/upgrade/upgrader/cstor_volume_upgrade.go
pkg/upgrade/upgrader/exec.go
pkg/upgrade/upgrader/helper.go
pkg/upgrade/upgrader/jiva_upgrade.go
pkg/upgrade/upgrader/spc_upgrade.go
pkg/upgrade/v1alpha2/kubernetes.go

This PR improves the error reporting and pre-flight checks for the upgrade. The mismatch of `errors` package import was causing loss of error messages. This PR makes the import consistent for all files.
**Checklist:**

fix(upgrade): improve logs and pre-upgrade checks

---

pkg/kubernetes/job/v1alpha1/build.go
pkg/kubernetes/volume/v1alpha1/build.go

- This is a PR for builder functions present in pkg/kubernetes
- Some testing is done, by checking the creation of Volume
- Have set the volume name to be the respective resource Name (for right now,  please comment on the PR, if some modification is needed)
**Checklist:**

refact(k8s-volumes): add configMap & secret based volume builder 

---

pkg/webhook/bd_replacement.go

This PR cherry picks https://github.com/openebs/maya/pull/1547 

fix(bd_replalcment): cherry pick validation bug fix PR (#1547)

---

pkg/upgrade/upgrader/helper.go
pkg/upgrade/upgrader/helper_test.go

This PR is to cherry-pick #1557.
**Checklist:**

cherry-pick(upgrade): add support for images having more than one ":" (#1557)

---

pkg/storagepoolclaim/v1alpha1/storagepoolclaim.go
tests/admission/admission_test.go
tests/cstor/clone/clone_test.go
tests/cstor/node-selector/volume_selector_test.go
tests/cstor/pool/negative/invalid_config_test.go
tests/cstor/pool/negative/invalid_storageclass_test.go
tests/cstor/pool/negative/provision_without_disk_test.go
tests/cstor/pool/negative/provision_without_pool.go
tests/cstor/pool/reconciliation/reconciliation_test.go
tests/cstor/snapshot/snapshot_test.go
tests/cstor/volume/provision_bulk_test.go
tests/cstor/volume/provision_negative_test.go
tests/cstor/volume/provision_test.go
tests/cstor/volume/replica_replace/replica_replace_test.go
tests/cstor/volume/scaleup_replica/scaleup_replica_test.go
tests/exporter/exporter_test.go
tests/operations.go

- This commit will fix the test cases related to the PR #1597 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes openebs/openebs#2855
**Checklist:**
Signed-off-by: chandan kumar <chandan.kr404@gmail.com>

test(spc): Fix the test related to the PR #1597

---

cmd/cspc-operator/app/storagepool_create.go

This PR mount sock file at empty directory and it is a continuation of PR: https://github.com/openebs/maya/pull/1601.
**Checklist:**

fix(sockfile): mount sock file at empty directory for CSPC

---

pkg/kubernetes/deployment/appsv1/v1alpha1/deployment.go
pkg/upgrade/templates/v1/cstor_pool.go
pkg/upgrade/templates/v1/cstor_target.go
pkg/upgrade/upgrader/csp_upgrade.go
pkg/upgrade/upgrader/cstor_volume_upgrade.go
pkg/upgrade/upgrader/exec.go

This PR adds support for new volumeMounts and volumes added in cstor pool and volume deployments. Refer #1583 #1599 #1601 
**Checklist:**

refact(upgrade): add volumes and mountpaths for cstor pools and volumes

---

tests/cstor/pool/negative/provision_without_pool.go

This commit increases the retry counts to verify CSP count after deleting SPC.
**Checklist:**

fix(BDD): fix BDD test case by increasing retries

---

cmd/cspc-operator/app/handler.go

This Pr cherry-picks the cspc fix for cspc operator. #1611 
**Checklist:**

cherry-pick(cspc): replace the spc label with cspc label

---

pkg/kubernetes/deployment/appsv1/v1alpha1/kubernetes.go
pkg/upgrade/templates/v1/jiva_target.go
pkg/upgrade/upgrader/jiva_upgrade.go

This PR cherry-picks the upgrade fixes. #1626 
**Checklist:**

cherry-pick(upgrade): scale down jiva target deploy before replica patch 

---

pkg/upgrade/upgrader/jiva_upgrade.go

This PR  
- fixes the timeout issue for sync verification for jiva replicas. 
- adds if condition to make job idempotent for scaling for controller deployment. 
**Checklist:**

fix(upgrade): increase timeout for httpClient

---

pkg/upgrade/upgrader/jiva_upgrade.go

This PR is cherry-pick for #1629 
**Checklist:**

cherry-pick(upgrade): increase timeout for httpClient

---

CHANGELOG.md

This PR adds the changelog for v1.8.0-RC1.
**Checklist:**

chore(CHANGELOG): add changelog for v1.8.0-RC1

---

.travis.yml

This PR adds email to get build notifications.
**Checklist:**

chore(travis): add email for build notifications

---

pkg/install/v1alpha1/cstor_volume.go

Fixes: https://github.com/openebs/openebs/issues/2862
This PR fixes the cStor volume provisioning failure if the storage class has `volumeBindingMode: WaitForFirstConsumer` and replica count > 1.
**Current Behaviour:**
Currently, volume provisioning is failed because of policy `preferedScheduleOnHostAnnotationSelector`. This policy will be populated only if the PVC was annotated with `volume.kubernetes.io/selected-node=<node_name>`. Kubernetes will be adding this annotation to PVC only if StorageClass has WaitForFirstConsumer binding mode intention of K8s is to provide the storage from that node but in case of cStor OpenEBS users can specify more than one replica count so storage will come from …

fix(provisioning): support to provision volumes in case of WaitForFirstConsumer

---

tests/cstor/pool/reconciliation/reconciliation_test.go
tests/operations.go

This PR adds checks on existing BDD to verify the pool protection finalizer on CSP.
This PR is covering test cases for PR: https://github.com/openebs/maya/pull/1635
- It will not cause any delay to run BDD with this test.
**Checklist:**

chore(BDD): Add checks to verify pool protection finalizer on CSP

---

pkg/install/v1alpha1/jiva_volume.go

This PR fixes the missing namespace from the target affinity spec in controller deployment.
**Checklist:**

fix(jiva): add namespace to podAffinity for target

---

tests/jiva/clone/provision_test.go
tests/jiva/clone/suite_test.go
tests/jiva/invalidconfig/invalidconfig_test.go
tests/jiva/node-selector/node_selector_test.go
tests/jiva/node-selector/suite_test.go
tests/jiva/node-stickiness/node_stickiness_test.go
tests/jiva/node-stickiness/suite_test.go
tests/jiva/snapshot/provision_test.go
tests/jiva/snapshot/suite_test.go
tests/jiva/volume/provision_test.go
tests/jiva/volume/suite_test.go

This PR updates the namespace passed to functions for jiva controller and replica pod checks.
**Checklist:**

fix(bdd): update the namespace for verifying jiva pods

---

pkg/install/v1alpha1/jiva_volume.go

The PR adds namespace for statefulset target pod affinity.
**Checklist:**

fix(jiva): add namespace for stateful set target affinity

---

pkg/kubernetes/storageclass/v1alpha1/build.go

This PR fixes the Runtime issues in creating StorageClass.
**Why we need it**:
This PR adds VolumeBindingMode only if it is not empty. This problem was introduced in PR: [1643](https://github.com/openebs/maya/pull/1643)
**Error**:
```sh
while creating storageclass {test-cstor-replica-scaleup-sc}
Expected
<*errors.StatusError | 0xc0001cea00>: {
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "StorageClass.storage.k8s.io \"test-cstor-replica-scaleup-sc-lskrg\" is invalid: volumeBindingMode: Unsupported value: \"\": supported values: \"Immediate\", \"WaitForFirstConsumer\"",
Reason: "Invalid", …
```

fix(bdd): fix BDD to avoid failures during creation of Storage Class

---

GNUmakefile
buildscripts/build.sh
buildscripts/provisioner-localpv/Dockerfile.ppc64le
buildscripts/provisioner-localpv/Makefile.mk

This PR adds local provisioner builds for ppc64le. 
**Checklist:**

feat(build): Adding local provisioner pv build for ppc64le

---

pkg/upgrade/upgrader/jiva_upgrade.go

This PR fixes the issue which might occur if the upgrade job is run after successful completion. It might scale down the controller which will not be patched and remained scaled-down forever.
**Checklist:**

fix(upgarde): scale down jiva contoller deployment only if not upgraded

---

pkg/upgrade/upgrader/jiva_upgrade.go

This PR cherry-picks PR #1663 to v1.9.x branch.
**Checklist:**

cherry-pick(upgarde): scale down jiva contoller deployment only if not upgraded (#1663)

---

buildscripts/apiserver/Dockerfile
buildscripts/cspc-operator-debug/Dockerfile
buildscripts/cspc-operator/Dockerfile
buildscripts/cvc-operator/Dockerfile
buildscripts/mayactl/Dockerfile
buildscripts/openebs-cluster/Dockerfile
buildscripts/provisioner-localpv/Dockerfile
buildscripts/upgrade/Dockerfile

This PR upgrades the alpine image version to 3.11.5.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/openebs/issues/2991

chore(build): update alpine base images to 3.11.5

---

buildscripts/apiserver/Dockerfile
buildscripts/cspc-operator-debug/Dockerfile
buildscripts/cspc-operator/Dockerfile
buildscripts/cvc-operator/Dockerfile
buildscripts/mayactl/Dockerfile
buildscripts/openebs-cluster/Dockerfile
buildscripts/provisioner-localpv/Dockerfile
buildscripts/upgrade/Dockerfile

This PR cherry picks #1660 to v1.9.x branch.
**Checklist:**

cherry-pick(build): update alpine base images to 3.11.5 (#1660)

---

pkg/install/v1alpha1/jiva_volume.go

This PR fixes the issue: if the jiva volume is deployed with custom replica tolerations while deleting the cleanup jobs are not able to schedule on the tainted nodes.
Adding the replica toleration to jobs fixes the issue.
Storageclass used:
```yaml
metadata:
name: jiva-2r
annotations:
value: "2"
- name: ReplicaTolerations
value: |
t1:
key: "nodeType"
operator: "Equal"
value: "storage"
effect: "NoSchedule"
```
Tolerations set on replica deployment:
```yaml
tolerations:
- effect: NoExecute
key: node.alpha.kubernetes.io/notReady
operator: Exists
- effect: NoExecute
key: …
```

fix(jiva): add tolerations to jiva cleanup jobs

---

pkg/install/v1alpha1/jiva_volume.go

This PR cherry-picks #1667 to v1.9.x branch.
**Checklist:**

cherry-pick(jiva): add tolerations to jiva cleanup jobs

---

CHANGELOG.md

This PR adds changelog for v1.9.0-RC1.
**Checklist:**

chore(CHANGELOG): add changelog for v1.9.0

---

changelogs/unreleased/1670-mittachaitu
changelogs/unreleased/1699-mittachaitu
changelogs/unreleased/CHANGELOG.md

This PR adds unreleased changelogs in the repo.
**Checklist:**

chore(doc): add unreleased changelogs in repo

---

pkg/upgrade/templates/v1/cstor_pool.go
pkg/upgrade/templates/v1/cstor_target.go
pkg/upgrade/upgrader/csp_upgrade.go
pkg/upgrade/upgrader/cstor_volume_upgrade.go
pkg/upgrade/upgrader/jiva_upgrade.go

This PR fixes the version comparison function as earlier string comparison will not work from 1.10.0 onwards.
**Checklist:**

fix(upgrade): fix version comparison function

---

buildscripts/push

This PR trims leading v from image tag.
**Checklist:**

refact(build): trim leading v from image tag

---

buildscripts/git-release

The PR is cherry-pick PR for git-release fix. Refer: #1691 
**Checklist:**

cherry-pick(build): fixing git-release file to ignore error if tag already exists (#1691)

---

pkg/install/v1alpha1/env.go
pkg/install/v1alpha1/env_setter.go
pkg/install/v1alpha1/env_setter_test.go
pkg/install/v1alpha1/flags.go
pkg/install/v1alpha1/openebs_crds.go

(cherry picked from commit f9eef6d6743971623a0b85df9dd4a412f939ad04)

feat(install): enable/disable crd installation

---

pkg/webhook/configuration.go

This PR handles the successful cleanup of old service, secret and webhookconfig for admission webhook in case of operator and helm due to non-uniform labels across different installations in v1.0.0 once they upgrade v1.10.0 version.
Above issue has been seen, when we install openebs v1.0.0 version using openebs-operator yaml
and upgrading the v1.0.0 version to the any greater version ( v1.1.0 onwards) using openebs-operator yaml (not with helm as helm maintain there set of labels in each resources, which take cares of upgrading/patching the resources).
Since we have changed the Webhook FailurePolicy: Fail , this causes failure for any configuration mistakes in webhook in older version …

cherry-pick(webhook): cleanup old resources from 1.0.0 release (#1696)

---

changelogs/unreleased/1704-Pensu

This PR adds changelog for #1704 
**Checklist:**

Adding changelog file for #1704

---

pkg/webhook/webhook.go

fix the compilation build errors
same constant has been added by 2 different PRs simultaneously causing the build failures
NO

fix(build): remove duplicate declaration of constant

---

pkg/webhook/spc.go
tests/cstor/volume/provision_test.go

This PR is cherry-pick of PR #1715 .
NA
Yes
**Checklist:**

cherry-pick(fix): update checks after de-provisioning the CStor Volume (#1715)

---

buildscripts/travis-build.sh

cherry-pick: https://github.com/openebs/maya/pull/1722

fix(build): travis CI failure in forked Repo git error

---

pkg/apis/openebs.io/v1alpha1/versionDetails.go

This PR cherry-picks the PR https://github.com/openebs/maya/pull/1724 to v1.11.x branch.
**Checklist:**

chore(upgrade): add support for upgrading to any custom tag within same version

---

changelogs/unreleased/1719-shubham14bajpai
pkg/upgrade/upgrader/helper.go

This PR cherry-picks #1719 to v1.11.x branch
**Checklist:**

fix(upgrade): increase wait for deployment rollout status (#1719)

---

pkg/webhook/configuration.go

Make webhook failure policy configurable using ENV
commit enable the webhook validatingwebhookconfiguration
failure policy configurable using a env called
ADMISSION_WEBHOOK_FAILURE_POLICY.
There are 2 types of failure policy which can be configurable
are `Fail` and `Ignore`. `Fail` will be the default policy
NO
Cherry-pick: #1726

refact(webhook): make webhook config failure policy configurable (#1726)

---

buildscripts/build.sh
pkg/apis/openebs.io/v1alpha1/versionDetails.go
pkg/client/k8s/v1alpha1/unstructured.go
pkg/client/k8s/v1alpha1/unstructured_test.go
pkg/install/v1alpha1/env_setter.go
pkg/util/unstructured.go
pkg/version/version.go
pkg/version/version_test.go

This PR is cherry-pick for #1733 .
**Checklist:**

fix(version): use tagged version instead of VERSION file during build

---

pkg/version/version.go

This PR is a cherry-pick PR for https://github.com/openebs/maya/pull/1735
**Checklist:**

fix(version): fix castemplate output runstask names

---

pkg/volume/volume.go

This PR is cherry-pick of #1738 
No
**Checklist:**

cherry-pick(fix): cherry-pick of PR #1738

---

CHANGELOG.md

This PR adds changelog for v2.0.0.
**Checklist:**

chore(CHANGELOG): add changelogs for v2.0.0

---

pkg/apis/openebs.io/v1alpha1/versionDetails.go

Cherry-pick PR for #1749 
**Checklist:**

chore(upgrade): add valid current versions for 2.1.0 upgrades

---

.travis.yml
changelogs/unreleased/1744-mittachaitu
ci/spc-manual.yaml
ci/test-script.sh
ci/travis-ci.sh
cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go

This PR is cherry-pick of #1744.
No
**Checklist:**

cherry-pick(spc): cherry pick provision cStor stripe based pools with single raid group #1744 to 1.12.x

---

.travis.yml
changelogs/unreleased/1744-mittachaitu
ci/spc-manual.yaml
ci/test-script.sh
ci/travis-ci.sh
cmd/maya-apiserver/app/server/restore_endpoint_v1alpha1.go
cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
pkg/algorithm/nodeselect/v1alpha1/select_node.go
pkg/algorithm/nodeselect/v1alpha1/select_node_test.go
pkg/blockdevice/v1alpha1/blockdevice.go
pkg/blockdevice/v1alpha1/blockdevice_test.go
pkg/blockdevice/v1alpha1/kubernetes_client_test.go
pkg/blockdevice/v1alpha1/spc_client_test.go
tests/cstor/cspc/provisioning/provisioning_test.go

This PR is cherry-picks of  following PRs #1744, #1747, and #1748  
No
**Checklist:**

cherry-pick(raidgroup fix, goversion, bd-tag): cherry pick PRs to 2.0.x 

---

changelogs/unreleased/1754-shubham14bajpai
cmd/admission-server/main.go
pkg/webhook/configuration.go
pkg/webhook/webhook.go

Cherry-pick PR for #1754 
**Checklist:**

feat(webhook): add validation for namspace delete requests

---

changelogs/unreleased/1754-shubham14bajpai
cmd/admission-server/main.go
pkg/webhook/configuration.go
pkg/webhook/webhook.go

Cherry-pick PR for #1754 
**Checklist:**

feat(webhook): add validation for namspace delete requests 

---

pkg/apis/openebs.io/v1alpha1/versionDetails.go

This PR adds 2.2.0 to the valid current version map to enable RC upgrades and custom image upgrades.
**Checklist:**

chore(version): add 2.2.0 to upgrade matrix

---

.github/workflows/build.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
.travis.yml
GNUmakefile
Makefile.buildx.mk
buildscripts/admission-server/Makefile.mk
buildscripts/admission-server/admission-server.Dockerfile
buildscripts/apiserver/Makefile.mk
buildscripts/apiserver/apiserver.Dockerfile
buildscripts/build.sh
buildscripts/buildxpush.sh
buildscripts/cstor-pool-mgmt/Makefile.mk
buildscripts/cstor-pool-mgmt/cstor-pool-mgmt.Dockerfile
buildscripts/cstor-volume-mgmt/Makefile.mk
buildscripts/cstor-volume-mgmt/cstor-volume-mgmt.Dockerfile
buildscripts/deploy.sh
buildscripts/upgrade/Makefile.mk
buildscripts/upgrade/upgrade.Dockerfile
ci/build-maya.sh

This PR adds support for multi-arch builds using github actions.
**Checklist:**

chore(build): add support for multi-arch builds

---

.github/workflows/build.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
.travis.yml
GNUmakefile
Makefile.buildx.mk
buildscripts/admission-server/Makefile.mk
buildscripts/admission-server/admission-server.Dockerfile
buildscripts/apiserver/Makefile.mk
buildscripts/apiserver/apiserver.Dockerfile
buildscripts/build.sh
buildscripts/buildxpush.sh
buildscripts/cstor-pool-mgmt/Makefile.mk
buildscripts/cstor-pool-mgmt/cstor-pool-mgmt.Dockerfile
buildscripts/cstor-volume-mgmt/Makefile.mk
buildscripts/cstor-volume-mgmt/cstor-volume-mgmt.Dockerfile
buildscripts/deploy.sh
buildscripts/upgrade/Makefile.mk
buildscripts/upgrade/upgrade.Dockerfile
ci/build-maya.sh

Cherry-pick PR for #1764 
**Checklist:**

chore(build): add support for multi-arch builds (#1764)

---

pkg/apis/openebs.io/v1alpha1/versionDetails.go

This PR adds 2.4.0 to the upgrade matrix.
**Checklist:**

chore(version): add 2.4.0 to upgrade matrix

---

CHANGELOG.md
changelogs/released/v2.4.0-RC1/1772-shubham14bajpai
changelogs/released/v2.4.0-RC1/1773-prateekpandey14
changelogs/released/v2.4.0-RC1/1774-prateekpandey14

This PR adds changelog for v2.4.0
**Checklist:**

chore(CHANGELOG): add changelogs for v2.4.0

---

pkg/apis/openebs.io/v1alpha1/versionDetails.go

This PR adds 2.4.1 to upgrade matrix
**Checklist:**

chore(version): add 2.4.1 to upgrade matrix

---

.github/workflows/build.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
pkg/apis/openebs.io/v1alpha1/versionDetails.go

This PR updates the buildx action version to the latest stable release. This PR also updates the upgrade matrix with 2.5.0.
**Checklist:**

chore(build): update the buildx action verison

---

CHANGELOG.md

This PR adds changelog for v2.5.0
**Checklist:**

chore(CHANGELOG): add changelogs for v2.5.0

---

pkg/webhook/webhook.go

This PR fixes the namespace deletion issue due to stale config in the cluster. 
https://github.com/openebs/openebs/issues/3338
**Checklist:**

fix(webhook): cleanup validatingconfig on openebs namespace deletion

---

CHANGELOG.md
changelogs/released/v2.6.0-RC1/1779-shubham14bajpai
changelogs/released/v2.6.0-RC1/1780-shubham14bajpai

chore(CHANGELOG): add changelogs for v2.6.0

---

pkg/apis/openebs.io/v1alpha1/versionDetails.go

This PR adds 2.7.0 to the upgrade matrix.
**Checklist:**

chore(version): add 2.7.0 to upgrade matrix

---

CHANGELOG.md
changelogs/released/v2.7.0-RC1/1784-shubham14bajpai
changelogs/released/v2.7.0-RC1/1785-shubham14bajpai
changelogs/released/v2.7.0-RC1/1787-shubham14bajpai
changelogs/released/v2.7.0-RC1/1788-prateekpandey14
changelogs/released/v2.7.0-RC1/1789-shubham14bajpai
changelogs/released/v2.7.0-RC1/1790-niladrih

Changelog PR for 2.7.0 release
**Checklist:**

chore(CHANGELOG): add changelogs for v2.7.0

---

pkg/apis/openebs.io/v1alpha1/versionDetails.go

This PR adds support for v2.8.0 upgrades.
**Checklist:**

chore(version): add 2.8.0 to upgrade matrix

---

.travis.yml
ci/build-maya.sh
ci/test-script.sh
pkg/webhook/configuration.go
pkg/webhook/webhook.go

fix(webhook): populate admissionReviewVersions as a required value

---

CHANGELOG.md
changelogs/released/v2.8.0-RC1/1794-prateekpandey14
changelogs/released/v2.8.0-RC1/1795-niladrih

This PR adds changelog for v2.8.0 release.
**Checklist:**

chore(CHANGELOG): add changelogs for v2.8.0

---

.github/workflows/build.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
pkg/apis/openebs.io/v1alpha1/versionDetails.go

Signed-off-by: Niladri Halder <niladri.halder@mayadata.io>
The build.yml and pull_request.yml workflows will ignore pushes made to `docs/` and `changelogs/` directories, all `.md` files, BUILDMETA, LICENSE, MAINTAINERS and VERSION files.
Added criteria to ignore build workflows on release. 
Adds Build & Push via Actions instead of makefile.

chore(github-action): Refine GitHub Actions criteria and add Build & Push Actions 

---

pkg/apis/openebs.io/v1alpha1/versionDetails.go

This PR adds the version 2.10.0 to upgrade matrix

chore(version): add 2.10.0 to upgrade matrix

---

README.md

- Update project README 
- Project deprecate status 
- Community links

refact(docs): update project README, status and community links

---

pkg/util/util.go
pkg/util/util_test.go

**What this PR does?**: Cherry-pick for #1806 
**Checklist:**

fix(webhook): fix version comparison of webhook resources

---

pkg/apis/openebs.io/v1alpha1/versionDetails.go

**What this PR does?**: Adds 2.11.0 to the upgrade matrix. 
**Checklist:**

chore(version): add 2.11.0 to upgrade matrix

---

README.md
pkg/install/v1alpha1/openebs_crds.go

- Update readme with new location of code
- Add deprecate note to all user facing CRDs

chore(deprecate): update readme with deprecation notes
