openebs/maya

command/stats.go
command/volume_stats.go

* maya volume stats fails with one replica running.
* Error handling was not there for all the cases.
* from now on volume stats will query replica status also . Earlier this case was not there in `stats.go`.
* err does not throw proper error on `resp.StatusCode=500` i.e, it throws `nil` for this case. Now it will throw proper error.
* Run the new binary with one replica down/pending status and  output will be something like this
```IQN     : iqn.2016-09.com.openebs.jiva:vol1
Volume  : vol1
Portal  : 10.109.27.40:3260
Size    : 1G
Replica|    Status|   DataUpdateIndex|
|          |                  |
Unknown|   Unknown|           Unknown|
10.44.0.4|    Online|                 0| …
```

Fixing #296 and add error handling

---

commands.go

Deprecate setup-omm/setup-osh CLI commands #371 fix dep
Deprecate omm-status/osh-status CLI commands #370 fix dep
The above commands are deprecated with the implementation of latest commands.
fixes openebs/openebs#371, openebs/openebs#370 
on terminal, type maya or maya setup-omm etc
Usage: 'maya' [--version] [--help] <command> [<args>]
Available commands are:
```sh
snapshot    Creates snapshot of a Volume
version     Prints the Maya version
volume      Creates a OpenEBS Volume 
```

omm-status/osh-status/setup-omm/setup-osh CLI commands are removed

---

command/volume_create.go
command/volume_create_test.go
command/volume_stats.go
command/volume_stop.go
command/volume_update.go
commands.go

This commit will fix the issue with volume delete with CLI 
command. Now maya cli will sent a request to M-apiserver 
for deletion of a specific volume.
``` maya volume delete -volname <volume> ```
fixes #29 
**How to verify this change**
Provisioned the Openebs Volume in K8s enviorment 
and deleted the volume from the maya cli using following command.
``` maya volume delete -volname <volume> ```
```
ubuntu@master01:~$ kubectl get pods 
NAME                                   READY     STATUS    RESTARTS   AGE
maya-apiserver-546443015-0zbhc         1/1       Running   0          5m
openebs-provisioner-3862123968-shvw0   1/1       Running   0          5m
vol1-ctrl-572094131-lx13j              1/1       Running   0 …
```

Fix: Volume Delete CLI Command

---

command/snapshot.go
command/snapshot_create.go
command/snapshot_delete.go
command/snapshot_list.go
command/snapshot_revert.go
command/version.go
command/volume.go
command/volume_create.go
command/volume_list.go
command/volume_stats.go
command/volume_stop.go
command/volume_update.go

This change will help maya cli to use same conventions
and terminologies across all its commands.
- Most of the commands text and help info
were changed
- Build/Install the maya binary
- Run the maya cli
- None
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #https://github.com/openebs/openebs/issues/419

standardize the terms used in maya cli

---

buildscripts/docker/Dockerfile

**This PR adds labels to docker file. The changes follow the label schema namespace.** 
**Addresses the issue discussed at https://github.com/openebs/openebs/issues/446#issuecomment-333374139**:
@vharsh Let me know your review. 
How to run : `docker build --build-arg VERSION=0.4 --build-arg BUILD_DATE=2017-08-01T23:20:50.52Z .`

Added docker labels - follows label schema namespace

---

.travis.yml

Previous Go version: 1.8
New Go version: 1.9.1
`fixes #539 in openebs repo` [link](https://github.com/openebs/openebs/issues/539)

Updated Go to v1.9.1

---

command/volume_create.go
command/volume_stop.go

Added error check

---

GNUmakefile
Vagrantfile
buildscripts/apiserver/Dockerfile
buildscripts/apiserver/build.sh
buildscripts/apiserver/demo-vol1.yaml
buildscripts/apiserver/entrypoint.sh
buildscripts/apiserver/push
orchprovider/k8s/v1/k8s.go
orchprovider/k8s/v1/k8s_test.go
types/v1/labels.go
types/v1/util.go
volumes/profile/volumeprovisioner/profile.go

It has been seen that a K8s setup might dedicate some
K8s nodes for control plane while some other nodes
for storage plane. This change will be able to handle
such setup needs.
This will fix https://github.com/openebs/openebs/issues/512
- accepts node taint toleration for volume controller
- accepts node taint toleration for volume replica
- understands ENV variable for above
- modifies buildscripts as apiserver is now under maya
repository.
- Refer Issue https://github.com/openebs/openebs/issues/600
- Get a K8s 1.8 or above setup
- Taint the nodes with appropriate taint key & value
- Create volume with node taint toleration enabled for volume
Controller
- Verify if volume …

add volume controller and volume replica node level taint toleration

---

buildscripts/apiserver/build.sh

Recent changes due to
https://github.com/openebs/openebs/issues/512 has resulted
in a bug where apiserver binary is not getting
build
- This fixes the build script with requried changes
- `make apiserver` should result in generation of
proper build artifcats
- run `apiserver` which is one of the artifacts of
build & see if it produces apiserver based CLI
- None

Fixes apiserver's build generation i.e. https://github.com/openebs/openebs/issues/606

---

types/v1/labels.go

Controller & Replica images needs to be set with :latest tag in Maya openebs/openebs#632

update Controller & Replica to :latest in labels.go

---

command/volume_create.go
types/v1/types.go

This commit will merge VsmSpec and volume struct
which will serve both purposes i.e sending a request
and getting a response to/from m-apiserver.
**Why is this change necessary**:
There is 2 different struct for volume related operations which can be merged to achieve the same.
VsmSpec :  Minimum create volume struct for sending a request to M-apiserver.
Volume : Struct which is response type for volume request , contains some more deep information about the particular volume can be merged into single type struct. 
This change will be  initial commit changes for issue openebs/openebs#420

Modify and Merge Volume struct

---

Dockerfile

**What this PR does / why we need it**: Should help openebs/openebs#625
Dockerfile building the maya, maya-apiserver and maya-agent binaries.
It still needs to get some more shape since I'm not an expert with Docker in order to support all the other rules on the Makefile.
Consider this as one step less to close the issue.

Make use of Docker to build maya components

---

cmd/maya-apiserver/app/server/volume_endpoint.go
command/volume_create.go
orchprovider/k8s/v1/k8s.go
orchprovider/k8s/v1/k8s_test.go
orchprovider/k8s/v1/util_test.go
orchprovider/nomad/v1/helper_funcs.go
orchprovider/nomad/v1/nomad_plug.go
orchprovider/orchestration.go
types/v1/profile/orchestrator/profile.go
types/v1/types.go
volume/profiles/profiles.go
volume/provisioners/jiva/jiva.go
volume/provisioners/jiva/util.go
volume/provisioners/volume.go

1. This PR is going to fix the API types of Volume.
2. Deprecate redundant structs from the API types.
3. Create single `Volume` struct API type for request and response.
4. Create `VolumeList` struct type for listing the volumes
5. Create `VolumeStatus` struct type, to know the current status/info of a Volume
fixes openebs/openebs#420
**How to verify this change**
Verified changes by using curl and CLI commands

Refactor Volume REST API types

---

Dockerfile
buildscripts/apiserver/Dockerfile
buildscripts/mayactl/Dockerfile

This commit will add back the dockerfiles to build the maya inside the docker container as well as 
build the docker-images of maya and maya-apiserver.

Adding Dockerfiles for maya & maya-apisever

---

orchprovider/k8s/v1/k8s.go
orchprovider/k8s/v1/k8s_test.go
types/v1/labels.go
types/v1/types.go
types/v1/util.go
volume/profiles/profiles.go

The current volume type makes use of key:value pairs
to determine all its properties. This feature implementation
should move away from using replica count from a generic
k:v pair to a typed property in VolumeSpec. This helps in
ensuring data validation due to typed schema and also paves
the way for representing complex properties in their
corresponding struct (this struct would then be nested inside
VolumeSpec).
Fixes #https://github.com/openebs/openebs/issues/693
- Implements Replicas as a typed property in VolumeSpec
- Details - https://github.com/openebs/openebs/issues/693
- Earlier way of providing replica count will not work
i.e. …

Add replica count as a typed property to Volume struct

---

GNUmakefile
buildscripts/agent/Dockerfile
buildscripts/agent/build.sh
buildscripts/agent/entrypoint.sh
buildscripts/agent/push

This PR adds the initial version of the build and docker files for maya-agent.
Fixes https://github.com/openebs/openebs/issues/690
**Special notes for your reviewer**: 
The build scripts are similar to maya-apiserver. Which also makes a case for merging all the build scripts together, which can be taken up in the future as part of : https://github.com/openebs/openebs/issues/499

docker and build scripts for agent - #690

---

buildscripts/apiserver/Dockerfile
command/volume_create.go
types/v1/types.go

1. This commit will deprecate the un-used types struct field of 
`VolumeSpec` as well as some other structs i.e `claim, resource` etc which are not getting 
used, from types.go file.
2. Install Bash shell inside the maya-apiserver container image
fixes openebs/openebs#684

deprecate VolumeSpec unused struct fields

---

GNUmakefile

maya-agent binary needs to be build when make all is given.
The change adds maya-agent to 'all' tag of GNUmakefile
make all command should be given to see maya-agent binary in bin directory
fixes #

Add maya-agent build command to makefile make all #132

---

cmd/maya-apiserver/app/server/volume_endpoint.go
orchprovider/k8s/v1/k8s.go
orchprovider/k8s/v1/k8s_test.go
orchprovider/k8s/v1/util.go
orchprovider/k8s/v1/util_test.go
orchprovider/nomad/v1/helper_funcs.go
orchprovider/nomad/v1/nomad_plug.go
types/v1/labels.go
volume/profiles/profiles.go
volume/provisioners/jiva/jiva.go

This is a part of bigger scheme of things namely
openebs/openebs#693, openebs/openebs#694 and
openebs/openebs#409
This particular implementation does a partial
fix of openebs/openebs#694
- Updates k8s/v1/util.go to include StorageClass
related operations
- Renames pvc to volume
- Cleans up k8s/v1/k8s.go
- make should work fine
- The actual verfication will be part of
bigger changes mentioned in above issues.
- None
**Special notes for your …

add K8s based StorageClass operations

---

GNUmakefile
buildscripts/agent/Dockerfile

The change is necessary for maya-agent to be connected with iscsi-targets.The os is changed from alpine to ubuntu to avoid certain file running errors on using iscsi. The make all command of makefile will test, build and push images of apiserver and maya-agent. 
The dockerfile's run field is added with open-iscsi. GNUmakefile is modified to test, build and push images of apiserver and maya-agent on 'all' field.
For maya-agent,  docker build -f Dockerfile
For makefile, make-all …

maya-agent iscsi and makefile images #740

---

buildscripts/apiserver/entrypoint.sh

This commit will fix mapiserver start flag which is changes to  --bind
from -bind with latest changes in maya-apiserver.
**Which issue this PR fixes** fixes openebs/openebs#748

Fix maya-apiserver entrypint for container image

---

cmd/maya-apiserver/app/command/start.go

Fix https://github.com/openebs/openebs/issues/789
As part of the cleanup to move to glog, the logOutput
was set to nil. This was crashing the maya-apiserver when
logs were being flushed.

Pass the stdout for logging the messages

---

orchprovider/detect_test.go

Signed-off-by: Marco Singer <markaum@gmail.com>
Add missing tests for `DetectOrchProviderFromEnv` function and improve the code coverage.
The original issue is in another repo: https://github.com/openebs/openebs/issues/790

tests(orchprovider): Add tests for DetectOrchProviderFromEnv

---

command/eval_status.go
command/install_maya.go
command/install_openebs.go
command/meta.go
command/network.go
command/node_status.go
command/server_members.go
command/snapshot.go
command/snapshot_create.go
command/snapshot_delete.go
command/snapshot_list.go

Fixes https://github.com/openebs/openebs/issues/362
Fixed a portion of mixed indentation in some files.

command: fix mixed indent

---

command/install.go
command/install_openebs.go

Issue -780
Fixing Lint in maya/command/install.go

Fixing Lint Issues

---

.travis.yml
buildscripts/agent/build.sh
buildscripts/apiserver/build.sh
buildscripts/mayactl/build.sh
buildscripts/travis-build.sh

This PR is one step towards enabling forked repo's to run e2e tests -- using minikube (https://github.com/openebs/openebs/issues/642)
- Added an wrapper script (travis-build.sh)
that copies the forked repo content to openebs/maya folder.
- Fix the build.sh files for git dependency. In case of forked
repo, running the builds from non-git directory will fail
the git commands
- Commented the golint since it is taking too much time and
should be re-enabled after fixing the current errros.

Enable travis to build maya from forked repo

---

types/v1/quantity.go

Fixes `golint` issues for `types/v1/quantity.go`
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes openebs/openebs#757
The open issues asks to resolve 
```
Line 16: warning: package comment should be of the form "Package v1 ..." (golint)
```
but I'm not too sure how to proceed. It looks like most of the files in that package have a similar `// This is extracted from ...` type comment. Should we leave this as is? Extract this into a `docs.go`? Change the comment specifically on `quantity.go`?

Fixing golint issues on types/v1/quantity.go.

---

types/v1/types.go

**What this PR does / why we need it**: It fixes linting issues in types/v1/types.go file
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes openebs/openebs#762

Fix linting issues in types/v1/types.go file

---

cmd/maya-apiserver/app/server/http.go
cmd/maya-apiserver/app/server/snapshot_endpoint.go
cmd/maya-apiserver/app/server/volume_endpoint.go
command/model.go
example/snap.yaml
example/snap2.yaml
volume/provisioners/jiva/snapshot_create.go
volume/provisioners/jiva/snapshot_list.go
volume/provisioners/jiva/snapshot_revert.go

This commit will enhance maya-apiserver to support snapshot
related API operation. Snapshot can be created/reverted by
simple yaml config file, and can be deleted by simple curl command.
2. How to verify this change ?
Create: Snapshot created by using simple config yaml file
Revert: Snapshot reverted by using simple config yaml file.
which creates 2 snapshot and then tried reverting to
each other.
list: Simple curl command will list down the created snapshot,
specific to particular volume.
: fixes #79, #73 , #72 , #12 , openebs/openebs#395 , openebs/openebs#258
```yaml
apiVersion: volumesnapshot/v1
kind: VolumeSnapshot
metadata:
Name: snapdemo1
spec:
VolumeName: ebsvol
-------
apiVersion: volumesnapshot/v1
kind: …
```

 Enhance Maya-apiserver to support snapshot API

---

cmd/maya-agent/k8s/constants.go
command/snapshot_revert.go

Fixes linting errors in `command/snapshot_revert.go` (#776)

---

cmd/maya-agent/app/exporter/collector/collector.go
command/volume_stats.go
command/volume_stats_test.go
pkg/util/constant.go
types/v1/constant.go
types/v1/math.go
types/v1/metrics.go

refactor volume stats
- To reuse existing structs.
- To remove redundant code and replace with generic one.
- Constants moved to `types/v1/`
- Implemented generic functions for mathemetical opertaions.
- Run maya binary in maya-apiserver pod to verify this change.
- none
- improvements: [#856]()https://github.com/openebs/openebs/issues/856

Refactor #856 volume stats

---

.travis.yml
ci/helm_install_openebs.sh
ci/mayactl/run_vol_create.sh
ci/mayactl/run_vol_delete.sh
ci/mayactl/run_vol_list.sh
ci/setup_env.sh
ci/test_mayactl.sh
ci/travis-ci.sh
ci/ubuntu-compile-nsenter.sh
command/volume_list.go
command/volume_stop.go
pkg/client/mapiserver/volume_delete.go
pkg/client/mapiserver/volumes_list.go

This PR contains some fixes for openebs/openebs#505, which will help in moving the maya volume related commands to COBRA. 
The changes included in this commit:
- Refactor the existing commands to delegate the mapaiserver client/server code to pkg/client/mapiserver
- Include basic sanity tests for create/list/delete volume (Currently this is based on shell script, but will be moving toward ginkgo or go based testing in future)
- Includes installation of ci images in minikube via helm

mayactl volume cmd refactor #505

---

cmd/maya-agent/app/exporter/collector/collector_test.go

- Unit test was not there for collector.go
- This commit adds unit test for collector.go
- run `go test` in collector package to verify change
- none
fix: [#696](https://github.com/openebs/openebs/issues/696)
6. Notes :
- Unit test is added only for collector, tests for the other files
will be added later in different PR.

Add unit test in exporter

---

command/snapshot_create.go
command/snapshot_delete.go
command/snapshot_list.go
command/snapshot_revert.go
pkg/client/jiva/controller_client.go
pkg/client/jiva/model.go
pkg/client/jiva/replica_client.go
volume/provisioners/jiva/snapshot_create.go
volume/provisioners/jiva/snapshot_list.go
volume/provisioners/jiva/snapshot_revert.go

This PR will refactor the jiva controller and replica client codes 
and move inside to `pkg/client/jiva`.
This will help us to write CTL commands related to Volume and snapshots.

Refactor Jiva controller and replica clients

---

cmd/maya-agent/app/exporter/collector/collector.go
cmd/maya-agent/app/exporter/collector/collector_test.go
types/v1/metrics.go

- volume uptime, volname, iqn and portal details were missing in exporter code.
- volume size was in bytes.
- added a gauge uptime and iqn, portal, volname as labels.
- changed the size into GB.
- run maya-agent locally or within maya-apiserver by passing controller's
IP as flag `maya-agent monitor`.
- or run as deployment.
- A little change on the structure, added two new fields Name and uptime
this depends on the jiva. PR openebs/jiva#30 raised for these changes.
improvement: openebs/openebs#886
fix: corrected the unit of volume size.
<!-- …

Add volname, iqn, portal as label in Uptime gauge

---

cmd/mayactl/app/command/commands.go
cmd/mayactl/app/command/snapshot/create.go
cmd/mayactl/app/command/snapshot/list.go
cmd/mayactl/app/command/snapshot/revert.go
cmd/mayactl/app/command/snapshot/snapshot.go
pkg/client/jiva/model.go
pkg/client/mapiserver/snapshot.go
types/v1/types.go

1. This commit will add and refactor snapshot cli using cobra pkg.
2. Adding apiserver client
3. This commit will add `snapshot create` and `snapshot revert` command using cobra pkg.
fixes openebs/openebs#506
```
$ mayactl
Maya means 'Magic' a tool for storage orchestration
Usage:
maya [command]
help        Help about any command
snapshot    Provides operations related to snapshot of a Volume
version     Prints version and other details relevant to maya
volume      Provides operations related to a Volume
Flags:
--alsologtostderr                  log to standard error as well as files
-h, --help                             help for maya
--log_backtrace_at …
```

Refactor snapshot Cli using cobra pkg

---

GNUmakefile
buildscripts/exporter/push

volume-exporter can be deployed as side-car to the openebs volumes. This exporter acts as an adaptor for fetching stats from the openebs volumes and exporting them in the prometheus format. 
This PR allows for adding the building and pushing of the volume exporter image via travis. 
Also, will stop building the maya-agent image till it is used.

Setup auto-build for maya-volume-exporter image

---

orchprovider/k8s/v1/k8s.go

A bug was injected due to StoragePool policy
implementation. The hostpath for each replica container
is same as it simply applies the path of StoragePool
policy.
- each volume replica container's hostpath will have unique
path suffixed in its hostpath
- create a volume & check the replica deployment yaml
- none

fixes issue 929 - hostpath is not unique for each replica container

---

orchprovider/k8s/v1/k8s.go
orchprovider/k8s/v1/util.go

Related to : https://github.com/openebs/maya/pull/200
The containers running within pod have no idea of the cluster IPs. To communicate with each other, they need to use localhost. 
The spec generated after making the changes from this commit are as follows:
```
maya-volume-exporter:
Container ID:  docker://2f122479098a720753967c203a7b2f37a6b98cff174c8c6e6822ee4c3b49ae27
Image:         openebs/m-exporter:ci
Image ID:      docker://sha256:28cfd6b38043ae3d0ae43404d11d4b653362ca8cb83d95ee20889c641f133f52
Port:          9500/TCP
Command:
maya-volume-exporter
Args:
-c=http://127.0.0.1:9501
State:          Running
Started:      Fri, 24 Nov 2017 09:24:17 +0530
Ready:          True
Restart Count:  0
Environment:    <none>
Mounts:
/var/run/secrets/kubernetes.io/serviceaccount from …
```

Use 127.0.0.1 as target ip for monitoring sidecar

---

volume/policies/v1/policy_jiva_k8s.go

It is seen that volume capacity is always taken from
StorageClass parameters. However, the capacity property
set in PVC should always prevail over any other value.
- changes the priority order & sets highest priority to
PVC
- create volume by setting volume capacity in PVC & StorageClass
- None

fixes openebs/openebs#934 - set capacity from PVC

---

orchprovider/k8s/v1/k8s.go
orchprovider/k8s/v1/util.go
types/v1/policies.go
volume/policies/v1/policy_jiva_k8s.go

Maya has been setting various policies against a volume
during later's provisioning. However, these set of
applied policies should get reflected when a volume
detail is queried. As of now, there is no proper way to
get the applied policies on any given openebs volume.
- The volume properties and policies are set in the
annotations property while doing a /info API call
- create volume & do a /info check
e.g. curl http://maya-api-service-ip:5656/latest/volumes/info/volume-name
- none
5. Sample output after an /info call to maya-api-service
```json
{
"metadata": {
"annotations": {
"openebs.io\/jiva-controller-cluster-ip": "10.0.0.110", …
```

Expose volume properties and policies through annotations

---

orchprovider/k8s/v1/k8s.go
orchprovider/k8s/v1/util.go
pkg/util/util.go
types/v1/defaults.go
types/v1/envs.go

The various images used during volume provisioning should
default to appropriate image name & have :latest as its tag.
In addition, these images should be exposed as ENV variables
in maya api service.
- All the images point to :latest
- All the images are controlled by ENV variable
- deploy maya api server with ENV variables
- create a volume and check for the correctness
of various images
- none

Set images with :latest tag & expose them as env variables

---

orchprovider/detect.go

golint issue on detect.go

---

cmd/maya-agent/app/command/commands.go
cmd/maya-agent/storage/block/device-list.go
cmd/maya-apiserver/app/server/http.go
cmd/maya-apiserver/app/server/http_test.go
cmd/maya-apiserver/app/server/metadata_endpoint_test.go
cmd/mayactl/app/command/snapshot/create.go
cmd/mayactl/app/command/snapshot/list.go
cmd/mayactl/app/command/snapshot/revert.go
cmd/mayactl/app/command/volume_create.go
pkg/client/mapiserver/snapshot.go
pkg/client/mapiserver/volume_create.go
pkg/client/mapiserver/volumes_list.go
pkg/nethelper/ipcalc.go
volume/provisioners/jiva/snapshot_create.go

General simplifications that prevent unnecessary calls.
There is no directly linked issue.
all: simplifications
* use `fmt.Errorf`, instead of `errors.New(fmt.Printf)` since `fmt.Errorf` already calls `errors.New`
* don't check error unnecessarily, return it
* use `bytes.String` directly instead of `string(bytes.Bytes())`

all: simplifications

---

orchprovider/k8s/v1/k8s.go
orchprovider/k8s/v1/k8s_test.go
orchprovider/k8s/v1/util.go
types/v1/labels.go
types/v1/policies.go

This commit will fix the status which was getting nil before. 
Now there will two status-phase "Running" and "NotRunning"
based on the container status inside the pod.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # openebs/openebs#674
**How to verify changes**:
1. Changes has been tested and below are the response from the M-apiserver, check the `controller-container-status` and `replica-container-status` keys. 
2. Deleted the pods manually and verified the status
* 1 replica , 1 controller pod with monitoring enabled
```sh
$ kubectl get po
NAME                                                            READY     STATUS    RESTARTS   AGE …
```

Fix Apiserver volume status

---

pkg/client/k8s/k8s.go
pkg/client/k8s/k8s_test.go

- Will simplify the K8s client invocations
- Will be reused across all maya components &
external ones if such a need arise
- Is part of openebs/openebs#976
- adds wrapper code for k8s client at pkg/client/k8s
- make should work fine
- unit tests for this change should not result in error
- none

wrapper over k8s client API invocations

---

pkg/client/k8s/k8s.go
pkg/client/k8s/k8s_test.go

- This helps in simplifying K8s API calls meant for ConfigMap
- This is a part of openebs/openebs#976
- Adds a wrapper to K8s ConfigMap API call
- make test should not result in error
- none

wrapper over K8s ConfigMap API call

---

pkg/maya/maya.go
pkg/maya/maya_test.go

- This will help maya in building a K8s Deployment object
from various options that are DevOps friendly
- This is part of openebs/openebs#976
- It create a wrapper object on K8s Deployment
- It provides some utility functions on this wrapper
- More utility functions will appear in future
- Some unit tests have been added for this change
- make test should not return any error
- none

Maya wrapper object for K8s Deployment object

---

pkg/client/k8s/k8s.go
pkg/maya/maya.go
pkg/maya/maya_test.go

- This will help maya in building a K8s ConfigMap object
from various options that are DevOps friendly
- ConfigMap forms one of the key elements in designing
the upcoming 0.6 release namely maya volume operator
- This is part of openebs/openebs#976 i.e. maya for DevOps
- Adds structures that deal with K8s ConfigMap
- Adds unit test relevant to this addition
- Updates few other unit test & code w.r.t structure design
- `make` should run without errors
- `cd pkg/maya && go test -v` should display the unit test
run details
- none
```bash
vagrant@maya-01:/opt/gopath/src/github.com/openebs/maya/pkg/maya$ go test -v
=== RUN   TestMayaBytes
--- PASS: TestMayaBytes (0.00s)
=== RUN   TestMayaConfigMapLoad
=== RUN   TestMayaConfigMapLoad/hello_yaml
=== RUN   TestMayaConfigMapLoad/valid_struct_yaml …
```

maya wrapper for kubernetes ConfigMap

---

pkg/client/k8s/k8s_test.go
pkg/maya/maya_test.go

Signed-off-by: dungeonmaster18 <umesh4257@gmail.com>
Adds sub test.
Here is the output:
k8s_test.go
```
$ go test -v
=== RUN   TestGetConfigMap
=== RUN   TestGetConfigMap/TestGetConfigMap
--- PASS: TestGetConfigMap (0.00s)
--- PASS: TestGetConfigMap/TestGetConfigMap (0.00s)
=== RUN   TestGetPVC
=== RUN   TestGetPVC/TestGetPVC
--- PASS: TestGetPVC (0.00s)
--- PASS: TestGetPVC/TestGetPVC (0.00s)
=== RUN   TestGetService
=== RUN   TestGetService/TestGetServices
--- PASS: TestGetService (0.00s)
--- PASS: TestGetService/TestGetServices (0.00s)
=== RUN   TestGetPod
=== RUN   TestGetPod/TestGetPod
--- PASS: TestGetPod (0.00s)
--- PASS: TestGetPod/TestGetPod (0.00s)
=== RUN   TestGetDeployment
=== RUN   TestGetDeployment/TestGetDeployment
--- PASS: …
```

Adds sub tests

---

cmd/mayactl/app/command/snapshot/create.go
cmd/mayactl/app/command/snapshot/list.go
cmd/mayactl/app/command/snapshot/revert.go
pkg/client/jiva/controller_client.go
pkg/client/mapiserver/snapshot.go
volume/provisioners/jiva/snapshot_create.go
volume/provisioners/jiva/snapshot_list.go

1.  Fix the snapshot list command to print created
snapshot of particular volume in table format.
2. Add short flag-name for the --volname(-n) and --snapname(-s)
3. fix jiva controller and replica status error issue
4. fix issue related to replica, it goes into unresponsive/status error(500), due to duplicate snapshot created and replica goes into shutdown state.
5.  Check snapshot existence before creating snapshot ,logged them properly and return that.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes : 
openebs/openebs#961, openebs/openebs#937
**How to verify this change ?**
Tested the changes in k8s cluster environment. 
```sh
I1215 …
```

Fix controller replica status error

---

cmd/maya-apiserver/app/server/volume_endpoint.go
orchprovider/k8s/v1/k8s.go
orchprovider/k8s/v1/util.go
types/v1/defaults.go
volume/policies/v1/policy_k8s.go

https://github.com/openebs/openebs/issues/1055
maya needs to accept namespace inorder to delete & read a volume
maya makes use of request header to extract the namespace during read and delete operation
- make should work fine
- curl to read & delete a volume should send the namespace in request header with key as namespace
- openebs provisioner should set the request header with key as namespace
- none
```bash
$ kubectl get deploy --all-namespaces -l=vsm
NAMESPACE   NAME               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
default     my-jiva-vsm-ctrl   1         1         1            1           52s
default     my-jiva-vsm-rep    2         2         2            1           52s
minio       my-jiva-vsm-ctrl   1         1         1            1           3m
minio …
```

fixes maya api server issue of multiple namespaces

---

cmd/mayactl/app/command/stats_helper.go
cmd/mayactl/app/command/volume.go
cmd/mayactl/app/command/volume_stats.go
pkg/client/jiva/helper.go
types/v1/metrics.go

- Refers to issue openebs/openebs#505
- All the commands and flags now moved to maya/cmd/mayactl/command and are using
the cobra library for the cli.
- Run mayactl inside maya-apiserver container to verify this change.
- Alternatively you can copy the binary inside the maya-apiserver and
run the following commands
* `mayactl volume stats -n=vol` to get in std I/O
* `mayactl volume stats -n=vol -j=json` to get in json.
- none
improvement: part of #179

Move older volume stats cli to cobra cli

---

pkg/client/k8s/k8s.go
pkg/maya/maya.go
pkg/maya/maya_test.go
pkg/maya/runner.go
pkg/maya/template.go
pkg/maya/yaml.go
pkg/util/unstructured.go

openebs needs to add storage policies as an intuitive way
for admins & users to use storage yet have granular control.
This is a partial commit w.r.t issue
https://github.com/openebs/openebs/issues/1007
https://github.com/openebs/openebs/issues/1010
https://github.com/openebs/openebs/issues/976
doc at
https://docs.google.com/document/d/1oX_AcDMuhg2HVn3nmYDaZ-ABQv_V0v_DhbbySUImAhg/
- adds RunTemplate & MayaTemplate related code
- make should run fine
- Examples should be provided to enable developer & user
to understand the usage
- None
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …

Add code w.r.t openebs storage policy - drop 1

---

cmd/maya-apiserver/app/command/commands_test.go

Unit test for maya-apiserver cmd. (commands.go)
Fixes: [openebs/785](https://github.com/openebs/openebs/issues/785)

#785 add command unit test

---

pkg/task/runner.go
pkg/volume/policy.go

Operator must set identity to a task & can refer to the
task result using this identity. This removes the
dependency on order index of a task.
fixes https://github.com/openebs/openebs/issues/1191
- Modifications are done that makes use of task
identity mentioned in VolumePolicy
- Use VolumePolicy with task identity & make use of
these identity in the task templates
- None
```yaml
kind: VolumePolicy
metadata:
name: openebs-policy-0.6.0
spec:
policies:
- name: VolumeMonitor
enabled: "true"
value: openebs/m-exporter:0.5.0
- name: ControllerImage
value: openebs/jiva:0.5.0
- name: ReplicaImage
value: …
```

Adds identity to task in VolumePolicy

---

orchprovider/k8s/v1/k8s.go
volume/policies/v1/policy_jiva_k8s.go
volume/policies/v1/util.go

fixes https://github.com/openebs/openebs/issues/1242
fixes https://github.com/openebs/openebs/issues/1189
Why is this change necessary ?
This ensures use of StoragePool when rbac settings are
applied.
- Failure to find specific StoragePool will error out
& fail the provisioning
- Failure to find default storage pool will result in
setting /var/openebs as the persistent path
- If StorageClass does not set any StoragePool, then it
results in setting /var/openebs as the persistent path
- Code uses StoragePool object in cluster scope than the earlier
use of namespace scope
- One can run through the steps & suggestions made in the
following link to verify the changes
- …

fixes storagepool in rbac setups

---

.travis.yml
ci/helm_install_openebs.sh
ci/setup_env.sh

The latest openebs helm chart prefixes the maya-apiservice with release and namespace information as is the convention of helm charts for service names.  This PR, modifies the code used by the mayactl to fetch the IP address of the maya-apiservice using the new naming convention. 
Also, this PR runs the helm chart with RBAC enabled. 
Related PR: https://github.com/openebs/maya/pull/267

enables rbac on minikube

---

.gitignore
Vagrantfile

This enables the vagrant VM to include openebs components
via helm after installing minikube.
In near future, the e2e test cases will be run on this
vagrant VM. Meanwhile, one can attempt to run the test cases
that are run in travis, as a manual operation within this VM.
In addition, I shall attempt to minimize the difference
between the travis run and launching this VM.
Signed-off-by: amitkumardas <amit.das@openebs.io>

adds rbac & charts to vagrant VM

---

orchprovider/k8s/v1/util.go
orchprovider/k8s/v1/util_test.go

Fixes #https://github.com/openebs/openebs/issues/1275
maya-apiserver - volume info API is returning only one replica, even when there are multiple replica running for a given volume. 
The response for volume info is formed by the maya-apiserver by querying the controller and replica kubernetes objects. Since there are multiple calls involved, the data received is temporarily stored in "VolumeMarker" - which can store keys with single and multiple values. Since Replica is supposed to be a multiple valued key, I added an unit test for the AddMultiples function. 
The unit test failed, indicating that, though VolumeMarker is updated with multiple values, when framing the response, only one value was being …

Fix the bug with multi-valued response #1275

---

pkg/template/template.go
pkg/template/txt_tpl_examples_test.go

Adds ability to set tolerations & others in volume policy
- This in itself will not enable tolerating the taints
- Appropriate PR(s) needs to be raised to openebs helm charts w.r.t volume policy CRD
- Appropriate PR(s) needs to be raised to volume policies objects
VolumePolicy will make use of `fromYaml` template function as well as control loop functions
i.e. `range` to enable tolerations.
e.g. a volume policy snippet will look like:
```yaml
- name: TaintTolerations
value: |-
t1:
key: node.openebs.io/disktype
operator: Equal
value: ssd
effect: NoSchedule
t2:
key: node.openebs.io/disktype
operator: Equal
value: ssd
effect: NoExecute
t3:
key: jk
operator: Equal
value: jv
effect: NoSchedule
- name: EvictionTolerations
value: |-
t1:
effect: NoExecute
key: node.alpha.kubernetes.io/notReady …
```

adds ability to set tolerations & others in volume policy

---

pkg/apis/openebs.io/v1alpha1/policy.go
pkg/client/k8s/k8s.go
pkg/task/result_executor.go
pkg/task/result_executor_test.go
pkg/task/runner.go
pkg/task/task.go
pkg/template/query.go
pkg/template/template.go
pkg/template/txt_tpl_examples_test.go
pkg/volume/volume.go

1/ Why is this change necessary?
This lets `volume controller` & `application` PODs
to run in the same topology key, e.g. in the same K8s node.
fixes https://github.com/openebs/openebs/issues/1257
2/ How does this change address the issue?
- `modified:   pkg/apis/openebs.io/v1alpha1/policy.go`
- Above change ensures use of pvc as a top level volume policy property
- `modified:   pkg/client/k8s/k8s.go`
- Above has changes for invoking K8s APIs w.r.t. PVC
- `new file:   pkg/task/result_executor.go`
- `new file:   pkg/task/result_executor_test.go`
- `new file:   pkg/template/query.go`
- Above introduces the concept of querying a task's result for specific data.
- It makes use of jsonpath from kubernetes client-go repository
- `modified:   pkg/task/runner.go`
- Above has changes to log …

will pin volume controller to run alongside the application pod

---

Gopkg.toml

Add github.com/golang/groupcache onto Gopkg.toml file until the crd-watcher importing this transitive dependency is merged. Related to https://github.com/openebs/maya/pull/279
dep makes sure that this package is not deleted even if it not
imported for every dep ensure.
This can be removed from Gopkg.toml file once the crd shared informer is merged.

Add groupcache transitive dependency to Gopkg.toml

---

cmd/mayactl/app/command/volume_stats.go
cmd/mayactl/app/command/volume_stats_test.go

`mayactl volume stats --volname <vol>` shows incorrect information
- To fix the issue openebs/openebs#1397
- Improve Unit test
- This commit fixes the issue by removing the unneccessary code.
- Create the volume with minimum three replicas
- Run `mayactl volume stats --volname <vol>` and it should show the
desired output.
- none
- none
Signed-off-by: utkarshmani1997 <utkarshmani1997@gmail.com>
- fix: openebs/openebs#1397
<!--
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes …

Fix mayactl volume stats command

---

buildscripts/apiserver/push

This PR adds the capability to push the m-apiserver:ci image to quay.io container repository: https://quay.io/repository/openebs/m-apiserver. 
The intent in pushing to quay.io repository is to explore the feasibility of enabling automated security scans and get additional container usage statistics. The changes can be further extended to push tagged images also to quay in the future.

push m-apiserver:ci image to quay.io repo

---

.travis.yml

fixes: openebs/openebs#298
Trying to start kubelet inside travis in minikube-0.26 fails. minikube-0.26
makes use of kubeadm bootstrapper which tries to start systemctl-kubelet. Overriding
with localkube bootstrapper(same as v0.25) solves the issue as of now. Also,
the version of kubectl is changed to 1.8 to match vendor.
--bootstrapper=localkube flag is added while starting minikube.
Ref: https://github.com/kubernetes/minikube/issues/2704

Change bootstrapper for minikube-0.26

---

.travis.yml
ci/helm_install_openebs.sh
ci/setup_env.sh
ci/ubuntu-compile-nsenter.sh

Travis builds on PRs are failing, due to setup issues with minikube 1.7.0
Found a couple of issues: 
- minikube has changed the way services are installed. a bootstrapper flag has to be specified. 
- helm had issues connecting to tiller, had to use a workaround of granting additional permissions. 
While fixing the above, also made the change to use the latest kubernetes stable openebs charts.

Fix travis build error with minikube 1.7.0

---

.travis.yml
ci/helm_install_openebs.sh
ci/setup_env.sh
ci/ubuntu-compile-nsenter.sh

Fix travis build error with minikube 1.7.0
The following changes were made:
- Upgrading the minikube to 1.9.4 and also specifying the bootstrapper as localkube
- Use the kubernetes stable chart and make the change to maya-apiservce env accordingly
- Fix issue with helm 2.9.0 connecting to tiller

Fix travis-failure on cstor-feature-integration

---

.travis.yml
ci/helm_install_openebs.sh
ci/setup_env.sh
ci/ubuntu-compile-nsenter.sh

Fix travis build error with minikube 1.7.0
The following changes were made:
- Upgrading the minikube to 1.9.4 and also specifying the bootstrapper as localkube
- Use the kubernetes stable chart and make the change to maya-apiservce env accordingly
- Fix issue with helm 2.9.0 connecting to tiller

Fix travis-failure master

---

cmd/maya-exporter/app/command/command.go
cmd/maya-exporter/app/command/command_test.go
cmd/maya-exporter/app/command/exporter.go
cmd/maya-exporter/app/command/exporter_test.go
cmd/maya-exporter/main.go

This commit adds the flag `storage.engine` or `-e` which can be
used to specify the storage engine while running the binary.
On branch feature-#1466
Changes to be committed:
modified:   app/command/command.go
new file:   app/command/command_test.go
modified:   app/command/exporter.go
new file:   app/command/exporter_test.go
modified:   main.go
- Refer to issue openebs/openebs#1466
- This commit adds the option for specifying the storage engine
via a flag which can be passed while running the binary.
- Build and Run the binary with flag "-e" followed by storage engine
and you should be able to get the result something like given below.
```
$ ./maya-exporter -e="cstor"
I0516 …
```

Add flag to specify the storage engine in maya-exporter

---

orchprovider/k8s/v1/util_test.go

Signed-off-by: Sumit Lalwani <sumit.lalwani97@gmail.com>
- Add unit-test cases in util_test.go for NS() function in util.go
- To reduce run time logic errors
**Which issue this PR fixes**: 
fixes: <https://github.com/openebs/openebs/issues/791>

Add unit-test cases for NS() function in util.go

---

orchprovider/k8s/v1/util.go

Changes the `maya-volume-exporter` binary name to `maya-exporter` as part of new changes.
The new changes was added by this PR https://github.com/openebs/maya/commit/82c0de3ff3b496ed64dcf63225021647bb964784

Change maya-volume-exporter --> maya-exporter

---

GNUmakefile

IMAGE_TAG for docker images needs to be available directly via makefile also.
IMAGE_TAG is handled in buildscripts/travis-build.sh for travis. If user tries to
run make commands directly on local machine, this tag which will not be populated
from travis-build.sh, will be populated from makefile.
It is handled in such a way, if IMAGE_TAG is not set, then set it as local.
Verify if IMAGE_TAG is not set. Run a make command and check if image tag is
local.
Note: IMAGE_TAG selection was handled in travis-build.sh because, it makes use of
travis environment variables and it would be helpful in future, in case of going
through or porting from travis related variables.
Signed-off-by: …

[cstor-integration] Handle IMAGE_TAG in makefile

---

cmd/mayactl/app/command/volume_info.go
pkg/client/k8s/k8s.go

Signed-off-by: Sumit Lalwani <sumit.lalwani97@gmail.com>
* Shows the volume replicas detail with the node name in which that volume is running.
* Shows volume name in mayactl volume info command.
* Adds extra column for Node in info details.
**Which issue this PR fixes**: fixes #350 

Add node name details in mayactl volume info command

---

GNUmakefile
buildscripts/test-cov.sh
cmd/mayactl/app/command/snapshot/create.go
cmd/mayactl/app/command/snapshot/list.go
cmd/mayactl/app/command/snapshot/revert.go
cmd/mayactl/app/command/snapshot/snapshot.go
cmd/mayactl/app/command/stats_helper.go
cmd/mayactl/app/command/stats_helper_test.go
cmd/mayactl/app/command/volume.go
cmd/mayactl/app/command/volume_create.go
cmd/mayactl/app/command/volume_delete.go
cmd/mayactl/app/command/volume_info.go
cmd/mayactl/app/command/volume_info_test.go
cmd/mayactl/app/command/volume_stats.go
cmd/mayactl/app/command/volume_stats_test.go
cmd/mayactl/app/command/volumes_list.go
pkg/client/mapiserver/snapshot.go
pkg/client/mapiserver/snapshot_test.go
pkg/client/mapiserver/volume_delete.go
pkg/client/mapiserver/volume_delete_test.go

1. This commit will enhance mayactl to perform volume create/delete/
list/stats/info cmd for volumes other then default namespace.
2. Mayactl snapshot create/list/revert cmds across volume namespace.
fixes: https://github.com/openebs/openebs/issues/1510
fixes: https://github.com/openebs/openebs/issues/1600
**Volume stats  of percona namespaced volume:**
```sh
$ mayactl volume stats -n percona --volname pvc-186ee6ee-6987-11e8-ac26-02b983f0a4db
Executing volume stats...
IQN     : iqn.2016-09.com.openebs.jiva:pvc-186ee6ee-6987-11e8-ac26-02b983f0a4db
Volume  : pvc-186ee6ee-6987-11e8-ac26-02b983f0a4db
Portal  : 10.111.86.151:3260
Size    : 5G
Replica|    Status|   DataUpdateIndex|
|          |                  |
10.47.0.2|   Running|                 0|
10.44.0.3|   Running|              2202| …
```

Support mayactl volume/snapshot operation across namespaces

---

cmd/mayactl/app/command/snapshot/create.go
cmd/mayactl/app/command/snapshot/list.go
cmd/mayactl/app/command/snapshot/revert.go
cmd/mayactl/app/command/snapshot/snapshot.go

```sh
$ mayactl snapshot -h
Command provides operations related to a volume snapshot.
If you have specified an OpenEBS volume in a namespace other than the 'default',
you must use --namespace flag with a command. If not, you will see the results only
in the 'default' namespace.
Usage: mayactl snapshot <subcommand> [options] [args]
Examples:
$ mayactl snapshot create --volname <vol> --snapname <snap>
$ mayactl snapshot create --volname <vol> --snapname <snap> --namespace test
$ mayactl snapshot list --volname <vol>
$ mayactl snapshot list --volname <vol> --namespace test
$ mayactl snapshot revert --volname <vol> --snapname <snap>
$ mayactl snapshot revert --volname <vol> --snapname <snap> --namespace test
Usage:
mayactl snapshot [command]
create      Creates a new …
```

 Fix mayactl snapshot command helptext

---

cmd/mayactl/app/command/commands.go
cmd/mayactl/app/command/volume.go
cmd/mayactl/app/command/volume_create.go
cmd/mayactl/app/command/volume_delete.go
cmd/mayactl/app/command/volume_info.go
cmd/mayactl/app/command/volume_stats.go
cmd/mayactl/app/command/volumes_list.go

Signed-off-by: Prateek <prateekpandey14@gmail.com>
fixes: https://github.com/openebs/maya/issues/354
```sh
$ mayactl volume -h
The following command provides operations related to a Volume.
Usage: mayactl volume <subcommand> [options] [args]
Examples:
$ mayactl volume create --volname <vol> --size <size>
$ mayactl volume list
$ mayactl volume delete --volname <vol>
$ mayactl volume delete --volname <vol> --namespace test
$ mayactl volume stats --volname <vol>
$ mayactl volume stats --volname <vol> --namespace test
$ mayactl volume info --volname <vol>
$ mayactl volume info --volname <vol> --namespace test
Usage:
mayactl volume [command]
create      Creates a new Volume
delete      Deletes a Volume
info        Displays Openebs Volume information
list        Displays …
```

Fix mayactl volume command helptext

---

orchprovider/k8s/v1/util.go

**What this PR does / why we need it**: There was a bug in util.go file in which if volprofile is not defined and if K.Name func is called then it leads to a infinite function call of Name() and NS()  which cause stack overflow and unwanted termination of the program

Fixes recusive bug in util.go file

---

orchprovider/k8s/v1/k8s.go
types/v1/labels.go

This PR adds a pvc label in the deployment specification files (controller and replica deployment).
Added pvc label in  createControllerDeployment() function in orchprovider/k8s.go 
https://docs.google.com/document/d/1voevyvyvEDfOW1IWjokKe9GVAGh0tmGCWZJSQH7QrBE/edit?usp=sharing

Add pvc label in controller and replica deployment

---

orchprovider/k8s/v1/util_test.go

**What this PR does / why we need it**:This pr adds unit test for isInCluster function present in util.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/openebs/issues/792

Adds unit test case for IsInCluster func of util.go

---

cmd/mayactl/app/command/volume_stats.go

* Fixes read and write iops output in mayactl stats, which was getting updated only if the json flag is set.
**output -**
```sh
$ mayactl volume stats --volname pvc-fa0ca615-7063-11e8-9373-44a842ee39a8
Executing volume stats...
---------------
IQN     :   iqn.2016-09.com.openebs.jiva:pvc-fa0ca615-7063-11e8-9373-44a842ee39a8
Volume  :   pvc-fa0ca615-7063-11e8-9373-44a842ee39a8
Portal  :   10.0.0.229:3260
Size    :   5G
Replica Stats : 
---------------- 
REPLICA        STATUS      DATAUPDATEINDEX
--------       -------     ---------------- 
172.17.0.5     Running     96935     
Performance Stats :
--------------------
r/s      w/s      r(MB/s)      w(MB/s)      rLat(ms)      wLat(ms)
----     ----     --------     -------- …
```

Fixes read and write iops output in mayactl stats

---

orchprovider/k8s/v1/k8s.go
orchprovider/k8s/v1/k8s_test.go
types/v1/labels.go
types/v1/util.go
volume/profiles/profiles.go

This PR allows the administrators to specify the nodes on which the OpenEBS Replica and Controller Pods have to be scheduled using Kubernetes "NodeSelector" option. While Taints/Tolerations also can be used for this purpose, "NodeSelectors" are much simpler to setup using the node labels. And an added advantage is that - this can be done without having to worry about pushing taints to non-storage nodes. 
The implementation follows the traditional approach of specifying an ENV variable similar to how taints and …

Add ENV variables to specify default node selectors

---

orchprovider/k8s/v1/k8s.go
types/v1/labels.go
types/v1/policies.go

Related to https://github.com/openebs/external-storage/pull/44
The provisioner will send additional information like application and the type of failure domain that needs to be set on the PVs created for a given application. If this information is available the maya-apiserver will have to do the following:
- If application label is received from provisioner (to the volume request), then add it to the controller and replica deployments. This label can further be used for setting affinity/anti-affinity rules or for performing some higher level abstractions like - taking a snapshot on all the volumes belonging to a given application at the same time. etc., 
- If a topology keys are sent, use them instead of …

Include application label passed from provisioner on jiva deployments

---

orchprovider/k8s/v1/k8s.go

The jiva controller and replica deployments use node tolerations that specify if the pod should be evicted or retained on the node. The node toleration labels have changed with the recent k8s version and a few new ones have been added. This PR addes the new tolerations that apply to jiva controller and replica deployments. 

Update the tolerations on jiva deployments

---

orchprovider/k8s/v1/k8s.go
types/v1/labels.go

The jiva controller needs to determine whether to have the volume as read-only/read-write based on the quorum from the replicas. When the count is not available (in 0.5.x), controller was depending on the registration process to determine the number of replicas that are connected. This auto-registration process leads to several race conditions for determining - whether the volume will be launched with a single replica or multiple replicas. By passing this replication factor, controller will handle the cases for multiple replica's better. 
**Special …

Add replication factor as env to jiva controller

---

orchprovider/k8s/v1/k8s.go

**What this PR does / why we need it**: 
This PR enhances the functionality provided by https://github.com/openebs/maya/pull/380
A application label will help to spread out the replicas across volumes as is supported by #380. However there may be cases where the different replica's within a given volume need to be spread across different AZs. This PR adds a check to see if the user has specified an application label, if not, it will use the auto-generated pvc label to spread out the replicas. 
This PR also fixes a case, where application developer …

allow topology key without application label for jiva replica deployments

---

pkg/task/meta.go
pkg/task/repeat_with.go
pkg/task/runner.go
pkg/task/task.go
pkg/template/template.go
pkg/template/template_test.go
pkg/volume/volume.go

This PR does the following:
- pretty print of template values during runtask execution errors
- this helps in debugging possible issues if any while running cas templates
- addTo is a new template function
- this appends new values with existing ones at specified key
- fix rollback logic for repeatWith based RunTask
- rollback will delete resources that was "put" via "repeatWith" RunTask
- fix repeatWith with "get" based RunTask action
- lets repeatWith RunTask to work with "get" based action
Signed-off-by: AmitKumarDas <amit.das@openebs.io>

fix issues associated with CAS Template execution

---

pkg/volume/volume.go

The provisioner would expect pvc name in create casvolume payload. Using pvc name it will extract the cas volume config from pvc.

Accept config from pvc, read pvc name from request

---

cmd/cstor-volume-mgmt/controller/volume-controller/handler_test.go

travis builds were failing because the namespace used for tests is "default" where as in the code we use "openebs" as the default namespace. Now using "openebs" namespace in tests also.

using openebs namespace in unit test code

---

cmd/maya-exporter/app/collector/cstorcollector.go
cmd/maya-exporter/app/collector/cstorcollector_test.go

1. Why is this change necessary?
-  As per the earlier commit capacity stats such as used size and sectorsize
details were not there in the metrics.
2. How does it address the issue?
-  This commit adds such details.
3. What side effects does this change have?
-  None
4. How to verify this change?
-  Deploy the maya-exporter on the cluster as sidecar and you should be
able to get the metrics.
5. Any specific message for reviewer ?
-  No
Signed-off-by: Utkarsh Mani Tripathi <utkarshmani1997@gmail.com>

[cstor-integration][TA2099] Add capacity stats

---

cmd/maya-apiserver/spc-actions/storagepool_create.go
pkg/apis/openebs.io/v1alpha1/cas_template_keys.go

**Change the key of CAS Template for pool creation**
The name of cas template for create/delete should
be present on spc yaml as annotaions.
Annotation is a key-value pair.
Previous setup was following :
[Key]: [Value]
openebs.io/create-template:[Name of the cas template]
This commit will change the Key for create cas template to following:
[Key]: [Value]
cas.openebs.io/create-pool-template: [Name of the cas template]
After merging the commit, the SPC yaml should use the updated key
only for successful creation of pool.

Change the key of CAS Template for pool creation

---

cmd/maya-apiserver/spc-actions/storagepool_delete.go
cmd/maya-apiserver/spc-watcher/controller.go
cmd/maya-apiserver/spc-watcher/handler.go
cmd/maya-apiserver/spc-watcher/runner.go
cmd/maya-apiserver/spc-watcher/start.go
pkg/apis/openebs.io/v1alpha1/cas_pool.go
pkg/apis/openebs.io/v1alpha1/cas_template_keys.go
pkg/storagepool/storagepool.go

This commit will remove the hardcoded cas template name from code.
The name of delete cas template should come as a part
of annotation in storagepoolclaim yaml
e.g.
cas.openebs.io/delete-pool-template: cstor-pool-delete-default-0.7.0

[TA2152]Removes hardcoded delete cas template name.

---

cmd/cstor-volume-mgmt/volume/volume.go

Changes to be committed:
M       cmd/cstor-volume-mgmt/volume/volume.go
1. Why is this change necessary?
-  use nodeBase field from cstor volume cr in place of nodebase in istgt.conf
2. How does it address the issue?
- uses the appropriate nodebase entry in istgt.conf
3. What side effects does this change have?
- nothing
4. How to verify this change?
-  deploy cstor volume management pod along with cstor volume crs and verify istgt.conf generated.

US2650: Use NodeBase field from CStor Volume CR in place of NodeBase in istgt.conf

---

install/v1alpha1-0.7.0/cstor-volume/volume.yaml

- Adds `nodeBase` field to `cstor-volume-create-putcstorvolumecr-default-0.7.0` runtask
- This is required to fix iqn in the same runtask
- This would be utilised by `cstor-vol` deploy

Add nodeBase and update iqn for cstorvolume

---

cmd/cstor-pool-mgmt/controller/common/common.go
cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
cmd/cstor-pool-mgmt/volumereplica/volumreplica_test.go

fixes: openebs/openebs#1698
This change involves change in making using of cstorvolume
name instead of uid.
When CRD is not found, the error log can be verified. To connect target and replicas, the name
must be common.

Modify cstorvolume uid to name and modify error log

---

install/v1alpha1-0.7.0/jiva-volume/volume.yaml

This PR will add iscsi, targetportal, iqn details to CASVolume schema under spec.

Use payload CASVolume instead of annotations

---

GNUmakefile
buildscripts/test-cov.sh

Ignore generated go files from travis CI test run.

Ignore generated code in travis CI run

---

install/v1alpha1-0.7.0/jiva-pool/pool.yaml
install/v1alpha1-0.7.0/jiva-volume/volume.yaml

The storage pool defined as per this commit ensures the use of a default host path i.e. `/var/openebs` to place the volume replica files.

add default storage pool to provision jiva volumes

---

cmd/cstor-pool-mgmt/volumereplica/volumereplica.go

- added -s option for  enabling thin-provisioning
- using 4K as the default volblocksize instead of 32K
- enabling compression by default with option compression=on

Create ZFS volume with compression, thin provisioning and with 4k blocksize by default

---

cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica.go

Subsequent delete calls causes the resource version
of the cstorvolumereplica to change.
When the first delete call is made the fetched cvr's
finalizer field is updated locally, meanwhile another
request arrives and the resource version of cvr in
k8s changes.
When the code tries to update cvr using the first
object it fetched the update fails due to rv mismatch.
To overcome this issue I have changed the update call
to patch. This would not be affected by multiple calls.
Changes:
modified:   cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
modified:   cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go
modified:   cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
**What this PR does / why we …

Use patch instead of update for cvr finalizer.

---

cmd/cstor-pool-mgmt/pool/pool.go

added error logs in CheckForZreplInitial and CheckForZreplContinuous methods to print the error message upon failure.

Added error logs in the healthcheck code of zrepl pool watcher

---

cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/maya-apiserver/spc-watcher/storagepool_create.go
pkg/apis/openebs.io/v1alpha1/cas_pool.go
pkg/storagepool/storagepool.go
pkg/storagepool/storagepool_template_engine.go

This PR will help to read openebs configs from spc (passed via annotations in spc)
to overwrite the default configs that can be used in run tasks.
The priority of openebs config will prevail over default config.

Add openebs config support in spc via annotations

---

pkg/client/k8s/k8s.go

PersistentVolume are not namespaced. Removed the passing of namespace parameter to the K8s API. 

Fix the get pv from CAS templates

---

pkg/engine/cas_template_engine.go
pkg/volume/volume_template_engine.go

This will enable castemplates of read/delete/list to specify default
config.

Add configTLP for read/delete/list CASEngine.

---

cmd/cstor-pool-mgmt/volumereplica/volumereplica.go

even when there are snapshots for that volume.

added -r option for zfs destroy command in order to delete a volume

---

pkg/engine/cas_template_engine.go

Using config tlp for fetching runNamespace was failing.
`err: runNamespace is empty.`
This was because the default values were not being set
by the Run() method.
The value of `c.templateValues[string(v1alpha1.ConfigTLP)]]`
is checked if nil and then set to default values. It would never
be nil as it is being set to an array during cas volume build.
Changed the initial value of the same to nil, now default values
are being set.

Bug fix: runNamespace not found.

---

cmd/mayactl/app/command/volume.go
cmd/mayactl/app/command/volume_info.go
cmd/mayactl/app/command/volume_info_test.go
cmd/mayactl/app/command/volume_test.go

-> This PR fixes replica status for cstor CASVolumes in volume info command in mayactl.
-> Currently Pool IP and access modes are not available. Need to add runtask for that .
-> Preview of ```mayactl volume info``` for cstor:
```
----------------
IQN           :   iqn.2016-09.com.openebs.cstor:default-cstor-volume-3602380723
Volume        :   default-cstor-volume-3602380723
Portal        :   10.35.251.53:3260
Size          :   4G
Status        :   running,running,running
Replica Count :   3
Replica Details :
-----------------
NAME                                                       STATUS      POOL NAME                  NODE    
---- …
```

Fix replica status for cstor CASVolume in volume info command in mayactl

---

pkg/client/k8s/v1alpha1/unstructured.go

This commit has following fix:
- Enhances the logic to transform the value of a resource
kind to its corresponding resource value
- e.g. kind 'pod' becomes resource 'pods'
- e.g. kind 'storageclass' becomes resource 'storageclasses'
NOTE:
Installer code makes use of client-go's dynamic package which in turn needs the use of GroupVersionResource. In addition, installer code takes yaml as input and tries to convert that to an unstructured instance before applying the same into kubernetes cluster. Since installer does not have a mechanism to get the resource value, it tries to build it based on kind's value.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …

enhance transforming kubernetes kind value to resource value

---

cmd/maya-apiserver/spc-watcher/storagepool_create.go

PR Description:
1. Name of cas templates is required to create and delete
storage pool.
2. The name of cas template can be fetched from :
I.  Via SPC annotations.
II. Via env variable.
The priority is(Decreasing priority).
Via SPC annotations--> Via env variable.
3. The validation for presence of annotations of CAS
template names for create and delete of pool in spc
watcher needs to be stripped off to support the above
priority based fetching.
4. Although handling for non availaiblity of CAS templates
is handled i.e. if not found at any of the places.
Refer to following PR for more details:
https://github.com/openebs/maya/pull/481/files

[Bug-Fix]Fix cas template annotations bug.

---

cmd/maya-apiserver/spc-watcher/storagepool_delete.go

Name of cas templates is required to create and delete
storage pool. This check is not required here once we get the
required templates from env.

Remove extra check for storagepool CAS template

---

pkg/apis/openebs.io/v1alpha1/cas_volume.go
pkg/util/env.go
pkg/volume/volume.go
pkg/volume/volume_test.go
types/v1/types.go

This commit does the following:
1. Add default castemplates for cstor read,create and delete
2. Rename jiva castemplates name for read,create and delete
3. Uncomment CStorVolume type
4. Introduce CASKey called CASTypeKey = "openebs.io/cas-type"
which would be used to fetch engine type from sc. This is the
same annotation key put in PV to define engine type.
5. If the castemplate is missing in SC annotation then switch
castemplate based on CASTypeKey. If CASTypeKey is not cstor
then default to jiva cas templates.
**Special notes …

Use env var fallback for missing cast names in sc.

---

pkg/client/k8s/v1alpha1/resource.go
pkg/client/k8s/v1alpha1/unstructured.go
pkg/install/v1alpha1/cstor_sparse_pool_claim_0.7.0.go
pkg/install/v1alpha1/installer.go

This commit has below fixes:
- Introduces new predicate w.r.t unstructured instances
- This predicate evaluates if the unstructured instance is namespaced scope
- sparse pool related storageclass resource is added
Other changes:
- The unstructured.go file is split into unstructured.go & resource.go
- installer.go file has been made more informative via comments

evaluate if resource is `namespaced` before install

---

pkg/client/k8s/v1alpha1/unstructured.go
pkg/install/v1alpha1/artifact.go
pkg/install/v1alpha1/cstor_pool_0.7.0.go
pkg/install/v1alpha1/cstor_volume_0.7.0.go
pkg/install/v1alpha1/installer.go
pkg/install/v1alpha1/jiva_volume_0.7.0.go
pkg/install/v1alpha1/registrar.go
pkg/install/v1alpha1/template_values.go
pkg/template/v1alpha1/template.go

This commit has following features:
- Adds sprig template functions to render the artifacts before installing the same
- The sprig template function that is currently used in artifact is `env`
- A sample usage is shown below:
```yaml
{{env "OPENEBS_IO_REPLICA_NODE_SELECTOR" | default "false"}}
```

add env as template function to artifacts

---

cmd/maya-apiserver/spc-watcher/handler.go
cmd/maya-apiserver/spc-watcher/lease.go
cmd/maya-apiserver/spc-watcher/lease_test.go
pkg/env/v1alpha1/env.go

1. Add code for lease logic.
2. Before creating a storagepool in
case of add event of spc, lease will
be acquired so that no two replica
process the same request.
**Newly Added Files**
1.cmd/maya-apiserver/spc-watcher/lease.go
2.cmd/maya-apiserver/spc-watcher/lease_test.go
**Modified File**
1.cmd/maya-apiserver/spc-watcher/handler.go
**Env Variables Used**
1. "OPENEBS_MAYA_POD_NAME"
2.  "OPENEBS_NAMESPACE"
The PR is dependent on following PR (as it uses env variables exposed by downward api):
https://github.com/openebs/openebs/pull/1870

[Bug Fix]Acquire lease on SPC for add event pool creation

---

cmd/mayactl/app/command/volume_create_test.go
cmd/mayactl/app/command/volumes_list.go
pkg/client/mapiserver/volumes_list.go
pkg/client/mapiserver/volumes_list_test.go

This commit will enhance the error logging , will read the response from http response body and print in case of http response status is not OK(200) 

 Extend error message and  print response error

---

pkg/install/v1alpha1/cstor_pool_0.7.0.go

For some of the vendors like AWS EBS Volumes we do not have a dev link.
This PR update the run task which will do following:
1. If disk dev-link is not present in the disk then it will use disk path to provision
storage pool. 

Use disk path if dev link is not present.

---

pkg/apis/openebs.io/v1alpha1/cas_volume.go
pkg/install/v1alpha1/cstor_volume_0.7.0.go
pkg/install/v1alpha1/jiva_volume_0.7.0.go

Some of the applications require 'xfs' as a filesystem on the
OpenEBS iSCSI PVs. This PR allows the user to specify a custom
format type `FSType` under StorageClass->`openebs.io/config`
The FSType value will be used by the provisioner to pass it
in the PV. Modified the CAS Volume to send the FSType in read
response.
Similarly the default LUN to connect to is also sent via the
CAS Volume to provisioner.

feat(policies): add policies to customize client fstype and lun

---

pkg/install/v1alpha1/cstor_pool_0.7.0.go
pkg/install/v1alpha1/cstor_sparse_pool_claim_0.7.0.go

cacheFile option provided in the SPC is ignored, and
a unique cacheFile path is auto generated using the SPC uuid
and provided to cstor-pool. The hardcoded value in SPC is
unusable, since it has to be unique across pools.
overProvisioning is always hardcoded to false. Providing
this option in the SPC will given an impression to user
that it can be enabled/disabled. Until this feature is
supported, removed the need to specify it via SPC.

refactor(cast): remove unused parameters from SPC

---

pkg/install/v1alpha1/cstor_volume_0.7.0.go
pkg/install/v1alpha1/jiva_volume_0.7.0.go

1. This commit will fix the volume list CAS templates for cstor and jiva, by putting default value if there are no values,  which was causing below errors in maya-apiserver logs.
` [ERR] http: Request GET /latest/volumes/, error: template: OutputYamlTpl:24:59:
executing "OutputYamlTpl" at <replace>: wrong number of args for replace: want 3 got 2
`
2. Remove the unused labels `pvc` and `openebs_pv`  from deployments which are no longer in use.

fix(maya-apiserver): volume list CAS template and remove unused labels

---

pkg/install/v1alpha1/cstor_volume_0.7.0.go

Mount /var/openebs/shared-{{ .Volume.owner }}-target from hostpath to  cstor volume target's istgt and management at /tmp
containers. This would be used to take core dumps.

chore(install): Mount /tmp for core dumps target deployment containers

---

ci/install_openebs.sh
pkg/client/k8s/v1alpha1/unstructured.go
pkg/install/v1alpha1/cstor_sparse_pool_claim_0.7.0.go
pkg/install/v1alpha1/cstor_sparse_pool_claim_0.7.0_test.go
pkg/install/v1alpha1/jiva_pool_0.7.0.go
pkg/install/v1alpha1/openebs_crds_0.7.0.go
pkg/install/v1alpha1/registrar.go
pkg/install/v1alpha1/snapshot_promoter_sc.go

This PR aims at reducing the manual operations when installing OpenEBS via helm charts and also to reduce some duplicated code across different helm charts.
- The CRDs don't change on every release and users don't need to customize/modify them. Hence it makes sense to install them via maya-installer and reduce the duplicated code between openebs-operator and various types of helm charts.
- Similarly, the default SP and SC for jiva have to be installed seperately by the user after installing via helm charts. This PR makes them available by default.
- Another additional step that user has to do when installing via helm charts is to create a StorageClass for snapshot promote(clone).

refactor(install): include CRDs and default SP, SCs into maya installer

---

pkg/install/v1alpha1/cstor_pool_0.7.0.go

Use the namespace passed from the configuration instead
of hardcoded value of openebs.

fix(install): remove hardcoded ns from cstor pool cast

---

pkg/install/v1alpha1/cstor_volume_0.7.0.go

The dummyfile mount to target deployment's mgmt and istgt container is
at /tmp/cstor is not required.
This commit removes the mounting.

fix(cast): remove /tmp/cstor dummyfile mount from cstor target pod

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
cmd/cstor-pool-mgmt/controller/start-controller/controller.go
cmd/cstor-pool-mgmt/pool/pool.go
cmd/cstor-pool-mgmt/pool/pool_test.go

- this change is to make pool mgmt container to restart itself there by re-importing a pool upon zrepl crash.
- this change also makes the pool-mgmt container to restart when pool creation or import fails. this is achieved by checking for the "zpool status" command output and finding out if there is no pool available  after handling the cstorpool add event.

refactor(cstor-integration)restart pool mgmt container when unable to find zrepl pool.

---

pkg/install/v1alpha1/cstor_volume_0.7.0.go
pkg/template/template.go
pkg/template/template_test.go

The cstor-volume-create-listcstorpoolcr-default-0.7.0 task was getting
the size of pool as actual count + 1. This is because when the list is
split there is an extra entry with content "" appended to the array.
e.g. 'a;b;' when split will give 3 values instead of two.
This was causing the pool size to appear as one size extra.
Fixed this by adding a function splitListTrim in template.go which would
first remove prefix and suffix seperator and then internally use the
same logic as that of splitList.

fix(runtask): Fix available pool count check.

---

pkg/template/runtask_functions.go
pkg/template/runtask_functions_test.go

Remove older `url` and `name` functions which were specific for keys
'url' and 'name' respectively and introduce a generic function
`withoption` which will accept both the key and value.

feat(cast): Introduce withoption function in cas template.

---

pkg/install/v1alpha1/cstor_pool_0.7.0.go
pkg/install/v1alpha1/cstor_sparse_pool_claim_0.7.0.go
pkg/install/v1alpha1/cstor_volume_0.7.0.go
pkg/install/v1alpha1/jiva_pool_0.7.0.go
pkg/install/v1alpha1/jiva_volume_0.6.0.go
pkg/install/v1alpha1/jiva_volume_0.7.0.go
pkg/install/v1alpha1/openebs_crds_0.7.0.go
pkg/install/v1alpha1/snapshot_promoter_sc.go
pkg/install/v1alpha1/version.go

-> Enhanced volume read runtask to give controller node name which can be consumed by mayactl .
-> Fixes empty namespace for cstor volumes in volume list.
-> volume list response: 
```
{
"items": [
{
"apiVersion": "v1alpha1",
"kind": "CASVolume",
"metadata": {
"annotations": {
"openebs.io/replica-ips": "10.4.1.8, 10.4.0.10, 10.4.2.8",
"openebs.io/replica-status": "running, running, running",
"openebs.io/volume-size": "5G",
"vsm.openebs.io/cluster-ips": "10.7.254.120",
"vsm.openebs.io/replica-count": "3",
"vsm.openebs.io/targetportals": "10.7.254.120:3260",
"openebs.io/iqn": "iqn.2016-09.com.openebs.jiva:default-jiva-testvol-1-1931265930", …
```

feat(mayactl) Enhance run task to get controller host name and fix NS for cstor response

---

cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
cmd/cstor-pool-mgmt/volumereplica/volumreplica_test.go

The binary capacity unit (e.g. Gi, Ki, Mi etc)
was failing for volume provisioning.
This PR will fix the fail.
**Note:The binary suffixes will be quantitatively equal to decimal suffix** 
Supported Binary Suffixes:
Ki, Mi, Gi, Ti, Pi, Ei will we quantitatively equal to K, M, G, T, P, E

(fix:binary capacity unit)add support for binary capacity unit

---

pkg/install/v1alpha1/cstor_volume_0.7.0.go

This PR fixes a typo in line 554 of the cstor_volume_0.7.0.go. It fixes "https://github.com/openebs/openebs/issues/1932"
Signed-off-by: gunjan01 <gunjan.tank9@gmail.com>

Fixes typo line 554 in cstor_volume_0.7.0.go

---

GNUmakefile
cmd/maya-agent/types/v1/storagebackend.go
pkg/client/http/v1alpha1/http_client.go
pkg/client/http/v1alpha1/http_client_test.go
pkg/client/jiva/controller_client.go
pkg/install/v1alpha1/jiva_snapshot_0.7.0.go
pkg/install/v1alpha1/registrar.go
pkg/jsonpath/v1alpha1/json_path.go
pkg/jsonpath/v1alpha1/json_path_test.go
pkg/msg/v1alpha1/msg.go
pkg/msg/v1alpha1/msg_test.go
pkg/storagepool/storagepool_template_engine.go
pkg/task/v1alpha1/http_command.go
pkg/task/v1alpha1/http_command_test.go
pkg/task/v1alpha1/jiva_volume_command.go
pkg/task/v1alpha1/jiva_volume_command_test.go
pkg/task/v1alpha1/jiva_volume_delete.go
pkg/task/v1alpha1/jiva_volume_delete_test.go
pkg/task/v1alpha1/runtask_command.go
pkg/task/v1alpha1/runtask_command_test.go
pkg/task/v1alpha1/store_command.go
pkg/task/v1alpha1/store_command_test.go
pkg/template/runtask_functions.go
pkg/template/runtask_functions_test.go
pkg/volume/volume.go

This commit makes use of generic http APIs exposed via CAS Template to take jiva snapshot.
This commit has below change:
- `pkg/task/v1alpha1`
- updates run command to understand select via json path query
- introduces store command which is a wrapper over run command & provides features like storing the run command execution result and conditional execution of run commands.
- introduces http based post, get, delete, put, patch operations as run commands
- `pkg/template/runtask_functions.go`
- introduces following template functions:
- storeAt, storeRunner, storeRunnerCond, runas, runAlways
- `pkg/install`
- introduces cas templates based artifacts w.r.t jiva snapshot operation
Dependencies:
- PR https://github.com/openebs/maya/pull/527 …

feat(cast, jiva, snapshot): add castemplate to take jiva snapshot

---

ci/setup_env.sh

The snapshot workflow is being changed to use the CAS templates. (#527)
Until mayactl is updated to use the CAS templates way of creating the
snapshots, disabling them from CI.

refactor(ci): disable the mayactl snapshot commands from ci temporarily

---

orchprovider/k8s/v1/k8s_test.go

Line 275: warning: if block ends with a return statement, so drop this else and outdent its block (golint)

Formatting issues - GoLint

---

pkg/snapshot/v1alpha1/snapshot_test.go

**What this PR does / why we need it**: Unset os' environment variables after each test that modifies it.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes openebs/openebs#1999
Signed-off-by: Rudy rudolf_bast@live.com

Fix modified env variable after tests

---

buildscripts/mayactl/build.sh

Signed-off-by: NerdyPepper <akshayoppiliappan@gmail.com>
This PR fixes a major typographical error, and various _potential_ issues, caused by not following Bash Style guidelines.
It fixes [this](https://github.com/openebs/openebs/issues/2023#issuecomment-427555678) issue.
Using ```#!/usr/bin/env bash``` has potential code injection issues (`bash` could be a malicious executable in the target environment), but I have not changed it.

Fix typographical error, adhere to bash style guidelines

---

cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
pkg/volume/volume.go
pkg/volume/volume_template_engine.go

This PR addresses https://github.com/openebs/openebs/issues/1966
The original ticket only said to fix a specific lint error but there were several more errors found when running golint.
Two big changes here to make lint happier.
1. Removal of the word "Volume' from public types in the volume package. This cause stutters on the consumer end "volume.VolumeOperation" and is now simpler "volume.Operation".
2. Constructor for NewCASVolumeEngine was returning a private struct. I wasn't sure if the plan was to make the struct public or not so I instead made the function return the interface that the engine is fulfilling.
Let me know if any of this isn't correct!

Fixed lint errors in the volume package

---

pkg/install/v1alpha1/cstor_volume_0.7.0.go

All the clones of a particular volume should be created on the same pool
as that of the original volume.
Add a runtask cstor-volume-create-listclonecstorvolumecr-default-0.7.0
which shadows the functionlity of cstor-volume-create-listcstorpoolcr-default-0.7.0
whenever the creating volume is a clone.

feat(cast): Add new runtask to support cstor cloning.

---

pkg/install/v1alpha1/cstor_snapshot_0.7.0.go
pkg/snapshot/v1alpha1/snapshot.go

Add cas template and runtasks to support cstor snapshot delete.  
Fixed bug function call from `getReadCASTemplate` to `getDeleteCASTemplate`
in snapshot `Delete` function.

feat(snapshot-delete): Add support to delete cstor-snapshot.

---

pkg/install/v1alpha1/jiva_snapshot_0.7.0.go
pkg/template/runtask_functions.go

Introduce function `toJsonObj` which converts given interface to json bytes.
Update runtask `openebs jiva-snapshot-create-invokehttp-default-0.7.0` to use above method.
Add output run task to jiva snapshot create cast.

fix(cast): Fix jiva snapshot cast.

---

cmd/cstor-pool-mgmt/controller/pool-controller/run_pool_controller.go

Adds a space before the package comment, which seems to fix the
warning given by golint.
Fixes https://github.com/openebs/openebs/issues/2101
I am not sure *why* golint is giving this error, it seems like this format is followed in other files with no issue. But adding a space does fix the error and golint does not complain anymore.

run_pool_controller.go: Fix golint issue

---

types/v1/types.go

This PR fixed the golint issue for the maya/types/v1/types.go
Fixes Issue https://github.com/openebs/openebs/issues/2141
Added a comment for const DeploymentKK.

Fix #2141 golint issues area/maya

---

GNUmakefile
buildscripts/apiserver/Dockerfile.rhel
buildscripts/apiserver/licenses/Apache-2.0.txt

Dockerfile will use openebs/rhel7 as a base image required for
RedHat container certification for OpenEBS images

feat(build): add RHEL based dockerfile for container certification

---

ci/setup_env.sh

Due to change in PV name (pvc-UUID), needs to read the volume name using CASType,
which is getting passed to mayactl operations.

fix(ci): use jsonpath to get the volume name for integration test

---

cmd/cstor-pool-mgmt/controller/pool-controller/run_pool_controller.go
cmd/mayactl/app/command/commands.go
cmd/mayactl/app/command/completion.go

The feature is implemented using `cobra-cli`'s builtin bash completion which fixes [#1987](https://github.com/openebs/openebs/issues/1987). Here, command `completion` is added to the `mayactl`, which will generate bash completion script.
To add mayactl autocompletion to your current shell, run `source <(mayactl completion)`.
To add mayactl autocompletion to your profile, so it automatically loaded in future shells run:
```bash
echo "source <(mayactl completion bash)" >> ~/.bashrc
```
Planning to add support for other shells like `zsh` also.

feat(mayactl): Adds bash completion for mayactl (#1987)

---

pkg/install/v1alpha1/snapshot_promoter_sc.go
pkg/snapshot/v1alpha1/snapshot.go
pkg/snapshot/v1alpha1/snapshot_test.go
pkg/volume/volume.go
pkg/volume/volume_test.go

A clone volume would always have promoter as default storage class.
This storage class is no distiguishable, it is common for jiva and
the cstor volume. The clone volume therefore should make use of the
the same sc as that of the source pv.
Modified the logic accordingly in both snapshot and volume engine.
Use sc from label > Use sc from pvref(if cast annotation is present) >
Use default annotation for given storage engine.

chore(cas engine): Use storage class from pv labels.

---

cmd/maya-exporter/app/collector/cstorcollector.go
cmd/maya-exporter/app/collector/cstorcollector_test.go
cmd/maya-exporter/app/collector/jivacollector_test.go
types/v1/metrics.go

This commit adds the following metrics in cstor side:
- Total read/write time
- Read/write block count
- Uptime
In addition this commit also removes the unused codes and
improves unit test readability.
- We still have to work on used size part. it's not been done yet
at the replication side.
Signed-off-by: Utkarsh Mani Tripathi <utkarshmani1997@gmail.com>

[TA3720, TA3722] feat(exporter): add missing stats

---

pkg/install/v1alpha1/cstor_volume.go

If the volume to be created is not clone volume then the runtask
cstor-volume-create-listclonecstorvolumecr-default-0.7.0 will list
all the present cvrs.
This is not required and will lead to unseen consequences like having
different pools than the source volume pools.
Fixed this by using a non existent label selector.

fix(cast): Fix cstor clone cast.

---

hack/cstor_volume/test/util.sh

Duplicate code in kubectlApply() and kubectlDelete() functions.
Refactored code to create a function 'prefixedFileNames()' with common code in util.sh file to ensure code reusability at its best (with least complexity, of course)
**Which issue this PR fixes**: fixes #730 
**Special notes for your reviewer**: Please label it with hacktoberfest label.

refactor(util.sh): removal of duplicate code in hack/cstor_volume/test/util.sh

---

cmd/maya-exporter/app/collector/cstorcollector.go
cmd/maya-exporter/app/collector/cstorcollector_test.go
cmd/maya-exporter/app/collector/jivacollector.go
cmd/maya-exporter/app/collector/metrics.go
types/v1/metrics.go

This commit fixes the following
- Fixes json tag of volume uptime to string
- Make common structure for jiva and cstore
- Add the missing fields in cstor
- Modularize the code
Depends on openebs/jiva#152 and openebs/istgt#175

fix(exporter): make common structure for both jiva and cstor

---

pkg/client/k8s/v1alpha1/node.go
pkg/usage/googleanalytics.go

- This will add `OS name, Kernel version` to the event hit.
improvement: https://github.com/openebs/openebs/issues/2257

fix(analytics) Add node information to GA hit

---

ci/install_openebs.sh

integration (or ci) tests are done by applying the openebs-operator
fetched from openebs/openebs repo. This file can either have images
specified as quay or docker.
Before applying the operator yaml, retag the local docker ci images
with quay tags.

refactor(ci): support both docker and quay images for ci

---

pkg/task/meta.go
pkg/task/task.go

This commit can disable execution of RunTask based on disable option
For example below RunTask will not get executed as `disable` field is set to true:
```yaml
kind: RunTask
metadata:
name: svc-list
spec:
meta: |
id: svcList
disable: true
runNamespace: {{.Volume.runNamespace}}
apiVersion: v1
kind: Service
action: list
options: |-
labelSelector: vsm={{ .Volume.owner }}
post: |
{{- .JsonResult | saveAs "svcList" .TaskResult | noop -}}
```

feat(cast): add disable option to RunTask

---

pkg/usage/googleanalytics.go
pkg/usage/versionset.go
pkg/version/version.go

- Earlier, If `pkg/usage` is used to send multiple events, it'll have to fetch constants from the Kubernetes API each time, now they are saved in environment variables.
- Moves fetching of version details in a new file, `pkg/usage/versionset.go`
- Changes `VERSION` to `0.8.0`
- Adds a function to get version in format `${GIT_TAG}-${GIT_SHORT_COMMIT}`
issue: https://github.com/openebs/openebs/issues/2257

refactor(version) Set the cluster constants in env variables

---

ci/setup_env.sh
pkg/install/v1alpha1/jiva_volume_0.7.0.go

Refer: 
https://github.com/openebs/openebs/issues/1246
After the jiva volumes are delete, the data stored
in the corresponding jiva pool directory is not
deleted. This can cause the space outage issues
when many jiva volumes are created and deleted.
This PR updates the delete jiva volume CAS templates
to launch a K8s job that clears the contents. A job
is scheduled with the node selector where replica
exists, so in case the node is offline during delete,
the job will still get executed after the nodes
comes back online.
Few things for future:
- When volume replica are migrated to a different node,
the data from older nodes needs to be cleared
- For volumes in earlier version, the contents
have to be manually deleted.

feat(jiva): add scrub job on deleted jiva replicas

---

cmd/maya-apiserver/app/command/start.go

This commit moves the start logic of storage pool controller post the API service is started successfully.

fix(spc, install, startup): move spc start logic post API service start

---

pkg/volume/volume.go
pkg/volume/volume_template_engine.go

This commit enables volume delete operation to make use of cas config available at PVC, SC to influence the delete logic.
The priority of cas config is as follows:
PVC >> SC >> default

feat(cast, v0.7.x): use cas config from PVC & SC for volume delete

---

pkg/volume/volume.go

This commit removes kubernetes API query against PVC resource during volume delete operation. It was seen that the volume's corresponding PVC object gets deleted by the time volume delete operation takes place.

fix(volume, cast): fix error due to use of PVC cas config during volume delete

---

pkg/install/v1alpha1/jiva_volume_0.7.0.go

When application and volume target pod are located in different nodes, a node down event on node containing target pod will cause the IO to break for the application.
It is sometimes desirable to **co-locate** the target pod on the same node as the application pod.
This commit uses the application pod label to create the affinity. The user will have to specify the following label on both application and PVC:
```yaml
openebs.io/target-affinity: <unique application name>
```
The volume target pod will have the following pod affinity rule:
```
affinity:
podAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector:
matchExpressions:
- key: openebs.io/target-affinity
operator: In
values:
- <unique application name>
topologyKey: kubernetes.io/hostname
```
The following cases …

feat(provisioning): add pod affinity expr to target pod

---

pkg/task/meta.go

With the introduction of disabled tasks, the CAST
engine should skip forming rollback tasks for runtasks
that evaluate to disabled.

fix(cast): do not perform rollback on disabled run tasks

---

ci/install_openebs.sh
ci/setup_env.sh
cmd/maya-apiserver/app/command/start.go
pkg/client/k8s/k8s.go
pkg/install/v1alpha1/jiva_volume.go
pkg/k8s/from_yaml.go
pkg/task/identity.go
pkg/task/meta.go
pkg/task/task.go
pkg/volume/volume.go

Cherry Pick the following commits:
- c8e7a7469caf6280e02e68af6ce6ee1a729c1584 ( feat(jiva): add scrub job on deleted jiva replicas (#786) )
- 3b1cda24832d197b5ef3ad9c8c3c41fda5d06441 ( fix(spc, install, startup): move spc start logic after API service starts)
- e173c3f117cc3eb404963b930591e31bc7dc600c ( feat(cast): add disable option to RunTask)
- 7fd61ebde133b8a847865f136a7c625a406d3b45 ( feat(cast, job): add Create, Get & Delete operation for job in CASTemplate)
- 250fd947f368462cb802ed2e16ede770c56fdcd1 ( refactor(ci): support both docker and quay images for ci (#785))
- ecb712039755a2f55b46ba4560767d1ad9fdd4e9 ( fix(volume, cast): fix error due to use of PVC cas config during volume delete )
- 5055eefd7005d35f94d38393c756f7cebdc2b1f9 ( feat(provisioning): add pod affinity expr to jiva …

chore(merge): cherry-fix jiva delete fixes from 0.7.x to master

---

Gopkg.lock
Gopkg.toml
cmd/maya-apiserver/app/command/start.go
pkg/usage/googleanalytics.go
pkg/usage/usage.go
pkg/usage/versionset.go
vendor/github.com/jpillora/go-ogle-analytics/client.go

- Earlier, sending events to `GoogleAnalytics` was a blocking call now it runs in a different `goroutine`
- This updates the `go-ogle-analytics` package to pickup from `openebs` organization, this has updated [vendor packages](https://github.com/openebs/go-ogle-analytics/pull/1/) which helps with [this limitation](https://blog.yaakov.online/kubernetes-getting-pods-to-talk-to-the-internet/) 
issue: https://github.com/openebs/openebs/issues/2257

enhancement(usage) Unblock sending usage events

---

cmd/cstor-volume-mgmt/controller/common/common.go
cmd/cstor-volume-mgmt/controller/volume-controller/handler.go
cmd/cstor-volume-mgmt/controller/volume-controller/handler_test.go
cmd/cstor-volume-mgmt/volume/volume.go
cmd/cstor-volume-mgmt/volume/volume_test.go
pkg/apis/openebs.io/v1alpha1/cstor_volume.go

The istgtcontrol command is expected to return response in a new json
format. This PR uses the updated json format.
The response is also going to contain the overall status of the volume.
If the cv is not in error,init,invalid states then the status in
response would be updated on the CV object.
Output of cstorvolume describe:
```yaml
Status:
Phase:  Healthy
Replica Statuses:
Replica Id:  2506826991850132511
Status:      HEALTHY
Replica Id:  6824451318329165203
Status:      HEALTHY
Replica Id:  3433388595249797004
Status:      HEALTHY
Events:
Type    Reason    Age                  From                                                                                                      Message
----    ------    ---- …
```

refactor(cstor-volume-mgmt): Use status being supplied by istgt command.

---

cmd/cstor-volume-mgmt/controller/volume-controller/handler.go
cmd/cstor-volume-mgmt/volume/volume_test.go
pkg/apis/openebs.io/v1alpha1/cstor_volume.go

The response from istgt was being parsed and then updated in the cv's
replica statuses field.
```yaml
Modified above logic to directly fill replica statuses in cv using
response.
Status:
Phase:  Healthy
Replica Statuses:
Checkpointed IO Seq:  0
Inflight Read:        0
Inflight Sync:        0
Inflight Write:       0
Replica Id:           11858145003581796177
Status:               HEALTHY
Up Time:              516
Checkpointed IO Seq:  0
Inflight Read:        0
Inflight Sync:        0
Inflight Write:       0
Replica Id:           16413594999089341547
Status:               HEALTHY
Up Time:              515
Checkpointed IO Seq:  0
Inflight Read:        0
Inflight Sync:        0
Inflight Write:       0
Replica Id:           3693374404252622418
Status:               HEALTHY
Up Time: …
```

refactor(cstor-volume): Use replica status from response to fill cv.

---

pkg/install/v1alpha1/cstor_volume.go

Only those CSP(s) were selected for volume replica that had 'Online' status.
This PR will allow selection of CSP for  replica irrespective of their status.
In near future volume distribution will enhance selection of CVR. 

fix(cvr): remove status based selection of csp for cvr(s).

---

cmd/cstor-pool-mgmt/controller/common/common.go
cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica_test.go
pkg/apis/openebs.io/v1alpha1/cstor_volume_replica.go

Put zfs volume status on cvr object on every rsync.
Example cvr object :
```json
{
"apiVersion": "openebs.io/v1alpha1",
"kind": "CStorVolumeReplica",
"metadata": {
"annotations": {
"cstorpool.openebs.io/hostname": "gke-cstor-it-default-pool-e84f5225-p7jk"
},
"creationTimestamp": "2018-11-22T06:55:38Z",
"finalizers": [
"cstorvolumereplica.openebs.io/finalizer"
],
"generation": 1,
"labels": {
"cstorpool.openebs.io/name": "sparse-claim-auto-edf5",
"cstorpool.openebs.io/uid": "183f17c6-ed8b-11e8-87fd-42010a800087",
"cstorvolume.openebs.io/name": "pvc-9e91f938-ee23-11e8-87fd-42010a800087",
"openebs.io/cas-template-name": "cstor-volume-create-default-0.8.0",
"openebs.io/persistent-volume": "pvc-9e91f938-ee23-11e8-87fd-42010a800087",
"openebs.io/version": "0.8.0"
}, …
```

feat(cvr): add zfs volume status on cvr object

---

cmd/maya-exporter/app/collector/cstorcollector.go
cmd/maya-exporter/app/collector/jivacollector.go
cmd/maya-exporter/app/collector/metrics.go

Add following volume status into exporter:
```
HELP openebs_volume_status Status of volume: (1, 2, 3, 4) = {Offline, Degraded, Healthy, Unknown}
TYPE openebs_volume_status gauge
openebs_volume_status 1
```
Depends on : openebs/istgt#181

feat(exporter): add volume status into exporter

---

cmd/cstor-volume-mgmt/controller/start-controller/controller.go

It was observed that post the commit bd44756e60bc1023bfa52d31ffcf5d70e25333f2
cstor-volume-mgmt was spinning high on cpu as soon as it came up. Ran the CPU
profiling on this binary by following the steps mentioned here:
http://rodrigodumont.com/2017/11/10/profile-go-micro-services-in-kubernetes-with-pprof/
Found that the methods startExternalVersionsInformerFactory and startSharedInformerFactory, 
where showing up on the top5 that used the CPU. 
Found that the above commit has actually refactored the code and added those two 
wrapper methods with a for {} loop. After reverting these changes, ran the CPU profile again
and got the following output:
```
Type: cpu
Time: Nov 23, 2018 at 2:26pm (UTC)
Duration: 3mins, Total samples = 50ms (0.028%)
Entering interactive mode (type "help" for …
```

fix(cstor-volume-mgmt): high cpu usage caused by for {} loop

---

cmd/cstor-pool-mgmt/volumereplica/volumereplica.go

fix(volumereplica) index out of bound error while parsing volume status

fix(volumereplica): index out of bound error while parsing volume status

---

pkg/install/v1alpha1/volume_stats.go

This commit fixes a bug related to cas template expression while building the volume stats output.

fix(cast, jiva, stats) error executing cast output for volume stats

---

pkg/install/v1alpha1/cstor_volume.go

The empty string in status does not very well expreses the status of
the cstor volume therefore as soon as it gets created it should always
have Init as status.

fix(cast): Add default status of created cstorvolume as Init.

---

cmd/maya-apiserver/spc-watcher/select_disk.go
cmd/maya-apiserver/spc-watcher/select_disk_test.go

Choose only active disk for pool provisioning.

fix(disk-selection): choose only active disk for pool provisioning

---

pkg/install/v1alpha1/cstor_volume.go

It would be useful to a reference of spc in the target deployment
when upgrading openebs.
Added label `openebs.io/storage-pool-claim` to the deployment.

chore(install): Add spc reference in target deployment label.

---

GNUmakefile

Add `kubegen` makefile target to generate only kubernetes CRD's autogen codes

fix(build): add Makefile target to generate k8s autogen

---

pkg/install/v1alpha1/cstor_volume.go

When application and volume target pod are located in different nodes, a node down event on node containing target pod will cause the IO to break for the application.
It is sometimes desirable to **co-locate** the target pod on the same node as the application pod.
This commit uses the application pod label to create the affinity. The user will have to specify the following label on both application and PVC:
```yaml
openebs.io/target-affinity: <unique application name>
```
The volume target pod will have the following pod affinity rule:
```
affinity:
podAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector:
matchExpressions:
- key: openebs.io/target-affinity
operator: In
values:
- <unique application name>
topologyKey: kubernetes.io/hostname
namespaces: …
```

feat(provisioning): add pod affinity expr to cstor target pod

---

cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go

If volume creation fails then the value in `cvol` object would be nil.
This was causing panic when volumeevents function was being called.
Fixed this by checking error first.
Fixes: https://github.com/openebs/openebs/issues/2305

fix(m-apiserver): Fire volume events only if volume creation is successful

---

cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go

Earlier the event was sent to Google Analytics after the event had been
successfully processed.
Now the event will be sent everytime it has been successfully received
as specified in the request body.
A bug was reported where, m-apiserver wasn't sending back the error to `openebs-provisioner` because a nil pointer dereference had occurred before
```
I1128 12:39:15.579893       7 logs.go:43] http: panic serving 10.130.0.1:46696: runtime error: invalid memory address or nil pointer dereference
goroutine 4770 [running]:
net/http.(*conn).serve.func1(0xc420854dc0)
/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/server.go:1726 +0xd0
panic(0x13ffaa0, 0x2036d10) …
```

fix(volume-event) Send volume event request metric to GA

---

cmd/cstor-pool-mgmt/controller/common/common.go
cmd/cstor-pool-mgmt/controller/start-controller/controller.go
cmd/cstor-pool-mgmt/controller/start-controller/controller_test.go
cmd/cstor-volume-mgmt/controller/common/common.go
cmd/cstor-volume-mgmt/controller/start-controller/controller.go
cmd/cstor-volume-mgmt/controller/start-controller/controller_test.go
pkg/install/v1alpha1/cstor_pool.go
pkg/install/v1alpha1/cstor_volume.go

Sometimes it is desired to alter the sync period of cstor-volume-mgmt or
cstor-pool-mgmt so that we get the update on CVR cr or CSV cr status as
desired.
The sync interval is configurable and it can be set using
.Config.ResyncInterval as a cas config.

feat(volume-mgmt,pool-mgmt): Make sync period of controller configurable

---

cmd/mayactl/app/command/commands.go

Stash mayactl snapshot command for 0.8 release.
Note:
1. Tested the changes by executing 
```
mayactl --help
Maya means 'Magic' a tool for storage orchestration
Usage:
mayactl [command]
completion  Outputs shell completion code for the specified shell (bash or zsh)
help        Help about any command
pool        Provides operations related to a storage pool
version     Prints version and other details relevant to maya
volume      Provides operations related to a Volume
Flags:
--alsologtostderr                  log to standard error as well as files
-h, --help                             help for mayactl
--log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
--log_dir string …
```

Hiding mayactl snapshot command for 0.8 release

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler_test.go
cmd/cstor-pool-mgmt/pool/pool.go
cmd/cstor-pool-mgmt/pool/pool_test.go
cmd/maya-apiserver/spc-watcher/handler_test.go
pkg/apis/openebs.io/v1alpha1/cstor_pool.go

There was a bug in code where cstor pool getting created
as pooltype 'striped' even we specify pooltype as 'mirrored'.
fixes: openebs/openebs#2301
Note: 
1. Tested the changes by creating mirrored pool using below SPC yaml
```
---
metadata:
name: mirroredexternalspc
spec:
name: mirroredexternalspc
type: disk
maxPools: 3
poolSpec:
poolType: mirrored
disks:
diskList:
- disk-4769b8d4a81fc4d220d959818d6ab671
- disk-547716b4c82c975c634d386a42ef35cb
- disk-7e9b37122292048f819a3abafccacdba
- disk-80774fe7f6aaedd2ebe381e97cece450
- disk-c60f90ac890508cfbf5d1ff9ff9e8cfb
- disk-d85fe8b916e876d1ed130e5c2117e9c0
---
metadata:
name: mirrored-externalsc …
```

fix(pool): Create pool with pool type as mirrored

---

pkg/apis/openebs.io/v1alpha1/cas_keys.go
pkg/client/k8s/v1alpha1/k8s.go
pkg/client/k8s/v1alpha1/unstructured.go
pkg/install/v1alpha1/installer.go
pkg/msg/v1alpha1/msg.go
pkg/template/template.go
pkg/template/template_test.go
pkg/version/kubernetes/version.go
pkg/version/kubernetes/version_test.go

This commit adds kubernetes version as a label to CASTemplate e.g. `kubeVersion: v1.9.7-gke.11`. In addition, a number of version related template functions have been exposed that can be used during
go templating.
Below are the introduced template functions:
- kubeVersionCompare
- kubeVersionEq
- kubeVersionGt
- kubeVersionGte
- kubeVersionLt
- kubeVersionLte
Below is a sample CASTemplate that gets installed due to this changes:
```yaml
kind: CASTemplate
metadata:
labels:
castName: storage-pool-read-default-0.8.0
kubeVersion: v1.9.7-gke.11
version: 0.8.0
name: storage-pool-read-default-0.8.0
```
Setting version as a label in CASTemplate results in having this label as a part of cast config that can be used via go templating in mapped RunTasks, for example: …

feat(install, cast) add kubernetes version as label to default CASTemplates

---

cmd/cstor-pool-mgmt/controller/common/common.go
cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
cmd/cstor-pool-mgmt/controller/pool-controller/new_pool_controller.go
cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go
cmd/cstor-pool-mgmt/pool/pool.go
pkg/lease/v1alpha1/csp_lease.go
pkg/lease/v1alpha1/csp_lease_test.go
pkg/lease/v1alpha1/lease.go
pkg/patch/v1alpha1/patch.go

**This PR adds CSP lease mechanism to avoid pool corruption issue in case of pool pod restarts.**
**This PR also add pool create/import resync logic in case of create/import failure in previous event.**
**Description:**
Add lease mechanism on csp object which will ensure that
no two pool pods process the csp object concurrently which
can lead to pool corruption.
**Summary:**
1. Once a pool pod comes into existence it takes a lease on its corresponding CSP.
2. Lease is taken by putting some information on the CSP object annotation. This `some information` is nothing but the `pod name` who acquires the lease and `leader transition`. `Leader transition` value( numeric) will tell how many times different pods have acquired the CSP. 
3. Once lease has been take by a pool pod it does not …

feat(csp):put lease mechanism on csp object

---

cmd/maya-apiserver/app/command/start.go
cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
pkg/env/v1alpha1/env.go
pkg/usage/const.go
pkg/usage/ping.go
pkg/usage/ping_test.go
pkg/usage/size.go
pkg/usage/usage.go
pkg/usage/versionset.go

It is required to know about running openebs instances around the world and collect **periodic** anonymous information from clusters on user's consent.
improvement: https://github.com/openebs/openebs/issues/2257
[old]
_To test the things, I have set the time duration to every ONE MINUTE, this will be changed to every ONE DAY, after it is tested by Travis-CI and other instances at openebs.ci_
[current]
1. If a volume is provisioned without replica-count details and if a user consents on sharing usage data with us, the replica-count value on our analytics dashboard will show up as `3` on `volume-provision` event.
2. This won't happen on a `volume-deprovision` event because of …

[US3000][TA3959] feat(usage health) Send openebs periodic health events

---

cmd/maya-apiserver/spc-watcher/handler.go
cmd/maya-apiserver/spc-watcher/handler_test.go
cmd/maya-apiserver/spc-watcher/select_disk.go
cmd/maya-apiserver/spc-watcher/select_disk_test.go
cmd/maya-apiserver/spc-watcher/storagepool_create.go
cmd/maya-apiserver/spc-watcher/storagepool_create_test.go
pkg/apis/openebs.io/v1alpha1/cas_keys.go
pkg/apis/openebs.io/v1alpha1/cas_pool.go
pkg/apis/openebs.io/v1alpha1/cas_template_keys.go
pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
pkg/install/v1alpha1/cstor_pool.go
pkg/storagepool/storagepool.go

1. Iteration for pool creation will not happen at runtasks
rather cstor-operator will one by one create pools to converge
to maxPool count.
2. minPool field in SPC is deprecated. Providing minPool field in
SPC won't do any thing.
3. Reconciliation has been added to manual provisioned pool.

[US3990]refactor:(cstor-operator): refactor cstor operator

---

pkg/install/v1alpha1/cstor_volume.go

Currently, the default toleration time for cStor target deployment is 300s which can be reduced to 30s for faster provisioning in case of node taint scenarios.
**Which issue this PR fixes** https://github.com/openebs/openebs/issues/2318

enhance(cstor_volume): add toleration time of 30s in cstor target deployment

---

pkg/install/v1alpha1/cstor_volume.go

Volume list run task currently searches target pods and services in `openebs` namespace due to which the namespace name and other target details can be populated when the target is deployed in PVC namespace.
-> Fixes <no value> error in volume list response when cstor volume is provisioned in PVC namespace by removing the namespace iteration, as list action without namespace will fetch resources from all the available namespace in k8s.
**Which issue this PR fixes** : https://github.com/openebs/openebs/issues/2317
** Steps to verify** :
-> Provision cstor volume in pvc namespace. Refer here https://medium.com/@princerachit/87e1d37d5d64.
-> Run ``` mayactl volume list``` or do a curl to volume …

fix(cstor_volume): Missing namespace and target details in volume list response when cstor volume target is deployed in PVC namespace

---

cmd/mayactl/app/command/volumes_list.go
pkg/apis/openebs.io/v1alpha1/cas_volume.go
pkg/client/k8s/k8s.go
pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go
pkg/task/meta.go
pkg/task/task.go

This PR does the following things.
-> Enhances CAS Engine to list PersistentVolume which will helpful in listing information of persistent volumes using Runtask.
-> Adds Runtask to fetch storageclass and access mode information for cstor and jiva which will helpful for clients that depends on m-apiserver for information related to volumes.
-> Adds access mode and storageclass information in volume list API which can be consumed by clients like mayactl.
-> Adds StorageClass and access mode information in mayactl ```volume list``` command which will be useful for users.
-> Output of `mayactl volume list`:
```
Namespace  Name                                      Status   Type   Capacity  Storage Class         Access Mode
---------  ----                                      ------   ---- …
```

enhance(mayactl): add SC and access mode information in volume list

---

pkg/install/v1alpha1/openebs_crds.go

This commit will add custom column for openebs cstorvolume, cstorvolumereplica, disk, cstorpool
custom resources.
After adding this feature we can able to list down the required specific info like status, size etc using
`kubectl get` command
for example:
```sh
$ kubectl get csp -n openebs
NAME                     ALLOCATED   FREE    CAPACITY    STATUS    TYPE       AGE
sparse-claim-auto-lja7   125K        9.94G   9.94G       Healthy   striped    1h
$ kubectl get cvr -n openebs
NAME                                                              USED  ALLOCATED  STATUS    AGE
pvc-9ca83170-01e3-11e9-812f-54e1ad0c1ccc-sparse-claim-auto-lja7   6K    6K         Healthy   1h
$ kubectl get cstorvolume -n openebs
NAME …
```

feat(CRD): add custom column for openebs CRD's

---

cmd/cstor-volume-mgmt/volume/volume_test.go
pkg/apis/openebs.io/v1alpha1/cstor_volume.go

the response status parameter for cmd `istgtcontrol -q replica` has been changed from status-->mode, this commit will replace the status parameter with mode in ReplicaStatus struct

refact(volume-mgmt): replace replica status with mode

---

cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
pkg/usage/const.go
pkg/usage/usage.go

- This change sets the Default CASType to `jiva` when it isn't specified in the volume-create request.
improvement: https://github.com/openebs/openebs/issues/2257

ref(volume-event) Set default CASType to jiva

---

cmd/mayactl/app/command/volume_info.go
pkg/install/v1alpha1/cstor_sparse_pool_claim.go
pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go

These PR does the following things
-> This PR adds application pod name and application namespace details in volume read request. 
-> This PR adds application details in mayactl volume describe command. The details currently include the application name and application namespace as of now.
-> This PR also adds ReplicaCount field in `openebs-cstor-sparse` storage class to make it similar to `openebs-jiva-default`.
-> Output of openebs-cstor-sparse :
```
metadata:
annotations:
- name: StoragePoolClaim
value: "cstor-sparse-pool"
value: "3"
#- name: TargetResourceLimits
#- name: AuxResourceLimits
openebs.io/cas-type: cstor
creationTimestamp: "2019-01-11T12:40:54Z"
name: openebs-cstor-sparse …
```

enhance(mayactl): add application details in mayactl and improved sparse storage class

---

bettercodehub.yml

This PR adds `bettrecodehub.yml` which will avoid scanning scripts and other programming languages except go

enhance(bettercodehub): adds bettercode.yml

---

bettercodehub.yml

This PR changes the wildcard pattern for exclude in bettercodehub.yml as the previous one doesn't seem to work.

refactor(bettercodehub.yml): changed wildcard pattern and increased component depth

---

pkg/install/v1alpha1/cstor_pool.go
pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go

Ref: https://github.com/openebs/openebs/issues/2294
With 0.7.0, there was support for configuring resource
limits on the pool and volume pod side-cars using
AuxiliaryResourceLimits. With this PR, added the support
to specify AuxilaryResourceRequests.
This feature is useful in cases where user has to specify
minimum requests like ephemeral storage etc. to avoid
erroneous eviction by K8s as described in the above issue.
Also, some of the resource types are very version dependent
so keeping this as generic and not providing any defaults in
this PR.
In the future, it is possible that OpenEBS Operator could
automatically determine the version and set default values
on the generated default Storage Class. …

fix(policies): support for resource requests on side-cars

---

pkg/install/v1alpha1/cstor_pool.go

This PR will add liveness check for cstor-pool container.
There are scenarios where I/O can be hung and in that case we may need to restart the cstor-pool container.

feat(CAS_Template)add liveness for cstor pool

---

cmd/mayactl/app/command/volume_info.go
cmd/mayactl/app/command/volume_stats.go
cmd/mayactl/app/command/volume_stats_test.go
cmd/mayactl/app/command/volumes_list.go
pkg/apis/openebs.io/v1alpha1/cas_volume.go
pkg/client/k8s/k8s.go
pkg/install/v1alpha1/cstor_sparse_pool_claim.go
pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go
pkg/task/meta.go
pkg/task/task.go

This PR contains cherrypicks of bugfixes and enhancements of CASTemplates and mayactl from the master branch.

cherry pick from master

---

cmd/maya-apiserver/spc-watcher/select_disk.go
cmd/maya-apiserver/spc-watcher/select_disk_test.go

Use all usable disks attached on node for pool provisioning.
fixes https://github.com/openebs/openebs/issues/2346
Deails about this fix can be found at https://github.com/openebs/openebs/issues/2346

[US4131]fix(cstor_operator): add all disk on node for pool provisioning

---

pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go

This PR adds storage class annotation in OpenEBS provisioned volume components like target svc, deployments and replica deployments
The label name is `openebs.io/storage-class-ref`.
-> An example of service after this PR.
```
apiVersion: v1
kind: Service
metadata:
annotations:
openebs.io/storage-class-ref: |
name: openebs-jiva-default
resourceVersion: 564
creationTimestamp: "2019-01-16T11:45:15Z"
labels:
openebs.io/cas-template-name: jiva-volume-create-default-0.8.0
openebs.io/controller-service: jiva-controller-svc
openebs.io/persistent-volume: pvc-3003f407-1984-11e9-b1bb-b4b686bd0cff
openebs.io/persistent-volume-claim: jiva-pvc
openebs.io/storage-engine-type: jiva
openebs.io/version: 0.8.0
pvc: jiva-pvc …
```

feat(provision): adds SC annotation to openebs volume components

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler_test.go
cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica_test.go
pkg/apis/openebs.io/v1alpha1/cstor_volume_replica.go

When cstor pool is **re-created** on the node (_e.g. node reboots with blank data as disks were ephemeral_), then the volumes need to be re-created by setting the **quorum** to _false_. 
_NOTE: Based on the quorum value, cstor target will decide whether the replica is considered for quorum decision._
This feature is hereby known as **ephemeral support**. This is implemented by setting the **quorum** property to _false_, for the volumes which are created on the nodes that are replacing existing nodes.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/openebs/issues/2358

feat(pool-mgmt): Add ephemeral support in cstor-pool-mgmt

---

cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go
cmd/maya-apiserver/spc-watcher/handler.go
cmd/maya-apiserver/spc-watcher/handler_test.go
cmd/maya-apiserver/spc-watcher/select_disk.go
cmd/maya-apiserver/spc-watcher/select_disk_test.go
cmd/maya-apiserver/spc-watcher/storagepool_create.go
cmd/maya-apiserver/spc-watcher/storagepool_create_test.go
pkg/apis/openebs.io/v1alpha1/cas_keys.go
pkg/apis/openebs.io/v1alpha1/cas_pool.go
pkg/apis/openebs.io/v1alpha1/cas_template_keys.go
pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
pkg/install/v1alpha1/cstor_pool.go
pkg/storagepool/storagepool.go

Following PR has been cherry picked:
1. https://github.com/openebs/maya/pull/871
2. https://github.com/openebs/maya/pull/867
3. https://github.com/openebs/maya/pull/884
4. https://github.com/openebs/maya/pull/894

chore(cherrypicks) : Move master fixes for cstor-operator from master to 0.8.1

---

pkg/install/v1alpha1/cstor_pool.go
pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go

Ref: https://github.com/openebs/openebs/issues/2294
With 0.7.0, there was support for configuring resource
limits on the pool and volume pod side-cars using
AuxilaryResourceLimits. With this PR, added the support
to specify AuxilaryResourceRequests.
This feature is useful in cases where user has to specify
minimum requests like ephemeral storage etc. to avoid
erroneous eviction by K8s as described in the above issue.
Also, some of the resource types are very version dependent
so keeping this as generic and not providing any defaults in
this PR.
In the future, it is possible that OpenEBS Operator could
automatically determine the version and set default values
on the generated default Storage Class.
(cherry picked from commit …

fix(policies): support for resource requests on side-cars (#889)

---

pkg/install/v1alpha1/cstor_volume.go
pkg/template/template.go
pkg/template/template_test.go

Signed-off-by: Vishnu Itta <vitta@mayadata.io>
This is cherry-pick of https://github.com/openebs/maya/pull/895 - to distribute volume provisioning randomly on the pools related to storage class

feat(vol_provision): distribute cvrs randomly on its pools (#895)

---

pkg/install/v1alpha1/cstor_volume.go

This commit adds TargetNodeSelector policy to cstor volumes which will be helpful for scheduling cstor target on a particular node. This property can be achieved by providing the node selector name as the CAS config in storage class. Example of the cas config:
- name: TargetNodeSelector
value: |-
node: appnode
You can more information here: https://docs.openebs.io/docs/next/storagepolicies.html
-> This is the cherry-pick of master PR #912

feature(cstor_volume): adds target node selector policy (#912)

---

cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go

(Q) Why is this required?
(A) The CASType isn't always specified in the volume-create request from
openebs-provisioner, also default CASType isn't `jiva`, it is what
has been specified in the storageClass used.
Earlier `jiva` was treated as the assumed default CASType.
(Q) What's changed?
(A) The volume-events' responses sent to openebs-provisioner is now
instrumented instead of the requests recieved by m-apiserver pod.
improvement: https://github.com/openebs/openebs/issues/2257

fix(vol-event) Instrument the responses of m-apiserver

---

buildscripts/build.sh

This commit changes the
BUILDMETA to `released` based on the TRAVIS_TAG to automate the release
process.
The BUILDMETA file is changed to `released` if TRAVIS_TAG doesnot contain
`RC` and is not empty.

fix(BUILDMETA): update BUILDMETA based on TRAVIS_TAG

---

pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go

This commit changes the target and replica deployment strategy to `Recreate`
as `Rolling Update` can make and the update stuck or can cause problem in
replica sync as all replicas should be at the same version during sync.

refactor(CAST): Changes jiva and cstor deployment strategy to `Recreate`

---

pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go

This commit adds:
1/ Target and Replica Toleration policies to jiva and 
2/ Target Toleration policy to cstor volumes
Above policies can be used in storageclass.
Example of **jiva** storage class for using the above policies:
```yaml
metadata:
name: openebs-jiva-default
annotations:
value: "1"
- name: StoragePool
value: default
- name: TargetTolerations
value: |
t1:
key: "key1"
operator: "Equal"
value: "value1"
effect: "NoSchedule"
t2:
key: "key1"
operator: "Equal"
value: "value1"
effect: "NoExecute"
- name: ReplicaTolerations
value: |
t1:
key: "key1"
operator: "Equal"
value: "value1"
effect: "NoSchedule"
t2:
key: …
```

enhance(CAST): Adds Target and Replica Toleration policies

---

pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go

This commit adds:
1. Target and Replica Toleration policies to jiva and 
2. Target Toleration policy to cstor volumes 
Above policies can be used in storageclass.
Example of **jiva** storage class for using the above policies:
```yaml
metadata:
name: openebs-jiva-default
annotations:
value: "1"
- name: StoragePool
value: default
- name: TargetTolerations
value: |
t1:
key: "key1"
operator: "Equal"
value: "value1"
effect: "NoSchedule"
t2:
key: "key1"
operator: "Equal"
value: "value1"
effect: "NoExecute"
- name: ReplicaTolerations
value: |
t1:
key: "key1"
operator: "Equal"
value: "value1"
effect: "NoSchedule"
t2: …
```

enhance(CAST): Adds support for Target and Replica Toleration

---

pkg/apis/openebs.io/v1alpha1/cstor_volume.go

This PR adds the InQuorum field in ReplicaStatus.
To display InQuorum value of ZFS volume replica by executing `kubectl describe cstorvolume -n openebs`
```
Status:
Phase:  Healthy
Replica Statuses:
Checkpointed IO Seq:  0
In Quorum:            1
Inflight Read:        0
Inflight Sync:        0
Inflight Write:       0
Mode:                 Healthy
Replica Id:           12977937036059533468
Up Time:              533
Events:
Type    Reason   Age                   From                                                                        Message
----    ------   ----                  ----                                                                        -------
Normal  Healthy  8m51s …
```

Adds InQuorum field in describe ouput of cstorvolumes

---

pkg/install/v1alpha1/jiva_volume.go

This commit removes the hardcoding of jiva volume delete scrub job image in RunTask which will allow users to override the image name from storage-class. The image can be overridden by explicitly providing the values in `cas.openebs.io/config` in annotations of jiva storage-class.
If no image is provided then `quay.io/openebs/openebs-tools:3.8` will be taken as the default image.
Example of storageclass to achieve this:
```
---
metadata:
name: jiva-scrub-image
annotations:
- name: ScrubImage
value: ashishranjan738/openebs-tools:latest
provisioner: openebs.io/provisioner-iscsi
---
```
**Which issue this PR fixes** : …

enhance(Runtask): Remove hardcoding of jiva delete scrub image

---

pkg/hash/v1alpha1/hash.go
pkg/hash/v1alpha1/hash_test.go

This PR implements a package to calculate the hash for the given object.
Decision maker for day2 operations.
**Usage:**
```
---
metadata:
name: mirroredexternalspc
annotations:
- name: CstorPoolImage
value: openebs/cstor-pool:ci
- name: CstorPoolMgmtImage
value: openebs/cstor-pool-mgmt:ci
spec:
name: mirroredexternalspc
type: disk
maxPools: 3
poolSpec:
poolType: mirrored
disks:
diskList:
- disk-2bfe6b64844a2fa6029264222bee9857
- disk-6a6bc74e0c4036c12bc6acfc2835f103
- disk-a85acac653297ff19e58d88a5507b7d8
- disk-b1396f8f4834a4a5bdbb8d74c858b709
- disk-cc545c5217d6b5f68454aea48c8cb1ba
- disk-e1ace2ff1ad8e492d195b7dbb1e10b99
```
We can pass anything from the above …

Implements a packge to calculate hash for given objects

---

cmd/cstor-volume-mgmt/volume/volume_test.go
pkg/apis/openebs.io/v1alpha1/cstor_volume.go

the response status parameter for cmd `istgtcontrol -q replica` has been changed from status-->mode, this commit will replace the status parameter with mode in ReplicaStatus struct
**Special notes for your reviewer**: Cherry-pic #878

refact(volume-mgmt): replace replica status with mode (cherry-pic #878)

---

cmd/maya-exporter/app/collector/collector.go
cmd/maya-exporter/app/collector/cstor.go
cmd/maya-exporter/app/collector/cstor_test.go
cmd/maya-exporter/app/collector/jiva.go
cmd/maya-exporter/app/collector/metrics.go
cmd/maya-exporter/app/collector/types.go
cmd/maya-exporter/app/command/server.go

Recently we have observed that if multiple requests are coming
concurrently, other request's are queued for longer duration since
there is one connection with istgt.
fixes:
1. Allow only one connection for each request.
2. Observed panic during chaos testing in str comparison, where it was
trying to access the index which is not read.
3. Added missing "WO" status for jiva.

[TA4936] fix(exporter): allow one connection per request with istgt

---

cmd/maya-exporter/app/collector/jiva.go

Due to recent PR #944 , we have added logs for the errors, which
was logging following error because "TotalReadBytes" and
"TotalWriteBytes" is not there in jiva and hence returning "" which
is not parseable.
```
E0220 10:44:56.158188   17778 metrics.go:274] failed to parse, err: strconv.ParseFloat: parsing "": invalid syntax
```

fix(exporter): remove unused metrics for jiva

---

pkg/install/v1alpha1/cstor_volume.go

- This commit fixes applications details which are not available when application and its volume target is not present in the same namespace
- It adds new label and a new annotation to `cstor target service` to store the PersistentVolumeClaim name and namespace
- This is later used to get application details
- Since this involves the addition of new labels to the service, the volumes provisioned with previous versions cannot avail this feature unless they are upgraded.
Labels that got added: _(needs to be part of volume upgrade)_
`openebs.io/persistent-volume-claim:<pvc name>`
Annotation that got added: _(needs to be part of volume upgrade)_
`openebs.io/pvc-namespace:<pvc-namespace>`
fixes: …

fix(mayactl): fixes application name & namespace not available during a volume describe

---

pkg/algorithm/cstorpoolselect/v1alpha1/select.go
pkg/algorithm/cstorpoolselect/v1alpha1/select_test.go
pkg/cstorpool/v1alpha2/cstorpool.go
pkg/cstorpool/v1alpha2/cstorpool_test.go
pkg/cstorpool/v1alpha2/doc.go
pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica.go
pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica_test.go
pkg/cstorvolumereplica/v1alpha1/kubernetes.go
pkg/cstorvolumereplica/v1alpha1/kubernetes_test.go
pkg/install/v1alpha1/cstor_volume.go
pkg/template/template.go

Users want to deploy applications using StatefulSet with application replication factor **"> 1"** and volume replication factor **"= 1"**; provided this application has the ability to replicate data across nodes in a given cluster. Some examples of such applications are _Cassandra_, _ElastiSearch_, _MongoDB_, etc. In other words, each instance of this kind of application(s) consume one volume and from the application p.o.v all these per-instance volumes should spread out across nodes to ensure High Availability of the application.
This commit adds the ability in cstor to correlate & hence distribute single replica volumes across pools _(which are in turn deployed in separate nodes)_ when application consuming all these volumes is …

feat(volume distribution, cstor replica, pool anti-affinity): adds support to distribute data across cstor storagepools

---

cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
pkg/install/v1alpha1/cstor_volume.go

This commit removes the finalizers from a cstor volume replica object. This ensures removal of cstor volume replica object from kubernetes. In addition, it will try to delete the underlying volume if cvr controller gets the delete event. With the removal of finalizer there is no more retry mechanism to
actually delete the underlying volume if there were issues encountered during earlier deletes.
CstorVolumeReplica aliased CVR has finalizers that prohibits deletion unless the volume gets deleted. This is a check to ensure proper cleanup even if delete events are missed & / or underlying volume was not deleted in earlier attempts.
There were observations that point to the fact that when the namespace (that contains these volumes) as well when the operator (that contains the CRD schema …

fix(cvr delete, finalizer): remove finalizers to ensure successful deletion

---

.gitlab-ci.yml

- Check for master and .x branches for build to trigger by using only:
refs option.
- Use the new CI_COMMIT_SHORT_SHA env to get the short commit SHA.
- Push the commit details to respective branches on e2e-infrastructure.
- Pass the branch details of MAYA to the platform repos to checkout
e2e-infrastructure for that particular branch when the infra-setup stage
is run.
- Deprecate GKE, EKS and AKS platforms.
- Run Packet platform, with k8s 1.11, 1.12 and 1.13 for master branch.
**Checklist:**

Enhancements and changes to GitLab CI YAML.

---

pkg/webhook/webhook.go

This fixes a bug where deleting a namespace, that doesn't have any PVC resource can trigger this validating webhook. This nil PVC resulted into a runtime error thus invalidating the validation. As a result of this invalidation, the validation is being retried that and ends up being in the same state forever.
Request name as nil will be ignored by the webhook validation policy. In other words webhook will validate this request successfully.
fixes: openebs/openebs/issues/2431
**Checklist:**

fix(webhook): ignore delete request for missing resource req name

---

pkg/client/k8s/k8s.go
pkg/task/identity.go
pkg/task/meta.go
pkg/task/task.go

This PR will introduce the following supports in runtask -
1. Patch operation for services.
2. Get operation for deployment(extensions/v1beta1).
3. Delete operation for replicaset(extensions/v1beta1).
4. Patch operation for CStor volumes.
5. Patch operation for CStor volume replicas(cvr).
**Checklist:**

enhance(cast engine): Add more support for operations in runtask

---

cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
pkg/apis/openebs.io/v1alpha1/cstor_volume_replica.go
pkg/install/v1alpha1/cstor_volume.go

This commit adds `ZvolWorkers`, `QueueDepth` and  `Luworkers` cstor volume config as CAS configuration. This can be set at StorageClass.
- `QueueDepth`: sets the **queue size at iSCSI target** which limits the ongoing IO count from client. 
- Defaults to 32
- `Luworkers`: sets the **number of threads** that are working on above queue
- Defaults to 6
- `ZvolWorkers`: sets **thread count at pool pod** that work on IOs received from iSCSI target of a particular volume
- Is associated with cstor volume replica
- Defaults to the number of cores on the machine
**Note:** _Default values will be used  in case of **invalid/None** values has been provided using config 
refer PR openebs/istgt/pull/237 and  openebs/istgt/pull/234 for more details._
- These …

feat(casconfig, perf, cstor): introduce ZvolWorkers, QueueDepth & Luworkers cstor volume config

---

cmd/maya-exporter/app/collector/cstor_test.go
cmd/maya-exporter/app/collector/metrics.go
cmd/maya-exporter/app/collector/types.go

- How does it impact end users?
The value of following time series will show 0:
`openebs_healthy_replica_count`
`openebs_degraded_replica_count`
- Where is the following observed?
This can be obeserved anywhere with `0.8.1` release
- Which output is the PR referring to?
Output of maya-exporter from `/metrics` endpoint
Ref: https://github.com/openebs/istgt/pull/211/files
**Checklist:**
Thanks to @kmova for reporting it.

fix(exporter): use camel case for replica status

---

pkg/install/v1alpha1/cstor_pool.go

Add pool exporter yaml in existing cstor-pool-create-putcstorpooldeployment-default
runTask. Pool exporter will be used as sidecar.
**Additional Info for Reviewer**:
Following env should be added into `openebs-operator.yaml` which will be used by m-apiserver for deployment purpose.
```
- name: OPENEBS_IO_CSTOR_POOL_EXPORTER_IMAGE                                                                                                               
value: "utkarshmani1997/m-exporter:pool-exporter7"
```
Helm chart need to be updated accordingly.
**Checklist:**

[TA5006] feat(exporter): add pool exporter yaml in runTask

---

pkg/client/k8s/k8s.go
pkg/k8s/from_yaml.go
pkg/task/identity.go
pkg/task/meta.go
pkg/task/task.go

This commit adds support to create and delete a kubernetes `StatefulSet` object via `CASTemplate`.
- Kubernetes api version supported for StatefulSet is "apps/v1"
- This support enables maya to provision volumes as StatefulSet as well.
_NOTE: Till now cstor & jiva volumes make use of kubernetes Deployment as a resource to provision volumes_
**Checklist:**

feat(cast, statefulset): add support for statefulset in castemplate

---

pkg/algorithm/cstorpoolselect/v1alpha1/select.go
pkg/algorithm/cstorpoolselect/v1alpha1/select_test.go
pkg/cstorpool/v1alpha2/cstorpool.go
pkg/cstorpool/v1alpha2/cstorpool_test.go
pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica.go
pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica_test.go
pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go
pkg/template/template.go

**Why we need it**:
Users want to deploy applications using StatefulSet with application replication factor "> 1" and volume replication factor "= 1", provided that the OpenEBS volumes' target and replica related resources have an affinity with the application. This means that, for a given OpenEBS volume, Target and replica related to that volume should be scheduled on the same node where the application resides.
This commit adds support for cstor target and replica affinity to an instance of StatefulSet application.
This feature can be enabled by using either of the following approach:
_NOTE: This approach requires change to StatefulSet spec_
- Add **`openebs.io/sts-target-affinity: <.metadata.name of STS>`** …

feat(cstor volume, sts): add cstor volume provisioning support in StatefulSet applications

---

GNUmakefile
buildscripts/exporter/Dockerfile
cmd/cstor-pool-mgmt/controller/common/common_test.go
cmd/cstor-pool-mgmt/controller/replica-controller/run_replica_controller_test.go
cmd/cstor-pool-mgmt/pool/pool_test.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica_test.go
cmd/maya-exporter/app/collector/cstor_test.go
cmd/maya-exporter/app/collector/metrics.go
cmd/maya-exporter/app/collector/pool/metrics.go
cmd/maya-exporter/app/collector/pool/pool.go
cmd/maya-exporter/app/collector/pool/pool_test.go
cmd/maya-exporter/app/collector/types.go
cmd/maya-exporter/app/collector/zvol/list.go
cmd/maya-exporter/app/collector/zvol/list_test.go
cmd/maya-exporter/app/collector/zvol/metrics.go
cmd/maya-exporter/app/collector/zvol/zvol.go
cmd/maya-exporter/app/collector/zvol/zvol_test.go
cmd/maya-exporter/app/command/command.go
cmd/maya-exporter/app/command/command_test.go
cmd/maya-exporter/main.go
pkg/install/v1alpha1/cstor_pool.go
pkg/util/exec-run.go
pkg/version/version.go
pkg/zpool/v1alpha1/zpool.go
pkg/zvol/v1alpha1/zvol.go

- Cherry-pick commits which introduce a new feature (pool-exporter) 
- Cherry-pick  commit which fixes a bug which was setting values of exporter's time series `openebs_healthy_replica_count` and `openebs_degraded_replica_count` to 0
**Checklist:**

Cherry pick pool exporter

---

cmd/maya-exporter/app/collector/pool/pool_test.go
cmd/maya-exporter/app/collector/zvol/list_test.go

This PR fixes flaky ci by increasing the goroutine count.
100 concurrent requests were being served in 1 second successfully while unit testing sometimes that's why it was failing.
**Checklist:**

fix(ci): increase goroutine count to fix ci

---

cmd/maya-exporter/app/collector/pool/pool_test.go
cmd/maya-exporter/app/collector/zvol/list_test.go

This PR fixes the flaky unit test of exporter by increasing the goroutine count.
100 concurrent requests were being served in 1 second successfully while unit testing sometimes that's why it was failing.
**Checklist:**

fix(exporter): increase goroutine count to fix ci

---

cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
pkg/install/v1alpha1/cstor_volume.go

Commit refactor the cstor tunnables env wrt to update
1. No env will be passed to target deployment if case there
is no cas-config tunnables present in SC
2. Use default zfs create command if zvolworkers cas-config
not present in SC
**Checklist:**

Refact(cas,runtask): refactor cstor tunnables ENV parameters

---

buildscripts/travis-build.sh

This commit adds `dep check` in Travis which will be helpful for
catching PRs responsible for breaking vendor dependencies.
-> After this PR the Travis will start failing for PRs whose vendor dependencies are not satisfied by `dep`.
**Checklist:**

enhance(travis): Adds `dep check` in travis

---

cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
pkg/install/v1alpha1/cstor_volume.go

1. No env will be passed to target deployment if case there
is no cas-config tunnables present in SC
2. Use default zfs create command if zvolworkers cas-config
not present in SC.
Cherry-pick: #993 

refact(cas,runtask): refactor cstor tunables ENV parameters (#993)

---

pkg/install/v1alpha1/cstor_volume.go

fix(mayactl): fixes application name & namespace not available during a volume describe
- This commit fixes applications details which are not available when application and its volume target is not present in the same namespace
- It adds new label and a new annotation to `cstor target service` to store the PersistentVolumeClaim name and namespace
- This is later used to get application details
- Since this involves the addition of new labels to the service, the volumes provisioned with previous versions cannot avail this feature unless they are upgraded.
Labels that got added: _(needs to be part of volume upgrade)_
`openebs.io/persistent-volume-claim:<pvc name>`
Annotation that got added: _(needs to be part of volume upgrade)_
`openebs.io/pvc-namespace:<pvc-namespace>`
fixes: …

chore(cherrypick,mayactl): fixes application name not available (#953)

---

pkg/install/v1alpha1/cstor_pool.go

This commit removes hardcoding hostPath in cstor pool pod deployments.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/openebs/issues/2456
**Checklist:**

fix(cstorpool): removes hard coding in hostpath of /tmp

---

pkg/install/v1alpha1/cstor_pool.go

This commit removes hardcoding hostPath in cstor pool pod deployments.
**Checklist:**

chore(cstor pool): cherry-pick of PR 1014

---

pkg/install/v1alpha1/cstor_volume.go

This commit removes hardcoding in host path for cstor target pod. Users can override the existing host path introducing a `OPENEBS_IO_CSTOR_TARGET_DIR` env in maya-apiserver deployment. Example of maya-apiserver deployment: 
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
name: maya-apiserver
spec:
replicas: 1
template:
metadata:
labels:
name: maya-apiserver
openebs.io/component-name: maya-apiserver
spec:
containers:
- name: maya-apiserver
imagePullPolicy: IfNotPresent
image: quay.io/openebs/m-apiserver:ci
ports:
- containerPort: 5656
env:
#- name: OPENEBS_IO_KUBE_CONFIG
#- name: OPENEBS_IO_K8S_MASTER
- name: …
```

fix(cstor volume): add hostpath config for target pod

---

pkg/install/v1alpha1/cstor_volume.go

Signed-off-by: Ashish Ranjan ashish.ranjan@mayadata.io
This commit removes hardcoding in host path for cstor target pod. Users can override the existing host path introducing **OPENEBS_IO_CSTOR_TARGET_DIR** env in maya-apiserver deployment. 
Sample maya-apiserver deployment:
```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
name: maya-apiserver
spec:
replicas: 1
template:
metadata:
labels:
name: maya-apiserver
openebs.io/component-name: maya-apiserver
spec:
containers:
- name: maya-apiserver
imagePullPolicy: IfNotPresent
image: quay.io/openebs/m-apiserver:ci
ports:
- containerPort: 5656
env:
#- name: OPENEBS_IO_KUBE_CONFIG
#- name: OPENEBS_IO_K8S_MASTER
- name: OPENEBS_IO_INSTALL_DEFAULT_CSTOR_SPARSE_POOL
value: "true" …
```

chore(cstor volume, cherry-pick): add config for target volume directory (#1018)

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go
pkg/install/v1alpha1/cstor_pool.go

This PR deletes the unix.sock file (_which is shared between the cstor-pool-mgmgt and cstor-pool_). This is deleted during cstor-pool container deletion phase via a preStop hook.
(https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/)
In other words, before triggering `kill` of cstor-pool container, kubernetes will execute this preStop hook.
This fix avoids `RPC` between cstor-pool-mgmt container of a new pod and cstor-pool container of the terminating pod i.e. old pod.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #https://github.com/openebs/openebs/issues/2447
Per …

fix(cstor-pool, sock): delete sock file before deleting for cstor-pool container

---

pkg/install/v1alpha1/cstor_pool.go

Cherry-pick commit from PR #1023 
This PR fixes the issue arising due to the change in `openebs.io/storage-pool-claim: {{.Storagepool.owner}}` label, which was moved into annotation from labels.
**Checklist:**

cherry-pick(cstor_pool_runtask): mv spc from annotation to labels

---

pkg/install/v1alpha1/cstor_pool.go

Cut the label ` openebs.io/storage-pool-claim: {{.Storagepool.owner}}` from annotation and move it to
labels.
This PR fix the issue arising due to change in the label, which was moved into annotation field in the PR: https://github.com/openebs/maya/pull/960/
**Checklist:**

fix(cstor_pool_runtask): mv spc from annotation to labels

---

cmd/mayactl/app/command/volume_info.go
pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go

This commit removes application information from mayactl volume describe command and api server read response.
The commits that gets reverted after this PR:
https://github.com/openebs/maya/commit/cec89577a2492a0929b0cfd2588e126ab333003c
https://github.com/openebs/maya/commit/8321b6f9b5f3dd088f1f2c75c9f43629e50b39bd
https://github.com/openebs/maya/commit/0e9ae16f5ab0dd53da270f5bef6d9bb0864d4340
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/maya/issues/1028
**Checklist:**

chore(cherry-pick,mayactl,runtask): Removes application information from mayactl

---

cmd/mayactl/app/command/volume_stats.go
cmd/mayactl/app/command/volume_stats_test.go

This commit removes volume and iqn information from mayactl volume stats command as these information is not comming anymore from volume exporter.
Output after this :
```
---------------
Volume  :   pvc-beae53f3-5222-11e9-9f6d-b4b686bd0cff
Size    :   4.000000
Performance Stats :
--------------------
r/s      w/s      r(MB/s)      w(MB/s)      rLat(ms)      wLat(ms)
----     ----     --------     --------     ---------     ---------
0        0        0.000        0.000        0.000         0.000    
Capacity Stats :
---------------
LOGICAL(GB)      USED(GB)
------------     ---------
0.000            0.000    
```
**Checklist:**

fix(mayactl): remove portal and iqn from volume stats

---

pkg/install/v1alpha1/cstor_pool.go

This PR deletes the preStop hook which is used to delete the unix.sock file (which is shared between the cstor-pool-mgmgt and cstor-pool) as soon as cstor-pool container deleted.
**Checklist:**

revert(cstor-pool, sock deletion): remove preStop hook used to delete sock file

---

pkg/client/k8s/k8s.go
pkg/kubernetes/replicaset/v1alpha1/kubernetes.go
pkg/task/meta.go
pkg/task/task.go

This PR add support for get list and delete of replicaset. Runtask related to these tasks given below -
1. get replicaset
```yaml
kind: RunTask
metadata:
name: task-getrs
namespace: default
spec:
meta: |
id: getrs
apiVersion: extensions/v1beta1
kind: ReplicaSet
action: get
runNamespace: openebs
objectName: cstor-sparse-pool-9gjf-76969fbfc9
post: |
{{- jsonpath .JsonResult "{.metadata.name}" | trim | saveAs "rs" .TaskResult | noop -}}
```
2. list replicaset
```yaml
kind: RunTask
metadata:
name: task-listrs
namespace: default
spec:
meta: |
id: listrs
apiVersion: extensions/v1beta1
kind: ReplicaSet
action: list
runNamespace: openebs
options: |-
labelSelector: app=cstor-pool,openebs.io/storage-pool-claim=cstor-sparse-pool
post: | …
```

enhance(cast engine): add replicaset get list delete actions

---

cmd/maya-apiserver/app/config/config.go

This PR will enable graceful shutdown for maya-apiserver using `SIGTERM`
Among other things, this commit helps to generate coverage reports. Maya API server binary needs to be compiled with `Testing` flags on. One can then launch a Kubernetes pod with this apiserver.test binary. Run the BDD test cases and get the coverage report. Now for this coverage report to get generated, apiserver need to exit gracefully.
Command to do a graceful shutdown:
```bash
ps -aux
kill -15 <pid>
```

chore(maya): enable graceful shutdown of apiserver

---

cmd/mayactl/app/command/volume_info.go
pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go

This commit removes application information from mayactl volume describe command and api server read response. 
This was done as errors were observed when the application had more than one volumes. This will be taken up with a better design.
**Checklist:**

revert(mayactl, runtask): remove application information from mayactl and runtask

---

pkg/castemplate/v1alpha1/kubernetes.go
pkg/castemplate/v1alpha1/kubernetes_test.go

This PR adds support for castemplate get operation.

refact(cast engine): add get castemplate support

---

cmd/maya-exporter/app/collector/cstor_test.go
cmd/maya-exporter/app/collector/metrics.go
cmd/maya-exporter/app/collector/types.go

* fix(exporter): use camel case for replica status
The value of following time series will show 0:
- openebs_healthy_replica_count
- openebs_degraded_replica_count
This can be obeserved anywhere with 0.8.1 release
Output of maya-exporter from /metrics endpoint
Refer - https://github.com/openebs/istgt/pull/211/files
Special Instruction for the reviewer:
- Added new mode "ERR" in switch case statement, which was missing earlier for jiva volumes.
**Checklist:**

fix(exporter, cherrypick): use camel case for replica status (#959)

---

pkg/kubernetes/patch/v1alpha1/patch.go
pkg/kubernetes/patch/v1alpha1/patch_test.go
pkg/task/meta.go
pkg/task/task.go
pkg/upgrade/result/v1alpha1/kubernetes.go
pkg/upgrade/result/v1alpha1/kubernetes_test.go
pkg/upgrade/result/v1alpha1/upgraderesult.go
pkg/upgrade/result/v1alpha1/upgraderesult_test.go

This PR adds a package for **patch** at pkg/kubernetes/patch/v1alpha1 which contains the basic builder functions to be called to patch a CR using runtask.
It will also add **patch** and **create** support for upgrade result cr in runtask.
**Checklist:**

feat(patch, upgrade-result): add patch and create support for upgrade result custom resource

---

.golangci.yml

This will help `openebs/maya` maintainers to keep a tab on various linting issues, via this config file. Each github PR can report any new issues.
NOTE: _Individual developers can setup golangci individually at their IDEs to learn more on the issues reported by GolangCI._
**Checklist:**

chore(golangci, lint): add golangci lint aggregator

---

pkg/install/v1alpha1/cstor_pool.go

Signed-off-by: mittachaitu <mittachaitu@gmail.com>
This PR fixes storagepool runtask to point ownerreference to corresponding csp. 
Below note is from kubernetes docs:
```
Note: Cross-namespace owner references is disallowed by design. This means: 1) Namespace-scoped dependents can only specify owners in the same namespace, and owners that are cluster-scoped. 2) Cluster-scoped dependents can only specify cluster-scoped owners, but not namespace-scoped owners.
```
https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #https://github.com/openebs/openebs/issues/2527
**Special notes for your …

fix(runtask): fix storagepool runtask to have ownerreference to csp

---

pkg/install/v1alpha1/cstor_pool.go

This PR fixes storagepool runtask to point ownerreference to corresponding CSP.
StoragePool related resources have owner references in following order:
- _SPC - owns -> CSP - owns -> Pool Deployment - owns -> SP_
This when understood further:
- SP _(which is a clustered-scope resource)_ has owner reference of Pool Deployments _(namespace-scoped resource)_. 
- This is wrong as per `Kubernetes Garbage Collector` and can subsequently lead to various problems.
- If user deletes pool deployment then corresponding SP will be deleted as per kubernetes GC 
- If SP is deleted nothing happens but disks are released. 
- So next time an auto provisioned SPC can use these released disks leading to different issues.
- Updates owner reference of …

Cherry-pick (fix, runtask): fix storagepool runtask to have ownerreference to csp (#1078)

---

pkg/kubernetes/objectmeta/v1alpha1/objectmeta.go
pkg/kubernetes/objectmeta/v1alpha1/objectmeta_test.go
pkg/kubernetes/ownerreference/v1alpha1/ownerreference.go
pkg/kubernetes/ownerreference/v1alpha1/ownerreference_test.go
pkg/kubernetes/typemeta/v1alpha1/typemeta.go
pkg/kubernetes/typemeta/v1alpha1/typemeta_test.go
pkg/upgrade/result/v1alpha1/upgraderesult.go
pkg/upgrade/result/v1alpha1/upgraderesult_test.go

This PR add supports to build **ObjectMeta**, **TypeMeta**, **OwnerReference** and **UpgradeResult** in idiomatic maya style.

feat(upgrade): add support to build upgrade result cr.

---

pkg/apis/stringer/v1alpha1/stringer.go
pkg/apis/stringer/v1alpha1/stringer_test.go

Most of the API structures in maya override `String()` & `GoString()` methods of Stringer & GoStringer interfaces. This is done to print details of the the structure while logging errors.
`String()` & `GoString()` make use of `Yaml()` to _pretty-print_ the entire instance.
However, in-case of any error during _un-marshaling_ to yaml, this instance is provided as-is to `fmt.Sprintf` as a fallback approach. However, this leads to invocation of `String()` once again since instance is an implementation of String() &/or GoString(). This results into a never ending loop causing a panic.
This commit solves above panic.

fix(stringer, debuggability): remove cyclic calls in stringer package

---

cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
cmd/maya-apiserver/cstor-operator/spc_lease.go

- fixed ineffectual assignment of `cmd` variable in `volumereplica`
- fixed ineffectual assignment of `err` variable in `spc_lease`
**Checklist:**

fix(lint): fix ineffectual assignment issues in cmd

---

cmd/maya-exporter/app/collector/pool/metrics.go
cmd/maya-exporter/app/collector/pool/pool.go

- removed unused param `ch` from `metrics` and `pool`
**Checklist:**

fix(lint):fix unused func param and result in cmd

---

pkg/lease/v1alpha1/csp_lease.go
pkg/lease/v1alpha1/csp_lease_test.go
pkg/template/template.go

- fixed ineffectual assignment of `err` variable in `csp_lease`
- fixed ineffectual assignment of `err` variable in `csp_lease_lest`
- fixed ineffectual assignment of `fields` in `template`
**Checklist:**

fix(lint): fix ineffectual assignment issues in pkg

---

pkg/install/v1alpha1/cstor_pool.go

This allow pool-exporter to be run in previleged mode, it is needed since other two containers `cstor-pool` and `cstor-pool-mgmt` runs in previleged mode and uses socket path for the communication, so on some clusters which add extra layer of security such as openshift, pool-exporter was failed to establish connection with the `cstor-pool` due to permission issue.
**Checklist:**

feat(pool-exporter): run pool-exporter in previleged mode

---

pkg/install/v1alpha1/cstor_volume.go

This commit fixes the issue of cstor target pod getting stuck at pending state when `sts-target-affinity` label is used due to the missing namespace in the podAffinity spec of the target deployment.
-> Since the cstor target and the application pods are deployed in the different namespace, the application's namespace need to be explicitly passed to the podAffinity spec of the target.
**Checklist:**

fix(sts,vol-mgmt): fix target pod stuck at pending state

---

cmd/maya-exporter/app/collector/pool/pool_test.go
pkg/install/v1alpha1/cstor_pool.go

add pool exporter yaml in runTask
run pool-exporter in previleged mode (#1113 )
**Checklist:**

Cherry-pick(exporter): add pool exporter yaml in runTask

---

.travis.yml

```sh
sudo minikube start --vm-driver=none --kubernetes-version=v1.13.0
o   minikube v0.35.0 on linux (amd64)
>   Configuring local host environment ...
!   The 'none' driver provides limited isolation and may reduce system security and reliability.
!   For more information, see:
-   https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md
>   Creating none VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
-   "minikube" IP address is 10.20.3.20
-   Configuring Docker as the container runtime ...
-   Preparing Kubernetes environment ...
@   Downloading kubeadm v1.13.0
@   Downloading kubelet v1.13.0
-   Pulling images required by Kubernetes v1.13.0 ...
-   Launching Kubernetes …
```

enhance(travis): update kubernetes version to 1.13 in travis

---

pkg/kubernetes/storageclass/v1alpha1/build.go
pkg/kubernetes/storageclass/v1alpha1/build_test.go

Add `WithVolumeBindingMode` as a build option to set specific volume binding mode against a SC.
**Checklist:**

enhance(sc, idiomatic): add volumebinding mode in storageclass

---

pkg/apis/openebs.io/v1beta1/storage_pool_claim.go
pkg/apis/openebs.io/v1beta1/zz_generated.deepcopy.go

1. Add `poolspec` in spc inside spc `spec` also so that this can be used in auto provisioning.
2. Add auto gen files for the added spec. 

feat(spc_v1beta1_schema): add poolspec in spc schema

---

GNUmakefile

This commit adds `make kubegendelete` target for deleting generating code by kubegen and also adds a travis check for this. This will be helpful for catching PR's that introduces inconsistency for generated codes.
**Checklist:**

fix(makefile): add make target to delete kubernetes generated code

---

integration-tests/artifacts/installer/v1alpha1/installer.go
pkg/unstruct/v1alpha2/kubernetes.go
pkg/unstruct/v1alpha2/kubernetes_test.go

1)  Adds the support to get the dynamic clientset using provided kubeConfig Path.
2) Adds UT for kubernetes package(`pkg/unstruct/v1alpha2/`).
**Checklist:**

feat(unstruct, idiomatic): add support to get dynamic clientset using KubeConfig path

---

pkg/kubernetes/client/v1alpha1/client.go
pkg/kubernetes/client/v1alpha1/client_test.go
pkg/kubernetes/node/v1alpha1/kubernetes.go
pkg/kubernetes/node/v1alpha1/kubernetes_test.go
pkg/kubernetes/persistentvolumeclaim/v1alpha1/kubernetes.go
pkg/kubernetes/persistentvolumeclaim/v1alpha1/kubernetes_test.go
pkg/kubernetes/pod/v1alpha1/kubernetes.go
pkg/kubernetes/pod/v1alpha1/kubernetes_test.go
pkg/kubernetes/storageclass/v1alpha1/kubernetes.go
pkg/kubernetes/storageclass/v1alpha1/kubernetes_test.go

This PR adds the support to get the clientset using provided kubeConfig Path.
Dependent PR need to merge:(https://github.com/openebs/maya/pull/1120)
**Checklist:**

feat(clientset, idiomatic): add support to get clientset using KubeConfig path

---

cmd/maya-apiserver/app/server/http.go
cmd/maya-apiserver/app/server/http_test.go
cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
pkg/apis/openebs.io/v1alpha1/cas_volume_test.go
pkg/castemplate/v1alpha1/cas_template_engine.go
pkg/client/k8s/v1alpha1/unstructured.go
pkg/task/meta.go
pkg/task/meta_test.go
pkg/task/runner.go
pkg/task/task.go
pkg/upgrade/result/v1alpha1/kubernetes.go
pkg/volume/volume.go
pkg/volume/volume_template_engine.go

Currently the logs are flooded with repeated error messages and debug messages which makes it difficult to find relevant information. This PR removes those repeated messages.
**Which issue this PR fixes** :
Earlier runtask failure log were having the pretty and inline objects both.
```
2019/04/30 09:24:04.199967 [DEBUG] http: Request /latest/meta-data/instance-id (49.668µs)
2019/04/30 09:24:04.200322 [DEBUG] http: Request /latest/volumes/ (GET)
I0430 09:24:04.200339       6 volume_endpoint_v1alpha1.go:77] received cas volume request: http method 'GET'
I0430 09:24:04.200350       6 volume_endpoint_v1alpha1.go:253] received volume list request
E0430 09:24:04.294134       6 runner.go:213] failed to …
```

debuggability(log): remove un-required log entries

---

cmd/upgrade/app/v1alpha1/executor.go
cmd/upgrade/app/v1alpha1/result.go
cmd/upgrade/app/v1alpha1/upgrade.go
pkg/errors/v1alpha1/types.go
pkg/upgrade/v1alpha1/config.go
pkg/upgrade/v1alpha1/config_test.go
pkg/upgrade/v1alpha1/engine.go
pkg/upgrade/v1alpha1/engine_test.go

This PR will change error package import path in `m-upgrade`.
Previously it was 
```go
import "github.com/pkg/errors"
```
now it will be
```go
import errors "github.com/openebs/maya/pkg/errors/v1alpha1"
```

debuggability (error package): change import path of error package in m-upgrade

---

pkg/install/v1alpha1/cstor_pool.go

This PR adds csp label to cStor-pool pod.

feat(runtask,cStor-pool) : add csp label to cStor-pool pod

---

pkg/install/v1alpha1/cstor_volume.go

This commit fixes the issue of cstor target pod getting stuck at pending state when `sts-target-affinity` label is used due to missing namespace in the target deployment.
**Checklist:**

fix(sts): fix target pod stuck at pending state (#1124)

---

cmd/maya-apiserver/app/server/http.go
cmd/maya-apiserver/app/server/http_test.go
pkg/errors/v1alpha1/types.go

Signed-off-by: shubham <shubham.bajpai@mayadat.io>
This PR removes unnecessary error message and brackets from the logs. 
Currently the logs have an extra error message and `{}` surrounding the entire message
```
2019/05/10 07:27:14.274444 [ERR] http: Request GET /latest/volumes/pvc-042b77bb-72f5-11e9-a678-54e1ad5e8320
{error(s) were found: failed to read volume: volume {pvc-042b77bb-72f5-11e9-a678-54e1ad5e8320} not found in namespace {default}
github.com/openebs/maya/cmd/maya-apiserver/app/server.(*volumeAPIOpsV1alpha1).read
/home/user/work/src/github.com/openebs/maya/cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go:209}
I0510 07:27:14.275722       6 volume_endpoint_v1alpha1.go:77] received cas volume request: http method {POST}
I0510 …
```

debuggability(log): removes unnecessary error message and brackets

---

cmd/upgrade/app/v1alpha1/executor.go
cmd/upgrade/app/v1alpha1/result.go
pkg/client/k8s/k8s.go

- Refactors owner reference fetch logic in m-upgrade
- Change environment variable name  
- Change `jsonkey` in remote exec output
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: pool-upgrade-config
namespace: default
data:
upgrade: |
casTemplate: cstor-pool-081-082
resources:
- name: pool-c3jd
kind: cStorpool
- name: pool-ji38
kind: cStorpool
- name: pool-jkd4
kind: cStorpool
---
apiVersion: batch/v1
kind: Job
metadata:
name: spc-cstor-sparse-pool-upgrade
spec:
template:
spec:
serviceAccountName: super-admin
containers:
- name:  upgrade
image: openebs/m-upgrade:ci
volumeMounts:
- name: config
mountPath: /etc/config
readOnly: true
env:
- name: OPENEBS_IO_POD_NAME
valueFrom:
fieldRef:
fieldPath: metadata.name
- name: …
```

refactor(m-upgrade): Refactor owner reference fetch logic in m-upgrade

---

cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
pkg/apis/openebs.io/v1alpha1/cas_keys.go
pkg/apis/openebs.io/v1alpha1/cas_template_keys.go
pkg/install/v1alpha1/jiva_volume.go
pkg/templatefuncs/v1alpha1/templatefuncs.go
pkg/volume/volume.go

This PR enables `nodeAffnity` to pin jiva replicas on their scheduled nodes. This is required since, jiva replica pods may move to other node(s) if pod gets rescheduled. Having `nodeAffnity` ensures that replica pods will never be scheduled to other nodes other than its original scheduled node. This setting will lead pending state if original schedule node(s) is no longer available. 
There are following cases when replica pods can be scheduled to other nodes without this setting:
- OOM (Out of memory)
- Doesn't have enough cpu resources
- Node is drained
- Replica deployment have been patched or edited using `kubectl patch` or `kubectl edit` commands.
This commit adds following RunTasks to `jiva-volume-create-default` …

feat(jiva, runtask): add patch replica runtask

---

cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
pkg/apis/openebs.io/v1alpha1/cas_keys.go
pkg/install/v1alpha1/jiva_volume.go
pkg/template/template.go
pkg/volume/volume.go

This PR enables nodeAffnity to pin jiva replicas on their scheduled nodes. This is required since, jiva replica pods may move to other node(s) if pod gets rescheduled. Having nodeAffnity ensures that replica pods will never be scheduled to other nodes other than its original scheduled node. This setting will lead pending state if original schedule node(s) is no longer available.
There are following cases when replica pods can be scheduled to other nodes without this setting:
- OOM (Out of memory)
- Doesn't have enough cpu resources
- Node is drained
- Replica deployment have been patched or edited using kubectl patch or kubectl edit commands.
This commit adds following RunTasks to jiva-volume-create-default CASTemplate:
- `jiva-volume-read-verifyreplicationfactor-default` to verify …

Cherry-pick(jiva, runtask): add patch replica runtask (#1119)

---

pkg/install/v1alpha1/jiva_snapshot.go
pkg/install/v1alpha1/jiva_volume.go

There have been some use cases where, users have requested for
an option to deploy the jiva pods in non-user (PVC) namespace.
For example:
- Granting additional privileges to jiva pods to access hostpath
might involve granting privileges to the entire namespace.
- When using backup with velero, on pvc namespace,
even the jiva pod related information is backed up
and during restore - duplicate set of jiva pods will be
created.
This PR introduces a StorageClass Policy for deploying the
jiva pods in OpenEBS Namespace. (Default is false, same
as earlier releases).
```
metadata:
name: jiva-pods-in-openebs-ns
annotations:
- name: DeployInOpenEBSNamespace …
```

feat(jiva): allow deploying of jiva pods in openebs ns

---

ci/travis-ci.sh
pkg/install/v1alpha1/jiva_snapshot.go

This PR introduces a new  runtask to fetch the target service
using the values provided by the snap cast engine.
Also fixes the travis tests to use the locally build images instead of 
pulling in from docker hub. 
**Checklist:**

fix(snapshots): fix jiva snaps with pods in openebs ns

---

Gopkg.lock
cmd/maya-apiserver/app/server/restore_endpoint_v1alpha1.go

Restore CR is being created for each restore on volume. Earlier restore CR name was created from Restore name and POOL UUID(on which restore will be executed). Due to this, if we are creating restore for multiple volumes (let say V1 and V2) then same CR(restore CR for V1) will be used for other volumes (restore for V2) having the same pool UUID.
This PR fixes the above scenario. With these changes, each restore has its own CR.
**Checklist:**

 cherry-pick(restore, v0.9.x) : fixing restore CR name 

---

cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
pkg/volume/volume.go

Signed-off-by: shubham <shubham.bajpai@mayadat.io>
Removes unnecessary cas object dumps in read requests.
*What the logs currently look like*
```
I0515 12:14:02.137363       6 volume_endpoint_v1alpha1.go:77] received cas volume request: http method 'GET'
I0515 12:14:02.137399       6 volume_endpoint_v1alpha1.go:162] received volume read request: pvc-e57cccbf-770a-11e9-bd08-54e1ad5e8320
2019/05/15 12:14:02.243921 [ERR] http: Request GET /latest/volumes/pvc-e57cccbf-770a-11e9-bd08-54e1ad5e8320
--  error converting YAML to JSON: yaml: mapping values are not allowed in this context
github.com/openebs/maya/pkg/volume.NewVolumeEngine
/home/user/work/src/github.com/openebs/maya/pkg/volume/volume_template_engine.go:82
--  failed to instantiate volume …
```

debuggability(log): removes unnecessary cas object dumps for read requests

---

CONTRIBUTING.md

This commit adds guidelines that a reviewer as well as a contributor can follow during a PR review process.
**Checklist:**

chore(docs, contributing): add guidelines for review comments

---

tests/README.md
tests/jiva/clone/provision_test.go
tests/jiva/clone/suite_test.go
tests/jiva/volume/provision_test.go
tests/jiva/volume/suite_test.go
tests/operations.go

This PR adds bdd test for provisioning of jiva clone
**Sample Testing output**
- provide kubeconfig path to test
`ginkgo -v -- -kubeconfig=/path/to/kubeconfig`
```
user:clone$ ginkgo -v -- -kubeconfig=/home/user/.kube/config
Running Suite: Test jiva clone provisioning
===========================================
Random Seed: 1558099279
Will run 6 of 6 specs
STEP: waiting for openebs-snapshot-operator pod to come into running state
STEP: creating a storageclass
[jiva] TEST JIVA CLONE …
```

feat(bdd, jiva) add BDD for provisioning jiva clone

---

pkg/cstorpool/v1alpha3/kubernetes.go
pkg/storagepoolclaim/v1alpha1/kubernetes.go
tests/cstor-pool/cstor_integration_test.go

Adds the `kubeconfig` flag to take the KubeConfigPath while running the bdd.
Use the below command to run the test
`ginkgo -v -- -kubeconfig=/path/to/kubeconfig`
**Checklist:**

tests(cstorpool): add flag to take kubeconfigpath

---

tests/cstor-volume/README.md
tests/cstor/volume/provision_test.go
tests/cstor/volume/suite_test.go
tests/operations.go

Adds BDD tests for cstor volume provisioning.
```sh
ginkgo -v -- -kubeconfig="/var/run/kubernetes/admin.kubeconfig"
Random Seed: 1558707760
[cstor] TEST VOLUME PROVISIONING when cstor pvc with replicacount 1 is created 
/home/prateek/gocode/src/github.com/openebs/maya/tests/cstor/volume/provision_test.go:96
STEP: building object of storageclass
STEP: …
```

feat(cstor,BDD): Add cstor volume BDD for volume provisioning

---

tests/cstor-pool/cstor_integration_test.go
tests/jiva/clone/provision_test.go
tests/jiva/clone/suite_test.go
tests/jiva/jiva.go
tests/jiva/snapshot/provision_test.go
tests/jiva/snapshot/suite_test.go
tests/jiva/volume/provision_test.go
tests/jiva/volume/suite_test.go

- Adds flag `replicas` to jiva related bdds to take replicacount value at run time.
Example 
```
ginkgo -v -- --kubeconfig=/home/user/.kube/config --replicas=1
```
- refactored cstor-pool bdd to wait longer for csp to come to healthy state. 
It was failing because of that.
**Checklist:**

refact(bdd) added flag to take replica count as input

---

cmd/upgrade/app/v1alpha1/result.go
pkg/kubernetes/pod/v1alpha1/pod.go
pkg/task/task.go
pkg/unstruct/v1alpha2/unstruct.go
pkg/unstruct/v1alpha2/unstruct_test.go
pkg/upgrade/result/v1alpha1/kubernetes.go
pkg/upgrade/result/v1alpha1/kubernetes_test.go
pkg/upgrade/result/v1alpha1/upgraderesult.go
pkg/upgrade/result/v1alpha1/upgraderesult_test.go
pkg/util/http/v1alpha1/http.go
tests/operations.go
tests/upgrade/0.8.2-0.9.0/jiva/suite_test.go
tests/upgrade/0.8.2-0.9.0/jiva/volume_test.go

Adds BDD test for upgrading jiva volume from 0.8.2 to 0.9.0
**Assumptions made**:
- The cluster does not have openebs installed.
- The cluster have no resources in default namespace. (Will be changed to other namespace)
Can provide kubeconfigpath and replica count while running the test.
```
user:jiva$ ginkgo -v -- -kubeconfig=/home/user/.kube/config -replicas=1
Running Suite: Test jiva volume upgrade
=======================================
Random Seed: 1558765568
STEP: applying openebs 0.8.2
STEP: creating above storageclass
STEP: building a pvc
STEP: creating …
```

feat(bdd, upgrade) add BDD for jiva volume upgrade

---

pkg/client/k8s/k8s.go
pkg/kubernetes/pod/v1alpha1/kubernetes.go
pkg/kubernetes/podexec/v1alpha1/podexec.go
pkg/task/task.go

This PR refactors pod exec functionality in order to improve the following -
- It adds exec as an operation to pod so that it can be called in the same way as other pod operations like get, list, delete, etc are called by caller.
- It tries to enhance pod exec code to be in idiomatic maya way.
**Checklist:**

refactor(CAST, exec): refactor runtask pod exec functionality

---

pkg/algorithm/cstorpoolselect/v1alpha1/select.go
pkg/cstorvolumereplica/v1alpha1/kubernetes.go
pkg/cstorvolumereplica/v1alpha1/kubernetes_test.go
tests/cstor/cstor.go
tests/cstor/snapshot/snapshot_test.go
tests/cstor/snapshot/suite_test.go
tests/cstor/volume/provision_test.go
tests/cstor/volume/suite_test.go
tests/operations.go
tests/sts/sts_test.go

Make replica count and maxpool count configurable using flags.
example:
`ginkgo -v -- --kubeconfig=/var/run/kubernetes/admin.kubeconfig --cstor-replicas=1 --cstor-maxpools=1`
**Checklist:**

feat(bdd,cstor): make replica count and pool count configurable

---

pkg/apis/openebs.io/ndm/v1alpha1/disk_types.go
pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/typed/ndm/v1alpha1/disk.go
pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/typed/ndm/v1alpha1/fake/fake_disk.go
pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/typed/ndm/v1alpha1/fake/fake_ndm_client.go
pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/typed/ndm/v1alpha1/ndm_client.go
pkg/client/generated/openebs.io/ndm/v1alpha1/informer/externalversions/ndm/v1alpha1/disk.go
pkg/client/generated/openebs.io/ndm/v1alpha1/informer/externalversions/ndm/v1alpha1/interface.go
pkg/client/generated/openebs.io/ndm/v1alpha1/lister/ndm/v1alpha1/disk.go
pkg/client/generated/openebs.io/ndm/v1alpha1/lister/ndm/v1alpha1/expansion_generated.go

When the NDM APIs were checked-in, it was made as namespace scoped. But the earlier disk resource was cluster scoped. This PR changes the Disk resource of NDM from `Namespace` scope to `Cluster` scope. 
Only one file(`pkg/apis/openebs.io/ndm/v1alpha1/disk_types.go`) has the actual changes. All other changes are from auto-generated code.
**Checklist:**

chore(code-gen): change NDM Disk APIs to Cluster scope

---

pkg/install/v1alpha1/env.go
pkg/install/v1alpha1/env_setter.go
pkg/install/v1alpha1/installer.go
pkg/install/v1alpha1/marshall.go
pkg/install/v1alpha1/registrar.go

This commit reduces flooding of logs during install of openebs crds and resources by maya api server.
In addition, this commit puts few code & code comments well within the limits of 80 chars.
**Checklist:**

chore(log, debuggability): reduce flooding of install logs

---

pkg/install/v1alpha1/jiva_volume.go

Signed-off-by: shashank855 <shashank.ranjan@mayadata.io>
- Refactor jiva-replica-deploment-runtask for jiva replica pod to get scheduled on Openshift (V-3.10).
- On Openshift (v-3.10) jiva replica pod goes into CrashLoopBackOff with the following log:
```
time="2019-06-05T01:02:50Z" level=error msg="failed to create tmp file /openebs/tmpFile.tmp, error: open /openebs/tmpFile.tmp: permission denied" 
time="2019-06-05T01:02:50Z" level=fatal msg="Error running start replica command: open /openebs/tmpFile.tmp: permission denied"
``` 
**Checklist:**

feat(runtask, priviledged) replica deployment runtask for scheduling replica pod on openshift 

---

tests/artifacts/openebs-ci.yaml

Currently, the travis CI depends on the openebs-operator.yaml defined in the openebs/openebs repository. However, as the majority of the components reside in this repository, and as new components are introduced - there is a dependency created to update the openebs/openebs repository to test the features that are still in development. 
And changing the openebs/openebs impacts both the tests of the other parallel features being worked on as well as other repositories. By having a local openebs-operator and have travis use it for maya repository testing, it will give opportunity to test features locally without impacting other repos. 
**Which issue this PR fixes** *(optional, in `fixes …

chore(operator): update artifacts operator yaml with latest changes

---

cmd/maya-exporter/app/collector/pool/metrics.go
cmd/maya-exporter/app/collector/pool/pool.go
cmd/maya-exporter/app/collector/pool/pool_test.go
cmd/maya-exporter/app/collector/types.go
cmd/maya-exporter/app/collector/zvol/list.go
cmd/maya-exporter/app/collector/zvol/list_test.go
cmd/maya-exporter/app/collector/zvol/metrics.go
cmd/maya-exporter/app/collector/zvol/zvol.go
cmd/maya-exporter/app/collector/zvol/zvol_test.go
cmd/maya-exporter/app/command/command.go
pkg/exec/mock/v1alpha1/mock.go
pkg/exec/types.go
pkg/exec/v1alpha1/exec.go
pkg/prometheus/exporter/mock/v1alpha1/mock.go
pkg/zpool/v1alpha1/zpool.go
pkg/zvol/v1alpha1/zvol.go

This commit implements pool exporter as per idiomatic standards.
- Move mock functions for prometheus into collector/mock package so that it can be utilized by all the collectors.
- Move mock functions of RealRunner structure into pkg/util and make it public.
- Remove the goroutines for verifying the reject request counter.
- Fix namings of the Test functions.
Add following counters:
- zpoolInitializeLibuzfsClientErrorCounter
- zfsStatsNoDataSetAvailableErrorCounter
- zfsStatsInitializeLibuzfsClientErrorCounter
- zfsListNoDataSetAvailableErrorCounter
- zfsListInitializeLibuzfsClientErrorCounter
break each metrics into individual function
**Which issue this PR fixes** *(optional, in …

cherry-pick(idiomatic-maya, exporter): pool exporter changes

---

cmd/cstor-pool-mgmt/controller/common/common.go
cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
pkg/install/v1alpha1/cstor_volume.go

This commit reverts a previous commit i.e. https://github.com/openebs/maya/pull/955
There were a few observations (that were expected) due to above commit. CVR used to have finalizers to execute cleanup operations due to delete event of corresponding volume. This is a standard
practice in kubernetes community to handle cleanups via reconciliation process.
However, we had to remove finalizers as seen in the commit 955 due to various reasons. These were:
[1] Inability to delete a openebs system namespace and expect entire openebs to get uninstalled
[2] Deletion of cstor volume did not delete CVRs due to the presence of finalizers. This was seen most of the times across various users and platforms. This was not easily reproducible in development environments.
With the current release i.e. …

fix(cvr, delete): add finalizer to reclaim space on volume delete

---

tests/exporter/exporter_test.go

- Make use of current spc schema where the value of spec.type has been changed to
blockdevice irrespective of disk and sparse.
- Remove hardcoded strings and use constants instead
- Rename metrics name `openebs_no_pool_available_error` to
`openebs_zpool_list_no_pool_available_error`
**Checklist:**

fix(bdd,exporter): rename metrics name

---

cmd/cstor-pool-mgmt/controller/common/common.go
cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
pkg/install/v1alpha1/cstor_volume.go

This is the cherrypick of https://github.com/openebs/maya/pull/1256

cherrypick(fix, cvr, delete): add finalizer to reclaim space on volume delete

---

tests/exporter/exporter_test.go

Make use of current spc schema where the type has been changed to
blockdevice irrespective of disk and sparse.
Remove hardcoded strings and use constants instead
Rename metrics name `openebs_no_pool_available_error` to
`openebs_zpool_list_no_pool_available_error`
**Checklist:**

cherry-pick(bdd,exporter): rename metrics name (#1258)

---

pkg/kubernetes/pod/v1alpha1/build.go
pkg/kubernetes/pod/v1alpha1/kubernetes.go
pkg/kubernetes/pod/v1alpha1/pod.go
tests/jiva/clone/provision_test.go
tests/operations.go

Adds data consistency check after creating clone pvc using two application pods.
```
user:clone$ ginkgo -v -- -kubeconfig=/home/user/.kube/config
Running Suite: Test jiva clone provisioning
===========================================
Random Seed: 1559818349
Will run 9 of 9 specs
STEP: waiting for openebs-snapshot-operator pod to come into running state
STEP: creating a storageclass
[jiva] TEST JIVA CLONE CREATION when pvc with replicacount n is created 
should …
```

refact(bdd, jiva) added data consistency check for clone creation BDD

---

cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
pkg/algorithm/nodeselect/v1alpha1/config.go
pkg/algorithm/nodeselect/v1alpha1/select_node.go
pkg/apis/openebs.io/v1alpha1/cas_pool.go
pkg/blockdevice/v1alpha1/blockdevice.go
pkg/blockdevice/v1alpha2/blockdevice.go
pkg/blockdevice/v1alpha2/build.go
pkg/blockdevice/v1alpha2/buildlist.go
pkg/blockdevice/v1alpha2/kubernetes.go
pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim.go
pkg/blockdeviceclaim/v1alpha1/build.go
pkg/blockdeviceclaim/v1alpha1/buildlist.go
pkg/blockdeviceclaim/v1alpha1/kubernetes.go

This PR adds the support to build blockdevice and blockdeviceclaim to perform CRUD operations on the BD and BDC by making use of client-go.
**Checklist:**

[cherry-pick] feat(bd, bdc, idiomatic): add blockdevice and blockdeviceclaim support as per idiomatic maya guide lines

---

pkg/install/v1alpha1/cstor_sparse_pool_claim.go

With latest cstor pool configuration changes, to create StoragePoolClaim we have to
use spc `type: blockdevice` as common type to create Storagepool based on either disk or sparse.
The type specific info i.e. `Sparse` and `Disk`  has been move to the `BlockDeviceClaim` resource.
```yaml
metadata:
name: sparse-claim-auto
spec:
name: sparse-claim-auto
type: blockdevice
maxPools: 1
minPools: 1
poolSpec:
cacheFile: /var/openebs/sparse/sparse-claim-auto.cache
overProvisioning: false
```
```yaml
metadata:
name: sparse-claim-auto
spec:
name: sparse-claim-auto
type: sparse
maxPools: 1
minPools: 1
poolSpec: …
```

refact(cstor-pool,sparse): Update SPC type to blockdevice

---

cmd/maya-apiserver/cstor-operator/spc/handler.go
cmd/maya-apiserver/cstor-operator/spc/handler_test.go
cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
cmd/maya-apiserver/cstor-operator/spc/storagepool_create_test.go
pkg/algorithm/nodeselect/v1alpha1/select_node.go
pkg/blockdevice/v1alpha1/blockdevice.go
pkg/blockdevice/v1alpha1/blockdevice_test.go
pkg/blockdevice/v1alpha1/kubernetes_client.go
pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim.go
pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim_test.go
pkg/blockdeviceclaim/v1alpha1/build.go
pkg/blockdeviceclaim/v1alpha1/build_test.go
pkg/blockdeviceclaim/v1alpha1/buildlist.go
pkg/blockdeviceclaim/v1alpha1/buildlist_test.go
pkg/blockdeviceclaim/v1alpha1/kubernetes.go
pkg/blockdeviceclaim/v1alpha1/kubernetes_test.go
pkg/volume/rounding.go
pkg/volume/rounding_test.go

This PR adds the support to create pool on unclaimed block devices.
Steps to create a pool on unclaimed block devices:
1. Deploy latest openebs-operator.yaml using `kubectl apply -f <file_name>`.
2. Check whether the openebs components are in running state or not
```bash
kubectl get po -n openebs
NAME                                         READY   STATUS             RESTARTS   AGE
maya-apiserver-78f66545fc-j5kvp              1/1     Running            0          15m
node-disk-operator-6c58d8596c-qk7rv          1/1     Running         0          15m
openebs-admission-server-f798484fd-v854b     1/1     Running            0          15m
openebs-localpv-provisioner-76ff6fd9-s9zwj   1/1     Running            0          15m
openebs-ndm-7547s …
```

feat(cstor-operator): add a support to create pools on unclaimed BD in manual mode

---

cmd/maya-apiserver/cstor-operator/spc/handler_test.go
cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
cmd/maya-apiserver/cstor-operator/spc/storagepool_create_test.go
pkg/algorithm/nodeselect/v1alpha1/select_node.go
pkg/blockdevice/v1alpha1/blockdevice.go
pkg/blockdevice/v1alpha1/blockdevice_test.go
pkg/blockdevice/v1alpha1/kubernetes_client.go
pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim.go
pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim_test.go
pkg/blockdeviceclaim/v1alpha1/build.go
pkg/blockdeviceclaim/v1alpha1/build_test.go
pkg/blockdeviceclaim/v1alpha1/buildlist.go
pkg/blockdeviceclaim/v1alpha1/buildlist_test.go
pkg/blockdeviceclaim/v1alpha1/kubernetes.go
pkg/blockdeviceclaim/v1alpha1/kubernetes_test.go
pkg/install/v1alpha1/cstor_sparse_pool_claim.go
pkg/volume/rounding.go
pkg/volume/rounding_test.go

This PR contains following cherry-picks
1) https://github.com/openebs/maya/pull/1264
2) https://github.com/openebs/maya/pull/1265
**Checklist:**

[cherry-pick] feat(cstor-operator): add a support to create pools on unclaimed BD in manual mode

---

pkg/install/v1alpha1/env.go
pkg/install/v1alpha1/env_setter.go
pkg/install/v1alpha1/installer.go
pkg/install/v1alpha1/marshall.go
pkg/install/v1alpha1/registrar.go

This commit reduces flooding of logs during install of
openebs crds and resources by maya api server.
In addition, this commit puts few code & code comments well
within the limits of 80 chars.
cherry-pick #1234
**Checklist:**

[cherry-pick-1234] chore(log, debuggability): reduce flooding of install logs

---

pkg/kubernetes/pod/v1alpha1/kubernetes.go
pkg/kubernetes/pod/v1alpha1/kubernetes_test.go
tests/jiva/clone/provision_test.go
tests/jiva/volume/provision_test.go
tests/jiva/volume/suite_test.go

Adds a check to verify that the replica pods connect to controller after controller or replica pods are restarted.
```
user:volume$ ginkgo -v -- -kubeconfig=/home/user/.kube/config
Running Suite: Test jiva volume provisioning
============================================
Random Seed: 1560147425
Will run 4 of 4 specs
STEP: creating a storageclass
[jiva] TEST VOLUME PROVISIONING when jiva pvc with replicacount n is created 
should create 1 controller pod and n …
```

refact(bdd, jiva) added target affinity check after controller and replica pods restart

---

pkg/kubernetes/deployment/appsv1/v1alpha1/deployment.go
tests/kubernetes/deployment/app_test.go
tests/localpv/hostdevice_test.go
tests/localpv/hostpath_test.go
tests/localpv/suite_test.go

This PR adds BDD test for provisioning localpv using `openebs-device` storageclass. This test requires a disk mounted to the node.
**Note**: *We can use* `--focus=HOSTPATH` *or* `--focus=HOSTDEVICE` *to run the specific test*. *Without the* `focus` *flag ginkgo will run both the tests*.
```
user:localpv$ ginkgo --focus=HOSTDEVICE  -v -- -kubeconfig=/home/user/.kube/config
Running Suite: Test application deployment
==========================================
Random Seed: 1560177319
Will run 12 of 16 specs
STEP: waiting for openebs-localpv-provisioner pod to come into running state
STEP: …
```

feat(bdd, localpv) add BDD for localpv provisioning using hostdevice

---

cmd/maya-apiserver/cstor-operator/spc/handler.go
cmd/maya-apiserver/cstor-operator/spc/handler_test.go
cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
pkg/algorithm/nodeselect/v1alpha1/select_node.go
pkg/algorithm/nodeselect/v1alpha1/select_node_test.go
pkg/apis/openebs.io/ndm/v1alpha1/blockdeviceclaim_types.go
pkg/blockdevice/v1alpha1/blockdevice.go
pkg/blockdevice/v1alpha1/blockdevice_test.go
pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim.go
pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim_test.go
pkg/storagepoolclaim/v1alpha1/storagepoolclaim.go

This PR add the support to use unclaimed block devices(BD) during auto provisioning of pool creation.
1) Deploy latest openebs-operator.yaml using `kubectl apply -f <file_name>`
2) Check whether the openebs components are in running state or not 
```bash
kubectl get po -n openebs
NAME                                         READY   STATUS             RESTARTS   AGE
maya-apiserver-78f66545fc-j5kvp              1/1     Running            0          15m
node-disk-operator-6c58d8596c-qk7rv          1/1     Running         0          15m
openebs-admission-server-f798484fd-v854b     1/1     Running            0          15m
openebs-localpv-provisioner-76ff6fd9-s9zwj   1/1     Running            0          15m
openebs-ndm-7547s …
```

feat(cstor-operator, blockdevice): add support to create cStor pools on unclaimed BD in auto mode

---

pkg/blockdevice/v1alpha2/kubernetes.go
tests/cstor/pool/negative/provision_without_disk_test.go
tests/operations.go

This PR adds a negative test of provisioning cstor volume without any disk.
```
user:negative$ ginkgo -focus=WITHOUT -v -- -kubeconfig=$HOME/.kube/config
Running Suite: Test cstor invalid config
========================================
Random Seed: 1560344530
Will run 1 of 5 specs
[cstor] [-ve] TEST PROVISION WITHOUT DISK when creating storagepoolclaim without disk 
should not create any cstorpool …
```

feat(bdd, cstor) BDD for provisioning volume without disk

---

GNUmakefile
pkg/kubernetes/persistentvolumeclaim/v1alpha1/build.go
pkg/kubernetes/persistentvolumeclaim/v1alpha1/build_test.go
pkg/kubernetes/persistentvolumeclaim/v1alpha1/buildlist.go
pkg/kubernetes/persistentvolumeclaim/v1alpha1/kubernetes.go
pkg/kubernetes/persistentvolumeclaim/v1alpha1/kubernetes_test.go
tests/cstor/volume/provision_bulk_test.go
tests/exporter/exporter_test.go

Signed-off-by: shubham shubham.bajpai@mayadata.io
This commit adds test logic that does the following:
creates multiple pvcs in a given namespace
verifies if all these pvcs were created successfully
deletes all these pvcs
verifies if each pvc resources are deleted
```
user:volume$ ginkgo -v --focus=BULK -- -kubeconfig=/home/user/.kube/config
Random Seed: 1560250881
Will run 4 of 5 specs
[cstor] …
```

bdd(pvc, cstor): add bulk create and delete of pvcs in a given namespace

---

pkg/algorithm/nodeselect/v1alpha1/select_node.go
pkg/algorithm/nodeselect/v1alpha1/select_node_test.go

**Manual Provisioning in 0.9.0:**
Manual provisioning implies specifying exact disks on which cStor pools need to be created. In other words, update diskList field on which pools need to be created.
**Example spc 0.9.0 yaml:**
```yaml
metadata:
name: cstor-disk
spec:
name: cstor-disk
type: disk
maxPools: 1
poolSpec:
disks:
diskList:
- disk-5a93ced3e2ee21eac7b930f670b5eab5
- sparse-5a92ced3e2ee21eac7b930f670b5eab5
- disk-5a94ced3e2ee21eac7b930f670b5eab5
```
In case of manual provisioning in 0.9.0 we are honoring spc.spec.type
For example in above yaml 
1) If spc.spec.type is specified as a `disk` we are creating pools only …

fix(cstor-operator): honour spc type in case of manual provisioning of cStor pool

---

pkg/install/v1alpha1/cstor_sparse_pool_claim.go

With latest cstor pool configuration changes, to create StoragePoolClaim we have to
use **spec.type** as `sparse` or `disk`.
In order to create pools on sparse files use type as `sparse`
Similarly to create pools on disk use type as `disk`.
Refer PR #https://github.com/openebs/maya/pull/1274 for more details
**Checklist:**

refact(cstor-pool,sparse): Update SPC type to sparse

---

pkg/install/v1alpha1/cstor_sparse_pool_claim.go

With latest cstor pool configuration changes, to create StoragePoolClaim we 
have to use spec.type as sparse or disk.
In order to create pools on sparse files use type as sparse
Similarly to create pools on disk use type as disk.
Refer PR ##1274 for more details
**Checklist:**

refact(cstor-pool,sparse): Update SPC type to sparse (#1284)

---

cmd/cstor-pool-mgmt/controller/pool-controller/new_pool_controller.go
cmd/maya-apiserver/cstor-operator/spc/controller.go
pkg/apis/openebs.io/v1alpha1/cas_keys.go

This PR stops the reconciliation process during upgrade process based on labels present on csp and spc CR
1. If spc yaml contains label `reconcile.openebs.io/disable: "true"` then reconciliation stops on particular spc
example yaml
```yaml
metadata:
name: cstor-sparse
labels:
reconcile.openebs.io/disable: true
spec:
name: cstor-sparse
type: sparse
maxPools: 1
poolSpec:
blockDevices:
blockDeviceList:
- sparse-177b6bc2ae2dd332c7a384a02179368b
```
2. If CSP CR contains label `reconcile.openebs.io/disable: "true"` then reconciliation stops on particular  csp resource.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will …

feat[cstor-operator, cstor-pool-mgmt, upgrade]: add support to stop reconciliation during upgrade

---

cmd/cstor-pool-mgmt/controller/pool-controller/new_pool_controller.go
cmd/maya-apiserver/cstor-operator/spc/controller.go

This PR stops the reconciliation process during upgrade process based on annotation present on csp and spc CR
1. If spc yaml contains annotation `reconcile.openebs.io/disable: "true"` then reconciliation stops on particular spc
example yaml
```yaml
metadata:
name: cstor-sparse
annotations:
reconcile.openebs.io/disable: "true"
spec:
name: cstor-sparse
type: sparse
maxPools: 1
poolSpec:
blockDevices:
blockDeviceList:
- sparse-177b6bc2ae2dd332c7a384a02179368b
```
2. If CSP CR contains annotation `reconcile.openebs.io/disable: "true"` then reconciliation stops on particular  csp resource.
example yaml
```yaml
apiVersion: v1 …
```

feat(cstor-operator, cstor-pool-mgmt, upgrade): add support to stop reconciliation during upgrade using annotations

---

cmd/provisioner-localpv/app/config.go
cmd/provisioner-localpv/app/doc.go
cmd/provisioner-localpv/app/helper_hostpath.go
cmd/provisioner-localpv/app/provisioner_blockdevice.go
pkg/kubernetes/persistentvolume/v1alpha1/build.go
pkg/kubernetes/persistentvolume/v1alpha1/build_test.go

When supporting OpenEBS Local PV using the block devices attached to the nodes, these block devices can be in one of the following states:
(a) User has attached the block device, formatted and mounted them.
- For Example: GKE with Local SSD
(b) User has attached the block device, un-formatted and not mounted.
- For Example: GKE with GPD
(c) Similar to (b), but device has only device path, but no dev links.
- For Example: VM with VMDK disks or AWS node with EBS
Initial version of the Local PV with block device supported (a). In other words, it expects user to format and mount these devices. 
With this PR, (b) and (c) are also supported. 
Provisioner will check if the device has a mounted path, if not it will pass either the dev link or the device path to the Local PV, along with the …

feat(localpv): allow creating Local PV on unformatted devices

---

cmd/cstor-pool-mgmt/controller/pool-controller/new_pool_controller.go
cmd/maya-apiserver/cstor-operator/spc/controller.go
pkg/algorithm/nodeselect/v1alpha1/select_node.go
pkg/algorithm/nodeselect/v1alpha1/select_node_test.go
pkg/apis/openebs.io/v1alpha1/cas_keys.go

This PR cherry-pick's the following commits
1. feat[cstor-operator, cstor-pool-mgmt, upgrade]: add support to stop reconciliation during upgrade       ( #1280 )
2. fix(cstor-operator): honour spc type in case of manual provisioning of cStor pool (#1281)
3. feat(cstor-operator, cstor-pool-mgmt, upgrade): add support to stop reconciliation during upgrade using annotations (#1288) 
**Checklist:**

[cherry-pick] (cstor-operator, cstor-pool-mgmt, bdc) #1281 #1280 #1288

---

cmd/provisioner-localpv/app/config.go
cmd/provisioner-localpv/app/doc.go
cmd/provisioner-localpv/app/helper_hostpath.go
cmd/provisioner-localpv/app/provisioner_blockdevice.go
pkg/kubernetes/persistentvolume/v1alpha1/build.go
pkg/kubernetes/persistentvolume/v1alpha1/build_test.go

When supporting OpenEBS Local PV using the block devices attached to the nodes, these block devices can be in one of the following states:
(a) User has attached the block device, formatted and mounted them.
For Example: GKE with Local SSD
(b) User has attached the block device, un-formatted and not mounted.
For Example: GKE with GPD
(c) Similar to (b), but device has only device path, but no dev links.
For Example: VM with VMDK disks or AWS node with EBS
Initial version of the Local PV with block device supported (a). In other words, it expects user to format and mount these devices.
With this PR, (b) and (c) are also supported.
Provisioner will check if the device has a mounted path, if not it will pass either the dev link or the device path to the Local PV, along with the configured …

[cherry-pick] feat(localpv): allow creating Local PV on unformatted devices (#1283)

---

pkg/usage/googleanalytics.go
pkg/usage/usage.go
pkg/usage/versionset.go

OpenEBS can be installed using different modes like helm,
operator, or partners like rancher, nks etc. This PR
helps track which type of installer are being used.
Also, this PR pushes the cluster identifier in an
additional field, that can be used by the reports
to co-relate volumes with clusters.
**Checklist:**

feat(usage): ability to include installer type in GA events

---

pkg/usage/googleanalytics.go
pkg/usage/usage.go
pkg/usage/versionset.go

OpenEBS can be installed using different modes like helm,
operator, or partners like rancher, nks etc. This PR
helps track which type of installer are being used.
Also, this PR pushes the cluster identifier in an
additional field, that can be used by the reports
to co-relate volumes with clusters.
(cherry picked from commit 7a31d504cb9abdfcf5345cdddcadcad27a4b3978)
**Checklist:**

[cherry-pick] feat(usage): ability to include installer type in GA events (#1296)

---

cmd/provisioner-localpv/app/provisioner.go
pkg/usage/const.go

(#1289)
This PR adds the support to send the provision and deprovision 
GA events for Local PV, iff GA is enabled on the local provisioner. 
/kind chore
/kind release
This is a cherry-pick of the #1298 PR
**Checklist:**

[cherry-pick] feat(usage): collect anonymous info about local-pv provisionioner #1289

---

tests/operations.go

This PR increases wait time for eventually functions for loaded machines. The BDDs are failing in openeshift pipelines because of this.
**Checklist:**

fix(bdd) increase wait time for loaded machines

---

tests/cstor/volume/provision_bulk_test.go
tests/cstor/volume/provision_test.go
tests/operations.go

This change delete the pools pods before starting pvc delete just to 
verify the reconciliation process for cstorvolume replica if its miss  the CVR destroy events and there is any stale left.
There were a few observations (that were expected), CVR used to have finalizers to execute cleanup operations due to delete event of corresponding volume. This is a standard
practice in kubernetes community to handle cleanups via reconciliation process.
With the current release i.e. 0.9.0 some users have started to face issues like space not getting reclaimed even after cstor volumes get deleted successfully. On further analysis, it was found that user had tried following operation:
`kubectl delete pvc --all -n some-namespace`
which led to deletion of pvc, pv, …

refact(cstor,BDD): verify cvr destroy event reconciliation via deleting pools pods

---

pkg/kubernetes/node/v1alpha1/kubernetes.go
tests/jiva/node-selector/node_selector_test.go
tests/jiva/node-selector/suite_test.go
tests/operations.go

This PR adds BDD to check the node selector cas config of storageclass for jiva volume. The BDD restarts the controller and replica pods and verifies whether they come back to the respective labelled nodes or not.
```
user:node-selector$ ginkgo -v -- -kubeconfig=/home/user/.kube/config
Running Suite: Test jiva volume node selector
Random Seed: 1560784499
Will run 2 of 2 specs
STEP: creating above storageclass …
```

feat(bdd, jiva) BDD to check node selector config

---

pkg/apis/openebs.io/ndm/v1alpha1/blockdevice_types.go
pkg/apis/openebs.io/ndm/v1alpha1/blockdeviceclaim_types.go

Changed BlockDevice and BlockDeviceClaim APIs
1. Introduced a new state `Released` in BlockDevice `ClaimState`. A BD will be in `Released` state once the associated BDC is deleted, and cleanup jobs are being performed on the BD. Once the cleanup job is successful, BD will be marked as `Unclaimed` and can be claimed by other BDCs
2. Removed `Mountpoint` from BDC. The field is irrevelant because it is not possible to create a claim with a particular mount point, since it involves iterating through all the BDs. 
`BlockVolumeMode` is introduced which is used to specify the type of BD to claim. Depending on the volume mode, either unformatted device or BD with a filesystem can be claimed
State transition of `claimState` for a block device
**1.** Sample …

fix(apis): change ndm apis

---

pkg/apis/openebs.io/ndm/v1alpha1/blockdevice_types.go
pkg/apis/openebs.io/ndm/v1alpha1/blockdeviceclaim_types.go

Changed BlockDevice and BlockDeviceClaim APIs
Introduced a new state Released in BlockDevice ClaimState. A BD will be in Released state once the associated BDC is deleted, and cleanup jobs are being performed on the BD. Once the cleanup job is successful, BD will be marked as Unclaimed and can be claimed by other BDCs
Removed Mountpoint from BDC. The field is irrevelant because it is not possible to create a claim with a particular mount point, since it involves iterating through all the BDs.
BlockVolumeMode is introduced which is used to specify the type of BD to claim. Depending on the volume mode, either unformatted device or BD with a filesystem can be claimed
Cherry-pick #1302 

cherry-pick(apis): change ndm apis

---

cmd/provisioner-localpv/app/helper_hostpath.go
cmd/provisioner-localpv/app/provisioner_hostpath.go
pkg/kubernetes/persistentvolume/v1alpha1/build.go
pkg/kubernetes/persistentvolume/v1alpha1/build_test.go
pkg/kubernetes/persistentvolume/v1alpha1/kubernetes.go
pkg/kubernetes/persistentvolume/v1alpha1/persistentvolume.go

This PR moves the logic to parse the PV attributes to
PV helper pkg.
(cherry picked from commit 4a1a2082084a8054bbd730f5dd171eba709e8672)
**Checklist:**

[cherry-pick] refactor(localpv): move the pv parsing to pv helper package (#1304)

---

tests/cstor/node-selector/suite_test.go
tests/cstor/node-selector/volume_selector_test.go

TargetNodeSelector allows you to specify the nodes where openebs targets have to be scheduled.
Test requires minimum 1 Node in k8s cluster, any available ready Node will be labeled using k8s patch 
with "nodetype: storage" to schedule the target volume pod to  above matched labeled Node.
TargetNodeSelector cas config label has been set using StorageClass
as below
```yaml
metadata:
annotations:
value: 1
- name: StoragePoolClaim
value: test-cstor-selector-sparse-pool-auto-1560848294807552442
- name: TargetNodeSelector
value: |-
nodetype: storage
openebs.io/cas-type: cstor
name: test-cstor-volume-selector-sc-7pcz6
```
```go
ginkgo -v -- …
```

feat(cstor, BDD): cstor volume provision using target node selector

---

cmd/cstor-pool-mgmt/controller/common/common.go
cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go
cmd/cstor-pool-mgmt/controller/replica-controller/run_replica_controller.go

This commit has following changes:
- remove the check where reconcile was avoided in case
of previous delete failures
- reduce instances of log flooding
- improve log messages
- modify & indent code to make it more readable
Related PR(s):
- https://github.com/openebs/maya/pull/1256
This commit tries to fix the symptom 2 talked in PR 1256
**Checklist:**

(cherry-pick)fix(cvr, delete): ensure cvr gets deleted during reconcile (#1263)

---

pkg/algorithm/nodeselect/v1alpha1/select_node.go
pkg/blockdevice/v1alpha1/blockdevice.go
pkg/blockdevice/v1alpha1/blockdevice_test.go

This PR adds the filter to filter out block devices which are in released state during auto provision mode.
**Checklist:**

feat(cstor-operator): filter out released block devices during auto provisioning

---

pkg/install/v1alpha1/jiva_volume.go

Signed-off-by: shashank855 <shashank.ranjan@mayadata.io>
- On Openshift (v-3.10) jiva replica pod goes into CrashLoopBackOff with the following log:
```
time="2019-06-05T01:02:50Z" level=error msg="failed to create tmp file /openebs/tmpFile.tmp, error: open /openebs/tmpFile.tmp: permission denied" 
time="2019-06-05T01:02:50Z" level=fatal msg="Error running start replica command: open /openebs/tmpFile.tmp: permission denied"
``` 
**Checklist:**

[cherry-pick] feat(runtask, priviledged) replica deployment runtask for scheduling replica pod on openshift #1248

---

pkg/kubernetes/client/v1alpha1/client.go
pkg/kubernetes/client/v1alpha1/client_test.go
pkg/kubernetes/pod/v1alpha1/kubernetes.go

This commit handles following idiomatic practices:
- reduce lines of code within a function
- code and code comments are well within 80 chars
- rename functions based on their behaviour
**Checklist:**

refactor(k8s, client): update kubernetes client as per idiomatic maya

---

pkg/kubernetes/deployment/appsv1/v1alpha1/deployment.go
pkg/kubernetes/deployment/appsv1/v1alpha1/deployment_test.go
pkg/kubernetes/podtemplatespec/v1alpha1/podtemplatespec.go
pkg/kubernetes/podtemplatespec/v1alpha1/podtemplatespec_test.go
pkg/kubernetes/service/v1alpha1/build.go
tests/kubernetes/deployment/app_test.go
tests/localpv/hostdevice_test.go
tests/localpv/hostpath_test.go

This PR 
- added a podtemplatespec builder to decouple the template and deployment builder.
It helps to avoid repeating functions like `WithLabels` in the same file.
- added function required to create target deployment for cstor volume.
**Checklist:**

refact(builder) added new methods to deploymet builder

---

pkg/kubernetes/deployment/appsv1/v1alpha1/deployment.go
pkg/kubernetes/deployment/appsv1/v1alpha1/deployment_test.go
pkg/kubernetes/deployment/appsv1/v1alpha1/kubernetes.go
pkg/kubernetes/deployment/appsv1/v1alpha1/rollout_status.go
tests/kubernetes/deployment/app_test.go
tests/localpv/hostdevice_test.go
tests/localpv/hostpath_test.go

This PR changes the the `Build()` of deployment builder to return `*apps.Deployment` instead of local `*Deploy` object
**Checklist:**

fix(builder, deployment): changed Build function to return api object

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-volume-mgmt/controller/volume-controller/handler.go
pkg/apis/openebs.io/v1alpha1/cstor_pool.go
pkg/apis/openebs.io/v1alpha1/cstor_volume.go
pkg/apis/openebs.io/v1alpha1/cstor_volume_replica.go
pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go

This PR adds the `LastUpdatedTime` and `LastTransitionTime` field for the status of `cstorvolume`, `cstorvolumereplica` and `cstorpool`.
sample csp :
```
kind: CStorPool
metadata:
annotations:
openebs.io/csp-lease: '{"holder":"openebs/cstor-sparse-pool-8y6d-7fb44586c6-xfphf","leaderTransition":1}'
creationTimestamp: "2019-07-03T06:51:17Z"
generation: 60
labels:
kubernetes.io/hostname: minikube
openebs.io/cas-template-name: cstor-pool-create-default-1.1.0
openebs.io/cas-type: cstor
openebs.io/storage-pool-claim: cstor-sparse-pool
openebs.io/version: 1.1.0
name: cstor-sparse-pool-8y6d
ownerReferences:
- apiVersion: openebs.io/v1alpha1
blockOwnerDeletion: true …
```

refact(cstor): added last update fields for cstor objects

---

pkg/kubernetes/client/v1alpha1/client.go
pkg/kubernetes/client/v1alpha1/client_test.go
pkg/upgrade/result/v1alpha1/kubernetes.go
pkg/upgrade/result/v1alpha1/kubernetes_test.go

This commit adds function that exposes creating a singleton instance for upgraderesult's kubeclient. This helps the caller code while creating a kubeclient instance since most of the properties of a kubeclient instance need to be set once in the lifetime of the process.
**Checklist:**

refactor(kubeclient): add singleton instance to upgraderesult kubeclient

---

Gopkg.lock
cmd/maya-apiserver/cstor-operator/cspc/cspc_lease.go
cmd/maya-apiserver/cstor-operator/cspc/storagepool_create.go
pkg/algorithm/nodeselect/v1alpha2/build_csp.go
pkg/algorithm/nodeselect/v1alpha2/config.go
pkg/algorithm/nodeselect/v1alpha2/select_node.go
pkg/kubernetes/deployment/appsv1/v1alpha1/deployment.go

This commit will do following:
1. Once BDC has been created for BD ( for pool provisioning), a CSP
will not be created once all the BDs are in *Claimed* state.
This means, more then one event will be rquired for a CSP to be created.
For the first time during pool provisioning, BD will be cheked for Claimed
state and if not claimed, BDC for them will be created and program shall
return.
In the next event, again the BDs will be checked for claimed state and if
claimed pool provisioning shall proceed else program shall return and so on.
2. In a single event, when a node has been visited for pool creation, in either
case success or failure, that node will not be revisited for pool creation.
This is required as one dirty node causing pool provisioning failure can stop
other subsequent nodes …

chore(cstor-operator): fix BD claim, pool resource naming and creation and node reprocessing

---

cmd/cstorvolumeclaim/cstorvolumeclaim.go
cmd/cstorvolumeclaim/start.go
cmd/maya-apiserver/app/command/start.go
cmd/maya-apiserver/cstor-operator/cspc/start.go
cmd/maya-apiserver/cstor-operator/cspc/start_test.go
cmd/maya-apiserver/cstor-operator/spc/start.go
cmd/maya-apiserver/cstor-operator/spc/start_test.go

- PR randomize the poollist to distribute the cstorvolumereplicas.
- Go's concurrency mechanisms don't prevent race conditions, so having a mutex lock here to prevent it 
from race conditions.
Build() fn of all controllers calls AddToScheme to adds all types of this clientset into the given scheme.
If multiple controllers happen to call this AddToScheme same time,
it causes panic with error saying concurrent map access. This lock is used to serialize the AddToScheme call of all controllers.

feat(cvc-controller) randomize usable pools before distributing CVR 

---

GNUmakefile

This PR modifies the `GNUmakefile` to use image name from variable instead of static string.
```
HUB_USER?=openebs
CSTOR_POOL_MGMT_REPO_NAME?=cstor-pool-mgmt
CSTOR_VOLUME_MGMT_REPO_NAME?=cstor-volume-mgmt
M_EXPORTER_REPO_NAME?=m-exporter
ADMISSION_SERVER_REPO_NAME?=admission-server
M_APISERVER_REPO_NAME?=m-apiserver
M_APISERVER_REPO_NAME?=m-apiserver
M_UPGRADE_REPO_NAME?=m-upgrade
```
With this changes, if developer want to create own image then he/she needs to update `HUB_USER` or `*_REPO_NAME` accordingly. No need to retag image for local development on every image-build.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue …

refactor(GNUmakefile) : Use variable for docker image name instead of static name

---

cmd/cstorvolumeclaim/controller.go
cmd/cstorvolumeclaim/cstorvolumeclaim.go
pkg/apis/openebs.io/v1alpha1/cas_keys.go
pkg/apis/openebs.io/v1alpha1/cstor_volume_claim.go

- Update CVC schema struct with `ReplicaCount` type.
- Add StoragePoolClaim (CstorPoolClusterClaim) name in CVC annotations
- Refactor controller to get replicaCount from the
cstorvolumeclaim schema instead of annotations.
1. CStorVolumeClaim
```yaml
kind: CStorVolumeClaim
metadata:
annotations:
openebs.io/config-class: openebs-cstor-sparse-auto
openebs.io/volumeID: pvc-d030e3e4-a700-11e9-b527-42010a800279
creationTimestamp: "2019-07-15T13:02:34Z"
finalizers:
- cvc.openebs.io/finalizer
generation: 3
labels:
openebs.io/storage-pool-claim: cstor-sparse-pool
name: pvc-d030e3e4-a700-11e9-b527-42010a800279
resourceVersion: "5114188"
selfLink: /apis/openebs.io/v1alpha1/namespaces/openebs/cstorvolumeclaims/ …
```

chore(cvc-controller): refactor CVC schema and CVR distribution logic

---

pkg/kubernetes/storageclass/v1alpha1/build.go
tests/csi/cstor/volume/provision_test.go
tests/csi/cstor/volume/suite_test.go

- commit update the changes in storageclass parameters required
for csi BDD tests to run with latest changes.
```
Random Seed: 1563432753
[cstor] [sparse] TEST VOLUME PROVISIONING when cstor pvc with replicacount 1 is created  …
```

 fix(csi,bdd): update csi test with latest changes

---

pkg/install/v1alpha1/cstor_sparse_pool_claim.go
pkg/install/v1alpha1/cstor_sparse_pool_claim_test.go
pkg/install/v1alpha1/env.go
pkg/install/v1alpha1/env_setter.go
pkg/install/v1alpha1/env_setter_test.go
pkg/install/v1alpha1/flags.go
pkg/install/v1alpha1/jiva_pool.go
pkg/install/v1alpha1/localpv_sc.go

Refer: https://github.com/openebs/openebs/issues/2665
The default storage pool and storage classes installed
by openebs-apiserer can't be customized by the user.
While further thoughts have to go into what aspects of
the storage configuration needs to be customized, this
PR allows to disable the creation of the default
storage classes/pools.
The new logic for creation of default config is as follows:
(a) if default config is enabled, create:
- jiva storage pool and jiva default storage class
- local pv storage classes for hostpath and device
(b) if default config is enabled and cstor sparse is enabled:
- create cstor sparse pool claim and its storage class
By default:
- config creation is enabled.
- cstor sparse is disabled
Note that the openebs snapshot promoter storage class
is …

feat(install): add flag to disable default config creation

---

cmd/maya-exporter/app/collector/collector.go
cmd/maya-exporter/app/collector/jiva.go
cmd/maya-exporter/app/collector/metrics.go
pkg/stats/v1alpha1/stats.go

Add client status in exporter metrics, this is useful in identifying
whether a client is connected to jiva target or not.
Depends on: openebs/jiva#233, openebs/gotgt#22
**Checklist:**

cherry-pick(exporter): add jiva target client status (#1340)

---

pkg/install/v1alpha1/openebs_crds.go

This PR adds upgrade task CRD to openebs crds list in pkg/install so that it can also be applied/created during maya installation along with other openebs crds.
**Checklist:**

feat(upgrade): add upgrade task crd to openebs crds list

---

cmd/maya-apiserver/cstor-operator/cspc/operations.go

Two or more consecutive named function parameters share a type,
omit the type from all but the last.

chore(gosimple): fix lint issue.

---

cmd/provisioner-localpv/app/backward_compatability.go
cmd/provisioner-localpv/app/start.go
pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim.go
pkg/blockdeviceclaim/v1alpha1/build.go
pkg/storagepoolclaim/v1alpha1/storagepoolclaim.go
pkg/storagepoolclaim/v1alpha1/upgrade.go
tests/localpv/hostdevice_test.go
tests/localpv/suite_test.go
tests/operations.go

Till 1.0, SPC and its BDCs doesn't have finalizer on them. From 1.1, for the sake of data protection, NDM forces its north-bound users to have finalizer on BDCs.
As part of 1.1 upgrade steps, existing BDCs that are created as part of localpv provisioning need to have localPVFinalizer  SPC.
This PR takes care of adding finalizers when the localpv provisioner starts.
**Checklist:**

feat(upgrade): set finalizers on BDCs related to local PV as 1.1 preupgrade

---

cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
pkg/apis/openebs.io/v1alpha1/cas_pool.go
pkg/apis/openebs.io/v1alpha1/cas_template_keys.go
pkg/install/v1alpha1/cstor_pool.go
pkg/storagepool/storagepool.go

This PR propagate cacheFile value which is set on spc to csp during csp creation.
When user applied below spc yaml
```yaml
metadata:
name: cstor-sparse
spec:
name: cstor-sparse
type: sparse
poolSpec:
cacheFile: /tmp/pool1.cache
maxPools: 1
```
cstor-operator will propagate cache file to csp
```yaml
kind: CStorPool
metadata:
annotations:
openebs.io/csp-lease: '{"holder":"openebs/cstor-sparse-s8ke-7c6f597fc7-kvkbp","leaderTransition":1}'
creationTimestamp: "2019-07-24T06:14:16Z"
generation: 1
labels:
kubernetes.io/hostname: 127.0.0.1
openebs.io/cas-template-name: …
```

fix(cstor-operator, spc): honour cachefile value on spc yaml

---

pkg/cstor/pool/v1alpha3/kubernetes.go
pkg/cstor/volume/v1alpha1/kubernetes.go
pkg/cstor/volumereplica/v1alpha1/kubernetes.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/csp_upgrade.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/cstor_volume_upgrade.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/exec.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/jiva_upgrade.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/spc_upgrade.go

This PR adds to upgrade functions for jiva volumes and cstor pools .
The pool upgrade has both the option of passing csp or spc as input.
**Sample pool upgrade output:**
```
user:maya$ upgrade 1.0.0 1.1.0-RC1 jivaVolume pvc-b32839ee-ade5-11e9-a5a1-42010a800144 openebs
pvc-b32839ee-ade5-11e9-a5a1-42010a800144-rep  patched
pvc-b32839ee-ade5-11e9-a5a1-42010a800144-ctrl  patched
pvc-b32839ee-ade5-11e9-a5a1-42010a800144-ctrl-svc patched
Upgrade Successful for pvc-b32839ee-ade5-11e9-a5a1-42010a800144
user:maya$ upgrade 1.0.0 1.1.0-RC1 cstorPool sparse-claim-auto-tpp2 openebs
patched csp sparse-claim-auto-tpp2
patched csp deployment sparse-claim-auto-tpp2
Upgrade Successful for csp sparse-claim-auto-tpp2 …
```

feat(upgrade): added upgrade files for 1.0.0-1.1.0 jivaVolume, pools and cstorVolume upgrades

---

cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
pkg/apis/openebs.io/v1alpha1/cas_pool.go
pkg/apis/openebs.io/v1alpha1/cas_template_keys.go
pkg/install/v1alpha1/cstor_pool.go
pkg/storagepool/storagepool.go

This PR propagate cacheFile value which is set on spc to csp during csp creation. This is cherry-pick of #1366 
When user applied below spc yaml
```yaml
metadata:
name: cstor-sparse
spec:
name: cstor-sparse
type: sparse
poolSpec:
cacheFile: /tmp/pool1.cache
maxPools: 1
```
cstor-operator will propagate cache file to csp
```yaml
kind: CStorPool
metadata:
annotations:
openebs.io/csp-lease: '{"holder":"openebs/cstor-sparse-s8ke-7c6f597fc7-kvkbp","leaderTransition":1}'
creationTimestamp: "2019-07-24T06:14:16Z"
generation: 1
labels:
kubernetes.io/hostname: 127.0.0.1
openebs.io/cas-template-name: …
```

cherry-pick(cstor-operator, spc): honour cachefile value on spc yaml

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
cmd/cstor-pool-mgmt/controller/pool-controller/handler_test.go
cmd/cstor-pool-mgmt/pool/pool.go
cmd/cstor-pool-mgmt/pool/pool_test.go

cstor-pool-mgmt, currently, imports pool with and without cache file. If both of them fails, it creates the pool based on CSP status.
This PR adds another option for importing pool i.e., dev directory. It gets the devices directory path from the path of one of the deviceIDs in the CSP.
Added unit testcase for a util fn.
TODO: Will add BDD
**Checklist:**

fix(import): importing pools with dev directory option

---

cmd/cstor-pool-mgmt/controller/new-pool-controller/handler.go
cmd/cstor-pool-mgmt/controller/new-pool-controller/new_pool_controller.go
cmd/maya-apiserver/cstor-operator/cspc/handler.go
pkg/algorithm/nodeselect/v1alpha2/build_csp.go
pkg/cstor/newpool/v1alpha3/build.go
pkg/cstor/poolcluster/v1alpha1/buildlist_test.go
pkg/cstor/poolcluster/v1alpha1/cstorpoolcluster.go

This PR does the following:
1. Add CSPC finalizer on CSPC resources.
2. Add CSPC finalizer on CSP resource.
3. Handle finalizer removal for CSPC resource deletion.

fix(cspc,csp): fix pool destroy functionality using finalizers

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
cmd/cstor-pool-mgmt/controller/pool-controller/handler_test.go
cmd/cstor-pool-mgmt/pool/pool.go
cmd/cstor-pool-mgmt/pool/pool_test.go

This PR is cherry-pick of #1372 
cstor-pool-mgmt, currently, imports pool with and without cache file. If both of them fails, it creates the pool based on CSP status.
This PR adds another option for importing pool i.e., dev directory. It gets the devices directory path from the path of one of the deviceIDs in the CSP.
**Checklist:**

[cherry-pick] fix(import): importing pools with dev directory option 

---

.gitlab-ci.yml

- Enable e2e pipelines to run on openshift for v1.0.x branch
**Checklist:**

refactor(gitlab-ci): Add openshift platform to mdap ci for v1.1.x branch

---

cmd/maya-apiserver/cstor-operator/cspc/operations.go

While pool expansion is carried out, the BD(s) are used to expand the pool without creating a corresponding BDC(s).
This PR fixes this issue. For every BD that will be used in pool expansion, a corresponding BDC will be created.
If a BD that is specified on CSPC for pool expansion is already claimed but not have the corresponding CSPC label, the BD will not be used for pool expansion and hence error out gracefully.
If the BD is already claimed and have a CSPC label -- the BD can be used for pool expansion.
**TODO:** Ensure that no two block devices are repeated in a CSPC manifest via validating webhook. 

fix:(cspc,pool expansion): create BDC(s) for BD(s) that are used in expansion

---

tests/csi/cstor/volume/provision_test.go

Changes enhance csi bdd test:
- With busybox app restart which remount the volume again
- Configurable replicaCount using flag `cstor-replicas`
```sh
$ ginkgo -v -- -kubeconfig=/var/run/kubernetes/admin.kubeconfig -cstor-maxpools=1 -cstor-replicas=1
Random Seed: 1563556612
[cstor] [sparse] TEST VOLUME PROVISIONING when cstor pvc with replicacount 1 is created 
should create cstor volume target …
```

chore(csi,bdd): enhance test with app restart and configurable replicaCount

---

cmd/upgrade/executor/cstor_spc.go
cmd/upgrade/executor/cstor_volume.go
cmd/upgrade/executor/env.go
cmd/upgrade/executor/error.go
cmd/upgrade/executor/jiva_volume.go
cmd/upgrade/executor/options.go
cmd/upgrade/executor/setup_job.go

This PR refactors the upgrade binary to make use of COBRA CLI. The upgrades can be performed on jiva volume, cstor spc and cstor volume using the new CLI. 
```
kiran_mova@kmova-dev:1.0.0-1.1.0$ upgrade
An utility to uggrade OpenEBS Storage Pools and Volumes,
run as a Kubernetes Job
Usage:
upgrade [command]
cstor-spc    Upgrade cStor SPC
cstor-volume Upgrade CStor Volume
help         Help about any command
jiva-volume  Upgrade Jiva Volume
```
The upgrades can also be performed using a Kubernetes Job YAML. A sample YAML for upgrading Jiva Volume is as follows:
```
---
apiVersion: batch/v1
kind: Job
metadata:
name: jiva-upg-100111-pvc-713e3bb6-afd2-11e9-8e79-42010a800065
spec:
backoffLimit: 4
template:
spec: …
```

refact(upgrade): refactor the cli for upgrade

---

tests/cstor/pool/reconciliation/reconciliation_test.go
tests/operations.go

This PR enhance existing bdd to check pod creation after restarting cstor pool pod.
Sample out of BDD:
When I create pool pod using ci image i.e openebs/cstor-pool-mgmt:ci.
Upon restart of cstor-sparse-pool pod pool is imported (verifying with zpool guid).
```sh
Running Suite: Test cstor invalid config
========================================
Random Seed: 1564472691
SPC POOL POD DELETION when We apply sparse-striped-auto spc yaml with maxPool count equal to 1on a k8s cluster having at …
```

chore(cstor-pool, bdd): enhace test with pool pod restart

---

pkg/kubernetes/node/v1alpha1/functions.go
pkg/kubernetes/node/v1alpha1/kubernetes.go
pkg/kubernetes/node/v1alpha1/kubernetes_test.go
pkg/templatefuncs/v1alpha1/templatefuncs.go

This commit exposes a go template function to fetch the hostname of a K8s node from the given node name. It also adds a singleton instance of k8s client for node APIs to avoid roundtrips to k8s
API server.
**Checklist:**

cast(hostname): fetch hostname from nodename

---

pkg/install/v1alpha1/jiva_volume.go

Related issue: https://github.com/openebs/openebs/issues/2695
Jiva Replica Deployment uses `nodeAffinity` to ensure that
replica pods are pinned to the nodes where they are initially created.
This is achieved by the following steps during provisioning:
- Launch the ReplicaDeployment without `nodeAffinity` with
required number of replicas.
- Read the `spec.nodeName` from each of the scheduled replica
pods.
- Patch the repplica deployment with `nodeAffinity` by
setting `kubernetes.io/hostname` to be `In` the list
of selected node names.
It has been observed that in some deployments hostname != nodename.
This results in jiva replicas not getting scheduled.
This PR converts the nodename into hostname before patching
with nodeAffinity. The CAS template function to support
this conversion was …

fix(jiva): patch replica deployment with correct hostname

---

cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
pkg/algorithm/nodeselect/v1alpha1/select_node.go
pkg/blockdevice/v1alpha1/blockdevice.go
pkg/storagepoolclaim/v1alpha1/storagepoolclaim.go
tests/cstor/pool/negative/invalid_config_test.go
tests/cstor/pool/negative/provision_without_disk_test.go
tests/cstor/pool/reconciliation/reconciliation_test.go
tests/operations.go

This PR does the following changes
1. Enhances the cstor pool creation test with required validations.
2. Moves DefaultDiskCount count from blockdevice package to storagepoolclaim package.
**Checklist:**

chore(cstor-pool, bdd): enhace cstor pool creation test by adding required validations

---

cmd/maya-apiserver/cstor-operator/cspc/operations.go
cmd/maya-apiserver/cstor-operator/cspc/storagepool_create.go

** Why we need this PR? **
1. While creating a pool deployment `node selector` was not propagated to the pool deployment
due to which there was undesired scheduling of pool pods.
This PR fixes this.
2. While expanding the pool -- the newly added BD(s) needs to be claimed by creating BDC(s). 
Once BDC is created for the associated BD, it can take a little to time for the BD to get `Claimed` 
and hence an error was returned causing the reconciler to complete the expansion in the next 
event.
In most cases -- `k` number of events was needed to add up `k` block devices for expansion 
that is very time-consuming.
This PR fixes this issue by creating BDC(s) first for all the newly added BD(s) on the CSPC and 
then go for expansion. 

fix(cspc,cstor-operator): fix node selector and optimize pool expansion

---

cmd/maya-apiserver/cstor-operator/spc/handler.go
cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
pkg/algorithm/nodeselect/v1alpha1/config.go
pkg/algorithm/nodeselect/v1alpha1/select_node.go
pkg/algorithm/nodeselect/v1alpha1/select_node_test.go
pkg/blockdevice/v1alpha1/blockdevice.go
pkg/install/v1alpha1/flags.go
pkg/storagepoolclaim/v1alpha1/storagepoolclaim.go
pkg/util/util.go
pkg/util/util_test.go

This PR creates required blockdeviceclaims based on spc configurations in auto mode(after the fix).
**Before the fix:**
Before the fix we are selecting blockdevices which are in claimed and unclaimed state and later we are getting the list of blockdevice claims belongs to current spc and giving preference to blockdevices which doesn't have claims this leads to create more bdc than required count.
**After the fix:**
This fix will filter the blockdevices based which are claimed by that spc and bd's which are in unclaimed state and after getting the list of blockdeviceclaims related to spc it honors this bdc list with filtered list and give preference to node which has claims on the node. 
1. BDD …

fix(bdc, cstor-operator): bdc creations in case of auto pool provisioning

---

cmd/cstor-pool-mgmt/pool/v1alpha2/create.go
cmd/cstor-pool-mgmt/pool/v1alpha2/disk_operation.go
pkg/apis/openebs.io/v1alpha1/cstorpool_cluster.go
pkg/cstor/poolcluster/v1alpha1/raidgroups/build.go

This PR removes the name field from raid groups in CSPC as it is and should not be used.

chore(cspc):remove name field from raid group.

---

cmd/cstor-pool-mgmt/controller/cstor-pool-instance/controller.go
cmd/cstor-pool-mgmt/controller/cstor-pool-instance/handler.go
cmd/cstor-pool-mgmt/controller/cstor-pool-instance/runner.go
cmd/cstor-pool-mgmt/controller/cstor-pool-instance/utils.go
cmd/cstor-pool-mgmt/controller/start-controller/controller.go

A new controller for new schema `CStorPoolInstance` has been added to maya. But, the variable names that are used for same are still as 'csp' or 'cstorpool' etc.
This PR is to change the variable/structure/function names in cmd/cstor-pool-mgmt/controller/cstor-pool-instance from csp/CStorPool to cspi/CStorPoolInstance.
This doesn't change any schema related things.
**Checklist:**

chore(naming): change var names from CSP to CSPI

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
cmd/cstor-pool-mgmt/controller/pool-controller/new_pool_controller.go
pkg/apis/openebs.io/v1alpha1/cstor_pool.go

CSP mgmt creates pool if pool import fails. This can cause data loss if disk is not accessible momentarily just at the time of import.
However, pool creation need to be declarative rather than 'if-else' logic which can be design buggy and prone to errors.
This PR looks for Status.Phase as 'Init' or 'PoolCreationFailed' to create the pool. If Status.Phase is any other string, csp mgmt will try to import the pool.
This can cause impact to the current workflow of Ephemeral disks, which works as of now, as NDM can't detect it as different disk and recognizes as previous disk.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR …

fix(csp): create pool if status is Init or PoolCreationFailed

---

tests/artifacts/openebs-ci.go
tests/localpv/hostpath_test.go
tests/localpv/suite_test.go

There have been some requests to allow only installing
the Local PV related components. Refer: https://github.com/openebs/openebs/issues/2706
This PR refactors the Local PV BDDs to check on
local pv and ndm components instead of m-apiserver.
Also, fixed an issue with a test failing to create the
hostpath deployment. labels were missed on the pod spec.
**Checklist:**

refactor(localpv bdd): allow to test when only local pv is installed

---

cmd/cspc-operator/app/start.go
cmd/cspc-operator/app/storagepool_create.go
cmd/cspi-mgmt/app/utils.go
pkg/apis/openebs.io/v1alpha1/cstor_volume.go
pkg/kubernetes/container/v1alpha1/container.go

This PR will do following :
1. Make zpool names same for all pools of a given CSPC.
2. Apart from above, it fixes a minor bug by putting proper image name
for CSPI deployment.
3. It introduces env vars to tune cspc-operator resync interval and images
for cspi-mgmt.

chore(cspc,cspi) : make zpool names same for all pools of a given CSPC

---

cmd/cspc-operator/app/storagepool_create.go
cmd/cstor-pool-mgmt/controller/common/common.go
cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/pool/v1alpha2/utils.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
cmd/cstorvolumeclaim/cstorvolumeclaim.go

Changes will add the env `OPENSBS_IO_POOL_NAME`  to get the `cstorPoolInstance` uid in case of cspc and csi based volumes provisioning.
- Above changes are done taking care with backward compatibilities for
older way of provisioning.
- `OPENSBS_IO_POOL_NAME` env has to be added in case of backup and restore controllers.
```
k get cvr -oyaml
apiVersion: v1
items:
- apiVersion: openebs.io/v1alpha1
kind: CStorVolumeReplica
metadata:
annotations:
cstorpoolinstance.openebs.io/hostname: 127.0.0.1
finalizers:
- cstorvolumereplica.openebs.io/finalizer
generation: 12
labels:
cstorpoolinstance.openebs.io/name: cspc-sparse-xgk5
cstorpoolinstance.openebs.io/uid: bf9024b9-4831-4dd2-b265-80f259c9890f …
```

fix(cvr,cspc,cspi): use Pool env to get the pool instance uid

---

pkg/cstor/poolcluster/v1alpha1/build.go
pkg/cstor/poolcluster/v1alpha1/kubernetes.go
pkg/cstor/poolcluster/v1alpha1/raidgroups/build.go
pkg/cstor/poolinstance/v1alpha3/buildlist.go
pkg/cstor/poolinstance/v1alpha3/kubernetes.go
tests/csi/cstor/volume/provision_test.go
tests/csi/cstor/volume/suite_test.go
tests/operations.go

PR updates the CSI bdd tests for csi based provisioning to use cspc based cstor pools instance.
```sh
Random Seed: 1566897455
[cstor] [sparse] TEST VOLUME PROVISIONING when cstor pvc with replicacount 1 is created 
/home/payes/gocode/src/github.com/openebs/maya/tests/csi/csto …
```

refact(csi,bdd): update csi bdd to use cspc based pool

---

pkg/client/k8s/v1alpha1/resource.go
pkg/client/k8s/v1alpha1/resource_test.go
pkg/install/v1alpha1/installer.go
tests/sanity/sanity_suite_test.go
tests/sanity/sanity_test.go
tests/sts/sts_suite_test.go
tests/sts/sts_test.go

This commit changes maya api server installer to skip updating default SPC as well as default SC resources if they were installed previously by older version(s) of maya or prior to maya api server restart(s).
**Checklist:**

fix(installer): skip re-apply of default SPC and SC resources

---

cmd/upgrade/executor/cstor_spc.go
cmd/upgrade/executor/cstor_volume.go
cmd/upgrade/executor/env.go
cmd/upgrade/executor/jiva_volume.go
cmd/upgrade/executor/options.go
cmd/upgrade/executor/resource.go
cmd/upgrade/executor/setup_job.go
cmd/upgrade/executor/upgradetask.go

This PR adds the switch case required to upgrade from OpenEBS 1.1 to 1.2. 
It also adds a new command to read inputs from `UpgradeTask` CR instead of flags.
**Checklist:**

refact(upgrade): added switch case for 1.2 upgrade and command for upgradetask

---

cmd/provisioner-localpv/app/config.go
cmd/provisioner-localpv/app/provisioner.go
cmd/provisioner-localpv/app/provisioner_blockdevice.go
cmd/provisioner-localpv/app/provisioner_hostpath.go

Refer: https://github.com/openebs/openebs/issues/2695
In some clusters, the node name is not same as the hostname as
described in the above issue. This PR modifies the Local Provisioner
to pick up the hostname from the selected node for provisioning
host path or picking the block devices.
**Checklist:**

feat(localpv): allow provisioning in clusters where nodename != hostname

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
cmd/cstor-pool-mgmt/controller/pool-controller/handler_test.go
cmd/cstor-pool-mgmt/pool/pool.go
cmd/cstor-pool-mgmt/pool/v1alpha2/status.go

fix the status parsing for cstorpoolinstance resource.
```sh
kubectl get cspi -n openebs
NAME               HOSTNAME    ALLOCATED   FREE    CAPACITY   STATUS   AGE
cspc-sparse-2kht   127.0.0.1   281K        9.94G   9.94G      ONLINE   13m
```

fix(cspi): update status parsing and get devicePath ignoring "/dev"

---

cmd/provisioner-localpv/app/config.go
cmd/provisioner-localpv/app/helper_blockdevice.go
cmd/provisioner-localpv/app/helper_hostpath.go
cmd/provisioner-localpv/app/provisioner.go
cmd/provisioner-localpv/app/provisioner_blockdevice.go
cmd/provisioner-localpv/app/provisioner_hostpath.go
pkg/kubernetes/persistentvolume/v1alpha1/persistentvolume.go
pkg/kubernetes/pod/v1alpha1/build.go

For provisioning Local PV, there are several components that work together like:
- provisioner that gets the node resource from Kubernetes
- helper pods that create/delete hostpath on selected node
- PV node affinity.
The provisioner was extracting the host name from the node resource
and passing it as:
- node name to init helper pod and
- hostname to PV node affinity.
Later during deprovision, the hostname was extracted from the PV
and passed as node name to cleanup helper pod.
One fix could have been to extract both node name and hostname and pass them as per the requirement.
To make this happen, during deprovision - the node resource will have to be obtained and node name extracted.
Also, using hostname and nodename for different interactions increases the cost of maintaining the code. …

refact(localpv): change all references from nodeName to nodeHostname

---

pkg/install/v1alpha1/openebs_crds.go

```sh
kubectl get cspi -n openebs
NAME               HOSTNAME    ALLOCATED   FREE    CAPACITY   STATUS   AGE
cspc-sparse-2kht   127.0.0.1   281K        9.94G   9.94G      ONLINE   13m
```

chore(cspi): add custom columns for cspi resource

---

pkg/apis/openebs.io/ndm/v1alpha1/blockdeviceclaim_types.go
pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim.go
pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim_test.go
tests/cstor/pool/negative/provision_without_disk_test.go

This PR read hostname from the new path in blockdeviceclaim.
i.e (cstor-operator read hostname from blockdeviceclaim.spec.BlockDeviceNodeAttributes.HostName instead of blockdeviceclaim.Spec.HostName).
**Checklist:**

fix(cstor-operater): read host Name from new path of blockdeviceclaim

---

cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go
cmd/cstor-pool-mgmt/controller/replica-controller/run_replica_controller.go

Logs of cstor-pool-mgmt container of pool pod currently gives logs in success path of CVR reconciliation at regular intervals as below:
```
I0828 08:10:41.406731       6 event.go:221] Event(v1.ObjectReference{Kind:"CStorVolumeReplica", Namespace:"openebs", Name:"pvc-c1f37dd2-c962-11e9-a264-42010a800105-cspc-disk-pool-5mqc", UID:"06c9315d-c963-11e9-a264-42010a800105", APIVersion:"openebs.io/v1alpha1", ResourceVersion:"34404", FieldPath:""}): type: 'Normal' reason: 'Synced' Resource status sync event
I0828 08:10:41.448198       6 handler.go:129] cvr {openebs/pvc-c1f37dd2-c962-11e9-a264-42010a800105-cspc-disk-pool-5mqc} reconciled successfully with current phase being {Healthy}
I0828 08:10:41.448238       6 run_replica_controller.go:124] workqueue item …
```

chore(logs): remove periodic messages in CVR reconciliation success path

---

tests/cstor/pool/negative/invalid_storageclass_test.go
tests/cstor/pool/negative/suite_test.go

This PR fixes the BDD by fetching target pod using the openebs.io/persistent-volume label.
**Checklist:**

fix(invalid sc, BDD): fix invalid storage class BDD during volume provisioning

---

cmd/cspc-operator/app/storagepool_create.go

```sh
k get deploy cspc-sparse-5f2z -oyaml
apiVersion: apps/v1
kind: Deployment
metadata:
annotations:
deployment.kubernetes.io/revision: "1"
openebs.io/monitoring: pool_exporter_prometheus
creationTimestamp: "2019-08-30T07:58:18Z"
generation: 1
labels:
app: cstor-pool
openebs.io/cstor-pool-cluster: cspc-sparse
openebs.io/cstor-pool-instance: cspc-sparse-5f2z
openebs.io/version: 1.2.0
name: cspc-sparse-5f2z
ownerReferences:
- apiVersion: openebs.io/v1alpha1
blockOwnerDeletion: true
controller: true
kind: CStorPoolInstance
name: cspc-sparse-5f2z
uid: 799d0566-3a61-4312-a221-654ac01be1af
resourceVersion: "5819"
selfLink: …
```

fix(cspc-operator): get cspc name from cspi labels instead of annotaions

---

tests/operations.go

This change is made adhering to the recent commits updating cspi status column.
```
Random Seed: 1567547530
[cstor] [sparse] TEST VOLUME PROVISIONING when cstor pvc with replicacount 1 is created 
/home/payes/gocode/src/github.com/openebs/maya/tests/csi/cstor/volume/provision_test.go:128
STEP: building a …
```

Update cspc status filter in csi BDD tests

---

pkg/install/v1alpha1/jiva_pool.go
pkg/install/v1alpha1/localpv_sc.go

API Server creates a default jiva storage pool and local pv
hostpath storage class - using /var/openebs and /var/openebs/local
as the default hostpath directories to store the jiva replica
and local pv data.
This PR allows users to customize the default path by passing in
a ENV variable to the API Server. In addition, this also allows
user to specify different locations for local pv and jiva or even
provide the flexibility to only custommize what is required or
fallback to the default values.
The following ENV variables need to be documented.
**`OPENEBS_IO_JIVA_POOL_DIR`**
**`OPENEBS_IO_LOCALPV_HOSTPATH_DIR`**
Note: Above ENV should be added to the openebs-operator and
helm charts.
Related Issue: 
- https://github.com/openebs/openebs/issues/2665
- …

feat(jiva,localpv): allow user to customize default hostpaths

---

pkg/install/v1alpha1/jiva_pool.go
pkg/install/v1alpha1/localpv_sc.go

API Server creates a default jiva storage pool and local pv
hostpath storage class - using /var/openebs and /var/openebs/local
as the default hostpath directories to store the jiva replica
and local pv data.
This PR allows users to customize the default path by passing in
a ENV variable to the API Server. In addition, this also allows
user to specify different locations for local pv and jiva or even
provide the flexibility to only custommize what is required or
fallback to the default values.
The following ENV variables need to be documented.
OPENEBS_IO_JIVA_POOL_DIR
OPENEBS_IO_LOCALPV_HOSTPATH_DIR
Note: Above ENV should be added to the openebs-operator and
helm charts.
Related Issue: https://github.com/openebs/openebs/issues/2665
(cherry …

feat(jiva,localpv): allow user to customize default hostpaths (#1433)

---

cmd/upgrade/executor/env.go
cmd/upgrade/executor/resource.go
pkg/apis/openebs.io/upgrade/v1alpha1/upgradetask.go
pkg/kubernetes/job/kubernetes.go
pkg/kubernetes/pod/v1alpha1/kubernetes.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/csp_upgrade.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/cstor_volume_upgrade.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/exec.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/helper.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/jiva_upgrade.go
pkg/upgrade/1.0.0-1.1.0/v1alpha1/spc_upgrade.go

This PR adds the code create or read from the UpgradeTask CR.
If the CR is not present job will create one for the resource. 
It also updates the CR with the current status of the upgrade.
This PR also includes the ability to upgrade multiple resources in one single job.
Sample job yaml will be
```
apiVersion: batch/v1
kind: Job
metadata:
name: jiva-vol-100110-pvc-7904a228-ca69-11e9-9c4f-54e1ad5e8320
spec:
backoffLimit: 4
template:
spec:
containers:
- name:  upgrade
args: 
- "jiva-volume"
- "--from-version=1.0.0"
- "--to-version=1.1.0"
- "--pv-name=pvc-7904a228-ca69-11e9-9c4f-54e1ad5e8320"
- "--v=4"
env:
- name: OPENEBS_NAMESPACE …
```

refact(upgrade): added functionality to create and update the UpgradeTask CR

---

.gitlab-ci.yml

- Migrate the k8s 1.11 and 1.12 cluster version and included k8s 1.14 and 1.15 clusters on packet platform.
**Checklist:**

refactor[gitlab]: Run tests in k8s-1.14 & k8s-1.15 clusters on packet platform

---

cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go
pkg/apis/openebs.io/v1alpha1/cstor_volume_replica.go

Fixes https://github.com/openebs/openebs/issues/2696
`Background:`
cstor-pool-mgmt maintains list of volumes available during import time. In Add handler, if the replica is not part of the list and CVR status is Empty, but, 'zfs list' shows that volume is available, it sets status as 'Duplicate' in CVR.
In Add/Update handler, any CVR with Duplicate status will not be reconciled, and the status will be left at Duplicate if it is set to duplicate once.
This status will NOT cause any problem to IOs because when the pool is imported, all the replicas gets activated. Only problem with this is the 'Status' which is NOT updated.
This situation of setting status as 'Duplicate' might be happening when the pool pods are restarted, pool-mgmt container is talking to a pool in another pod which might …

[2696] fix(cvr): changing Duplicate status as Online on CVR

---

cmd/cspc-operator/app/cspc_lease.go
cmd/cspc-operator/app/handler.go

This PR will enable highly available lease for cspc-operator pod.
Once a cspc-operator pod acquires a lease on CSPC object, only that pod will be able to process and no other pod will be able to process the CSPC with lease.
If in case, the leader ( leader is the pod who has acquired the lease on the CSPC ) has died another pod can acquire CSPC with lease for processing it.

chrore(cspc): enable cspc-operator to take lease for the lifetime on cspc

---

tests/csi/cstor/volume/provision_test.go
tests/csi/cstor/volume/resize_test.go
tests/csi/cstor/volume/target_deployment_reconciliation.go
tests/csi/cstor/volume/utils.go

```
Random Seed: 1568960833
[csi] [cstor] TEST TARGET DEPLOYMENT RECONCILIATION App is deployed and target deployment is deleted 
Should run Target Deployment Reconciliation Test
/home/payes/gocode/src/github.com/openebs/maya/tests/csi/cstor/volume/target_deployment_reconciliation.go:28
STEP: Creating storage class
STEP: …
```

BDD(csi): Add target deployment reconciliation test

---

pkg/cstorvolumeclaim/v1alpha1/build.go
pkg/cstorvolumeclaim/v1alpha1/cstor_volume_claim.go
pkg/cstorvolumeclaim/v1alpha1/kubernetes.go
pkg/cstorvolumeclaim/v1alpha1/utils.go
tests/csi/cstor/volume/pvc_without_app_test.go
tests/csi/cstor/volume/utils.go
tests/operations.go

```
Random Seed: 1569306542
[csi] [cstor] TEST PVC CREATION DELETION WITHOUT APP PVC is created and deleted 
Should run PVC creation and deletion test
/home/payes/gocode/src/github.com/openebs/maya/tests/csi/cstor/volume/pvc_without_app_test.go:28
STEP: Creating storage class
STEP: creating above storageclass
STEP: …
```

bdd(csi): Add tests for pvc deletion without app

---

Gopkg.lock
pkg/client/k8s/k8s.go
pkg/install/v1alpha1/cstor_pool.go
pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go
pkg/k8s/from_yaml.go
pkg/task/meta.go
pkg/task/task.go

The k8s v1.16 release will stop serving the deprecated API versions
in favor of newer and more stable API versions, more info can be found here
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # https://github.com/openebs/openebs/issues/2747
**Checklist:**

chore(installer): add appsv1 deployment apis support in installer

---

cmd/cstorvolumeclaim/controller.go

PR add the cstorvolumeclaim events duing provisioning and raise events in case of any failurs occurs.
```sh
k describe cvc
Name:         pvc-beb54734-c6ec-4e7f-b618-8271a92d6634
Namespace:    openebs
Labels:       openebs.io/cstor-pool-cluster=cspc-sparse
Annotations:  openebs.io/volumeID: pvc-beb54734-c6ec-4e7f-b618-8271a92d6634
API Version:  openebs.io/v1alpha1
Kind:         CStorVolumeClaim
Metadata:
Creation Timestamp:  2019-09-24T15:37:33Z
Finalizers:
cvc.openebs.io/finalizer
Generation:        6
Resource Version:  1501
Self Link:         /apis/openebs.io/v1alpha1/namespaces/openebs/cstorvolumeclaims/pvc-beb54734-c6ec-4e7f-b618-8271a92d6634
UID: …
```

chore(cvc-controller): add provisioning failure events

---

GNUmakefile

Changes:
- The current version of makefile uses the default tag `develop-ci` for `cstor-base` image, but cStor images are pushed with default `ci` tag.

fix(make): Fixing cstor-base tag

---

cmd/cspc-operator/app/storagepool_create.go
pkg/install/v1alpha1/cstor_pool.go

Signed-off-by: Meghna Singh <meghna.singh@mayadata.io>
With this PR the command in livenessProbe in cstorpool yaml will set the value of  `io.openebs:livenesstimestamp` property to current timestamp, whose value earlier was set to $date due to some quoting issue in the command. This PR fixes it.

Fix shell quoting in livenessprobe command in csp yaml

---

Gopkg.lock
cmd/cstorvolumeclaim/controller_base.go
cmd/cstorvolumeclaim/start.go
pkg/kubernetes/leaderelection/leader_election.go
pkg/kubernetes/leaderelection/leader_election_test.go

This commits adds the leader-election API with lease for cvc-controller using built-in Kubernetes leader election APIs.
Leader election, in simple words, is the mechanism that guarantees that only one instance of the cvc-controller — or one instance of the maya-apiserver — is actively making decisions, while all the other
instances are inactive, but ready to take leadership if something happens to the active one.
Note: Tested the changes with 2 replicas of maya-apiserver pod and at the time only 1 pod took the lease and processed the event.
```sh
prateek:maya$ kubectl get pods -n openebs
NAME                                           READY   STATUS …
```

feat(leader-election): add lease API with leader election for cvc-controller

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-volume-mgmt/controller/volume-controller/handler.go
cmd/maya-apiserver/cstor-operator/spc/handler.go

This PR fixes the issue of cstorvolume getting into error state after upgrade. It also includes the refactoring of upgrade code.
**Checklist:**

fix(cv): fixed invalid config in case of cstorvolume upgrade

---

pkg/env/v1alpha1/env.go

The else part is not redundant, so the codeblock is moved out.
- This PR fixes linting issues with maya/pkg/env/v1alpha1/env.go file. It removes redundant else and moves the else block code out.
This PR fixes linting issues issue #2150
**Checklist:**

Issue #2150 | Lint the file maya/pkg/env/v1alpha1/env.go

---

cmd/cspc-operator/app/handler.go
cmd/cstorvolumeclaim/controller.go
cmd/cstorvolumeclaim/cstorvolumeclaim.go
cmd/maya-apiserver/cstor-operator/spc/handler.go
pkg/algorithm/nodeselect/v1alpha2/build_csp.go
pkg/cstor/poolcluster/v1alpha1/build.go
pkg/cstor/poolinstance/v1alpha3/build.go
pkg/cstor/volume/v1alpha1/build.go
pkg/cstor/volumereplica/v1alpha1/build.go
pkg/cstorvolumeclaim/v1alpha1/build.go

changes uses new spec versiondetails and set the current and
desired versions for cstorvolume,cstorvolumereplica, cspc and cstorpool
instances resources in case of csi based volume and pool provisioning.
more info #1448

refact(cv,cvr,cspc,cspi): populate version details for csi based provisioning

---

.golangci.yml
.travis.yml

This PR adds version to the golangci config yaml to fix the golangci-lint internal error.
This PR also bumps the golang version of travis to 1.12.10.
**Checklist:**

fix(golangci-lint): Added version to golangci config file

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-volume-mgmt/controller/volume-controller/handler.go
cmd/cstor-volume-mgmt/volume/volume.go
cmd/cstor-volume-mgmt/volume/volume_test.go
cmd/maya-apiserver/cstor-operator/spc/handler.go
pkg/upgrade/upgrader/csp_upgrade.go
pkg/upgrade/upgrader/cstor_volume_upgrade.go
pkg/upgrade/upgrader/spc_upgrade.go

This PR stops the upgrade code from restarting the target pod while setting the `DesiredReplicationFactor` for older volumes.
This PR also handles the nil `err.Error()` panic.
It also reduce the wait time for verification functions in upgrade-job to make the job faster.
**Checklist:**

fix(upgrade): avoided restart of target pod while upgrade

---

cmd/cspc-operator/app/handler.go

This PR fixes nil object fields access  when an error happens
while populating version details on cspc object
**Checklist:**

fix(cspc operator): fix bug while populating version details on cspc (#1483)

---

cmd/cspc-operator/app/storagepool_create.go

CStor pool pods have stickiness to nodes.
But, if cluster autoscaler decides to scale down the node where pool pod is running, data won't be available to application.
This PR is to let CA NOT to scale down nodes where CSPI related pods are running.
**Checklist:**

feat(CA): safe-to-evict to false to disable scaledown for CSPI pods

---

GNUmakefile
buildscripts/apiserver/Dockerfile.arm64
buildscripts/apiserver/Makefile.mk
buildscripts/build.sh
buildscripts/mayactl/Makefile.mk
buildscripts/provisioner-localpv/Dockerfile.arm64
buildscripts/provisioner-localpv/Makefile.mk

Modularize the Makefile by pushing the mayactl, apiserver targets
to their specific folders in order to make it easier to modify/enhance
and for better readability.
Added the build check for arm64 as well as added Dockerfile for
creating arm64 based apiserver and local provisioner.
The following command can be used to build arm64 images for 
apiserver and local provisioner. 
```
make all.arm64
```
The images will be built on top of `arm64v8/ubuntu:18.04`.
For building with a different base, the following command can be used. 
```
export BASE_DOCKER_IMAGEARM64=arm64v8/ubuntu:16.04;make all.arm64
```
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …

refactor(build): setup arm builds for apiserver and local provisioner

---

cmd/provisioner-localpv/app/start.go

klog flags for levelled verbose logging is added to the flagset.
localpv provisioner extensively uses the levelled verbose logging mechanism of klog. But the flag to specify the log level is missing. It was not added to the cobra command flag set. This PR adds all the associated flags of klog as global flags to the cobra command flag set.
From the user perspective there will be no change. If the user wants to get more verbose logging, the flag can be used along with the command to the container.
**Without klog flags**
```
akhil@MayaData:~/openebs/maya$ bin/provisioner-localpv/provisioner-localpv --help
Manage the Host Path PVs that includes: validating, creating,
deleting and cleanup tasks. Host Path PVs are setup with
node affinity
Usage: …
```

fix(provisioner,localpv,cmd): add klog flags to flag set

---

Gopkg.lock
cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
cmd/cstor-volume-mgmt/controller/volume-controller/handler.go
cmd/cstor-volume-mgmt/controller/volume-controller/new_volume_controller.go
cmd/cstor-volume-mgmt/volume/volume.go
cmd/cstor-volume-mgmt/volume/volume_test.go
pkg/cstor/volume/v1alpha1/cstorvolume.go
pkg/util/fileoperator.go
pkg/util/fileoperator_test.go

This PR adds replica scale down support in the cstor-volume-mgmt(sidecar of cstor-istgt).
**Note:**
1. Only one replica at a time should be removed.
**Pre-requisites:**
1. All the cstorvolume replicas(CVR) should be in a `Healthy` state except the cstorvolume replica that is going to delete(i.e deleting CVR can be in any state).
2. There shouldn't be any ongoing scaleup process(Verify using cstorvolume CR replicationFactor should be equal to the desiredReplicationFactor).
**Steps to execute by the user/operator:**
1. The user will decrease the value of the desired replication factor and remove the replicaID entry from cstorvolume which will under cstorvolume.Spec.ReplicaDeatails by using …

feat(cstor-volume-mgmt): add replica scale down support

---

pkg/webhook/configuration.go

add missing labels in admission webhook related configurations and services

refact(webhook): add missing labels in config,secret and service

---

cmd/cspc-operator/app/storagepool_create.go

Currently the cspi deployment have mount path as `shared-cspi-name` which is different for all cspis for a cspc. This can cause data protection issues as two different lock files exists and two different pods can write on same disk. This PR changes the mount path as `shared-cspc-name` to make it same for all cspis for a given cspc.
**Checklist:**

fix(cspc): replace shared mount path with cspc name

---

cmd/admission-server/main.go

atal out admission server in case of missing ENV's error and configs

refact(webhook): fatal out admission server in case of missing ENV's error

---

cmd/maya-exporter/app/collector/zvol/metrics.go
cmd/maya-exporter/app/collector/zvol/pool_synctime.go
cmd/maya-exporter/app/collector/zvol/pool_synctime_test.go
cmd/maya-exporter/app/command/command.go

The liveness probe sets io.openebs:livenesstimestamp zfs property but in exporter we were fetching openebs.io:livenesstimestamp, due to which the correct timestamp was not set in last_sync_metric. So, this commit fixes the same.
Signed-off-by: Meghna Singh <singhmegna79@gmail.com>

fix(exporter): modify zfs get command

---

cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica_test.go
cmd/upgrade/executor/cstor_spc.go
pkg/apis/openebs.io/v1alpha1/cstor_volume_replica.go

This PR adds the `NewReplicaDegraded` and
`ReconstructingNewReplica` status phase to cStorVolumeReplica(CVR).
Explanation:
**NewReplicaDegraded**: 
CVRStatusNewReplicaDegraded describes replica is recreated (due to pool
recreation[underlying disk got changed]/volume replica scaleup cases) and
just connected to the target. Volume replica has to start reconstructing
data from another available healthy replica. Until volume replica
becomes healthy whatever data written to it is lost(NewReplica also not part
of any quorum decision).
**ReconstructingNewReplica**:
CVRStatusReconstructingNewReplica describes volume replica is recreated
and it started reconstructing entier data from another healthy …

chore(CVR status): add CVR phases based on scenarios

---

pkg/volume/volume_template_engine.go
pkg/volume/volume_template_engine_test.go

Fixed below issues
- volume_template_engine.go:60:42: exported func NewVolumeEngine returns
unexported type *volume.volumeEngine, which can be annoying to use
- volume_template_engine.go:30:6: type name will be used as
volume.VolumeEngine by other packages, and that stutters; consider calling this Engine
Signed-off-by: Sona Praneeth Akula <sonapraneeth.akula@gmail.com>
**Checklist:**

fixed golint issues in volume engine

---

pkg/upgrade/upgrader/exec.go

This PR fixes wrong error reporting in different cases: 
- When upgradeTask CR is not present then it should only return the actual error from the job.
- When the CR is present it checks for backoff limit via env `POD_NAME` which is mentioned when the upgradeTask CR is created before the job is launched. In this case both the actual error and if the backoff limit error should be reported.
**Checklist:**

fix(upgrade): handle errors for upgradeTask CR

---

cmd/admission-server/main.go
pkg/kubernetes/secret/kubernetes.go
pkg/kubernetes/webhook/validate/v1alpha1/kubernetes.go
pkg/webhook/configuration.go

This PR automates the deletion of older admission webhook configurations. It also adds version label to new configs to differentiate between old and new configs.
This will require addition of `list` clusterrole for `validatingwebhookconfig`. 
**Checklist:**

refact(admission): automate deletion of older config

---

pkg/upgrade/templates/v1/cstor_pool.go

This PR updates the livenessprobe command for cstor pools when upgrading to 1.4.0.
**Checklist:**

fix(upgrade): update livenessprobe command for cstor pools

---

pkg/webhook/configuration.go

This change requires in case of helm chart where deployment
name can be changed in automated env's in some cases.
Use admission deployment labels to get the deployment object
to create the OwnerReference to set in created admission
configuration and resources.
cherry-pick #1526 
**Checklist:**

refact(admission): use admission label to get the deployment

---

pkg/webhook/configuration.go

This fixes the issue to deploy openebs admission server
components to deploy in any namespace.

fix(admission): remove hardcoded openebs namespace

---

cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica.go

This PR fixes the following changes:
1. Current code doesn't handle reconciliation logic for volume replica creation
failures. This PR fixes this bug by returning the same status phase of CVR whatever currently held by CVR and during every sync call logic will checks whether volume replica needs to be created or not. If volume replica needs to be created it will trigger the call to create volume replica(Note: Before triggering zfs command it will also check in the pool whether replica already exists or not).
2. This PR also update with volume replica status by triggering `ZFS stats <dataset_name>`
command whenever volume replica created or imported.
**Which issue this PR fixes** *(optional, in …

fix(cStorVolumeReplica): reconciliation logic for volume replica creation failures

---

.gitlab-ci.yml

- Modified the Branch names for packet platform. For a every K8s release we were creating a new branch in gitlab repo and we have to modify the branch name in gitlab ci yaml. To avoid this branch name has been changed as a generic name.
```
k8s-ultimate means last newer release version [1.16]
k8s-penultimate - second last [1.15]
k8s-antepenultimate - Third last [1.14]
```
**Checklist:**

refactor[gitlab-yaml]: Updated the branch name for packet platform

---

cmd/provisioner-localpv/app/env.go
pkg/install/v1alpha1/jiva_volume.go

Helper pods are used to run tasks like:
- cleaning up of jiva files after jiva PV is deleted or
- create or remove host path directories for hostpath Local PV.
A similar helper pod is used by NDM to scrub the block devices
after they have been released. The only addition in case of NDM
helper pod is to have `linux-utils` package on top 
of the alpine linux. As the jiva and hostpath Local PV can also use
the linux utils package, and to reduce the dependency on number
of images to be maintained, changing the default image to be
`openebs/linux-utils`
This PR helps with:
- making sure the same linux-utils image is used across all the components of openebs. 
- set the default help image to use the latest tag, so new version of OpenEBS will automatically get updated with new images. 
- use the …

fix(tools): set default helper pod image to latest

---

cmd/provisioner-localpv/app/env.go
cmd/provisioner-localpv/app/env_test.go
cmd/provisioner-localpv/app/helper_hostpath.go
cmd/provisioner-localpv/app/provisioner_hostpath.go
pkg/kubernetes/pod/v1alpha1/build.go

This PR adds openebs service account to the pods launched by local-pv provisioner. This is because in Openshift / CoreOS clusters, the pods need to be in privileged security context and should use the openebs service account which has a privileged SCC in openshift.

fix(provisioner, localpv): add service account to helper pods

---

cmd/cspc-operator/app/handler.go
cmd/cspc-operator/app/operations.go
cmd/cstor-pool-mgmt/pool/v1alpha2/disk_operation.go
cmd/cstor-pool-mgmt/pool/v1alpha2/modify.go
cmd/cstor-pool-mgmt/pool/v1alpha2/pool_utils.go
cmd/cstor-pool-mgmt/pool/v1alpha2/pool_utils_test.go
cmd/maya-apiserver/cstor-operator/spc/handler.go
pkg/apis/openebs.io/v1alpha1/cas_pool.go
pkg/apis/openebs.io/zpool/v1alpha1/pool_topology.go
pkg/apis/openebs.io/zpool/v1alpha1/pool_topology_test.go
pkg/blockdevice/v1alpha2/kubernetes.go
pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim.go
pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim_test.go
pkg/blockdeviceclaim/v1alpha1/kubernetes.go
pkg/env/v1alpha1/env.go
tests/localpv/hostdevice_test.go

This PR adds a feature to support disk replacement in CSPI-Mgmt. CSPI-Mgmt
does in the following way
1. Verifies whether the modified device is already in use by the pool. If yes mgmt
will return without triggering any zpool commands. If not in use by pool
then mgmt will trigger `zpool <replace pool_name> <old_path> <new_path>`
2. After initiating the replacement process CSPI-Mgmt will look for resilvering
process. On successful completion of resilvering cspi-mgmt will unclaim
old block device and remove the `openebs.io/bd-predecessor` annotation from the new block device claim.
**Design PR for disk replacement**
In openebs: https://github.com/openebs/openebs/pull/2846
**This PR touches below production code:**
1. While getting the zpool dump output …

feat(disk-replacement, cspi): add disk replacement support in cspi mgmt

---

cmd/cspc-operator/app/operations.go
pkg/apis/openebs.io/v1alpha1/cstor_pool_instance.go

This PR adds support to replace the block device in cspc operator. cspc operator
will replace block device in the corresponding raid group in the appropriate node 
CSPI. CSPC Operator will replace the raid group in CSPI only if **one block device** is
replaced by the user in a raid group.
**Steps need to be performed by the user to trigger block device replacement**
Below is the current CSPC
```yaml
kind: CStorPoolCluster
metadata:
name: cstor-pool-mirror
spec:
pools:
- nodeSelector:
kubernetes.io/hostname: kubernetes-node1
raidGroups:
- type: mirror
isWriteCache: false
isSpare: false
isReadCache: false
blockDevices:
- blockDeviceName: node1-bd-1
- …
```

feat(disk replacement, cspc): add feat to support disk replacement in CSPC Operator

---

pkg/apis/openebs.io/v1alpha1/cas_keys.go
pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim.go
pkg/webhook/bd_replacement.go
pkg/webhook/bd_replacement_test.go
pkg/webhook/cspc.go

This PR adds validation of CSPC for block device replacement operation.
**NOTES:** This PR does not contain capacity validation for block device replacement. This will be raised in a subsequent PR.

feat(blockdevice_replacment): add validation webhook for blockdevice replacement

---

cmd/provisioner-localpv/app/helper_blockdevice.go
cmd/provisioner-localpv/app/provisioner.go
cmd/provisioner-localpv/app/provisioner_blockdevice.go
pkg/blockdeviceclaim/v1alpha1/build.go
pkg/kubernetes/container/v1alpha1/container.go
pkg/kubernetes/persistentvolumeclaim/v1alpha1/build.go
tests/localpv/hostdevice_test.go

- Added Raw Block Volume Support for LocalPV
- To use this the PVC spec.volumeMode should be set to Block. For eg:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: my-pvc
spec:
accessModes:
- ReadWriteOnce
volumeMode: Block
storageClassName: openebs-device
resources:
requests:
storage: 10Gi
```
- In return the PV would look like:
```
apiVersion: v1
kind: PersistentVolume
metadata:
annotations:
local.openebs.io/blockdeviceclaim: bdc-pvc-aeb55a2e-11d9-11ea-adb6-42010a800fc1
pv.kubernetes.io/provisioned-by: openebs.io/local
creationTimestamp: "2019-11-28T12:22:15Z"
finalizers:
- kubernetes.io/pv-protection
labels:
openebs.io/cas-type: local-device
name: pvc-aeb55a2e-11d9-11ea-adb6-42010a800fc1
resourceVersion: "2622843"
selfLink: …
```

[Feat.]Raw Block Volume Support for LocalPV

---

pkg/webhook/bd_replacement.go

This PR fixes the validation bug for block device replacement.
Context : 
While replacing a block device in a pool config( node level ) at an index higher than 1 in CSPC YAML -- BD validation was not working. The reason was that the newer cspc pool config was not picked for validation and hence the pool config validation was missed.

chore(bd_replalcment): fix bd replacement validation bug

---

pkg/install/v1alpha1/cstor_pool.go

This PR fixes the liveness probe on cstor-pool container by adding `timeout` setting for command execution(run a command with a time limit). `timeout` will be helpful in a case when the disks are detached from the node and when liveness triggers command(zfs set... command) it will be hung forever and kubelet will not treat them as a failures. Kubelet also retries execute the same command after `timeoutSeconds` mentioned in the liveness probe. By triggering `timeout 30 zfs set io.openebs:livenesstimestamp="$(date +%s)" cstor-<pool_name>` will kill the process if it exceeds more than 30 seconds and returns non-zero exit status.
**Note:**
1. When the disks are detached from the node cStor pool …

fix(cstor-pool-mgmt): fix livenessprobe in cStor pool deployment

---

pkg/upgrade/templates/v1/cstor_pool.go

This PR appends `timeout 120` to the command and `cluster-autoscaler.kubernetes.io/safe-to-evict: "false"` to the annotations in the cstor pool deployment. 
Refer : https://github.com/openebs/maya/pull/1544 https://github.com/openebs/maya/pull/1546
**Checklist:**

refact(upgrade): updated cstor pool deployment template

---

cmd/cspc-operator/app/storagepool_create.go
pkg/install/v1alpha1/cstor_pool.go

- add 120 seconds cmd timeout value for zfs command which will
kill the cmd process if it exceeds more than 120 seconds and
returns non-zero exit status.
- Change Probe timeout seconds to 150 seconds.
- Change PeriodSeconds interval to 60 seconds
- add safe-to-evict to false to disable scaledown for CSP pods refer https://github.com/openebs/maya/pull/1481
```yaml
k get pods cspc-sparse-jbhs-666bcf6788-thtgf -oyaml
apiVersion: v1
kind: Pod
metadata:
annotations:
cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
openebs.io/monitoring: pool_exporter_prometheus
prometheus.io/path: /metrics
prometheus.io/port: "9500"
prometheus.io/scrape: "true"
creationTimestamp: "2019-12-11T10:02:06Z"
generateName: cspc-sparse-jbhs-666bcf6788-
labels:
app: …
```

fix(cspi): add timeout seconds in zfs cmd used for liveness probe and safe-evict annotation on CSP

---

cmd/cspc-operator/app/storagepool_create.go
pkg/install/v1alpha1/cstor_pool.go

cherry-pick #1546 
- add 120 seconds cmd timeout value for zfs command which will
kill the cmd process if it exceeds more than 120 seconds and
returns non-zero exit status.
- Change Probe timeout seconds to 150 seconds.
- Change PeriodSeconds interval to 60 seconds.
- add safe-to-evict to false to disable scaledown for CSP pods

fix(cspi): add timeout seconds in zfs cmd used for liveness probe (#1546)

---

pkg/install/v1alpha1/cstor_pool.go

This PR fixes the liveness probe on cstor-pool container by adding `timeout` setting for command execution(run a command with a time limit). `timeout` will be helpful in a case when the disks are detached from the node and when liveness triggers command(zfs set... command) it will be hung forever and kubelet will not treat them as a failures. 
Kubelet also retries execute the same command after timeoutSeconds mentioned in the liveness probe. By triggering timeout 120 zfs set io.openebs:livenesstimestamp="$(date +%s)" cstor-<pool_name> will kill the process if it exceeds more than 120 seconds and returns non-zero exit status.
cherry-pick #1544

fix(cstor-pool-mgmt): fix livenessprobe in cStor pool deployment (#1544)

---

pkg/upgrade/templates/v1/cstor_pool.go

- This PR appends `timeout 120` to the command in the cstor pool deployment
- added annotation to pool delpoyment template to disable eviction by auto scaler
cherry-pick #1545 

refact(upgrade): updated cstor pool deployment template (#1545)

---

pkg/install/v1alpha1/jiva_volume.go

The default helper pod image used for cleaning data
after jiva PVs are deleted is hardcoded. The only way
to override is to provide via StorageClass SrubImage.
For supporting arm use cases or any custom image
repositories, all the jiva classes need to include
the above attribute.
This PR helps to pass the default image via the
env `OPENEBS_IO_HELPER_IMAGE`, similar to how it is
passed to Local Provisioner.
Refer:
https://github.com/openebs/openebs/issues/1295#issuecomment-562643605
**Checklist:**

feat(jiva): allow passing cleanup helper pod image as env

---

pkg/upgrade/upgrader/helper.go
pkg/upgrade/upgrader/helper_test.go

This PR fixes the `getBaseImage` function which only expected only one `:` to be present before the image tag. There can be cases where proxy image url can have more than one `:`. 
Refer: https://github.com/openebs/openebs/issues/2857
**Checklist:**

fix(upgrade): add support for images having more than one ":"

---

GNUmakefile
buildscripts/cstor-pool-mgmt-debug/Dockerfile
buildscripts/cstor-pool-mgmt-debug/entrypoint.sh
cmd/cstor-pool-mgmt/controller/pool-controller/run_pool_controller.go
cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
pkg/debug/debug.go
pkg/debug/release.go
pkg/debug/types.go
pkg/kubernetes/service/v1alpha1/build.go
tests/cstor/volume/provision_bulk_test.go
tests/cstor/volume/provision_negative_test.go
tests/cstor/volume/provision_test.go
tests/cstor/volume/suite_test.go
tests/operations.go

This PR does the following changes
1. This PR provides the capability to get debug build for the cstor-pool-mgmt.
2. Debug build has an injection server running on port 8080 on all the cstor-pool-mgmgt
which can be used to inject the errors for CR's and ZFS operations for negative path testing.
**Test Process Covered In BDD:**
- Inject ZFS Creation error and CVR updated Error by selecting one random Pool(volume dataset won't be created and CVR update will not be done).
- Eject the ZFS Creation error and check whether the dataset is created or not.
- Eject the CVR update Error and check the CVR status it should be `Healthy`.
**To Run Positive Volume Provisioning BDD:**
1. Navigate to …

chore(cStorVolume_bdd): add negative test cases for cStorVolumeProvisioning

---

cmd/cspc-operator/app/storagepool_create.go
pkg/algorithm/nodeselect/v1alpha2/build_csp.go
pkg/apis/openebs.io/v1alpha1/cstorpool_cluster.go
pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
pkg/kubernetes/podtemplatespec/v1alpha1/podtemplatespec.go

This PR adds the capability to pass tolerations via CSPC to the pool pods.
Following is an example CSPC YAML to pass tolerations: 
```yaml
kind: CStorPoolCluster
metadata:
name: cspc-mirror
spec:
tolerations:
- key: "key"
operator: "Equal"
value: "value"
effect: "NoSchedule"
pools:
- nodeSelector:
kubernetes.io/hostname: "gke-cstor-demo-default-pool-3385ab41-1r1n"
raidGroups:
- type: "mirror"
isWriteCache: false
isSpare: false
isReadCache: false
blockDevices:
- blockDeviceName: "blockdevice-6380099a0365d2ebe45d4eb03e7a48df"
- blockDeviceName: "blockdevice-c44d3872abc609182a80f74b66d23202"
poolConfig:
tolerations:
- key: "key1"
operator: "Equal"
value: "value1"
effect: "NoSchedule"
- nodeSelector:
kubernetes.io/hostname: …
```

feat(cspc): add capability to pass tolerations to pool pods via cspc

---

cmd/cstor-pool-mgmt/controller/backup-controller/handler.go
cmd/cstor-pool-mgmt/controller/backup-controller/new_backup_controller.go
cmd/cstor-pool-mgmt/controller/backup-controller/run_backup_controller.go
cmd/cstor-pool-mgmt/controller/restore/handler.go
cmd/cstor-pool-mgmt/controller/restore/new_restore_controller.go
cmd/cstor-pool-mgmt/controller/restore/run_restore_controller.go

Changes:
- Added level base logging to cstor backup/restore the controller to reduce frequent logging during update event
**Checklist:**

chore(cstor-backup): Removing frequent logging from cstor backup/restore controller

---

cmd/cspc-operator/app/storagepool_create.go
pkg/algorithm/nodeselect/v1alpha2/build_csp.go
pkg/apis/openebs.io/v1alpha1/cstorpool_cluster.go
pkg/kubernetes/podtemplatespec/v1alpha1/podtemplatespec.go

This PR adds support to pass priority class to the pool pod.
Following is an example CSPC to pass pod priority class name to the pool pods : 
```yaml
kind: CStorPoolCluster
metadata:
name: cspc-mirror
spec:
priorityClassName: high-priority 
pools:
- nodeSelector:
kubernetes.io/hostname: "gke-cstor-demo-default-pool-3385ab41-pjc2"
raidGroups:
- type: "mirror"
isWriteCache: false
isSpare: false
isReadCache: false
blockDevices:
- blockDeviceName: "sparse-10236852f152126baf87c56f6e853805"
- blockDeviceName: "sparse-ac1a50c4185f55cdfffed3a3c0d4a7b1"
- nodeSelector:
kubernetes.io/hostname: "gke-cstor-demo-default-pool-3385ab41-w1ht"
raidGroups:
- type: "mirror"
isWriteCache: false
isSpare: false
isReadCache: false
blockDevices:
- …
```

feat(cspc): add support to pass priority class to the pool pods

---

GNUmakefile
buildscripts/apiserver/Makefile.mk
buildscripts/cspi-mgmt/Makefile.mk
buildscripts/cstor-pool-mgmt/Makefile.mk
buildscripts/cstor-volume-mgmt/Dockerfile.arm64
buildscripts/cstor-volume-mgmt/Makefile.mk
buildscripts/exporter/Makefile.mk
buildscripts/provisioner-localpv/Makefile.mk

, maya-exporter and cspi-mgmt
Relate: https://github.com/openebs/openebs/issues/1295
- move cstor-pool-mgmt, cstor-volume-mgmt, maya-exporter and cspi-mgmt build
scripts to their specific folders and add arm build scripts
- add Dockerfile for createing arm64 based cstor-volume-mgmt
Signed-off-by: wangzihao <wangzihao18@huawei.com>
**Checklist:**

refactor(build): setup arm builds for cstor-pool-mgmt, cstor-volume-mgmt

---

cmd/cspc-operator/app/storagepool_create.go
pkg/algorithm/nodeselect/v1alpha2/build_csp.go
pkg/apis/openebs.io/v1alpha1/cstor_pool_instance.go
pkg/apis/openebs.io/v1alpha1/cstorpool_cluster.go
pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
pkg/cstor/poolinstance/v1alpha3/build.go

This PR will add schema to pass auxResource limit to cStor pool pod side car containers via poolConfig.
The DefaultAuxResource is set if auxResource is not present in the poolConfig for the particular pool.
```yaml
kind: CStorPoolCluster
metadata:
name: sparse-claim-auto
spec:
resources:
requests:
memory: "64Mi"
cpu: "250m"
limits:
memory: "128Mi"
cpu: "500m"
pools:
- nodeSelector:
kubernetes.io/hostname: 127.0.0.1
poolConfig:
cacheFile: /tmp/sparse-claim-auto.cache
compression: ""
defaultRaidGroupType: mirror
overProvisioning: false
auxResources:
requests:
memory: "50Mi"
cpu: "400m"
limits:
memory: "100Mi"
cpu: "400m"
raidGroups:
- blockDevices:
- …
```

refact(cspc): add schema for auxResource in poolConfig

---

cmd/provisioner-localpv/app/provisioner_hostpath.go

while creating cleanup pod for openebs-hostpath, service account name needs to be given. #1542  added service account only to init pod. This will add the service account to cleanup pod also.
Continuation of #1542

fix(provisioner,localpv): add SA while creating cleanup pod

---

pkg/upgrade/upgrader/jiva_upgrade.go

This PR removes the pod exec from the jiva volume upgrade verification step to avoid failure of jobs when `pods/exec` permission is not provided or `DenyEscalatingExec` is used to configure the cluster.
**Checklist:**

refact(upgrade): remove pod exec from jiva volume verification

---

cmd/cstor-pool-mgmt/pool/v1alpha2/modify.go
cmd/cstor-pool-mgmt/pool/v1alpha2/pool_utils.go
pkg/algorithm/nodeselect/v1alpha2/build_csp.go
pkg/algorithm/nodeselect/v1alpha2/select_node.go
pkg/apis/openebs.io/v1alpha1/cas_pool.go
pkg/blockdevice/v1alpha2/blockdevice.go
pkg/blockdevice/v1alpha2/blockdevice_test.go
pkg/webhook/bd_replacement.go
pkg/webhook/bd_replacement_test.go
pkg/webhook/cspc.go
pkg/webhook/cspc_test.go

This PR adds general validation in the admission server to validate CSPC.
**Below are the validations added to admission server:**
1. Adds validation to verify the duplicate block devices in CSPC.
2. Adds validation to verify the duplicate nodes in CSPC.
3. Adds validation to verify block devices mentioned on pool spec should belong to the same node where node selector is pointing.
4. Adds validation to verify block device should not be claimed by other CSPC/third party.
5. Adds validation to verify Raid Group or Block Device alone shouldn’t be removed.
6. Adds validation to verify block device should not have a fstype and it should be active. 
7. Adds validation to verify the capacity of replacing block device(Changes will be adopted only if …

chore(cspc, validation webhook): add a support for CSPC general validation in admission server

---

GNUmakefile
cmd/cstor-pool-mgmt/controller/common/common_test.go
cmd/cstor-pool-mgmt/controller/replica-controller/run_replica_controller_test.go
cmd/cstor-pool-mgmt/pool/pool.go
cmd/cstor-pool-mgmt/pool/pool_test.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica_test.go
pkg/util/exec-run.go

This PR logs the stdout of the triggered command parallelly before
completion of command execution(added only during import command).
This will help during debug time(Mainly when command hung
after some progress).
Sample output:
```logs
I0103 10:40:47.636925       6 exec-run.go:78] ============= Before Logging ==============
2020-01-03/10:40:47.655 Verifying pool existence on the device /var/openebs/sparse/0-ndm-sparse.img
2020-01-03/10:40:47.656 Verifying pool existence on the device /var/openebs/sparse/2-ndm-sparse.img
2020-01-03/10:40:47.657 Skipping /var/openebs/sparse/0-ndm-sparse.img device due to no labels on device
2020-01-03/10:40:47.657 Verifying pool existence on the device …
```

chore(cstor-pool-mgmt): add logs during pool import

---

cmd/provisioner-localpv/app/config.go
cmd/provisioner-localpv/app/helper_hostpath.go
cmd/provisioner-localpv/app/provisioner_hostpath.go
pkg/kubernetes/pod/v1alpha1/build.go

- This PR is fixing the deploying of the helperPod used by localPV-provisioner (`openebs-hostpath`), when the nodes are tainted, by adding the respective tolerations to the pod.
- With reference to PR: https://github.com/openebs/openebs/issues/2860
- In this PR, I have added a more struct of `corev1.Tolerations`, in helperPod Config.
- Added a struct of `corev1.Taints` in the node related details.
- Added helper to get the appropriate details.
- For testing purposes, added taints to the nodes, on which the PV was claimed, then commented out the exit for …

feat(localpv-hostpath): support provisioning on nodes with taints

---

cmd/provisioner-localpv/app/config.go
cmd/provisioner-localpv/app/helper_hostpath.go
cmd/provisioner-localpv/app/provisioner_hostpath.go
pkg/kubernetes/pod/v1alpha1/build.go

Provisioning Local PV with hostpath requires launching of helper pods to create or delete the PV directory. This feature support launching helper pods on nodes that have taints. 
The provisioner will get the taints applied on the node and apply them as tolerations to the helper pods. 
Refer: openebs/openebs#2860
This commit does the following:
- Adds - Taints information to the podOpts
- Extends the Pod Builder with a new method that will convert taints to tolerations
- A node object is passed to the PV creation, so taints are easily extracted. 
- During PV deletion, fetch the node object from hostname - used during delete of the volume
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>
**Which issue this PR fixes** *(optional, in `fixes …

feat(localpv-hostpath): support provisioning on nodes with taints (#1560)

---

pkg/install/v1alpha1/cstor_pool.go
pkg/install/v1alpha1/cstor_volume.go

This PR mounts the `/var/openebs` of the container into  OPENEBS_IO_BASE_DIR/<cstor_target/pool>/<resource_name> on the host path.
These changes are made to persist core files on the host path.
**How Users Can Configure**
Users can specify the value of OPENEBS_IO_BASE_DIR in Maya deployment.
While creating cStor pool/volume corresponding component will read the ENV value
and use base_dir for mounting. If ENV doesn't exist base_dir will mount `/var/openebs`.
Below are PR's to support dumping core in /var/openebs/core inside a container:
cStor: https://github.com/openebs/cstor/pull/284
istgt: https://github.com/openebs/istgt/pull/298
**Which issue this PR fixes** *(optional, in `fixes #<issue …

fix(cStor, deployments): add OpenEBS base directory in deployments

---

pkg/algorithm/cstorpoolselect/v1alpha1/select.go
pkg/algorithm/cstorpoolselect/v1alpha1/select_test.go
pkg/apis/openebs.io/v1alpha1/cas_keys.go
pkg/cstor/pool/v1alpha2/cstorpool.go
pkg/cstor/pool/v1alpha2/cstorpool_test.go
pkg/install/v1alpha1/cstor_volume.go
pkg/storagepoolclaim/v1alpha1/storagepoolclaim.go

This PR adds a feature to limit the over-provisioning of a CStor volume on SPC pools and hence fixes the issue https://github.com/openebs/openebs/issues/2855 for cStor volume provisioned on SPC.
A similar feature for CSPC would be introduced in upcoming PRs.
Refer to following doc for solution approach: 
https://docs.google.com/document/d/1JFsrZsOiV9GLG4IJ6mDrbNf5flvS1BKExCzI8J3hX2I/edit
Example : 
```yaml
metadata:
name: disk-claim-auto
spec:
name: disk-claim-auto
type: disk
maxPools: 3
minPools: 3
poolSpec:
cacheFile: /tmp/disk-claim-auto.cache
overProvisioning: false
```
All the pools created under above SPC YAML will obey the over provisioning policy ( i.e. disabled).
Consider an example, if a CStor volume is …

feat(spc): add feature to limit overprovisioning of cstor volumes

---

pkg/install/v1alpha1/cstor_pool.go
pkg/install/v1alpha1/cstor_volume.go

This PR updates the mountPath from `/var/openebs to /var/openebs/<container_name>` inside the cStor containers.
These changes are required to have clean directories on the host machine.
**Checklist:**

fix(cStor, deployments): update mount paths in cStor deployments

---

pkg/install/v1alpha1/cstor_volume.go

This commit fixes a bug that was not allowing the clone volumes to
get created if overprovisioning was disabled.
Details  : 
In the case of clone volumes, the capacity of CSP was not being passed which caused the overprovisioning policy to error out due to empty capacity.
Now clone volume will be created on the specific pools only where the source volume exists.
To fix this, an entire map of CSP capacity vs uid is passed via runtask and the capacity for the specific CSP where clone volume needs to come is picked from the map to decide on overprovisioning requirements.
Signed-off-by: Ashutosh Kumar <ashutosh.kumar@mayadata.io>

fix(overprovisioning): fix overprovisioning bug in case of clone volume

---

cmd/cspc-operator/app/cleanup.go
cmd/cspc-operator/app/handler.go
cmd/cspi-mgmt/app/handler.go
pkg/algorithm/nodeselect/v1alpha2/build_csp.go
pkg/cstor/poolcluster/v1alpha1/cstorpoolcluster.go
tests/cstor/cspc/provisioning/cspc_provisioning_utils_test.go
tests/cstor/cspc/provisioning/provisioning_test.go
tests/operations.go

When a cspi is deleted or the cspc is scaled down by removing a poolSpec the bdcs for the cspi are not cleaned up. This results in stale resource and unwanted claims on bd which can be used by other resources. This PR adds the cleanup of bdcs in such cases.
Sample BDD output:
```sh
mayadata:provisioning$ ginkgo --focus=STRIPE  -v -- -kubeconfig=/var/run/kubernetes/admin.kubeconfig 
Running Suite: Test cstor invalid config
========================================
Random Seed: 1579607994
Will run 20 of 38 specs …
```

fix(cspc): cleanup bdcs after deletion or scaledown of cspi

---

cmd/cstor-pool-mgmt/pool/pool.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
tests/admission/admission_test.go
tests/csi/cstor/volume/utils.go
tests/cstor/clone/clone_test.go
tests/cstor/node-selector/volume_selector_test.go
tests/cstor/pool/negative/provision_without_pool.go
tests/cstor/snapshot/snapshot_test.go
tests/cstor/volume/provision_negative_test.go
tests/cstor/volume/provision_test.go
tests/cstor/volume/replica_replace/replica_replace_test.go
tests/cstor/volume/replica_replace/replica_replace_utils_test.go
tests/cstor/volume/scaleup_replica/scaleup_replica_test.go
tests/operations.go

Changes:
- When dataset or pool doesn't exist on zfs, cvr/csp controller should return success in case of dataset/pool deletion.
**Checklist:**

fix(pool-mgmt): Removing stale CVR/CSP when dataset/pool does not exist

---

.gitlab-ci.yml

- Commented the curl request to trigger pipeline in packet for PR merges as we were going to triggering pipelines to schedule a time with ci tag.
- Konvoy pipelines has been triggered for stable release tags instead of the every PR merges.

refactor(gitlab-yaml): Removed the request to trigger pipeline in packet

---

pkg/kubernetes/secret/kubernetes.go
pkg/kubernetes/service/v1alpha1/kubernetes.go
pkg/kubernetes/webhook/validate/v1alpha1/kubernetes.go
pkg/webhook/configuration.go
pkg/webhook/cspc.go

This PR adds validation for cspc deletion. When a volume is still present on the cspc pool the deletion of cspc should not be allowed.
```sh
mayadata:setup$ k delete cspc --all
Error from server (BadRequest): admission webhook "admission-webhook.openebs.io" denied the request: invalid cspc sparse-pool-1 deletion: volume still exists on pool sparse-pool-1-ff87
```
This PR also fixes the pre-upgrade cleanup or update of webhook secret, service, and validator.
**Checklist:**

fix(cspc, webhook): add validation for cspc deletion

---

Gopkg.lock
cmd/cspc-operator/app/storagepool_create.go
cmd/cvc-operator/controller/cstorvolumeclaim.go
cmd/cvc-operator/controller/cvc_controller.go
cmd/cvc-operator/controller/start.go
pkg/apis/openebs.io/v1alpha1/cas_keys.go
pkg/apis/openebs.io/v1alpha1/cas_pool.go
pkg/apis/openebs.io/v1alpha1/cstor_volume_claim.go
pkg/cstor/volumereplica/v1alpha1/utils.go
pkg/cstorvolumeclaim/v1alpha1/utils.go
pkg/hash/hash_test.go
pkg/kubernetes/poddisruptionbudget/kubernetes.go
pkg/kubernetes/poddisruptionbudget/poddisruptionbudget.go

This PR adds support to create PodDisruptionBudget only for cStor Pool pods
which contains HA volume replicas(volume provisioned with >= 3 replicas) in cStor pools.
Valid voluntary disruptions will be disallowed on cStor pool pods if eviction of cStor pool pod affects the volume quorum factor.
- Draining a node for repair or upgrade.
- Draining a node from a cluster to scale the cluster down.
**Example for PDB creation:**
Provisioned a CSPC with five pool specs that intern creates 5 cStor pools. Now hundreds of HA volumes are provisioned with 3 replicas and volume replicas can be scheduled in any random order across CSPC cStor pools, no.of PDBs’ will be combination among the cStor pools. In …

feat(PDB, cStor Pools): add a support to create PDB for cStor

---

pkg/algorithm/cstorpoolselect/v1alpha1/select.go
pkg/apis/openebs.io/v1alpha1/cstor_pool.go

Following PR added support to restrict overprovisioning of volumes on a cStor pool. Please go through the following links to understand more.
https://github.com/openebs/maya/pull/1577
https://github.com/openebs/openebs/issues/2855
SPC has a field `overProvisioning` that was never used and the PR made use of that to decide on overprovisioning requirements.
Now every existing SPC might have SPC created with missing `overProvisioning` field(the missing field will have by default a false value as the field is of bool type) or value set to false.
Now, there can be failure in subsequent volume provisioning if a user intends to over-provision -- to fix this one would need to edit SPC yaml to turn `overProvisioning` to true.
This PR introduces a new field `thickProvisoning` to decide on …

chore(spc):introduce new field to control overprovisioning

---

pkg/webhook/cspc.go

This PR fixes the bug in the admission server whether claimed block device claimed by other CSPC/third parties. 
**Actual bug:**
Getting CSPC name from the annotation of blockdeviceclaim. Actually CSPC name should be fetched from blockdeviceclaim labels.
**How Bug is skipped:**
Used wrapf without any errors so it returns nil (https://github.com/pkg/errors/blob/614d223910a179a466c1767a985424175c39b465/errors.go#L202)
**Checklist:**

fix(validation): fix a bug in CSPC general validations

---

pkg/install/v1alpha1/cstor_pool.go

This PR mounts sock file on emptyDir.
When the cStor pool pod is deleted then another pool pod will try come into running state(which will be bought up by deployment controller) at this time old pod will be in terminating state and another pod will be container creating state at this time cStor-pool-mgmt will talks to cStor-pool container of old pod via sock file since it is persisted on the host path.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #https://github.com/openebs/openebs/issues/2696
**Checklist:**

fix(sockfile): mount sockfile on emtyDir

---

cmd/cspc-operator/app/storagepool_create.go
cmd/cvc-operator/controller/cstorvolumedeployment.go
pkg/env/v1alpha1/env.go
pkg/install/v1alpha1/cstor_volume.go

This PR is a continuation of PR: https://github.com/openebs/maya/pull/1583 and new deployments strictly follow to store component related files in one path of the host machine and that path called OPENEBS_IO_BASE_DIR.
**How Users Can Configure:**
If users need to configure base directory he has to set on OPENEBS_IO_BASE_DIR Env in cspc-operator & CVC-operator.
What files stored in the host machine:
- When CSPC is deployed pool pod will generate lock file, sock file, core files, and pool cache file inside the container and the container path is mounted on  **BASE_DIR/cstor-pool/<cspc_name>** host path.
- When cStor volume is deployed target pod will store core files inside the container and the …

fix(new cStor deployments): add OpenEBS base directory in new CStor deployments

---

pkg/install/v1alpha1/jiva_volume.go

This commit fix the issue where scrub jobs were failing on openshift platform
or where non previleged pods are not allowed to access/modify hostpath.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # https://github.com/openebs/openebs/issues/2893
none
**Checklist:**

fix(jiva-cleanup): allow cleanup jobs to run as previleged mode

---

cmd/cspc-operator/app/storagepool_create.go
pkg/install/v1alpha1/cstor_pool.go
pkg/upgrade/templates/v1/cstor_pool.go

This PR fixes the shadow mount points in cStor-pool deployment by
updating sock file mount path from `/var/run` to `/var/tmp/sock`.
This PR handles upgrade changes and new cStor pool deployments.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #https://github.com/openebs/openebs/issues/2902
Tested the changes on gke(using disks) by building cstor-pool image and cstor-pool-mgmt image on top of cstor-pool image.(Test images: mittachaitu/cstor-pool:sock_path1, mittachaitu/cstor-pool-mgmt:fix_sock1)
**Checklist:**

fix(mountpath): fix sock file mount path in pool deployments

---

tests/cstor/pool/reconciliation/reconciliation_test.go

This PR adds a check that waits for restarted maya-apiserver to come to running state before continuing the test further.
**Checklist:**

fix(BDD): wait for restarted pod to come to running state

---

cmd/cspc-operator/app/handler.go

This PR replaces the spc label with cspc label in the cspc-operator. If the finalizers are removed from the cspi and for some unknown reason the deletion is stuck then in that case the cspc should not be deleted before cspi deletion.

fix(cspc): replace the spc label with cspc label

---

.travis.yml
ci/travis-ci.sh
ci/udev_check.c

This PR adds a test case to verify the existence of udev inside cstor-pool container.
- After merging https://github.com/openebs/openebs/pull/2943 Travis of this PR needs to trigger once again. 
**Checklist:**

fix(travis): add check to verify existence of udev

---

cmd/maya-exporter/app/collector/zvol/metrics.go
cmd/maya-exporter/app/collector/zvol/pool_synctime.go

This PR fixes a bug in the pool sync time metrics collector in Maya-exporter.
If the last request is in progress, don't queue the current request during pool
last Sync time metrics collection and increment the reject request counter.
**Note**
This PR is the address comments of #1615.
UnitTest will be added once after understanding the flow.
**Checklist:**

fix(exporter): Handle pool sync time metrics collection gracefully

---

cmd/cstor-pool-mgmt/controller/common/common.go
cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
cmd/cstor-pool-mgmt/pool/pool.go
cmd/cstor-pool-mgmt/pool/pool_test.go
cmd/maya-apiserver/cstor-operator/spc/handler.go
cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
pkg/apis/openebs.io/v1alpha1/cas_pool.go
pkg/apis/openebs.io/v1alpha1/cas_template_keys.go
pkg/apis/openebs.io/v1alpha1/cstor_pool.go
pkg/install/v1alpha1/cstor_pool.go
pkg/install/v1alpha1/openebs_crds.go
pkg/storagepool/storagepool.go

Changes:
- Added support to set readOnly threshold for SPC/CSP.
Sample SPC spec
```
spec:
name: cstor-pool
type: sparse
maxPools: 3
poolSpec:
roThresholdLimit: 80
```
Sample CSP spec:
```
spec:
group:
- blockDevice:
- deviceID: /var/openebs/sparse/2-ndm-sparse.img
inUseByPool: true
name: sparse-362d689cfa30cf1ac2cd11ca6dcf9449
poolSpec:
cacheFile: /tmp/pool1.cache
overProvisioning: false
roThresholdLimit: 80
thickProvisioning: false
```
Sample output :
```
kubectl get csp -n openebs
NAME              ALLOCATED   FREE    CAPACITY   STATUS    READONLY   TYPE      AGE
cstor-pool-1mns   117M        9.82G   9.94G      Healthy   true      striped   3h
```
```
Events:
Type     Reason                 Age                  From       Message
----     ------ …
```

feat(spc,csp): adding support for pool ReadOnly Threshold limit

---

cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go

If user hasn't provided any roThresholdLimit in SPC then SPC controller will create CSP with default roThresholdLimit=85.
Related issue: https://github.com/openebs/openebs/issues/2937

feat(csp, poolROThreshold):  setting pool ReadOnly Threshold limit default to 85

---

cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
cmd/maya-apiserver/app/server/backup_endpoint_v1alpha1.go

This change fix the logic to fetch the last snapshot name from `cstorcompletedbackups.openebs.io` for scheduled backup. If first backup for schedule fails then last snapshot name for next backup, for the same schedule, should be empty.
fixes https://github.com/openebs/openebs/issues/2926

fix(backup, cstor): fetching correct snap name in case of base backup failure

---

pkg/util/util.go
pkg/webhook/configuration.go
pkg/webhook/cvc.go
pkg/webhook/cvc_test.go
pkg/webhook/webhook.go

This PR adds validations for CVC update requests and also handles upgrade changes for the admission server controller(CVC scaling feature PR https://github.com/openebs/maya/pull/1613).
**This PR Covers Below Validations and Test Cases For CVC Update:**
- Reject the request if  Replica Count was modified.
- Reject the request if the repetition of pool names either under the spec or status of CVC.
- Reject the request if the existing pool names were modified with new pool names.
- Reject the request if Scaling(Up/Down) was triggered when one other request is in progress. 
- Reject the request if more than one replica was scaled down that one replica at a time for scale down. 
- Reject the request …

feat(validation): add webhook validations for CVC replica scale 

---

pkg/kubernetes/deployment/appsv1/v1alpha1/kubernetes.go
pkg/upgrade/templates/v1/jiva_target.go
pkg/upgrade/upgrader/jiva_upgrade.go

This PR adds a step to scale down jiva target deploy before upgrading replica deploy.
Sample logs:
```sh
mayadata:upgrade$ k logs -f jiva-vol-170180-pvc-4c3f661f-4cdc-4244-9916-1983c43c87b9-b5fjq
I0310 16:41:56.788304       1 jiva_volume.go:80] Started upgrading jivaVolume{pvc-4c3f661f-4cdc-4244-9916-1983c43c87b9} from 1.7.0 to 1.8.0-RC1
I0310 16:41:56.788348       1 jiva_volume.go:87] Upgrading to 1.8.0-RC1
I0310 16:41:57.087781       1 jiva_upgrade.go:424] Scaling down target deploy pvc-4c3f661f-4cdc-4244-9916-1983c43c87b9-ctrl in default namespace
I0310 16:42:07.280325       1 helper.go:68] Patching deployment pvc-4c3f661f-4cdc-4244-9916-1983c43c87b9-rep
I0310 16:42:32.595875       1 …
```

refact(upgrade): scale down jiva target deploy before replica patch

---

cmd/maya-exporter/app/collector/cstor.go
pkg/apis/openebs.io/v1alpha1/cas_keys.go
pkg/cstor/volumereplica/v1alpha1/cstorvolumereplica.go
pkg/install/v1alpha1/cstor_volume.go
pkg/kubernetes/persistentvolume/v1alpha1/build.go
pkg/upgrade/upgrader/jiva_upgrade.go
pkg/util/util.go
pkg/volume/volume.go
tests/cstor/clone/clone_test.go
tests/cstor/volume/provision_test.go
tests/operations.go

Changes:
- CStor backup/restore plugin `openebs/velero-plugin` creates PVC using restore annotation `openebs.io/created-through` to disable connection between CStor replica and target. Recently we removed this annotation and moved it to CASVolume for local snapshot support, but since cloud-snapshot of velero-plugin is already using this feature, we need to handle this until all the changes mentioned in https://github.com/openebs/velero-plugin/pull/47 and https://github.com/openebs/velero-plugin/pull/46 gets merged.

fix(restore,pvc): handling of pvc's annotation for existing velero-plugin's restore 

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
pkg/apis/openebs.io/v1alpha1/cas_pool.go
pkg/upgrade/templates/v1/cstor_pool.go
pkg/upgrade/upgrader/csp_upgrade.go

This PR adds the Pool Protection finalizer(`openebs.io/pool-protection`) on CSP.
This finalizer will be added only if the CSP controller picks CSP object for reconciliation.
**Performed Upgrade Testing With Changes:**
```sh
kubectl logs -f cstor-spc-180190-cstor-sparse-pool-knrwl -n openebs
I0318 08:38:55.257364       1 cstor_spc.go:82] Upgrading to 1.9.0
I0318 08:38:55.582297       1 helper.go:68] Patching deployment cstor-sparse-pool-lqu8
I0318 08:39:56.064983       1 helper.go:95] Deployment cstor-sparse-pool-lqu8 rolled out successfully
I0318 08:39:56.065070       1 csp_upgrade.go:188] patched csp deployment cstor-sparse-pool-lqu8
I0318 08:39:56.078297       1 csp_upgrade.go:151] patched …
```

fix(csp): add pool protection finalizer on CSP

---

cmd/provisioner-localpv/app/provisioner.go
cmd/provisioner-localpv/app/provisioner_blockdevice.go
cmd/provisioner-localpv/app/provisioner_hostpath.go

- remove cstor prefix from localPV log messages
- remove cstor prefix from localPV alert messages.

refact(log): remove cstor prefix from localPV log and alert messages

---

ci/mayactl.sh
pkg/install/v1alpha1/jiva_volume.go
pkg/templatefuncs/v1alpha1/runtask_functions.go

This PR updates the runtasks
-  to create, read and delete multiple replica deployments for jiva volumes.
-  to create all the openebs resources for jiva volumes in openebs namespace.
**Local Test Results:**
```sh
mayadata:setup$ k get pods,svc,deploy
NAME                                                                  READY   STATUS    RESTARTS   AGE
pod/maya-apiserver-d9fccfdcc-p5d2h                                    1/1     Running   0          6m13s
pod/openebs-admission-server-695dbc8b74-sqrkn                         1/1     Running   0          8m19s
pod/openebs-localpv-provisioner-6f4d68b57f-ldjqv                      1/1     Running   0          8m18s
pod/openebs-ndm-lwsk6 …
```

refact(jiva): create separate replica deployments and move all resources to openebsNamespace

---

pkg/apis/openebs.io/ndm/v1alpha1/blockdevice_types.go
pkg/blockdevice/v1alpha1/blockdevice.go
pkg/blockdevice/v1alpha2/blockdevice.go

- add DriveType and BlockSize fields into BlockDevice spec
- These are the same changes as in PR [#33](https://github.com/openebs/api/pull/33)

feat(apis): add new fields into BlockDevice

---

cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica.go

This PR adds the pending snapshots under CVR status.pendingsnapshots only if CVR underwent `Rebuilding`. This PR is continuation of PR https://github.com/openebs/maya/pull/1639.
**How Does It Gets Pending Snapshots**:
The replica which is undergoing rebuilding will get the list of pending snapshots from other peer CVR's Snapshot information.
**Sample YAML output when Rebuilding is in Progress**:
```yaml
kind: CStorVolumeReplica
metadata:
annotations:
cstorpool.openebs.io/hostname: e2e1-node3
isRestoreVol: "false"
openebs.io/storage-class-ref: |
name: single-sc
resourceVersion: 41963
creationTimestamp: "2020-04-01T09:47:53Z"
finalizers:
- cstorvolumereplica.openebs.io/finalizer
generation: 9
labels: …
```

 feat(pendingsnapshots): add pending snapshots on CVR by talking to peer replicas

---

pkg/kubernetes/pod/v1alpha1/buildlist.go
pkg/kubernetes/pod/v1alpha1/buildlist_test.go
pkg/kubernetes/pod/v1alpha1/pod.go
pkg/kubernetes/storageclass/v1alpha1/build.go
pkg/kubernetes/storageclass/v1alpha1/build_test.go
tests/cstor/volume/provision_test.go
tests/cstor/volume/suite_test.go
tests/cstor/volume/waitforfirstconsumer_test.go
tests/operations.go

This PR covers the test positive test case for PR https://github.com/openebs/maya/pull/1637.
This covers following TestCases:
- Provision CStor volume with single and multiple replicas with WaitForFirstConsumer Volume Binding mode. 
**Steps To Run BDD**:
Step1: cd into dir `tests/cstor/volume` after cloning Maya
Step2: Command to run the `WaitForFirstConsumer` test
```sh
ginkgo -v -focus="\[WAITFORFIRSTCONSUMER\] " -- -kubeconfig=<path_to_kube_config> -cstor-maxpools=<no.of_pools> -cstor-replicas=<no.of_replicas>
```
**Special notes for …

feat(BDD): add positive test cases for verifying waitforfirstconsumer With CStor Volume Provisioning

---

cmd/cstor-pool-mgmt/controller/backup-controller/handler.go
cmd/maya-apiserver/app/server/backup_endpoint_v1alpha1.go

Changes:
- This PR adds new DELETE op support for CStor backups`/latest/backups` to delete the CStor backup resources.
- If backup is non-scheduled backup then Maya-Apiserver will delete the relevant CStorBackup, CStorCompletedBackups and CStor snapshot.
- In case of scheduled backup, 
A) If backup is last generated one then Maya-Apiserver will delete the relevant CStorBackup, CStorCompletedBackups and CStor snapshot, so next new backup will be full backup
B) If backup is not the last one then maya-apiserver will delete the relevant CStorBackup and CStor snapshot
REST API query format:
`<APISERVER_ADDR>/latest/backups/<BACKUP_NAME>?volume=<VOL_NAME>&namespace=<PVC_NAMESPACE>&schedule=<SCHEDULE_NAME>`
Sample query URL:
`http://10.0.0.94:5656/latest/backups/emyqevym-20200401174441?volume=pvc …

feat(cstorBackup, delete): support for snapshot deletion

---

pkg/upgrade/templates/v1/jiva_replica.go
pkg/upgrade/upgrader/helper.go
pkg/upgrade/upgrader/jiva_upgrade.go

This PR adds support to migrate the old jiva volume resources to openebs namespace.
Test job logs:
```sh
mayadata:upgrade$ k logs -f jiva-vol-170180-pvc-fc34fbbd-6661-4f40-9-39a3-qjgtt
I0402 11:54:14.024428       1 jiva_volume.go:83] Started upgrading jivaVolume{pvc-be1d95bf-205d-49e2-8bc6-83f4c8ba42af} from 1.6.0 to 1.9.0-RC1
I0402 11:54:14.024504       1 jiva_volume.go:90] Upgrading to 1.9.0-RC1
I0402 11:54:14.117842       1 jiva_upgrade.go:413] Scaling down old deployments
I0402 11:54:14.117872       1 helper.go:325] Scaling deploy pvc-be1d95bf-205d-49e2-8bc6-83f4c8ba42af-ctrl in default namespace to 0
I0402 11:54:29.171796       1 helper.go:325] Scaling deploy …
```

feat(upgrade): add support to migrate jiva volumes resources to openebs namespace

---

pkg/cstor/pool/v1alpha3/cstorpool.go
tests/operations.go

This test fixes the CSP reconciliation BDD.
**Reason For Failure**:
When CSP deletion is triggered it takes a time(very small time)
to remove from etcd due to finalizer existence on it.
As this test is performing continuous deletion of CSP
and expecting them to be created. In this process of
deleting in nth deletion, it takes the deleted object to
perform the deletion. So when CSP is deleted from etcd
and deleting the same object causes the problem and
reporting object not found error.
```sh
STRIPED SPARSE SPC
/home/k8s/go_projects/src/github.com/openebs/maya/tests/cstor/pool/reconciliation/reconciliation_test.go:35
when We we delete cstor sparse pool pod …
```

fix(BDD): fix SPC reconciliation BDD by adding extra filter

---

cmd/provisioner-localpv/app/config.go
cmd/provisioner-localpv/app/helper_blockdevice.go
cmd/provisioner-localpv/app/provisioner_blockdevice.go
pkg/blockdeviceclaim/v1alpha1/build.go
pkg/blockdeviceclaim/v1alpha1/build_test.go
tests/localpv/README.md
tests/localpv/suite_test.go

Ref: https://github.com/openebs/openebs/issues/2916
This PR makes use of the Label Selector capability
added in the BDC. More details: https://github.com/openebs/openebs/issues/2921
The BDC Label Selector feature makes it possible for
administrators to `tag` a set of block devices and use
them for creating Local PV (device).
To use the Label Selector feature with Local PV (Devices)
the administrator is expected to `tag` a set of
block devices by assigning them the label:
` openebs.io/block-device-tag=< tag-value >`.
The `< tag-value >` can be passed to Local PV storage class
via cas annotations. If the value is present, then Local PV
device provisioner will set the following additional selector
on the BDC:
`openebs.io/block-device-tag=< tag-value >` …

feat(localpv-device): allow local pv device on select devices

---

cmd/upgrade/executor/cstor_spc.go
cmd/upgrade/executor/cstor_volume.go
cmd/upgrade/executor/jiva_volume.go

This PR enables the bulk upgrade option for upgrade jobs where multiple volumes or spc can be upgraded in one job.
Updated job yaml:
```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
#VERIFY that you have provided a unique name for this upgrade job.
#The name can be any valid K8s string for name. This example uses
#the following convention: jiva-vol-<flattened-from-to-versions>
name: jiva-vols-160190-busybox
#VERIFY the value of namespace is same as the namespace where openebs components
spec:
backoffLimit: 4
template:
spec:
containers:
- name:  upgrade
args:
- "jiva-volume"
- "--from-version=1.6.0"
- "--to-version=1.9.0"
#VERIFY that …
```

feat(upgrade): enable bulk upgrade for volumes and spc

---

.travis.yml
buildscripts/git-release

OpenEBS Control Plane code is split across multiple repos.
For releasing control plane code, multiple repo's need
to be tagged in a certain order.
This fix will help to trigger the release
on the downstream repo. In this case, after
releasing openebs/maya, the following repos should be
tagged:
- openebs/velero-plugin
- openebs/cstor-csi
- openebs/jiva-operator
Note: Due to multiple jobs running in travis,
the release on the downstream should be done
only after the longest job that pushes the
containers is completed. This is manually
configured via ENV variable RELEASE_DOWNSTREAM.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that …

chore(build): trigger downstream repo release

---

.travis.yml
GNUmakefile
buildscripts/admission-server/Makefile.mk
buildscripts/cspc-operator-debug/Makefile.mk
buildscripts/cspc-operator/Dockerfile.arm64
buildscripts/cspc-operator/Makefile.mk
buildscripts/cvc-operator/Makefile.mk
buildscripts/deploy.sh
buildscripts/travis-build.sh
buildscripts/upgrade-082090/Makefile.mk
buildscripts/upgrade/Makefile.mk
ci/travis-ci.sh

- add support for building arm64 images from travis ci
- enabled arm64 support for m-upgrade
- enabled arm64 support for cspc-operator
- enabled arm64 support for admission-server
- fixed bug in amr64 build of cvc-operator
- add support to push images of amd64 and arm64 from travis ci
- removed auto build of old m-upgrade binaries
enable automatically building arm64 images from ci

feat(build): enable arm64 auto build

---

.travis.yml
GNUmakefile
buildscripts/admission-server/Makefile.mk
buildscripts/cspc-operator-debug/Makefile.mk
buildscripts/cspc-operator/Dockerfile.arm64
buildscripts/cspc-operator/Makefile.mk
buildscripts/cvc-operator/Makefile.mk
buildscripts/deploy.sh
buildscripts/travis-build.sh
buildscripts/upgrade-082090/Makefile.mk
buildscripts/upgrade/Makefile.mk
ci/travis-ci.sh

- add support for building arm64 images from travis ci
- enabled arm64 support for m-upgrade
- enabled arm64 support for cspc-operator
- enabled arm64 support for admission-server
- fixed bug in arm64 build of cvc-operator
- add support to push images of amd64 and arm64 from travis ci
- removed auto build of old m-upgrade binaries
- exit the ci, if a test fails
- unit tests and kubegen will be executed only for amd64
cherry-pick #1650

cherry-pick(build): enable arm64 auto build (#1650)

---

cmd/provisioner-localpv/app/provisioner_hostpath.go

Ref: https://github.com/openebs/openebs/issues/2993
After the PV is created and node affinity is set
based on kubernetes.io/hostname label, either:
- hostname label changed on the node or
- the node is deleted from the cluster.
This PR fixes the panic, by logging the details
of the node hostname that no longer exists
in the cluster.
The code doesn't force delete the PV, considering that
the node might intermittently be out of the cluster.
If the user decides that node is not going to come back,
then the user can go ahead with force delete of pv using
`kubectl delete pv`.
An alternate case is that node hostname has really changed.
In this case, the user will have to perform a manual migration
of the localpv-hostpath PV to the new node using the …

fix(localpv-hostpath):pv deletion caused panic, if node not found

---

cmd/provisioner-localpv/app/provisioner_hostpath.go

Ref #1662 
After the PV is created and node affinity is set
based on kubernetes.io/hostname label, either:
- hostname label changed on the node or
- the node is deleted from the cluster.
This PR fixes the panic, by logging the details
of the node hostname that no longer exists
in the cluster.
The code doesn't force delete the PV, considering that
the node might intermittently be out of the cluster.
If the user decides that node is not going to come back,
then the user can go ahead with force delete of pv using
`kubectl delete pv`.
An alternate case is that node hostname has really changed.
In this case, user will have to perform a manual migration
of the localpv-hostpath PV to the new node using the
following steps:
- Scale down the deployment or sts using the PVC.
- Save the PVC and PV …

fix(localpv-hostpath): pv deletion caused panic when node not found

---

cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
pkg/apis/openebs.io/v1alpha1/cstor_volume_replica.go

- Enables the feature gate REBUILD_ESTIMATES by default(previous PRs https://github.com/openebs/maya/pull/1639, https://github.com/openebs/maya/pull/1641). 
- Removes extra fields under CVR.Status.Snapshots, current it has only LogicalReferenced.
**LogicalReferenced**: Size in bytes of the volume when the snapshot was taken.
**Example CVR YAML**:
```yaml
kind: CStorVolumeReplica
metadata:
annotations:
cstorpool.openebs.io/hostname: 127.0.0.1
isRestoreVol: "false"
openebs.io/storage-class-ref: |
name: single-sc
resourceVersion: 20797
creationTimestamp: "2020-04-15T18:20:34Z"
finalizers:
- cstorvolumereplica.openebs.io/finalizer
generation: 27
labels: …
```

chore(CVR): enable REBUILD_ESTIMATES feature gate

---

cmd/cstor-pool-mgmt/controller/replica-controller/handler.go

This PR is required to update the status on CVR even though if an error occurred while fetching the snapshot info from ZFS instead of returning error(Returning error informs to not to update the CVR status). Since the Restore test in openebs/velero-plugin depends on the [status of CVR](https://github.com/openebs/velero-plugin/blob/837917c2bfa526ddc9a8ab492053fd3607cbe886/tests/sanity/backup_test.go#L171) it is essential to update the status irrespective of snapshot list.
This PR records the error if the error occurs while fetching the snapshot information from ZFS.
**Does this PR require any upgrade …

fix(cStorvolumereplica): record the error while fetching the snapshot information

---

pkg/util/util.go
pkg/webhook/configuration.go

commit 
- update the validatiingwebhookconfiguration failure
policy to `Fail` from `Ignore`
- Handle the `validatingwebhookconfiguration` upgrade to 1.10.0 version 
Fixes: https://github.com/openebs/openebs/issues/3005

refact(webhook): update webhookconfiguration failure policy to Fail

---

changelogs/unreleased/1682-mynktl
cmd/cstor-pool-mgmt/controller/restore/handler.go
cmd/maya-apiserver/app/server/restore_endpoint_v1alpha1.go

This PR is required to fix the issue https://github.com/openebs/maya/issues/1677.
This PR updates the REST api for cstore restore to report failure if cstorrestore resource is in invalid state.
There is one additional change in restore controller in cstor-pool-mgmt to ignore the update if cstorrestore CR is having state `Done` or `Failed`
No
- Restart the cstor-pool pod when restore is in-progress state
- outcome is restore failed
- Restart the cstor-pool pod before it process the cstorrestore CR
- outcome is restore failed
- Restart the cstor-pool pod once it update the …

fix(cstor-restore): fixing restore api to return failure if cstorrestore is in invalid state

---

tests/cstor/clone/clone_test.go
tests/jiva/clone/provision_test.go
tests/jiva/node-stickiness/node_stickiness_test.go
tests/jiva/snapshot/provision_test.go

This PR fixes the BDD failures in the [pipeline](https://gitlab.openebs.ci/openebs/e2e-openshift/pipelines/6457). Pipeline failing because we introduced new checks for PVC deletions request. Now, PVC will be allowed to delete only if the volume doesn't have volumesnapshots and volumesnapshotdata.
This PR wait till deletion of `volumesnapshotdata` object from etcd after triggering
the deletion of volumesnapshot object deletion.
No
Yes!! Ran the related test case in a single node cluster.
**Any additional information for your …

fix(BDD): add checks for snapshotdata deletion in BDDs

---

changelogs/unreleased/1678-slalwani97
cmd/maya-exporter/app/collector/zvol/metrics.go
cmd/maya-exporter/app/collector/zvol/pool_synctime.go
cmd/maya-exporter/app/collector/zvol/pool_synctime_test.go

This PR fixes the generation of duplicate metrics of openebs_zpool_last_sync_time metric.
This PR makes the labeled `pool` value as a pod name, which means the label will be the same in case of error and non-error. So that it does not lead to two different metrics. It also does not set the last_sync_time value in case of error so as to retain the previous metric value.
Signed-off-by: Sumit Lalwani <sumit.lalwani97@gmail.com>

fix(maya-exporter): fix duplicate metrics for openebs_zpool_last_sync_time

---

.travis.yml

Earlier We were tagging release with semantic version 1.x.x, which is changed to v1.x.x and there are cases where tag can be on custom release branches, like v1.9.x-hotfix or v1.9.x-custom, apart from regular release branch (v1.9.x).
This PR fixes the tagging for downstream repo with new semver(like v1.9.1) and also translate the given tag to the corresponding release branch with custom suffixes.
Using the new logic, some examples of tag to branch mappings are:
v1.9.0-RC1 => v1.9.x
v1.9.0-hotfixid => v1.9.x-hotfixid
v1.9.0 => v1.9.x
v1.9.1 => v1.9.x
v1.9.0-custom-RC1 => v1.9.x-custom
v1.9.0-custom => v1.9.x-custom
v1.9.1-custom => v1.9.x-custom
NA
**If the changes …

refactor(travis): fixing travis for tagging downstream repo

---

GNUmakefile

The docker tags are created by removing the `v` from
prefix of TRAVIS_TAG (github tag). Using TRAVIS_TAG
to fetch cstor base image fails to build cstor related 
containers. 
While fetching the cstor base images, trim the leading `v` from the
TRAVIS_TAG
NA
Need to test this in Travis with tags. 
Ref: https://github.com/openebs/maya/pull/1684
**Checklist:**

refactor(build): fix cstor base tag

---

GNUmakefile

fixes Makefile trim logic to trim out the `v` from the cstor base tag image
Earlier logic only works in bash script but not in Makefiles
commit update the trim expression in Makefile which is failing
with the error unterminated variable reference due to error
in parsing expression
Similar logic works in bash script but not in Makefiles
NA
NA
**Checklist:**

fix(Makefile): update the expression to trim 'v' from tag

---

buildscripts/git-release

git-release script returns error if release at targeted branch already exists. This PR address this issue.
Fix the git-release to validate the error message and return error only if tag creation failed.
**Checklist:**

refact(build): fixing git-release file to ignore error if tag already exists

---

.gitignore

Signed-off-by: Saurav Tiwary <srv.twry@gmail.com>
When using Goland, the IDE creates a `.idea` directory which shouldn't be tracked in the version control. 
Adds it in the `.gitignore`.
No
Not necessary
**Checklist:**

chore(gitignore): add .idea to gitignore

---

pkg/install/v1alpha1/env.go
pkg/install/v1alpha1/env_setter.go
pkg/install/v1alpha1/env_setter_test.go
pkg/install/v1alpha1/flags.go
pkg/install/v1alpha1/openebs_crds.go

When helm install for openebs was introduced,
there was no way for helm to install CRDs. So
api-server included the code to install the CRDs
as part of initialization.
With Helm 3, the CRDs can be installed via
helm. There have been some requests for moving
the CRD installations outside of the code for
cases where Kubernetes installers like Lokomotive
and others, would like granular control on
how the required objects are installed.
This commit adds an ENV variable that allows
users to enable/disable the CRD install code.
NA
**Any …

feat(install): enable/disable crd installation

---

pkg/webhook/configuration.go

This PR handles the successful cleanup of old service, secret and webhookconfig for admission webhook in case of operator and helm due to non-uniform labels across different installations in v1.0.0 once they upgrade v1.10.0 version.
Above issue has been seen, when we install openebs v1.0.0 version using openebs-operator yaml 
and  upgrading the v1.0.0 version to the any greater version ( v1.1.0 onwards) using openebs-operator yaml (not with helm as helm maintain there set of labels in each resources, which take cares of upgrading/patching the resources).
Since we have changed the Webhook `FailurePolicy: Fail` , this causes failure for any configuration mistakes in webhook in older …

fix(webhook): cleanup old resources from 1.0.0 release

---

.travis.yml
GNUmakefile
buildscripts/travis-build.sh
ci/build-maya.sh

There are a few places that had IMAGE_ORG
hardcoded to openebs, making the travis
builds on forked repos to fail.
Use the container org from ENV IMAGE_ORG. Default is openebs. 
Also included some minor fixes like:
- added check to copy coverage only if it exists
- removed the step to deploy binaries - which are not used
No
Verified by triggering a build on forked repo. 
https://travis-ci.com/github/mayadata-io/maya/builds/168407713

refactor(build): fix hard coding of image org

---

changelogs/unreleased/1698-utkarshmani1997
cmd/maya-exporter/app/collector/collector.go
cmd/maya-exporter/app/collector/cstor.go
cmd/maya-exporter/app/collector/cstor_test.go
cmd/maya-exporter/app/collector/metrics.go

This commit fixes an issue where it handles the concurrent http
requests and rejects it if a request is already in progress.
It adds a new metrics "openebs_target_reject_request_counter" to increase the count
of rejected requests, which can be helpful in debugging and improves mutex locking.
No
- Introduce delay in fake server written in cstor_test.go and send multiple concurrent get requests to
the exporter, it will only process 1 request at a time and rest other requests will be rejected and new metrics …

refact(exporter): handle concurrent scrape requests

---

.travis.yml
GNUmakefile
buildscripts/travis-build.sh
ci/build-maya.sh

There are a few places that had IMAGE_ORG
hardcoded to openebs, making the travis
builds on forked repos to fail.
Also included some minor fixes like:
- added check to copy coverage only if it exists
- removed the step to deploy binaries - which are not used
(cherry picked from commit 0b208c2c0b010581bbc2f0d03f6ec0012dfd227d)

refactor(build): fix hard coding of image org (#1703)

---

.travis.yml
GNUmakefile
buildscripts/deploy.sh
buildscripts/travis-build.sh

This PR adds automation for building ppc64le image for localpv provisioner. This is a follow up to: https://github.com/openebs/maya/pull/1632
Adds ppc64le build in travis file for localpv provisioner.
**Checklist:**

feat(build): Automating localpv provisioner build for ppc64le

---

cmd/cstor-pool-mgmt/controller/pool-controller/new_pool_controller.go

This PR helps to delete the CSPs which are in `DeletionFailed` state. This state can exist on CSP when an error returned during the destruction of the pool(command used `zpool destroy <pool_name>`). When CSP is deleted it will make sure to destroy the pool on the disk to ensure pool destruction CSP has a finalizer called `openebs.io/pool-protection`. Failure in the `zpool destroy` command can cause due to any reason few are like:
- When unable to execute `zpool destroy <pool_name>`.
- when zrepl it self return and error `cannot destroy 'pool1': the pool is busy`
This PR reconcile even after the object is marked for deletion and still exist in etcd(because …

fix(cstor-pool-mgmt): reconcile even after deletion timestamp is set on CSP

---

changelogs/unreleased/1708-kmova
cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
cmd/provisioner-localpv/app/provisioner.go
pkg/install/v1alpha1/cstor_volume.go
pkg/install/v1alpha1/jiva_volume.go
pkg/usage/googleanalytics.go
pkg/usage/usage.go

From the usage analytics collected, it is hard
to know why a particular type of storage engine
is used over other.
As the PVC names typically correspond to the
application, this commit helps in adding PVC name
to the volume events.
The PVC name will be set as CampaignName property
in analytics.
Not applicable
Verified by creating cstor, jiva and Local PV volumes. The PVC name was sent as part of the campaign. 
The changes done in this PR needs to be made for ZFS Local PV and CSI volumes as well. 
**Checklist:**
Signed-off-by: …

feat(usage): include pvc name in volume events

---

GNUmakefile
buildscripts/deploy.sh

Required to cleanup Makefile build and image targets no longer maintained 
Commit removes the cstor v1 apis based controller, cspc, cvc , cspi makefile image and builds
target which is no longer maintained in `maya` repo and migrated to `openebs/cstor-operators` repo
as part of future enhancements.
**Checklist:**

chore(Makefile): remove cspc,cvc,cspi based controller image builds

---

cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
cmd/cstor-pool-mgmt/pool/pool.go
pkg/webhook/configuration.go
pkg/webhook/spc.go
pkg/webhook/spc_test.go
pkg/webhook/webhook.go

This PR is required to avoid the SPC deletion when
CStorVolumeReplicas exist in the pool and also it
avoids overwriting the pool on the disk during creation
if other pool traces  exist on the disk.
This PR does the following changes
- Validates the SPC deletion request and rejects
the SPC deletion request if it has CVRs that exist
SPC pools(i.e CSP).
- It avoids the force creation of CStorPools i.e pool
creation will fail if there are any pool traces on the disk.
Yes, and upgrade related changes are already handled in PR.
**If the changes in this PR are …

fix(spc): validate SPC deletion request

---

pkg/apis/openebs.io/v1alpha1/cas_keys.go
pkg/snapshot/v1alpha1/snapshot.go
pkg/webhook/webhook.go
pkg/webhook/webhook_test.go

PR required to handle PVC validation checks before starting the volume migration operations,
for example, ignore the PVC deletion if snapshots are exists.  
- Add skip validations checks in webhook validations via annotations:
There are some cases like volume migration where we need to delete
the old pvc and create new pvc based on CSI, in such cases we need
to ignore/skip the validations  related to snapshots .
- Ignore old snapshots delete request once migrated to CSI based volumes. Once we migrate the volumes to CSI, we have to migrate the snapshot as well, once snapshots are migrated, backend snapshot will be bind to new CSI snapshot type, and it requires clean up of the older snapshot related resources as …

skip validations checks and handle snapshot deletion once migrated to CSI

---

pkg/webhook/spc.go
tests/cstor/volume/provision_test.go

This PR is required to fix the failure BDD in [pipeline](https://gitlab.openebs100.io/openebs/e2e-openshift/-/jobs/218676) due to new changes in admission [server](https://github.com/openebs/maya/pull/1710).
This PR verifies and make sure that target pod and CVRs related
to volume should not present in etcd after deleting the PVC.
Not Applicable
Yes, Ran the BDD couple of times
```sh
ginkgo -v -focus="\[Cstor Volume Provisioning Positive\] TEST VOLUME PROVISIONING" -- …
```

fix(BDD): update checks after de-provisioning the CStor Volume

---

buildscripts/travis-build.sh

Fix for Travis CI failure in forked maya repositories, which is failed due to `Not a git repository` error after copying from forked path to actual go import path.
Clone the forked repo using `rsync` and set the `TRAVIS_BUILD_DIR` 
NA
**Checklist:**

fix(build): travis CI failure in forked Repo git error

---

pkg/apis/openebs.io/v1alpha1/versionDetails.go

This PR enables the upgrade between different custom images of the same version. This will allow users to upgrade between RC builds and also the custom builds they have locally of the format `version-customTag` for example `1.11.0-mybuild`. This will be supported by 1.11.0 onwards.
Limitation: there will be no validations for the custom tag following the version.
**Checklist:**

chore(upgrade): add support for upgrading to any custom tag within same version

---

changelogs/unreleased/1719-shubham14bajpai
pkg/upgrade/upgrader/helper.go

This PR fixes the wait time for deployment to roll out after it is patched. Now the job will wait indefinitely for the deployment pod to come up once it is patched successfully. This PR fixes the issue https://github.com/openebs/openebs/issues/3062
No
**Manual test performed**
Patched kubelet code to take 10 minutes for podSync.
Upgraded 1.8.0 to 1.11.0.
Job logs:
```sh
mayadata:upgrade$ k logs -f cstor-spc-1901100-8p72j
I0619 06:04:59.587201       1 cstor_spc.go:100] Started upgrading storagePoolClaim{sparse-claim} from 1.8.0 to 1.11.0
I0619 06:05:00.008563       1 helper.go:68] Patching deployment sparse-claim-j8jr
I0619 06:05:00.105448 …
```

fix(upgrade): increase wait for deployment rollout status

---

changelogs/unreleased/1720-kmova
cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
cmd/provisioner-localpv/app/provisioner.go
tests/artifacts/jiva-pvc-invalid-name.yaml
tests/artifacts/local-d-pvc-invalid-name.yaml
tests/artifacts/local-pvc-long-name.yaml

https://github.com/openebs/openebs/issues/3064
Adds nil checks to catch provisioning errors. 
No
- Verified by creating a PVC with name > 63 chars long. The output shows the following error when `kubectl describe pvc` is executed. 
```
Warning  ProvisioningFailed    2s (x2 over 17s)   openebs.io/provisioner-iscsi_openebs-provisioner-684b6b8584-96kvx_261d65dd-b150-11ea-bd60-2e484c01cabe  failed to provision volume with StorageClass "openebs-jiva-default": Internal Server Error: failed to create volume
....
.... snipped verbose output. …
```

fix(usage): add nil checks to avoid panic

---

pkg/webhook/configuration.go

make webhook validatingwebhookconfiguration  configurable
commit enable the webhook validatingwebhookconfiguration
failure policy configurable using a env called
ADMISSION_WEBHOOK_FAILURE_POLICY.
There are 2 types of failure policy which can be configurable
are `Fail` and `Ignore`. `Fail` will be the default policy
NO
- deployed the admission server using `ignore` failure policy and verified that it got configured properly
**Checklist:**

refact(webhook): make webhook config failure policy configurable

---

changelogs/unreleased/1720-kmova
cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
cmd/provisioner-localpv/app/provisioner.go
tests/artifacts/jiva-pvc-invalid-name.yaml
tests/artifacts/local-d-pvc-invalid-name.yaml
tests/artifacts/local-pvc-long-name.yaml

(cherry picked from commit d70090d250308f58f9e6826715124f031ee7e9fc)
Once a PVC create request is processed by the CAST,
the response is inspected to fetch the PVC name
and other details to generate an analytics log.
This was done as part of the PR: https://github.com/openebs/maya/pull/1708
This commit adds a nil check to handle the case of an error response
to avoid a panic.

fix(usage): add nil checks to avoid panic (#1720)

---

pkg/version/version.go

PR fixes the issue with output runtask version suffix  ( RC1 --> rc1) . (Changes got missed to commit earlier due to some local rebase errors and got stashed locally)
more info #1733 
```sh
Response Code from ApiServer: 500
Retrying.... 31
Logs of api-server: 
labels:
castName: jiva-volume-list-default-1.12.0-ee-rc1
kubeVersion: v1.13.0
version: 1.12.0-ee-RC1
name: jiva-volume-list-default-1.12.0-ee-rc1
resourceVersion: "1633"
selfLink: /apis/openebs.io/v1alpha1/castemplates/jiva-volume-list-default-1.12.0-ee-rc1
uid: 47c9f62e-cab7-11ea-8dde-42010a1e017c
spec:
defaultConfig: null
fallback: ""
output: jiva-volume-list-output-default-1.12.0-ee-RC1
run:
tasks:
- …
```

fix(version): fix castemplate output runstask version suffix

---

pkg/volume/volume.go

This PR fixes CStor volume provisioning issue. Currently
REST request to create CStor volume will fail if request
is made without creating PVC because of following bug:
- When the REST API is called to create volume it will
verify whether request payload has PVC name. If PVC
name doesn't exist then it will skip execution of
`cstor-volume-create-puttargetservice-default` runtask
but with latest changes above runtask is not skipped and
leads to failure in the creation of CStor volume.
For more info: #[1735](https://github.com/openebs/maya/pull/1735)
This PR skips the execution of …

fix(volume provisioning): fix CStor volume provisioning request without creating PVC

---

cmd/provisioner-localpv/app/start.go

Allow user to skip leader election feature.
commit adds the `LEADER_ELECTION_ENABLED` env to allow user
to enable/disable the leader election feature of localpv
provisioner.
If env is not configured, leader election will be disabled by
default.
No
**Checklist:**

refact(localpv): add ENV to allow skipping leader election

---

.travis.yml

To bump the stable go version 1.14.7 and to ignore the PPC build job failure in travis 
- bump go version to 1.14.7
- Allowed ppc job to fail in the build matrix without causing the entire build to fail
No

chore(build): bump go version to 1.14.7 and allow ppc jobs to fail in travis

---

.travis.yml
changelogs/unreleased/1744-mittachaitu
ci/spc-manual.yaml
ci/test-script.sh
ci/travis-ci.sh
cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go

This PR is required to provision CSP with a single raid group
instead of multiple raid groups.
NOTE: One raid group can accumulate `n` blockdevices
This PR provision cStor stripe pool with a single raid group
instead of multiple raid groups, having multiple raid groups
for stripe based pool configuration doesn't make sense.
Even though CSP is created with multiple raid groups but
the underlying pool will be with a single raid group.
Currently, changes are handled in SPC to CSPC based migration.
**If the changes in this PR are manually verified, list down …

fix(spc): provision cStor stripe based pools with single raid group

---

cmd/maya-apiserver/app/server/restore_endpoint_v1alpha1.go
pkg/algorithm/nodeselect/v1alpha1/select_node.go
pkg/algorithm/nodeselect/v1alpha1/select_node_test.go
pkg/blockdevice/v1alpha1/blockdevice.go
pkg/blockdevice/v1alpha1/blockdevice_test.go
pkg/blockdevice/v1alpha1/kubernetes_client_test.go
pkg/blockdevice/v1alpha1/spc_client_test.go
tests/cstor/cspc/provisioning/provisioning_test.go

This commit adds the capability to specify allowed BD tags on SPC via
annotations.
The annotation key is `cstor.openebs.io/allowed-bd-tags` and the allowed value
is comma-separated strings.
For example "fast,slow" is a possible value, and in this case SPC provisioner
will reject BDs that have a BD tag (`openebs.io/block-device-tag`) present on
it and the value is other than fast or slow.
Signed-off-by: Ashutosh Kumar <ashutosh.kumar@mayadata.io>

feat(spc): add capability to specify allowed BD tags on SPC

---

changelogs/unreleased/1754-shubham14bajpai
cmd/admission-server/main.go
pkg/webhook/configuration.go
pkg/webhook/webhook.go

**What this PR does?**:  
This PR adds validation on the deletion of openebs namespace
to avoid
- loss of data in case of accidental deletion of
namespace
- stale resources with finalizers in openebs namespace which
maybe stuck on namespace deletion.
**Does this PR require any upgrade changes?**: 
Yes already handled in the PR itself. Tested 1.10 to latest upgrade: namespace gets added to validatingwebhookconfigurations automatically.
Local test performed:
Both jiva and cstor volume exist
```sh
mayadata:setup$ kubectl get pvc
NAME                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS           AGE
demo-vol-claim-2      Bound …
```

feat(webhook): add validation for namspace delete requests

---

pkg/apis/openebs.io/v1alpha1/versionDetails.go
pkg/upgrade/templates/v1/cstor_target.go
pkg/upgrade/templates/v1/jiva_target.go
pkg/upgrade/upgrader/cstor_volume_upgrade.go
pkg/upgrade/upgrader/jiva_upgrade.go

OpenEBS provides an option to disable volume monitor which results in one less container for the m-exporter image. This PR allows upgrade to work irrespective of whether the monitor is enabled or not.
Tested both Volume Monitor enabled and disabled for both jiva and cstor.
**Checklist:**

fix(upgrade): allow upgrades for volumes without monitor

---

.travis.yml
GNUmakefile
RELEASE.md
buildscripts/deploy.sh
ci/build-maya.sh
tests/artifacts/openebs-ci.yaml

As part of enabling multi-arch repo and deprecating the
openebs/maya repo, the local pv provisioner code is being
migrated to https://github.com/openebs/dynamic-localpv-provisioner
Disabling the travis builds on Local PV provisioner in
the openebs/maya repository

refactor(localpv): move builds to dynamic-localpv-provisioner repo

---

GNUmakefile
RELEASE.md
buildscripts/deploy.sh
ci/build-maya.sh

As part of enabling multi-arch repo and deprecating the
openebs/maya repo, the maya exporter code is being
migrated to https://github.com/openebs/openebs-exporter
Disabling the travis builds on maya exporter in
the openebs/maya repository
No 
**Checklist:**

refactor(exporter): move builds to openebs-exporter repo

---

changelogs/unreleased/1761-zlymeda
cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go
cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
tests/framework/v1alpha1/framework.go
tests/sts/sts_suite_test.go
tests/sts/sts_test.go

Auto-setting of targetip on CVR if openebs.io/restore-completed is found
Currently, users have to set targetip on CVRs after restore. Corresponding change in https://github.com/openebs/velero-plugin/pull/131 will mark CVRs which needs to update the targetip. Changes in this PR will check the annotation and set the targetip.
Sets targetip on CVRs marked with openebs.io/restore-completed annotation.
No
`make test` in velero-plugin repository with changes deployed.
_Mention if this PR is part of any design or a continuation of …

fix(restore): set targetip on CVRs after restore is completed

---

Makefile.buildx.mk
buildscripts/admission-server/admission-server.Dockerfile
buildscripts/apiserver/apiserver.Dockerfile
buildscripts/cstor-pool-mgmt/cstor-pool-mgmt.Dockerfile
buildscripts/cstor-volume-mgmt/cstor-volume-mgmt.Dockerfile
buildscripts/upgrade/upgrade.Dockerfile

The RELEASE_TAG env set in the action is not propagated to the buildx container. This PR fixes the same.
**Checklist:**

fix(build): propagate RELEASE_TAG to buildx container

---

cmd/upgrade/executor/options.go

The upgrade job changes the image urls on pools and volumes to quay.io if the `--to-version-image-prefix` is not set
As the multi-arch images are not pushed to quay.io the upgrade may fail.
**Checklist:**

fix(upgrade): remove quay.io as default url-prefix

---

cmd/upgrade/executor/options.go

The upgrade job changes the image urls on pools and volumes to quay.io if the `--to-version-image-prefix` is not set
As the multi-arch images are not pushed to quay.io the upgrade may fail.
**Checklist:**

fix(upgrade): remove quay.io as default image-prefix

---

pkg/install/v1alpha1/jiva_volume.go

required for provision jiva volume deployments in
restricted environment using pod security policy(PSP)
**Checklist:**

fix(jiva): add serviceAccount name in jiva deployments

---

pkg/webhook/configuration.go

To support dry run command, validatingwebhookconfiguration `SideEffects` needs to be set as `None` .
NO
Manual testing is done with upgrade to latest ci build.
**Checklist:**

fix(webhook): update webhook config sideEffects to None

---

pkg/apis/openebs.io/v1alpha1/versionDetails.go
pkg/install/v1alpha1/jiva_volume.go

This Pr adds the serviceAccountName to the jiva cleanup jobs while deleting a volume. 
https://github.com/openebs/openebs/issues/3331
**Checklist:**

fix(jiva): add serviceAccount to clean up jobs

---

pkg/algorithm/nodeselect/v1alpha1/select_node.go
pkg/blockdeviceclaim/v1alpha1/build.go

LocalPV Device from [openebs/dynamic-localpv-provisioner](https://github.com/openebs/dynamic-localpv-provisioner) requires addition of ownerReference for the BDC to the PVC. This file is included in the vendor directory for the dynamic-localpv-provisioner repo.
The workflow involved here:
1. Add ownerReference for BDC in https://github.com/openebs/maya/tree/master/pkg/blockdeviceclaim/v1alpha1/build.go
2. Update vendoring directory in openebs/dynamic-localpv-provisioner
3. Add owner reference option in https://github.com/openebs/dynamic-localpv-provisioner/tree/master/cmd/provisioner-localpv/app/helper_blockdevice.go
4. Pass PVC to reference to getBlockDevicePath method
5. blockdeviceclaim/v1alpha1/build.go attaches owner reference. …

fix(api): add ownerReference for BDC

---

pkg/util/util.go
pkg/util/util_test.go

This PR fixes the issue where the validatingwebhookconfiguration did not get updated the upgrading from 1.12.0 to latest versions.
```
failed to patch cspc cstor-cspc-disk-pool: Internal error occurred: failed calling webhook "admission-webhook.cstor.openebs.io": converting (v1.AdmissionReview) to (v1beta1.AdmissionReview): unknown conversion
```
**Checklist:**

fix(webhook): fix version comparison of webhook resources

---

cmd/maya-apiserver/app/command/start.go
cmd/maya-apiserver/cstor-operator/spc/handler.go
pkg/algorithm/nodeselect/v1alpha1/select_node.go
pkg/apis/openebs.io/v1alpha1/versionDetails.go
pkg/blockdevice/v1alpha1/blockdevice.go
pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim.go
pkg/blockdeviceclaim/v1alpha1/kubernetes.go
pkg/blockdeviceclaim/v1alpha1/kubernetes_test.go
pkg/storagepoolclaim/v1alpha1/storagepoolclaim.go
tests/operations.go

Signed-off-by: Niladri Halder <niladri.halder@mayadata.io>
To be able to pass a context.Context down the stack. Presently, the client operations wrapper fucntions derive their own context.Context from the caller's Context, without giving the caller function the option to explicitly pass a context.Context.
v2.12.0 Version Bump:
This PR also contains a commit for the v2.12.0 verion bump.
Adds an argument to the abstraction functions for the client-go operations in pkg/blockdeviceclaim/v1alpha1/kubernetes.go
Also passes a context.TODO() from existing callers of the functions in the repo.
v2.12.0 Version Bump:
Add entry for the v2,12.0 version bump.
No.
**If the changes …

refact(blockdeviceclaim-build-files): Add context argument to BDC client operations + v2.12.0 version bump

---

.travis.yml
tests/artifacts/crds.yaml

Change the version in the CRDs to v1 and make the
necessary movements of the elements to pass the
CRD v1 validations like:
- rename version to versions
- set the defaults for a specific version
- set the schema validation to `x-kubernetes-preserve-unknown-fields`
Also, this PR removes the installation of CRDs that are already
migrated to cstor CSI:
- cstorpoolinstances
- cstorvolumeclaims
- cstorvolumepolicies
Related to #1811 

fix(crd): migration from v1beta1 to v1

---

pkg/blockdeviceclaim/v1alpha1/build.go
pkg/blockdeviceclaim/v1alpha1/build_test.go

Signed-off-by: Abhishek Agarwal <abhishek.agarwal@mayadata.io>
Adds a new function to add Selectors to BDC. Currently only one fixed selector can be added to the BDC and that is `"openebs.io/block-device-tag"`.
The function added will allow to add any number of selector labels to the BDC by passing a map of string key and values.
No.
**Checklist:**

fix(blockdeviceclaim-build-file): Add new build function to add any BDC selectors
